export type MasterMenuChild={title:string;legacyCode?:string;moduleCode?:string;route?:string};
export type MasterMenuItem={code:string;number:string;title:string;icon:string;moduleCode?:string;route?:string;panel?:string;children:MasterMenuChild[]};

const child=(title:string,legacyCode?:string,moduleCode?:string,route?:string):MasterMenuChild=>({title,legacyCode,moduleCode,route});

export const MASTER_MENU:MasterMenuItem[]=[
{code:"management",number:"01",title:"پنل مدیریت",icon:"⌂",route:"/admin",moduleCode:"command-center",children:[child("مرکز فرماندهی عملیاتی","","command-center","/command-center"),child("هوش تجاری و تحلیل هوشمند","45-search-analytics"),child("هوش مصنوعی سازمانی","40-ai-finance")]},
{code:"organization",number:"02",title:"پنل سازمان‌ها و شرکت‌ها",icon:"◈",route:"/modules/?code=02-organizations",moduleCode:"governance",children:[child("ساختار سازمان","02-organizations",undefined,"/modules/?code=02-organizations&tab=structure"),child("سازمان‌ها","02-organizations",undefined,"/modules/?code=02-organizations&tab=organizations"),child("هلدینگ‌ها","02-organizations",undefined,"/modules/?code=02-organizations&tab=holdings"),child("شرکت‌ها","02-organizations",undefined,"/modules/?code=02-organizations&tab=companies"),child("شعب و نمایندگی‌ها","02-organizations",undefined,"/modules/?code=02-organizations&tab=branches"),child("واحدهای سازمانی","02-organizations",undefined,"/modules/?code=02-organizations&tab=units"),child("دپارتمان‌ها","02-organizations",undefined,"/modules/?code=02-organizations&tab=departments"),child("مراکز هزینه سازمان","02-organizations",undefined,"/modules/?code=02-organizations&tab=cost"),child("مراکز درآمد سازمان","02-organizations",undefined,"/modules/?code=02-organizations&tab=revenue"),child("مراکز سود سازمان","02-organizations",undefined,"/modules/?code=02-organizations&tab=profit"),child("ساختار مالکیت","02-organizations",undefined,"/modules/?code=02-organizations&tab=ownership"),child("تنظیمات سازمان","02-organizations",undefined,"/modules/?code=02-organizations&tab=settings"),child("منابع انسانی","39-human-resources",undefined,"/modules/?code=39-human-resources&tab=employees"),child("حقوق و دستمزد","39-human-resources",undefined,"/modules/?code=39-human-resources&tab=payroll"),child("حضور و غیاب","39-human-resources",undefined,"/modules/?code=39-human-resources&tab=attendance"),child("مدیریت پروژه","30-projects-cost-centers",undefined,"/modules/?code=30-projects-cost-centers&tab=projects"),child("تولید","24-production",undefined,"/modules/?code=24-production&tab=production"),child("نگهداری و تعمیرات","24-production",undefined,"/modules/?code=24-production&tab=maintenance")]},
{code:"users-access",number:"03",title:"پنل کاربران، نقش‌ها و دسترسی‌ها",icon:"◇",route:"/modules/?code=03-users-access",moduleCode:"identity",children:[child("مدیریت کاربران و حساب‌ها","03-users-access",undefined,"/modules/?code=03-users-access&tab=users"),child("پروفایل کاربران","03-users-access",undefined,"/modules/?code=03-users-access&tab=profiles"),child("نقش‌ها و مسئولیت‌ها","02-identity",undefined,"/modules/?code=03-users-access&tab=roles"),child("گروه‌های کاربری","02-identity",undefined,"/modules/?code=03-users-access&tab=groups"),child("کاتالوگ مجوزها و دسترسی‌ها","02-identity",undefined,"/modules/?code=03-users-access&tab=permissions"),child("سیاست‌های امنیتی","03-users-access",undefined,"/modules/?code=03-users-access&tab=policies"),child("احراز هویت و ورود امن","02-identity",undefined,"/modules/?code=03-users-access&tab=auth"),child("احراز هویت دومرحله‌ای","03-users-access",undefined,"/modules/?code=03-users-access&tab=twofa"),child("نشست‌ها و دستگاه‌های مجاز","02-identity",undefined,"/modules/?code=03-users-access&tab=sessions"),child("تاریخچه ورود و ممیزی امنیتی","02-identity",undefined,"/modules/?code=03-users-access&tab=audit")]},
{code:"customers-360",number:"04",title:"پنل مشتریان و پرونده ۳۶۰",icon:"◎",route:"/modules/?code=04-customers-360",moduleCode:"crm",children:[child("مشتریان و پرونده ۳۶۰","04-customers-360"),child("فروش و درآمد","22-sales-revenue"),child("بازاریابی و محتوا","44-marketing-content"),child("پشتیبانی و خدمات","43-communication-hub")]},
{code:"smart-calendar",number:"05",title:"پنل تقویم هوشمند",icon:"◷",route:"/modules/?code=05-smart-calendar",moduleCode:"smart-calendar",children:[child("تقویم سازمانی","05-smart-calendar"),child("رویدادها و برنامه‌ها","05-smart-calendar"),child("روزهای کاری و تعطیلات","05-smart-calendar"),child("تأییدیه‌ها و زمان‌بندی","05-smart-calendar")]},
{code:"business-rules",number:"06",title:"پنل قوانین کسب‌وکار",icon:"↻",route:"/modules/?code=06-business-rules",moduleCode:"business-rules",children:[child("قوانین و فرآیندها","06-business-rules"),child("گردش کار","06-business-rules"),child("اتوماسیون هوشمند","06-business-rules")]},
{code:"sla",number:"07",title:"پنل مدیریت SLA",icon:"◌",route:"/modules/?code=07-sla",moduleCode:"sla-management",children:[child("SLA سازمانی","07-sla"),child("سطوح خدمت","07-sla"),child("کارتابل و تعهدات","07-sla"),child("پایش SLA","07-sla")]},
{code:"accounting-finance",number:"08",title:"پنل حسابداری و مالی",icon:"₿",route:"/modules/?code=08-accounting-finance",moduleCode:"accounting-finance",children:[child("حسابداری و کدینگ","08-accounting-finance",undefined,"/modules/?code=08-accounting-finance&tab=accounts"),child("اسناد و دفاتر","08-accounting-finance",undefined,"/modules/?code=08-accounting-finance&tab=documents"),child("گزارش‌های مالی","33-budget-financial-control"),child("بهای تمام‌شده","25-costing"),child("حساب‌های دریافتنی","27-receivables"),child("حساب‌های پرداختنی","28-payables"),child("خزانه و بانک","26-treasury-bank"),child("چک و اسناد","08-check-documents"),child("کیف پول و دفترکل","29-wallet-ledger"),child("دارایی‌های ثابت","31-fixed-assets"),child("مالیات و صورتحساب الکترونیکی","32-tax-e-invoicing"),child("بودجه و کنترل مالی","33-budget-financial-control"),child("تعهدات مالی","34-financial-commitments"),child("تأمین مالی و اعتبارات","35-credit-financing"),child("مدیریت وام‌ها","36-loans"),child("وثایق و ضمانت‌ها","37-collateral-guarantees"),child("وصول مطالبات","38-collections"),child("مغایرت‌گیری و تطبیق","49-reconciliation"),child("حسابداری مدیریت","08-accounting-finance",undefined,"/modules/?code=08-accounting-finance&tab=reports")]},
{code:"commerce",number:"09",title:"پنل تجارت و فروشگاه‌ها",icon:"⌘",route:"/modules/?code=09-commerce-stores",moduleCode:"marketplace",children:[child("محصولات و کالاها","23-inventory-warehouse",undefined,"/marketplace/products"),child("فروشگاه‌ها","09-commerce-stores",undefined,"/marketplace/stores"),child("مدیریت فروشندگان","09-commerce-stores",undefined,"/marketplace/sellers"),child("فروش و سفارشات","22-sales-revenue",undefined,"/marketplace/orders"),child("خرید و تأمین","21-purchasing-supply"),child("انبار و موجودی","23-inventory-warehouse"),child("لجستیک و تحویل","12-logistics-supply"),child("زنجیره تأمین و لجستیک","48-shipping-delivery")]},
{code:"domains",number:"10",title:"پنل مدیریت دامنه‌ها",icon:"◈",route:"/modules/?code=09-commerce-stores&panel=domains",moduleCode:"domain-management",panel:"domains",children:[child("دامنه‌های سازمان","09-commerce-stores"),child("دامنه‌های فروشگاه","09-commerce-stores"),child("دامنه‌های اختصاصی فروشندگان","09-commerce-stores"),child("اتصال دامنه و SSL","09-commerce-stores")]},
{code:"acceptors",number:"11",title:"پنل پذیرندگان",icon:"◎",route:"/modules/?code=09-commerce-stores&panel=acceptors",moduleCode:"acceptors",panel:"acceptors",children:[child("پذیرندگان","09-commerce-stores"),child("پروفایل پذیرنده","09-commerce-stores"),child("قرارداد پذیرنده","47-contracts-legal"),child("تسویه پذیرندگان","10-wallet-ledger"),child("گزارش پذیرندگان","45-search-analytics")]},
{code:"sellers",number:"12",title:"پنل فروشندگان",icon:"◇",route:"/marketplace/sellers",moduleCode:"sellers",panel:"sellers",children:[child("فروشندگان","09-commerce-stores",undefined,"/marketplace/sellers"),child("فروشگاه فروشنده","09-commerce-stores",undefined,"/marketplace/stores"),child("دامنه فروشنده","09-commerce-stores"),child("کمیسیون فروشندگان","10-wallet-ledger"),child("تسویه فروشندگان","10-wallet-ledger"),child("گزارش فروشندگان","45-search-analytics")]},
{code:"payments-settlement",number:"13",title:"پنل پرداخت و تسویه",icon:"▣",route:"/modules/?code=10-wallet-ledger&panel=payments",moduleCode:"payments-settlement",panel:"payments",children:[child("درگاه‌ها","46-unified-applications"),child("درگاه‌های چندارزی","46-unified-applications"),child("پرداخت‌ها","26-treasury-bank"),child("تسویه‌ها","10-wallet-ledger"),child("دفترکل کیف پول","10-wallet-ledger"),child("کمیسیون‌ها","10-wallet-ledger"),child("برگشت و Refund","10-wallet-ledger")]},
{code:"form-builder",number:"14",title:"پنل فرم‌ساز",icon:"▤",route:"/modules/?code=16-page-builder&panel=form",moduleCode:"page-builder",panel:"form",children:[child("فرم‌ها","14-form-builder"),child("فیلدها","16-page-builder"),child("گردش فرم","16-page-builder"),child("اعتبارسنجی","16-page-builder"),child("انتشار فرم","16-page-builder"),child("Submissionها","16-page-builder")]},
{code:"menu-builder",number:"15",title:"پنل منوساز",icon:"☷",route:"/modules/?code=16-page-builder&panel=menu",moduleCode:"page-builder",panel:"menu",children:[child("منوی مرکزی","15-menu-builder"),child("ساختار منو","16-page-builder"),child("مجوز منو","16-page-builder"),child("ترتیب و جایگاه","16-page-builder"),child("انتشار منو","16-page-builder")]},
{code:"page-builder",number:"16",title:"پنل صفحه‌ساز",icon:"▥",route:"/modules/?code=16-page-builder",moduleCode:"page-builder",children:[child("صفحات","16-page-builder"),child("Page Builder","16-page-builder"),child("Widget Builder","16-page-builder"),child("Templateها","16-page-builder"),child("نسخه‌بندی صفحات","16-page-builder"),child("انتشار صفحات","16-page-builder")]},
{code:"frontend-management",number:"17",title:"پنل مدیریت فرانت‌اند",icon:"✦",route:"/modules/?code=16-page-builder&panel=frontend",moduleCode:"frontend-management",children:[child("Theme Manager","16-page-builder"),child("قالب‌ها","16-page-builder"),child("Header","16-page-builder"),child("Footer","16-page-builder"),child("مدیریت Frontend","17-frontend-management"),child("زبان و ترجمه صفحات","16-page-builder")]},
{code:"notifications",number:"18",title:"پنل اعلان‌ها",icon:"◉",route:"/modules/?code=18-notifications",moduleCode:"communications",children:[child("مرکز اعلان","18-notifications"),child("پیامک","18-notifications"),child("ایمیل","18-notifications"),child("Push","18-notifications"),child("WhatsApp","18-notifications"),child("Telegram","18-notifications"),child("پیام درون‌سامانه","18-notifications"),child("Template","18-notifications"),child("صف ارسال","18-notifications"),child("تاریخچه ارسال","18-notifications")]},
{code:"documents-governance",number:"19",title:"پنل مستندات و حاکمیت اسناد",icon:"▤",route:"/modules/?code=19-documents-governance",moduleCode:"documents-governance",children:[child("زونکن دیجیتال","19-documents-governance"),child("مدیریت اسناد","19-documents-governance"),child("اتوماسیون اداری","19-documents-governance"),child("قراردادها و امور حقوقی","47-contracts-legal"),child("احراز هویت و مدارک","02-identity"),child("OCR و اسناد هوشمند","41-ai-documents-ocr"),child("حسابرسی و کنترل داخلی","42-audit-internal-control")]},
{code:"system-settings",number:"20",title:"پنل تنظیمات و مدیریت سامانه",icon:"⚙",route:"/modules/?code=20-system-settings",moduleCode:"governance",children:[child("تنظیمات مرکزی","20-system-settings"),child("یکپارچه‌سازی‌ها","46-unified-applications"),child("API و توسعه‌دهندگان","46-unified-applications"),child("پورتال‌ها و اپلیکیشن‌ها","46-unified-applications"),child("مانیتورینگ سیستم","50-release-health"),child("پشتیبان‌گیری و نگهداری","50-release-health"),child("حساب کاربری","03-users-access")]} 
];
