"use client";
import {useEffect,useMemo,useState} from "react";
import {api} from "../../lib/api";
type ModuleItem={id:number;code:string;title:string;core:string;lifecycle:string;record_count:number;route?:string|null;description?:string|null};
export default function Admin(){
 const [me,setMe]=useState<any>(null),[modules,setModules]=useState<ModuleItem[]>([]),[health,setHealth]=useState<{status?:string;database?:string}>({}),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{try{const [session,catalog,h]=await Promise.all([api<any>("/api/auth/me"),api<any>("/api/platform/modules"),fetch("/health",{credentials:"include"}).then(x=>x.ok?x.json():{})]);if(!alive)return;setMe(session.user);setModules(catalog.items||[]);setHealth(h)}catch(e){if(alive){setError(e instanceof Error?e.message:"نشست معتبر نیست.");setTimeout(()=>{location.href="/login"},250)}}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const totals=useMemo(()=>({records:modules.reduce((n,m)=>n+(m.record_count||0),0),active:modules.filter(m=>m.lifecycle==="active"||m.lifecycle==="operational").length,cores:new Set(modules.map(m=>m.core)).size}),[modules]);
 return <main><header className="page-head"><div><span className="eyebrow">مرکز مدیریت نگار آذین فدک</span><h1>داشبورد مدیریتی</h1><p className="muted">{me?.fullName||me?.email||"در حال بررسی نشست..."}</p></div><a className="back-link" href="/">منوی مرکزی سازمان</a></header>
 {error&&<div className="error">{error}</div>}
 <section className="cards"><article className="card"><span className="card-number">{modules.length}</span><h3>ماژول‌های فعال</h3><p>ثبت‌شده در کاتالوگ عملیاتی و قابل مشاهده بر اساس سطح دسترسی.</p></article><article className="card"><span className="card-number">{totals.records}</span><h3>رکوردهای واقعی</h3><p>داده‌های ثبت‌شده در PostgreSQL، بدون داده نمایشی ساختگی.</p></article><article className="card"><span className="card-number">{totals.cores}</span><h3>هسته‌های کسب‌وکار</h3><p>گروه‌بندی عملیاتی برای دسترسی سریع به بخش‌های سامانه.</p></article><article className="card"><span className="card-number">{health.database==="ok"?"OK":"CHECK"}</span><h3>وضعیت پایگاه داده</h3><p>{health.database==="ok"?"ارتباط با PostgreSQL برقرار است.":"نیازمند بررسی سرویس مرکزی."}</p></article></section>
 <section className="runtime-panel" style={{marginTop:24}}><div className="panel-title"><div><h2>دسترسی سریع</h2><span>{loading?"در حال دریافت...":totals.active+" بخش عملیاتی آماده استفاده"}</span></div></div><div className="record-list">{modules.slice(0,12).map(m=><a className="record-row" key={m.code} href={"/modules/?code="+encodeURIComponent(m.code)}><div><strong>{m.title}</strong><small>{m.code} · {m.core} · {m.record_count} رکورد</small><code>{m.description||"فضای عملیاتی متصل به سرویس مرکزی"}</code></div><span>ورود ←</span></a>)}</div>{!loading&&modules.length>12&&<a className="back-link" href="/">مشاهده همه بخش‌ها در منوی مرکزی</a>}</section>
 </main>;
}