"use client";
import {useEffect,useState} from "react";
import styles from "./AccountingFinanceWorkspace.module.css";

type Book={id:string;code:string;title:string;currency:string;book_mode:string};
type Period={id:string;code:string;title:string;starts_on:string;ends_on:string;status:string;book_id:string;book_title:string};
type Account={id:string;code:string;name:string;account_type:string};
type Doc={id:string;document_no:string;document_date:string;description:string;status:string;total_debit:string;total_credit:string;book_title?:string;period_title?:string};
type Center={id:string;code:string;title:string;center_type:string;status:string};

const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
async function request(path:string,options:RequestInit={}){const r=await fetch(api+path,{credentials:"include",...options,headers:{"Content-Type":"application/json","X-CSRF-Token":csrf(),...(options.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||"عملیات ناموفق بود");return b;}

export default function AccountingFinanceWorkspace(){
 const [tab,setTab]=useState("accounts"),[books,setBooks]=useState<Book[]>([]),[periods,setPeriods]=useState<Period[]>([]),[docs,setDocs]=useState<Doc[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[centers,setCenters]=useState<Center[]>([]);
 const [error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [period,setPeriod]=useState({bookId:"",code:"",title:"",startsOn:"",endsOn:""});
 const [center,setCenter]=useState({code:"",title:"",centerType:"cost"});\n const [account,setAccount]=useState({code:"",name:"",accountType:"general",accountMode:"hybrid",bookId:""});\n const [editingAccount,setEditingAccount]=useState<string|null>(null);
 const [doc,setDoc]=useState({bookId:"",periodId:"",documentNo:"",documentDate:new Date().toISOString().slice(0,10),description:""});
 const [lines,setLines]=useState([{accountId:"",debit:"",credit:"",description:""},{accountId:"",debit:"",credit:"",description:""}]);
 const [reports,setReports]=useState<any>(null);

 const load=async()=>{try{setError("");const b=await request("/api/accounting-finance/overview");setBooks(b.books||[]);setPeriods(b.periods||[]);setDocs(b.documents||[]);setAccounts(b.accounts||[]);setCenters(b.costCenters||[]);if(!period.bookId&&b.books?.[0])setPeriod(x=>({...x,bookId:b.books[0].id}));if(!doc.bookId&&b.books?.[0])setDoc(x=>({...x,bookId:b.books[0].id}));}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 useEffect(()=>{const t=new URLSearchParams(window.location.search).get("tab");const map:any={"accounting-finance-1":"accounts","accounting-finance-2":"documents","accounting-finance-3":"periods","accounting-finance-4":"centers","accounting-finance-5":"reports"};if(t&&map[t])setTab(map[t]);load()},[]);
 const savePeriod=async()=>{setSaving(true);try{await request("/api/accounting-finance/periods",{method:"POST",body:JSON.stringify(period)});setPeriod(x=>({...x,code:"",title:"",startsOn:"",endsOn:""}));await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const saveAccount=async()=>{setSaving(true);try{await request(editingAccount?"/api/accounting-finance/accounts/"+editingAccount:"/api/accounting-finance/accounts",{method:editingAccount?"PATCH":"POST",body:JSON.stringify(account)});setAccount({code:"",name:"",accountType:"general",accountMode:"hybrid",bookId:""});setEditingAccount(null);await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};\n const saveCenter=async()=>{setSaving(true);try{await request("/api/accounting-finance/cost-centers",{method:"POST",body:JSON.stringify(center)});setCenter({code:"",title:"",centerType:"cost"});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const saveDoc=async()=>{setSaving(true);try{await request("/api/accounting-finance/documents",{method:"POST",body:JSON.stringify({...doc,lines:lines.map(x=>({...x,debit:Number(x.debit||0),credit:Number(x.credit||0)}))})});setDoc(x=>({...x,documentNo:"",description:""}));setLines([{accountId:"",debit:"",credit:"",description:""},{accountId:"",debit:"",credit:"",description:""}]);await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const status=async(id:string,s:string)=>{try{await request("/api/accounting-finance/documents/"+id+"/status",{method:"PATCH",body:JSON.stringify({status:s})});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 const periodStatus=async(id:string,s:string)=>{try{await request("/api/accounting-finance/periods/"+id+"/status",{method:"PATCH",body:JSON.stringify({status:s})});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 const runReports=async()=>{try{setReports(await request("/api/accounting-finance/reports"))}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 const addLine=()=>setLines(x=>[...x,{accountId:"",debit:"",credit:"",description:""}]);
 const setLine=(i:number,k:string,v:string)=>setLines(x=>x.map((a,n)=>n===i?{...a,[k]:v}:a));
 const tabs=[["accounts","دفتر حساب‌ها"],["documents","اسناد حسابداری"],["periods","دوره‌های مالی"],["centers","مرکز هزینه"],["reports","گزارش مالی"]];
 return <main className={styles.workspace} dir="rtl">
  <header className={styles.header}><div><span>هسته مالی</span><h1>حسابداری و مالی</h1><p>دفتر حساب‌ها، اسناد متوازن، دوره‌های کنترل‌شده، مراکز هزینه و گزارش‌های مبتنی بر داده واقعی.</p></div><div className={styles.metric}>{books.length} دفتر · {docs.length} سند</div></header>
  {error&&<div className={styles.error}>{error}</div>}
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>{setTab(k);if(k==="reports")runReports()}}>{t}</button>)}</nav>

  {tab==="accounts"&&<section className={styles.grid}><article className={styles.panel}><h2>{editingAccount?"ویرایش حساب":"ایجاد حساب"}</h2><div className={styles.form}><label>کد حساب<input disabled={!!editingAccount} value={account.code} onChange={e=>setAccount({...account,code:e.target.value})}/></label><label>نام حساب<input value={account.name} onChange={e=>setAccount({...account,name:e.target.value})}/></label><label>نوع حساب<input value={account.accountType} onChange={e=>setAccount({...account,accountType:e.target.value})}/></label><label>ماهیت<select value={account.accountMode} onChange={e=>setAccount({...account,accountMode:e.target.value})}><option value="official">رسمی</option><option value="internal">غیررسمی</option><option value="hybrid">ترکیبی</option></select></label><label>دفتر<select value={account.bookId} onChange={e=>setAccount({...account,bookId:e.target.value})}><option value="">بدون دفتر</option>{books.map(b=><option key={b.id} value={b.id}>{b.code} · {b.title}</option>)}</select></label></div><button className={styles.primary} onClick={saveAccount} disabled={saving||!account.code||!account.name}>{editingAccount?"ذخیره تغییرات":"ایجاد حساب"}</button></article><article className={styles.panel}><div className={styles.title}><div><h2>ساختار حساب‌ها</h2><small>کدینگ واقعی سازمان و اتصال به دفتر مالی</small></div><span>{accounts.length} حساب</span></div><div className={styles.table}><div className={styles.tr+" "+styles.th}><b>کد</b><b>نام حساب</b><b>نوع</b><b>عملیات</b></div>{accounts.map(a=><div className={styles.tr} key={a.id}><span>{a.code}</span><strong>{a.name}</strong><span>{a.account_type}</span><button className={styles.secondary} onClick={()=>{setEditingAccount(a.id);setAccount({code:a.code,name:a.name,accountType:a.account_type,accountMode:(a as any).account_mode||"hybrid",bookId:(a as any).book_id||""})}}>ویرایش</button></div>)}{!accounts.length&&<div className={styles.empty}>حسابی برای این سازمان ثبت نشده است.</div>}</div></article></section>}

  {tab==="documents"&&<section className={styles.grid}><article className={styles.panel}><h2>ثبت سند حسابداری</h2><div className={styles.form}><label>دفتر<select value={doc.bookId} onChange={e=>setDoc({...doc,bookId:e.target.value})}>{books.map(b=><option key={b.id} value={b.id}>{b.code} · {b.title}</option>)}</select></label><label>دوره<select value={doc.periodId} onChange={e=>setDoc({...doc,periodId:e.target.value})}><option value="">بدون دوره</option>{periods.filter(p=>p.status==="open").map(p=><option key={p.id} value={p.id}>{p.code} · {p.title}</option>)}</select></label><label>شماره سند<input value={doc.documentNo} onChange={e=>setDoc({...doc,documentNo:e.target.value})}/></label><label>تاریخ<input type="date" value={doc.documentDate} onChange={e=>setDoc({...doc,documentDate:e.target.value})}/></label><label className={styles.full}>شرح<input value={doc.description} onChange={e=>setDoc({...doc,description:e.target.value})}/></label></div><h3>ردیف‌های سند</h3>{lines.map((l,i)=><div className={styles.line} key={i}><select value={l.accountId} onChange={e=>setLine(i,"accountId",e.target.value)}><option value="">حساب</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><input type="number" placeholder="بدهکار" value={l.debit} onChange={e=>setLine(i,"debit",e.target.value)}/><input type="number" placeholder="بستانکار" value={l.credit} onChange={e=>setLine(i,"credit",e.target.value)}/><input placeholder="شرح ردیف" value={l.description} onChange={e=>setLine(i,"description",e.target.value)}/></div>)}<button className={styles.secondary} onClick={addLine}>افزودن ردیف</button><button className={styles.primary} disabled={saving} onClick={saveDoc}>{saving?"در حال ثبت...":"ثبت سند"}</button></article><article className={styles.panel}><div className={styles.title}><h2>اسناد اخیر</h2><span>{docs.length}</span></div>{docs.map(d=><div className={styles.card} key={d.id}><div><strong>{d.document_no}</strong><small>{d.document_date} · {d.status} · {d.book_title}</small><p>{d.description||"بدون شرح"}</p></div><div className={styles.actions}>{d.status==="draft"&&<button onClick={()=>status(d.id,"submitted")}>ارسال</button>}{d.status==="submitted"&&<button onClick={()=>status(d.id,"approved")}>تأیید</button>}{d.status==="approved"&&<button onClick={()=>status(d.id,"posted")}>ثبت قطعی</button>}</div></div>)}</article></section>}

  {tab==="periods"&&<section className={styles.grid}><article className={styles.panel}><h2>ایجاد دوره مالی</h2><div className={styles.form}><label>دفتر<select value={period.bookId} onChange={e=>setPeriod({...period,bookId:e.target.value})}>{books.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label><label>کد دوره<input value={period.code} onChange={e=>setPeriod({...period,code:e.target.value})}/></label><label>عنوان<input value={period.title} onChange={e=>setPeriod({...period,title:e.target.value})}/></label><label>از تاریخ<input type="date" value={period.startsOn} onChange={e=>setPeriod({...period,startsOn:e.target.value})}/></label><label>تا تاریخ<input type="date" value={period.endsOn} onChange={e=>setPeriod({...period,endsOn:e.target.value})}/></label></div><button className={styles.primary} onClick={savePeriod} disabled={saving}>ایجاد دوره</button></article><article className={styles.panel}><h2>چرخه دوره‌ها</h2>{periods.map(p=><div className={styles.card} key={p.id}><div><strong>{p.code} · {p.title}</strong><small>{p.starts_on} تا {p.ends_on} · {p.status}</small></div><div className={styles.actions}>{p.status==="open"&&<button onClick={()=>periodStatus(p.id,"closed")}>بستن</button>}{p.status==="closed"&&<button onClick={()=>periodStatus(p.id,"locked")}>قفل</button>}</div></div>)}</article></section>}

  {tab==="centers"&&<section className={styles.grid}><article className={styles.panel}><h2>مرکز هزینه / درآمد / سود</h2><div className={styles.form}><label>کد<input value={center.code} onChange={e=>setCenter({...center,code:e.target.value})}/></label><label>عنوان<input value={center.title} onChange={e=>setCenter({...center,title:e.target.value})}/></label><label>نوع<select value={center.centerType} onChange={e=>setCenter({...center,centerType:e.target.value})}><option value="cost">هزینه</option><option value="revenue">درآمد</option><option value="profit">سود</option></select></label></div><button className={styles.primary} onClick={saveCenter} disabled={saving}>ثبت مرکز</button></article><article className={styles.panel}><h2>مراکز ثبت‌شده</h2>{centers.map(c=><div className={styles.card} key={c.id}><div><strong>{c.code} · {c.title}</strong><small>{c.center_type} · {c.status}</small></div></div>)}</article></section>}

  {tab==="reports"&&<section className={styles.grid}><article className={styles.panel}><div className={styles.title}><h2>گزارش مالی</h2><button className={styles.secondary} onClick={runReports}>به‌روزرسانی</button></div>{reports?.statements&&<div className={styles.stats}><div><small>درآمد</small><strong>{Number(reports.statements.revenue).toLocaleString("fa-IR")}</strong></div><div><small>هزینه</small><strong>{Number(reports.statements.expense).toLocaleString("fa-IR")}</strong></div></div>}<div className={styles.table}><div className={styles.tr+" "+styles.th}><b>کد</b><b>حساب</b><b>بدهکار</b><b>بستانکار</b></div>{(reports?.trialBalance||[]).map((a:any)=><div className={styles.tr} key={a.id}><span>{a.code}</span><strong>{a.name}</strong><span>{Number(a.debit).toLocaleString("fa-IR")}</span><span>{Number(a.credit).toLocaleString("fa-IR")}</span></div>)}</div></article><article className={styles.panel}><h2>کنترل اسناد</h2><p className={styles.note}>گزارش‌ها فقط از اسناد با وضعیت «ثبت قطعی» محاسبه می‌شوند؛ داده نمایشی ساختگی وارد محاسبات نمی‌شود.</p><div className={styles.stats}><div><small>اسناد قطعی</small><strong>{reports?docs.filter(x=>x.status==="posted").length:"-"}</strong></div><div><small>تراز بدهکار</small><strong>{reports?Number(reports.trialBalance?.reduce((n:number,x:any)=>n+Number(x.debit),0)||0).toLocaleString("fa-IR"):"-"}</strong></div></div></article></section>}
 </main>;
}
