"use client";
import {useEffect,useState} from "react";
import styles from "./BusinessRulesWorkspace.module.css";
type Data={rules:any[];conditions:any[];actions:any[];versions:any[];priorities:any[]};
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["business-rules-1","قواعد"],["business-rules-2","شرایط"],["business-rules-3","اقدامات"],["business-rules-4","اولویت اجرا"],["business-rules-5","نسخه قواعد"]];
export default function BusinessRulesWorkspace(){
 const [tab,setTab]=useState("business-rules-1"),[d,setD]=useState<Data>({rules:[],conditions:[],actions:[],versions:[],priorities:[]}),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [ruleId,setRuleId]=useState(""),[ruleKey,setRuleKey]=useState(""),[title,setTitle]=useState(""),[eventKey,setEventKey]=useState(""),[description,setDescription]=useState(""),[priority,setPriority]=useState("100");
 const [fieldKey,setFieldKey]=useState(""),[operator,setOperator]=useState("eq"),[comparison,setComparison]=useState(""),[actionKey,setActionKey]=useState(""),[actionType,setActionType]=useState(""),[parameters,setParameters]=useState("{}"),[changeNote,setChangeNote]=useState("");
 const load=async()=>{const r=await fetch(api+"/api/business-rules/overview",{credentials:"include"});const b=await r.json();if(!r.ok)throw Error(b.error||"خطا");setD(b)};
 useEffect(()=>{const p=new URLSearchParams(location.search);setTab(p.get("tab")||"business-rules-1");load().catch(e=>setError(e.message))},[]);
 const post=async(path:string,body:any)=>{setSaving(true);setError("");try{const r=await fetch(api+path,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(body)});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"عملیات انجام نشد");await load();return b}catch(e){setError(e instanceof Error?e.message:"خطا");throw e}finally{setSaving(false)}};
 const patch=async(path:string,body:any)=>{setSaving(true);setError("");try{const r=await fetch(api+path,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(body)});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ویرایش انجام نشد");await load();return b}catch(e){setError(e instanceof Error?e.message:"خطا");throw e}finally{setSaving(false)}};
 const remove=async(path:string)=>{const r=await fetch(api+path,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);throw Error(b?.error||"حذف انجام نشد")}await load()};
 const createRule=()=>post("/api/business-rules/rules",{ruleKey,title,eventKey,description,priority:Number(priority)||100});
 const addCondition=()=>post("/api/business-rules/rules/"+ruleId+"/conditions",{fieldKey,operator,comparisonValue:comparison,sortOrder:d.conditions.filter(x=>x.rule_id===ruleId).length});
 const addAction=()=>post("/api/business-rules/rules/"+ruleId+"/actions",{actionKey,actionType,parameters:JSON.parse(parameters||"{}"),sortOrder:d.actions.filter(x=>x.rule_id===ruleId).length});
 return <main className={styles.wrap} dir="rtl"><header><div><span>منوی مرکزی سازمان · ۰۶</span><h1>قواعد کسب‌وکار</h1><p>موتور قواعد برای کنترل شرط، اقدام، اولویت و انتشار نسخه‌ها</p></div><button onClick={()=>load()}>به‌روزرسانی</button></header><nav>{tabs.map(([k,t])=><a className={tab===k?styles.active:""} href={"/modules/?code=06-business-rules&tab="+k} key={k}>{t}</a>)}</nav>{error&&<div className={styles.error}>{error}</div>}
 {tab==="business-rules-1"&&<section className={styles.grid}><div className={styles.panel}><h2>قاعده جدید</h2><div className={styles.form}><input placeholder="شناسه قاعده" value={ruleKey} onChange={e=>setRuleKey(e.target.value)}/><input placeholder="عنوان قاعده" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="رویداد محرک" value={eventKey} onChange={e=>setEventKey(e.target.value)}/><input placeholder="اولویت" type="number" value={priority} onChange={e=>setPriority(e.target.value)}/><textarea placeholder="شرح" value={description} onChange={e=>setDescription(e.target.value)}/><button disabled={saving} onClick={createRule}>ثبت قاعده</button></div></div><div className={styles.panel}><h2>قواعد فعال و پیش‌نویس</h2>{d.rules.map(x=><article key={x.id}><div><b>{x.title}</b><small>{x.rule_key} · {x.event_key} · {x.status} · اولویت {x.priority}</small></div><div className={styles.actions}><button onClick={()=>{setRuleId(x.id);setTab("business-rules-2")}}>شرایط</button><button onClick={()=>{setRuleId(x.id);setTab("business-rules-3")}}>اقدامات</button><button onClick={()=>{setRuleId(x.id);setTab("business-rules-5")}}>نسخه‌ها</button><button className={styles.danger} onClick={()=>remove("/api/business-rules/rules/"+x.id)}>حذف</button></div></article>)}</div></section>}
 {tab==="business-rules-2"&&<section className={styles.grid}><div className={styles.panel}><h2>افزودن شرط</h2><select value={ruleId} onChange={e=>setRuleId(e.target.value)}><option value="">قاعده را انتخاب کنید</option>{d.rules.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select><div className={styles.form}><input placeholder="کلید فیلد" value={fieldKey} onChange={e=>setFieldKey(e.target.value)}/><select value={operator} onChange={e=>setOperator(e.target.value)}><option value="eq">برابر</option><option value="neq">نابرابر</option><option value="gt">بزرگ‌تر</option><option value="gte">بزرگ‌تر یا مساوی</option><option value="lt">کوچک‌تر</option><option value="lte">کوچک‌تر یا مساوی</option><option value="contains">شامل</option><option value="in">در فهرست</option><option value="exists">وجود دارد</option></select><input placeholder="مقدار مقایسه" value={comparison} onChange={e=>setComparison(e.target.value)}/><button onClick={addCondition}>افزودن شرط</button></div></div><div className={styles.panel}><h2>شرایط ثبت‌شده</h2>{d.conditions.map(x=><article key={x.id}><span>{x.rule_title}</span><span>{x.field_key} · {x.operator} · {JSON.stringify(x.comparison_value)}</span><button className={styles.danger} onClick={()=>remove("/api/business-rules/conditions/"+x.id)}>حذف</button></article>)}</div></section>}
 {tab==="business-rules-3"&&<section className={styles.grid}><div className={styles.panel}><h2>افزودن اقدام</h2><select value={ruleId} onChange={e=>setRuleId(e.target.value)}><option value="">قاعده را انتخاب کنید</option>{d.rules.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select><div className={styles.form}><input placeholder="کلید اقدام" value={actionKey} onChange={e=>setActionKey(e.target.value)}/><input placeholder="نوع اقدام" value={actionType} onChange={e=>setActionType(e.target.value)}/><textarea placeholder='پارامترهای JSON مانند {"channel":"sms"}' value={parameters} onChange={e=>setParameters(e.target.value)}/><button onClick={addAction}>افزودن اقدام</button></div></div><div className={styles.panel}><h2>اقدامات ثبت‌شده</h2>{d.actions.map(x=><article key={x.id}><span>{x.rule_title}</span><span>{x.action_key} · {x.action_type}</span><button className={styles.danger} onClick={()=>remove("/api/business-rules/actions/"+x.id)}>حذف</button></article>)}</div></section>}
 {tab==="business-rules-4"&&<section className={styles.panel}><h2>اولویت اجرای قواعد</h2>{d.rules.sort((a,b)=>a.priority-b.priority).map(x=><article key={x.id}><div><b>{x.title}</b><small>اولویت فعلی: {x.priority}</small></div><div className={styles.formInline}><input defaultValue={x.priority} id={"priority-"+x.id} type="number"/><button onClick={()=>post("/api/business-rules/rules/"+x.id+"/priority",{priority:Number((document.getElementById("priority-"+x.id) as HTMLInputElement).value),reason:"به‌روزرسانی اولویت"})}>ثبت اولویت</button></div></article>)}</section>}
 {tab==="business-rules-5"&&<section className={styles.panel}><h2>نسخه قواعد</h2>{d.rules.map(x=><article key={x.id}><div><b>{x.title}</b><small>{d.versions.filter(v=>v.rule_id===x.id).length} نسخه</small></div><div className={styles.actions}><button onClick={()=>post("/api/business-rules/rules/"+x.id+"/versions",{changeNote:changeNote||"ایجاد نسخه جدید"})}>ایجاد نسخه</button>{d.versions.filter(v=>v.rule_id===x.id).slice(0,3).map(v=><button key={v.id} disabled={v.status==="published"} onClick={()=>post("/api/business-rules/versions/"+v.id+"/publish",{})}>{v.status==="published"?"منتشر شده":"انتشار v"+v.version_no}</button>)}</div></article>)}<textarea placeholder="یادداشت تغییر نسخه" value={changeNote} onChange={e=>setChangeNote(e.target.value)}/></section>}
 </main>;
}
