"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./CollateralGuaranteesWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه"],["collateral","وثایق"],["guarantor","ضامنین"],["evaluation","ارزیابی"],["release","آزادسازی"]];
const initial={contract:"",type:"وثیقه",code:"",person:"",security:"ملک",description:"",estimated:"",accepted:"",valuation:"",document:"",limit:"",status:"ثبت اولیه",release:"",notes:""};

export default function CollateralGuaranteesWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/16-collateral-guarantees/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت اطلاعات وثایق انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="collateral")a=a.filter(x=>x.data?.["record-type"]==="وثیقه");if(tab==="guarantor")a=a.filter(x=>x.data?.["record-type"]==="ضامن");if(tab==="evaluation")a=a.filter(x=>["در انتظار ارزیابی","تأیید شده"].includes(String(x.data?.["security-status"]||"")));if(tab==="release")a=a.filter(x=>x.data?.["security-status"]==="آزاد شده");return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const save=async()=>{if(!String(form.contract||"").trim()||!String(form.code||"").trim()||!String(form.person||"").trim())return setError("شماره قرارداد، کد وثیقه/ضمانت و شناسه مالک یا ضامن الزامی است.");setSaving(true);setError("");try{const data={"contract-code":form.contract,"record-type":form.type,"security-code":form.code,"person-id":form.person,"security-type":form.security,description:form.description,"estimated-value":Number(form.estimated||0),"accepted-value":Number(form.accepted||0),"valuation-date":form.valuation,"document-reference":form.document,"guarantee-limit":Number(form.limit||0),"security-status":form.status,"release-date":form.release,notes:form.notes};const r=await fetch(API+"/api/platform/modules/16-collateral-guarantees/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"collateral-guarantee",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({contract:d["contract-code"]||"",type:d["record-type"]||"وثیقه",code:d["security-code"]||"",person:d["person-id"]||"",security:d["security-type"]||"ملک",description:d.description||"",estimated:d["estimated-value"]??"",accepted:d["accepted-value"]??"",valuation:d["valuation-date"]||"",document:d["document-reference"]||"",limit:d["guarantee-limit"]??"",status:d["security-status"]||"ثبت اولیه",release:d["release-date"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const changeStatus=async(r:R,status:string)=>{const d={...r.data,"security-status":status,...(status==="آزاد شده"?{"release-date":new Date().toISOString().slice(0,10)}:{})};const x=await fetch(API+"/api/platform/modules/16-collateral-guarantees/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"تغییر وضعیت انجام نشد.");return}await load()};
 const remove=async(id:number)=>{if(!confirm("این سابقه حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/16-collateral-guarantees/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۱۶</span><h1>وثایق و ضمانت‌ها</h1><p>مدیریت چرخه ثبت، ارزیابی، تأیید، نگهداری و آزادسازی تضمین‌های قرارداد.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>کل سوابق</small><b>{items.filter(x=>x.data?.["record-type"]==="وثیقه").length.toLocaleString("fa-IR")}</b><small>وثیقه</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش تضمین":"ثبت وثیقه یا ضامن"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>شماره قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label><label>نوع تضمین *<select value={String(form.type)} onChange={e=>set("type",e.target.value)}><option>وثیقه</option><option>ضامن</option></select></label>
    <label>کد وثیقه/ضمانت *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>شناسه مالک/ضامن *<input value={String(form.person)} onChange={e=>set("person",e.target.value)}/></label>
    <label>نوع وثیقه/ضمانت<select value={String(form.security)} onChange={e=>set("security",e.target.value)}>{["ملک","خودرو","سپرده بانکی","ضمانت شخصی","چک","سفته","سایر"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>وضعیت<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["ثبت اولیه","در انتظار ارزیابی","تأیید شده","در رهن","آزاد شده","رد شده"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>ارزش برآوردی<input type="number" min="0" value={String(form.estimated)} onChange={e=>set("estimated",e.target.value)}/></label><label>ارزش پذیرفته‌شده<input type="number" min="0" value={String(form.accepted)} onChange={e=>set("accepted",e.target.value)}/></label>
    <label>تاریخ ارزیابی<input type="date" value={String(form.valuation)} onChange={e=>set("valuation",e.target.value)}/></label><label>تاریخ آزادسازی<input type="date" value={String(form.release)} onChange={e=>set("release",e.target.value)}/></label>
    <label>مرجع سند<input value={String(form.document)} onChange={e=>set("document",e.target.value)}/></label><label>سقف ضمانت<input type="number" min="0" value={String(form.limit)} onChange={e=>set("limit",e.target.value)}/></label>
    <label className={styles.full}>شرح<textarea rows={2} value={String(form.description)} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق ثبت‌شده</small><h2>فهرست تضمین‌ها</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در قرارداد، کد یا شناسه..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["record-type"]||"")} · {String(r.data?.["security-type"]||"")} · {String(r.data?.["security-status"]||"")}</small><span>{Number(r.data?.["accepted-value"]||r.data?.["guarantee-limit"]||0).toLocaleString("fa-IR")} ریال</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{tab==="evaluation"&&<button className={styles.confirm} onClick={()=>changeStatus(r,"تأیید شده")}>تأیید ارزیابی</button>}{tab==="release"&&<button className={styles.release} onClick={()=>changeStatus(r,"آزاد شده")}>آزادسازی</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>رکوردی ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
