"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./CollectionWorkflowWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه کارتابل"],["new","جدید"],["follow","در حال پیگیری"],["waiting","در انتظار بدهکار"],["escalated","ارجاع شده"]];
const init={code:"",delinquency:"",contract:"",borrower:"",assignment:"",collector:"",priority:"عادی",channel:"تماس تلفنی",attempts:"",lastAction:"",nextAction:"",contact:"موفق",commitDate:"",commitAmount:"",actionResult:"",escalation:"بدون ارجاع",status:"جدید",completion:"",createdBy:"",notes:""};
export default function CollectionWorkflowWorkspace(){
const[tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...init}),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/28-collection-workflow/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت کارتابل وصول انجام نشد");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>items.filter(r=>{const s=String(r.data?.["workflow-status"]||"جدید");return tab==="all"||tab==="new"?tab==="all"||s==="جدید":tab==="follow"?s==="در حال پیگیری":tab==="waiting"?s==="در انتظار اقدام بدهکار":s==="ارجاع شده"}),[items,tab]);
const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...init})};
const save=async()=>{if(["code","delinquency","contract","borrower","assignment","collector"].some(k=>!String(form[k]||"").trim()))return setError("کد پرونده، معوق، قرارداد، بدهکار، تاریخ ارجاع و کارشناس الزامی است.");setSaving(true);try{const data={"case-code":form.code,"delinquency-code":form.delinquency,"contract-code":form.contract,"borrower-id":form.borrower,"assignment-date":form.assignment,"collector":form.collector,"priority":form.priority,"channel":form.channel,"attempt-count":Number(form.attempts||0),"last-action-date":form.lastAction,"next-action-date":form.nextAction,"contact-result":form.contact,"commitment-date":form.commitDate,"commitment-amount":Number(form.commitAmount||0),"action-result":form.actionResult,"escalation-level":form.escalation,"workflow-status":form.status,"completion-reason":form.completion,"created-by":form.createdBy,"notes":form.notes};const r=await fetch(API+"/api/platform/modules/28-collection-workflow/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"collection-workflow",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data})}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت کارتابل انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["case-code"]||"",delinquency:d["delinquency-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",assignment:d["assignment-date"]||"",collector:d.collector||"",priority:d.priority||"عادی",channel:d.channel||"تماس تلفنی",attempts:d["attempt-count"]??"",lastAction:d["last-action-date"]||"",nextAction:d["next-action-date"]||"",contact:d["contact-result"]||"موفق",commitDate:d["commitment-date"]||"",commitAmount:d["commitment-amount"]??"",actionResult:d["action-result"]||"",escalation:d["escalation-level"]||"بدون ارجاع",status:d["workflow-status"]||"جدید",completion:d["completion-reason"]||"",createdBy:d["created-by"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
const patch=async(r:R,ch:Record<string,unknown>)=>{const d={...r.data,...ch};const x=await fetch(API+"/api/platform/modules/28-collection-workflow/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:String(d["workflow-status"]||r.status),data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد");return}await load()};
const contact=(r:R)=>patch(r,{"workflow-status":"در حال پیگیری","last-action-date":new Date().toISOString().slice(0,10),"contact-result":"موفق","attempt-count":Number(r.data?.["attempt-count"]||0)+1});
const commit=(r:R)=>patch(r,{"workflow-status":"در انتظار تعهد","commitment-date":new Date().toISOString().slice(0,10),"contact-result":"وعده پرداخت"});
const escalate=(r:R)=>patch(r,{"workflow-status":"ارجاع شده","escalation-level":"سرپرست وصول"});
const complete=(r:R)=>patch(r,{"workflow-status":"تکمیل شده","completion-reason":"توافق پرداخت"});
const remove=async(id:number)=>{const x=await fetch(API+"/api/platform/modules/28-collection-workflow/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!x.ok){setError("حذف انجام نشد");return}await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۸</span><h1>کارتابل و عملیات وصول تسهیلات</h1><p>مدیریت ارجاع، پیگیری، تعهد پرداخت و گردش عملیات وصول در یک کارتابل متمرکز.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>پرونده وصول</small><b>{items.filter(x=>x.data?.["workflow-status"]==="در حال پیگیری").length.toLocaleString("fa-IR")}</b><small>در حال پیگیری</small></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش پرونده وصول":"ارجاع پرونده به کارتابل"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
<div className={styles.fields}><label>کد پرونده *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد پرونده معوق *<input value={String(form.delinquency)} onChange={e=>set("delinquency",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label><label>شناسه بدهکار *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label><label>تاریخ ارجاع *<input type="date" value={String(form.assignment)} onChange={e=>set("assignment",e.target.value)}/></label><label>کارشناس وصول *<input value={String(form.collector)} onChange={e=>set("collector",e.target.value)}/></label><label>اولویت<select value={String(form.priority)} onChange={e=>set("priority",e.target.value)}>{["عادی","مهم","فوری","بحرانی"].map(x=><option key={x}>{x}</option>)}</select></label><label>کانال پیگیری<select value={String(form.channel)} onChange={e=>set("channel",e.target.value)}>{["تماس تلفنی","پیامک","اعلان سامانه","مراجعه حضوری","نامه رسمی","پیگیری حقوقی"].map(x=><option key={x}>{x}</option>)}</select></label><label>تعداد پیگیری<input type="number" min="0" value={String(form.attempts)} onChange={e=>set("attempts",e.target.value)}/></label><label>آخرین اقدام<input type="date" value={String(form.lastAction)} onChange={e=>set("lastAction",e.target.value)}/></label><label>اقدام بعدی<input type="date" value={String(form.nextAction)} onChange={e=>set("nextAction",e.target.value)}/></label><label>نتیجه تماس<select value={String(form.contact)} onChange={e=>set("contact",e.target.value)}>{["موفق","عدم پاسخ","وعده پرداخت","رد تماس","شماره نامعتبر","نیازمند مراجعه"].map(x=><option key={x}>{x}</option>)}</select></label><label>تاریخ تعهد<input type="date" value={String(form.commitDate)} onChange={e=>set("commitDate",e.target.value)}/></label><label>مبلغ تعهد<input type="number" min="0" value={String(form.commitAmount)} onChange={e=>set("commitAmount",e.target.value)}/></label><label>سطح ارجاع<select value={String(form.escalation)} onChange={e=>set("escalation",e.target.value)}>{["بدون ارجاع","سرپرست وصول","مدیریت اعتبارات","واحد حقوقی","اجرای تعهدات"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت کارتابل<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["جدید","در حال پیگیری","در انتظار اقدام بدهکار","در انتظار تعهد","ارجاع شده","تکمیل شده","مختومه"].map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.full}>نتیجه اقدام<textarea rows={2} value={String(form.actionResult)} onChange={e=>set("actionResult",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label></div>
<button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت در PostgreSQL"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>سوابق واقعی</small><h2>کارتابل وصول</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد پرونده، قرارداد یا بدهکار..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>کارشناس: {String(r.data?.collector||"")} · اولویت: {String(r.data?.priority||"")}</small><span>وضعیت: {String(r.data?.["workflow-status"]||"")} · پیگیری: {String(r.data?.["attempt-count"]||0)}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{["جدید","در حال پیگیری"].includes(String(r.data?.["workflow-status"]||""))&&<button className={styles.follow} onClick={()=>contact(r)}>ثبت پیگیری</button>}{["در حال پیگیری","در انتظار اقدام بدهکار"].includes(String(r.data?.["workflow-status"]||""))&&<button className={styles.promise} onClick={()=>commit(r)}>تعهد پرداخت</button>}{!["ارجاع شده","تکمیل شده","مختومه"].includes(String(r.data?.["workflow-status"]||""))&&<button className={styles.escalate} onClick={()=>escalate(r)}>ارجاع</button>}{!["تکمیل شده","مختومه"].includes(String(r.data?.["workflow-status"]||""))&&<button className={styles.complete} onClick={()=>complete(r)}>تکمیل</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>پرونده‌ای در این کارتابل ثبت نشده است.</div>}</div></section></section></main>}