"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./CreditDisbursementWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه پرداخت‌ها"],["pending","در انتظار پرداخت"],["processing","در حال پردازش"],["paid","پرداخت شده"],["failed","ناموفق/برگشتی"]];
const initial={code:"",contract:"",application:"",borrower:"",approved:"",amount:"",date:"",method:"واریز بانکی",account:"",reference:"",plan:"",confirmation:"در انتظار تأیید",status:"پیش‌نویس",processor:"",processed:"",failure:"",notes:""};

export default function CreditDisbursementWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/22-credit-disbursement/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت پرداخت‌ها انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="pending")a=a.filter(x=>["پیش‌نویس","در انتظار پرداخت"].includes(String(x.data?.["disbursement-status"]||"")));if(tab==="processing")a=a.filter(x=>x.data?.["disbursement-status"]==="در حال پردازش");if(tab==="paid")a=a.filter(x=>x.data?.["disbursement-status"]==="پرداخت شده");if(tab==="failed")a=a.filter(x=>["ناموفق","برگشت خورده"].includes(String(x.data?.["disbursement-status"]||"")));return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const save=async()=>{if(!String(form.code||"").trim()||!String(form.contract||"").trim()||!String(form.borrower||"").trim()||!String(form.amount||"").trim()||!String(form.date||"").trim())return setError("کد پرداخت، قرارداد، دریافت‌کننده، مبلغ پرداختی و تاریخ الزامی است.");setSaving(true);setError("");try{const data={"disbursement-code":form.code,"contract-code":form.contract,"application-code":form.application,"borrower-id":form.borrower,"approved-amount":Number(form.approved||0),"disbursement-amount":Number(form.amount||0),"disbursement-date":form.date,"payment-method":form.method,"bank-account":form.account,"bank-reference":form.reference,"installment-plan":form.plan,"recipient-confirmation":form.confirmation,"disbursement-status":form.status,"processed-by":form.processor,"processed-at":form.processed,"failure-reason":form.failure,notes:form.notes};const r=await fetch(API+"/api/platform/modules/22-credit-disbursement/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"credit-disbursement",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت پرداخت انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["disbursement-code"]||"",contract:d["contract-code"]||"",application:d["application-code"]||"",borrower:d["borrower-id"]||"",approved:d["approved-amount"]??"",amount:d["disbursement-amount"]??"",date:d["disbursement-date"]||"",method:d["payment-method"]||"واریز بانکی",account:d["bank-account"]||"",reference:d["bank-reference"]||"",plan:d["installment-plan"]||"",confirmation:d["recipient-confirmation"]||"در انتظار تأیید",status:d["disbursement-status"]||"پیش‌نویس",processor:d["processed-by"]||"",processed:d["processed-at"]||"",failure:d["failure-reason"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status?:string)=>{const d={...r.data,...changes};const x=await fetch(API+"/api/platform/modules/22-credit-disbursement/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:status||r.status,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const process=(r:R)=>patch(r,{"disbursement-status":"در حال پردازش","processed-by":"کاربر جاری","processed-at":new Date().toISOString()},"در حال پردازش");
 const confirmPayment=(r:R)=>patch(r,{"disbursement-status":"پرداخت شده","recipient-confirmation":"تأیید شده","processed-at":new Date().toISOString()},"پرداخت شده");
 const reverse=(r:R)=>patch(r,{"disbursement-status":"برگشت خورده"},"برگشت خورده");
 const remove=async(id:number)=>{if(!confirm("این پرداخت حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/22-credit-disbursement/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۲</span><h1>پرداخت تسهیلات</h1><p>مدیریت دستور پرداخت، پردازش، تأیید دریافت و کنترل برگشت پرداخت‌های تسهیلات.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>پرداخت</small><b>{items.filter(x=>x.data?.["disbursement-status"]==="پرداخت شده").length.toLocaleString("fa-IR")}</b><small>موفق</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش پرداخت":"ثبت پرداخت تسهیلات"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد پرداخت *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label>
    <label>کد درخواست اعتبار<input value={String(form.application)} onChange={e=>set("application",e.target.value)}/></label><label>شناسه دریافت‌کننده *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label>
    <label>مبلغ مصوب<input type="number" min="0" value={String(form.approved)} onChange={e=>set("approved",e.target.value)}/></label><label>مبلغ پرداختی *<input type="number" min="0" value={String(form.amount)} onChange={e=>set("amount",e.target.value)}/></label>
    <label>تاریخ پرداخت *<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label><label>روش پرداخت<select value={String(form.method)} onChange={e=>set("method",e.target.value)}>{["واریز بانکی","انتقال داخلی","پرداخت مرحله‌ای","سایر"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>حساب مقصد<input value={String(form.account)} onChange={e=>set("account",e.target.value)}/></label><label>مرجع بانکی<input value={String(form.reference)} onChange={e=>set("reference",e.target.value)}/></label>
    <label>برنامه بازپرداخت<input value={String(form.plan)} onChange={e=>set("plan",e.target.value)}/></label><label>تأیید دریافت<select value={String(form.confirmation)} onChange={e=>set("confirmation",e.target.value)}>{["در انتظار تأیید","تأیید شده","عدم تأیید"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>وضعیت پرداخت<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","در انتظار پرداخت","در حال پردازش","پرداخت شده","ناموفق","برگشت خورده","لغو شده"].map(x=><option key={x}>{x}</option>)}</select></label><label>پردازش‌کننده<input value={String(form.processor)} onChange={e=>set("processor",e.target.value)}/></label>
    <label>زمان پردازش<input type="datetime-local" value={String(form.processed).slice(0,16)} onChange={e=>set("processed",e.target.value)}/></label><label className={styles.full}>علت خطا<textarea rows={2} value={String(form.failure)} onChange={e=>set("failure",e.target.value)}/></label>
    <label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت پرداخت در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق ثبت‌شده</small><h2>صف پرداخت تسهیلات</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد پرداخت، قرارداد یا مرجع بانکی..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["disbursement-date"]||"")} · مبلغ: {String(r.data?.["disbursement-amount"]||0)} · {String(r.data?.["payment-method"]||"")}</small><span>وضعیت: {String(r.data?.["disbursement-status"]||"")} · مرجع: {String(r.data?.["bank-reference"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{["پیش‌نویس","در انتظار پرداخت"].includes(String(r.data?.["disbursement-status"]||""))&&<button className={styles.process} onClick={()=>process(r)}>پردازش</button>}{r.data?.["disbursement-status"]==="در حال پردازش"&&<button className={styles.confirm} onClick={()=>confirmPayment(r)}>تأیید پرداخت</button>}{r.data?.["disbursement-status"]==="پرداخت شده"&&<button className={styles.reverse} onClick={()=>reverse(r)}>برگشت</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>پرداختی ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
