"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./CreditScoringWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه ارزیابی‌ها"],["pending","در انتظار"],["scored","تکمیل‌شده"],["review","نیازمند بازبینی"],["risk","سطح ریسک"]];
const initial={code:"",applicant:"",application:"",date:"",score:"",risk:"متوسط",income:"",payment:"",debt:"",identity:"",status:"در انتظار بررسی",reviewer:"",notes:"",valid:""};

export default function CreditScoringWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/19-credit-scoring/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت ارزیابی‌ها انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="pending")a=a.filter(x=>["در انتظار بررسی","در حال ارزیابی"].includes(String(x.data?.["score-status"]||"")));if(tab==="scored")a=a.filter(x=>x.data?.["score-status"]==="تکمیل شده");if(tab==="review")a=a.filter(x=>x.data?.["score-status"]==="نیازمند بازبینی");if(tab==="risk")a=a.filter(x=>["زیاد","بحرانی"].includes(String(x.data?.["risk-level"]||"")));return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const save=async()=>{if(!String(form.code||"").trim()||!String(form.applicant||"").trim()||!String(form.date||"").trim())return setError("کد اعتبارسنجی، شناسه متقاضی و تاریخ ارزیابی الزامی است.");setSaving(true);setError("");try{const data={"scoring-code":form.code,"applicant-id":form.applicant,"application-code":form.application,"evaluation-date":form.date,"credit-score":Number(form.score||0),"risk-level":form.risk,"income-score":Number(form.income||0),"payment-history-score":Number(form.payment||0),"debt-score":Number(form.debt||0),"identity-score":Number(form.identity||0),"score-status":form.status,reviewer:form.reviewer,"review-notes":form.notes,"valid-until":form.valid};const r=await fetch(API+"/api/platform/modules/19-credit-scoring/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"credit-scoring",title:String(form.code)+" / "+String(form.applicant),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت ارزیابی انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["scoring-code"]||"",applicant:d["applicant-id"]||"",application:d["application-code"]||"",date:d["evaluation-date"]||"",score:d["credit-score"]??"",risk:d["risk-level"]||"متوسط",income:d["income-score"]??"",payment:d["payment-history-score"]??"",debt:d["debt-score"]??"",identity:d["identity-score"]??"",status:d["score-status"]||"در انتظار بررسی",reviewer:d.reviewer||"",notes:d["review-notes"]||"",valid:d["valid-until"]||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status?:string)=>{const d={...r.data,...changes};const x=await fetch(API+"/api/platform/modules/19-credit-scoring/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:status||r.status,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const calculate=(r:R)=>{const d=r.data;const vals=["income-score","payment-history-score","debt-score","identity-score"].map(k=>Number(d?.[k]||0));const score=Math.round(vals.reduce((a,b)=>a+b,0)/4);const risk=score>=80?"کم":score>=60?"متوسط":score>=40?"زیاد":"بحرانی";return patch(r,{"credit-score":score,"risk-level":risk,"score-status":"تکمیل شده"},"تکمیل شده")};
 const remove=async(id:number)=>{if(!confirm("این ارزیابی حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/19-credit-scoring/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۱۹</span><h1>اعتبارسنجی و امتیاز اعتباری</h1><p>ثبت ارزیابی، امتیازدهی و تعیین سطح ریسک متقاضیان بر پایه اطلاعات واقعی پرونده.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>ارزیابی</small><b>{items.filter(x=>x.data?.["score-status"]==="تکمیل شده").length.toLocaleString("fa-IR")}</b><small>تکمیل‌شده</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش ارزیابی":"ثبت ارزیابی اعتباری"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد اعتبارسنجی *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>شناسه متقاضی *<input value={String(form.applicant)} onChange={e=>set("applicant",e.target.value)}/></label>
    <label>کد درخواست اعتبار<input value={String(form.application)} onChange={e=>set("application",e.target.value)}/></label><label>تاریخ ارزیابی *<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label>
    <label>امتیاز نهایی<input type="number" min="0" max="100" value={String(form.score)} onChange={e=>set("score",e.target.value)}/></label><label>سطح ریسک<select value={String(form.risk)} onChange={e=>set("risk",e.target.value)}>{["کم","متوسط","زیاد","بحرانی"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>امتیاز درآمد<input type="number" min="0" max="100" value={String(form.income)} onChange={e=>set("income",e.target.value)}/></label><label>سابقه پرداخت<input type="number" min="0" max="100" value={String(form.payment)} onChange={e=>set("payment",e.target.value)}/></label>
    <label>امتیاز تعهدات<input type="number" min="0" max="100" value={String(form.debt)} onChange={e=>set("debt",e.target.value)}/></label><label>امتیاز هویتی<input type="number" min="0" max="100" value={String(form.identity)} onChange={e=>set("identity",e.target.value)}/></label>
    <label>وضعیت ارزیابی<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["در انتظار بررسی","در حال ارزیابی","تکمیل شده","نیازمند بازبینی","باطل شده"].map(x=><option key={x}>{x}</option>)}</select></label><label>ارزیاب<input value={String(form.reviewer)} onChange={e=>set("reviewer",e.target.value)}/></label>
    <label>اعتبار تا<input type="date" value={String(form.valid)} onChange={e=>set("valid",e.target.value)}/></label><label className={styles.full}>یادداشت ارزیابی<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت ارزیابی در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق ثبت‌شده</small><h2>صف اعتبارسنجی</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد، متقاضی یا درخواست..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>امتیاز: {String(r.data?.["credit-score"]||0)} · ریسک: {String(r.data?.["risk-level"]||"")} · {String(r.data?.["score-status"]||"")}</small><span>درآمد {String(r.data?.["income-score"]||0)} · پرداخت {String(r.data?.["payment-history-score"]||0)} · تعهدات {String(r.data?.["debt-score"]||0)}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{(tab==="all"||tab==="pending")&&<button className={styles.calculate} onClick={()=>calculate(r)}>محاسبه</button>}{tab==="review"&&<button className={styles.confirm} onClick={()=>patch(r,{"score-status":"تکمیل شده"},"تکمیل شده")}>تأیید</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>ارزیابی ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
