"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./CreditDecisionsWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه مصوبات"],["pending","در انتظار تصمیم"],["decided","تصمیم‌گیری شده"],["published","ابلاغ شده"],["expired","منقضی/لغو"]];
const initial={code:"",application:"",scoring:"",applicant:"",requested:"",approved:"",term:"",rate:"",decision:"تأیید",date:"",maker:"",conditions:"",reason:"",status:"پیش‌نویس",valid:"",notes:""};

export default function CreditDecisionsWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/20-credit-decisions/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت مصوبات انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="pending")a=a.filter(x=>["پیش‌نویس","در انتظار تصمیم"].includes(String(x.data?.["decision-status"]||"")));if(tab==="decided")a=a.filter(x=>x.data?.["decision-status"]==="تصمیم‌گیری شده");if(tab==="published")a=a.filter(x=>x.data?.["decision-status"]==="ابلاغ شده");if(tab==="expired")a=a.filter(x=>["منقضی","لغو شده"].includes(String(x.data?.["decision-status"]||"")));return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const save=async()=>{if(!String(form.code||"").trim()||!String(form.application||"").trim()||!String(form.applicant||"").trim()||!String(form.requested||"").trim())return setError("کد تصمیم، کد درخواست، شناسه متقاضی و مبلغ درخواستی الزامی است.");setSaving(true);setError("");try{const data={"decision-code":form.code,"application-code":form.application,"scoring-code":form.scoring,"applicant-id":form.applicant,"requested-amount":Number(form.requested||0),"approved-amount":Number(form.approved||0),"approved-term":Number(form.term||0),"approved-rate":Number(form.rate||0),decision:form.decision,"decision-date":form.date,"decision-maker":form.maker,conditions:form.conditions,reason:form.reason,"decision-status":form.status,"valid-until":form.valid,notes:form.notes};const r=await fetch(API+"/api/platform/modules/20-credit-decisions/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"credit-decision",title:String(form.code)+" / "+String(form.application),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت مصوبه انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["decision-code"]||"",application:d["application-code"]||"",scoring:d["scoring-code"]||"",applicant:d["applicant-id"]||"",requested:d["requested-amount"]??"",approved:d["approved-amount"]??"",term:d["approved-term"]??"",rate:d["approved-rate"]??"",decision:d.decision||"تأیید",date:d["decision-date"]||"",maker:d["decision-maker"]||"",conditions:d.conditions||"",reason:d.reason||"",status:d["decision-status"]||"پیش‌نویس",valid:d["valid-until"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status?:string)=>{const d={...r.data,...changes};const x=await fetch(API+"/api/platform/modules/20-credit-decisions/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:status||r.status,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const decide=(r:R)=>patch(r,{"decision-status":"تصمیم‌گیری شده","decision-date":new Date().toISOString().slice(0,10)},"تصمیم‌گیری شده");
 const publish=(r:R)=>patch(r,{"decision-status":"ابلاغ شده"},"ابلاغ شده");
 const remove=async(id:number)=>{if(!confirm("این مصوبه حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/20-credit-decisions/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۰</span><h1>تصمیم‌گیری اعتباری</h1><p>ثبت، بررسی، تصمیم و ابلاغ مصوبات اعتباری متصل به درخواست و اعتبارسنجی.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>مصوبه</small><b>{items.filter(x=>x.data?.["decision-status"]==="ابلاغ شده").length.toLocaleString("fa-IR")}</b><small>ابلاغ‌شده</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش مصوبه":"ثبت مصوبه اعتباری"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد تصمیم *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد درخواست اعتبار *<input value={String(form.application)} onChange={e=>set("application",e.target.value)}/></label>
    <label>کد اعتبارسنجی<input value={String(form.scoring)} onChange={e=>set("scoring",e.target.value)}/></label><label>شناسه متقاضی *<input value={String(form.applicant)} onChange={e=>set("applicant",e.target.value)}/></label>
    <label>مبلغ درخواستی *<input type="number" min="0" value={String(form.requested)} onChange={e=>set("requested",e.target.value)}/></label><label>مبلغ مصوب<input type="number" min="0" value={String(form.approved)} onChange={e=>set("approved",e.target.value)}/></label>
    <label>مدت مصوب (ماه)<input type="number" min="0" value={String(form.term)} onChange={e=>set("term",e.target.value)}/></label><label>نرخ مصوب<input type="number" min="0" step="0.01" value={String(form.rate)} onChange={e=>set("rate",e.target.value)}/></label>
    <label>نتیجه تصمیم<select value={String(form.decision)} onChange={e=>set("decision",e.target.value)}>{["تأیید","تأیید مشروط","رد","نیازمند بررسی بیشتر"].map(x=><option key={x}>{x}</option>)}</select></label><label>تاریخ تصمیم<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label>
    <label>تصمیم‌گیرنده<input value={String(form.maker)} onChange={e=>set("maker",e.target.value)}/></label><label>وضعیت مصوبه<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","در انتظار تصمیم","تصمیم‌گیری شده","ابلاغ شده","منقضی","لغو شده"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>اعتبار مصوبه تا<input type="date" value={String(form.valid)} onChange={e=>set("valid",e.target.value)}/></label><label className={styles.full}>شروط مصوبه<textarea rows={2} value={String(form.conditions)} onChange={e=>set("conditions",e.target.value)}/></label>
    <label className={styles.full}>دلایل تصمیم<textarea rows={2} value={String(form.reason)} onChange={e=>set("reason",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت مصوبه در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق ثبت‌شده</small><h2>صف تصمیم‌های اعتباری</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد تصمیم، درخواست یا متقاضی..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.decision||"")} · مبلغ درخواستی: {String(r.data?.["requested-amount"]||0)} · مصوب: {String(r.data?.["approved-amount"]||0)}</small><span>وضعیت: {String(r.data?.["decision-status"]||"")} · تصمیم‌گیرنده: {String(r.data?.["decision-maker"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{["پیش‌نویس","در انتظار تصمیم"].includes(String(r.data?.["decision-status"]||""))&&<button className={styles.decide} onClick={()=>decide(r)}>ثبت تصمیم</button>}{r.data?.["decision-status"]==="تصمیم‌گیری شده"&&<button className={styles.publish} onClick={()=>publish(r)}>ابلاغ</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>مصوبه‌ای ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
