"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./CreditCommitteeWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه جلسات"],["planned","برنامه‌ریزی شده"],["active","در حال برگزاری"],["held","برگزار شده"],["closed","مختومه"]];
const initial={code:"",application:"",decision:"",date:"",time:"",type:"اعتباری",chair:"",secretary:"",members:"",requested:"",proposed:"",result:"تأیید",reason:"",conditions:"",status:"برنامه‌ریزی شده",minutes:"",next:"",notes:""};

export default function CreditCommitteeWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/21-credit-committee/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت جلسات کمیته انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="planned")a=a.filter(x=>x.data?.["meeting-status"]==="برنامه‌ریزی شده");if(tab==="active")a=a.filter(x=>x.data?.["meeting-status"]==="در حال برگزاری");if(tab==="held")a=a.filter(x=>x.data?.["meeting-status"]==="برگزار شده");if(tab==="closed")a=a.filter(x=>x.data?.["meeting-status"]==="مختومه");return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const save=async()=>{if(!String(form.code||"").trim()||!String(form.application||"").trim()||!String(form.date||"").trim())return setError("کد جلسه، کد درخواست و تاریخ جلسه الزامی است.");setSaving(true);setError("");try{const data={"committee-code":form.code,"application-code":form.application,"decision-code":form.decision,"meeting-date":form.date,"meeting-time":form.time,"committee-type":form.type,chairperson:form.chair,secretary:form.secretary,members:form.members,"requested-amount":Number(form.requested||0),"proposed-amount":Number(form.proposed||0),decision:form.result,"decision-reason":form.reason,conditions:form.conditions,"meeting-status":form.status,"minutes-reference":form.minutes,"next-review-date":form.next,notes:form.notes};const r=await fetch(API+"/api/platform/modules/21-credit-committee/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"credit-committee",title:String(form.code)+" / "+String(form.application),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت جلسه انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["committee-code"]||"",application:d["application-code"]||"",decision:d["decision-code"]||"",date:d["meeting-date"]||"",time:d["meeting-time"]||"",type:d["committee-type"]||"اعتباری",chair:d.chairperson||"",secretary:d.secretary||"",members:d.members||"",requested:d["requested-amount"]??"",proposed:d["proposed-amount"]??"",result:d.decision||"تأیید",reason:d["decision-reason"]||"",conditions:d.conditions||"",status:d["meeting-status"]||"برنامه‌ریزی شده",minutes:d["minutes-reference"]||"",next:d["next-review-date"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status?:string)=>{const d={...r.data,...changes};const x=await fetch(API+"/api/platform/modules/21-credit-committee/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:status||r.status,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const start=(r:R)=>patch(r,{"meeting-status":"در حال برگزاری"},"در حال برگزاری");
 const hold=(r:R)=>patch(r,{"meeting-status":"برگزار شده"},"برگزار شده");
 const close=(r:R)=>patch(r,{"meeting-status":"مختومه"},"مختومه");
 const remove=async(id:number)=>{if(!confirm("این جلسه کمیته حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/21-credit-committee/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۱</span><h1>کمیته اعتباری</h1><p>مدیریت جلسات، اعضا، بررسی درخواست‌ها، ثبت نتیجه و مختومه‌سازی فرآیند کمیته اعتباری.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>جلسه</small><b>{items.filter(x=>x.data?.["meeting-status"]==="برگزار شده").length.toLocaleString("fa-IR")}</b><small>برگزارشده</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش جلسه":"ثبت جلسه کمیته"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد جلسه *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد درخواست اعتبار *<input value={String(form.application)} onChange={e=>set("application",e.target.value)}/></label>
    <label>کد تصمیم اعتباری<input value={String(form.decision)} onChange={e=>set("decision",e.target.value)}/></label><label>تاریخ جلسه *<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label>
    <label>ساعت جلسه<input value={String(form.time)} onChange={e=>set("time",e.target.value)}/></label><label>نوع کمیته<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["اعتباری","تجدیدنظر","ریسک","مدیریت اعتبارات"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>رئیس جلسه<input value={String(form.chair)} onChange={e=>set("chair",e.target.value)}/></label><label>دبیر جلسه<input value={String(form.secretary)} onChange={e=>set("secretary",e.target.value)}/></label>
    <label className={styles.full}>اعضای کمیته<textarea rows={2} value={String(form.members)} onChange={e=>set("members",e.target.value)}/></label>
    <label>مبلغ درخواست<input type="number" min="0" value={String(form.requested)} onChange={e=>set("requested",e.target.value)}/></label><label>مبلغ پیشنهادی<input type="number" min="0" value={String(form.proposed)} onChange={e=>set("proposed",e.target.value)}/></label>
    <label>نتیجه کمیته<select value={String(form.result)} onChange={e=>set("result",e.target.value)}>{["تأیید","تأیید مشروط","رد","ارجاع برای بررسی بیشتر"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت جلسه<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["برنامه‌ریزی شده","در حال برگزاری","برگزار شده","لغو شده","مختومه"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label className={styles.full}>دلایل تصمیم<textarea rows={2} value={String(form.reason)} onChange={e=>set("reason",e.target.value)}/></label><label className={styles.full}>شروط مصوبه<textarea rows={2} value={String(form.conditions)} onChange={e=>set("conditions",e.target.value)}/></label>
    <label>مرجع صورتجلسه<input value={String(form.minutes)} onChange={e=>set("minutes",e.target.value)}/></label><label>تاریخ بازبینی<input type="date" value={String(form.next)} onChange={e=>set("next",e.target.value)}/></label>
    <label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت جلسه در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق ثبت‌شده</small><h2>جلسات کمیته</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد جلسه، درخواست یا صورتجلسه..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["committee-type"]||"")} · {String(r.data?.["meeting-date"]||"")} · {String(r.data?.decision||"")}</small><span>وضعیت: {String(r.data?.["meeting-status"]||"")} · مبلغ پیشنهادی: {String(r.data?.["proposed-amount"]||0)}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{r.data?.["meeting-status"]==="برنامه‌ریزی شده"&&<button className={styles.start} onClick={()=>start(r)}>شروع جلسه</button>}{r.data?.["meeting-status"]==="در حال برگزاری"&&<button className={styles.hold} onClick={()=>hold(r)}>ثبت نتیجه جلسه</button>}{r.data?.["meeting-status"]==="برگزار شده"&&<button className={styles.close} onClick={()=>close(r)}>مختومه</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>جلسه‌ای ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
