"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./Customer360Workspace.module.css";
type D={customers:any[];interactions:any[];purchases:any[];financial:any[]};
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["customer-360-1","پرونده مشتری"],["customer-360-2","مشخصات هویتی"],["customer-360-3","تعاملات"],["customer-360-4","سوابق خرید"],["customer-360-5","نمای مالی"]];
export default function Customer360Workspace(){
 const [tab,setTab]=useState("customer-360-1"),[d,setD]=useState<D>({customers:[],interactions:[],purchases:[],financial:[]}),[selected,setSelected]=useState<any>(null),[name,setName]=useState(""),[no,setNo]=useState(""),[mobile,setMobile]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{const r=await fetch(api+"/api/customer-360/overview",{credentials:"include"});const b=await r.json();if(!r.ok)throw Error(b.error||"خطا");setD(b)};
 useEffect(()=>{const p=new URLSearchParams(location.search);setTab(p.get("tab")||"customer-360-1");load().catch(e=>setError(e.message))},[]);
 const post=async(path:string,body:any)=>{setSaving(true);try{const r=await fetch(api+path,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error||"خطا");await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const chosen=selected||d.customers[0];
 const customerRows=useMemo(()=>d.customers,[d.customers]);
 return <main className={styles.wrap} dir="rtl"><header><div><span>منوی مرکزی سازمان · ۰۴</span><h1>مشتری ۳۶۰</h1><p>پرونده یکپارچه مشتری، هویت، تعاملات، خرید و نمای مالی</p></div><button onClick={()=>load()}>به‌روزرسانی</button></header><nav>{tabs.map(([k,t])=><a key={k} className={tab===k?"active":""} href={"/modules/?code=04-customer-360&tab="+k}>{t}</a>)}</nav>{error&&<div className={styles.error}>{error}</div>}
 {tab==="customer-360-1"&&<section className={styles.grid}><div className={styles.panel}><h2>ثبت پرونده مشتری</h2><div className={styles.form}><input placeholder="شماره مشتری" value={no} onChange={e=>setNo(e.target.value)}/><input placeholder="نام و نام خانوادگی" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="موبایل" value={mobile} onChange={e=>setMobile(e.target.value)}/><button disabled={saving} onClick={()=>post("/api/customer-360/customers",{customerNo:no,fullName:name,mobile})}>ثبت مشتری</button></div></div><div className={styles.panel}><h2>پرونده‌ها</h2>{customerRows.map(c=><article key={c.id} onClick={()=>setSelected(c)} className={chosen?.id===c.id?styles.selected:""}><div><b>{c.full_name}</b><small>{c.customer_no} · {c.mobile||"بدون موبایل"}</small></div><span>{c.status}</span></article>)}</div></section>}
 {tab==="customer-360-2"&&<section className={styles.panel}><h2>مشخصات هویتی</h2>{chosen?<><div className={styles.form}><input placeholder="نوع مدرک" id="docType"/><input placeholder="شماره مدرک" id="docNo"/><button onClick={()=>{const t=(document.getElementById("docType") as HTMLInputElement).value,n=(document.getElementById("docNo") as HTMLInputElement).value;post("/api/customer-360/customers/"+chosen.id+"/identities",{documentType:t,documentNumber:n})}}>ثبت مشخصات</button></div><p>پرونده انتخاب‌شده: <b>{chosen.full_name}</b></p></>:<div>ابتدا یک مشتری ثبت یا انتخاب کنید.</div>}</section>}
 {tab==="customer-360-3"&&<section className={styles.panel}><h2>تعاملات</h2>{d.interactions.map(x=><article key={x.id}><div><b>{x.subject}</b><small>{x.full_name} · {x.channel} · {new Date(x.occurred_at).toLocaleString("fa-IR")}</small><p>{x.body}</p></div></article>)}</section>}
 {tab==="customer-360-4"&&<section className={styles.panel}><h2>سوابق خرید</h2>{d.purchases.map(x=><article key={x.id}><div><b>{x.description}</b><small>{x.full_name} · {Number(x.amount).toLocaleString("fa-IR")} · {x.status}</small></div></article>)}</section>}
 {tab==="customer-360-5"&&<section className={styles.panel}><h2>نمای مالی</h2>{d.financial.map(x=><article key={x.id}><div><b>{x.full_name}</b><small>دریافتنی: {Number(x.receivable).toLocaleString("fa-IR")} · پرداختنی: {Number(x.payable).toLocaleString("fa-IR")}</small></div><span>اعتبار {Number(x.credit_limit).toLocaleString("fa-IR")}</span></article>)}</section>}
 </main>
}