"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./DigitalBinderWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه اسناد"],["contracts","قراردادها"],["identity","مدارک هویتی"],["collateral","وثایق"],["archive","بایگانی"]];
const initial={binder:"",entityType:"قرارداد وام",entityCode:"",title:"",docType:"قرارداد",file:"",version:"1",date:"",status:"ثبت شده",conf:"داخلی",description:"",notes:""};

export default function DigitalBinderWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/17-digital-binder/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت اسناد انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اسناد")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="contracts")a=a.filter(x=>x.data?.["document-type"]==="قرارداد");if(tab==="identity")a=a.filter(x=>x.data?.["document-type"]==="مدرک هویتی");if(tab==="collateral")a=a.filter(x=>["سند وثیقه","ضمانت‌نامه"].includes(String(x.data?.["document-type"]||"")));if(tab==="archive")a=a.filter(x=>x.data?.["document-status"]==="بایگانی شده");return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const save=async()=>{if(!String(form.binder||"").trim()||!String(form.entityCode||"").trim()||!String(form.title||"").trim()||!String(form.file||"").trim())return setError("کد زونکن، شناسه پرونده، عنوان سند و مرجع فایل الزامی است.");setSaving(true);setError("");try{const data={"binder-code":form.binder,"entity-type":form.entityType,"entity-code":form.entityCode,"document-title":form.title,"document-type":form.docType,"file-reference":form.file,"version":Number(form.version||1),"document-date":form.date,"document-status":form.status,"confidentiality":form.conf,description:form.description,notes:form.notes};const r=await fetch(API+"/api/platform/modules/17-digital-binder/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"digital-binder-document",title:String(form.title),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت سند انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت سند")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({binder:d["binder-code"]||"",entityType:d["entity-type"]||"قرارداد وام",entityCode:d["entity-code"]||"",title:d["document-title"]||"",docType:d["document-type"]||"قرارداد",file:d["file-reference"]||"",version:d.version??"1",date:d["document-date"]||"",status:d["document-status"]||"ثبت شده",conf:d.confidentiality||"داخلی",description:d.description||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const status=async(r:R,s:string)=>{const d={...r.data,"document-status":s};const x=await fetch(API+"/api/platform/modules/17-digital-binder/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:s,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"تغییر وضعیت سند انجام نشد.");return}await load()};
 const remove=async(id:number)=>{if(!confirm("این سند حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/17-digital-binder/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و اسناد · ماژول ۱۷</span><h1>زونکن دیجیتال</h1><p>ثبت و مدیریت ساختاریافته اسناد پرونده‌های اعتباری، قراردادها، وثایق و مدارک هویتی.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>سند</small><b>{items.filter(x=>x.data?.["document-status"]==="تأیید شده").length.toLocaleString("fa-IR")}</b><small>تأییدشده</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش سند":"ثبت سند در زونکن"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد زونکن *<input value={String(form.binder)} onChange={e=>set("binder",e.target.value)}/></label><label>نوع پرونده *<select value={String(form.entityType)} onChange={e=>set("entityType",e.target.value)}>{["قرارداد وام","درخواست اعتبار","وثیقه","ضامن","مشتری","سایر"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>شناسه پرونده *<input value={String(form.entityCode)} onChange={e=>set("entityCode",e.target.value)}/></label><label>عنوان سند *<input value={String(form.title)} onChange={e=>set("title",e.target.value)}/></label>
    <label>نوع سند<select value={String(form.docType)} onChange={e=>set("docType",e.target.value)}>{["قرارداد","مدرک هویتی","سند وثیقه","ضمانت‌نامه","رسید پرداخت","گزارش ارزیابی","مکاتبه","سایر"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>مرجع فایل *<input value={String(form.file)} onChange={e=>set("file",e.target.value)} placeholder="شناسه یا مسیر امن فایل"/></label>
    <label>نسخه<input type="number" min="1" value={String(form.version)} onChange={e=>set("version",e.target.value)}/></label><label>تاریخ سند<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label>
    <label>وضعیت سند<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","ثبت شده","تأیید شده","منسوخ","بایگانی شده"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>محرمانگی<select value={String(form.conf)} onChange={e=>set("conf",e.target.value)}>{["عمومی","داخلی","محرمانه","بسیار محرمانه"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label className={styles.full}>شرح<textarea rows={2} value={String(form.description)} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت سند در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>اسناد ثبت‌شده</small><h2>فهرست زونکن</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در عنوان، پرونده یا مرجع فایل..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["entity-code"]||"")} · {String(r.data?.["document-type"]||"")} · {String(r.data?.["document-status"]||"")}</small><span>نسخه {String(r.data?.version||1)} · {String(r.data?.confidentiality||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{r.data?.["document-status"]!=="تأیید شده"&&<button className={styles.confirm} onClick={()=>status(r,"تأیید شده")}>تأیید</button>}{r.data?.["document-status"]!=="بایگانی شده"&&<button className={styles.archive} onClick={()=>status(r,"بایگانی شده")}>بایگانی</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>سندی ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
