"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentComplianceWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",doc:"",title:"",reqCode:"",reqTitle:"",reqType:"قانونی",authority:"",control:"مستندات اجباری",owner:"",review:"",due:"",status:"در حال بررسی",risk:"عادی",evidence:"",finding:"",corrective:"",closure:"",notes:""};
const opts:any={reqType:["قانونی","مقرراتی","سازمانی","قراردادی","امنیتی","حفاظت داده","کیفی"],control:["مستندات اجباری","تأیید دوره‌ای","سطح دسترسی","نگهداری","نسخه معتبر","ثبت رویداد","بازبینی"],status:["منطبق","منطبق با اصلاحات","غیرمنطبق","در حال بررسی","منقضی","معاف"],risk:["عادی","کم","متوسط","زیاد","بحرانی"]};
export default function DocumentComplianceWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/49-document-compliance/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت کنترل‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data["compliance-status"]===tab),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-compliance",title:d.title||d.doc,status:"active",data:{"compliance-code":d.code,"document-code":d.doc,"document-title":d.title,"requirement-code":d.reqCode,"requirement-title":d.reqTitle,"requirement-type":d.reqType,authority:d.authority,"control-type":d.control,owner:d.owner,"review-date":d.review,"due-date":d.due,"compliance-status":d.status,"risk-level":d.risk,"evidence-reference":d.evidence,finding:d.finding,"corrective-action":d.corrective,"closure-date":d.closure,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.doc.trim()||!form.title.trim()||!form.reqCode.trim()||!form.reqTitle.trim()||!form.owner.trim())return setError("کد کنترل، سند، الزام و مسئول کنترل الزامی است.");try{const r=await fetch(API+"/api/platform/modules/49-document-compliance/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/49-document-compliance/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:"active",data:{...r.data,...data}})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات ناموفق بود")}else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["compliance-code"]||"",doc:d["document-code"]||"",title:d["document-title"]||r.title,reqCode:d["requirement-code"]||"",reqTitle:d["requirement-title"]||"",reqType:d["requirement-type"]||"قانونی",authority:d.authority||"",control:d["control-type"]||"",owner:d.owner||"",review:d["review-date"]||"",due:d["due-date"]||"",status:d["compliance-status"]||"در حال بررسی",risk:d["risk-level"]||"عادی",evidence:d["evidence-reference"]||"",finding:d.finding||"",corrective:d["corrective-action"]||"",closure:d["closure-date"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/49-document-compliance/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
const assess=(r:R)=>patch(r,{"compliance-status":"منطبق"}),correct=(r:R)=>patch(r,{"compliance-status":"منطبق با اصلاحات"}),close=(r:R)=>patch(r,{"compliance-status":"منطبق", "closure-date":new Date().toISOString()}),waive=(r:R)=>patch(r,{"compliance-status":"معاف"});
const tabs=[["all","همه"],["منطبق","منطبق"],["منطبق با اصلاحات","با اصلاحات"],["غیرمنطبق","غیرمنطبق"],["در حال بررسی","در حال بررسی"],["منقضی","منقضی"],["معاف","معاف"]];
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۹</small><h1>کنترل انطباق و الزامات مستندات</h1><p>مدیریت الزامات قانونی، مقرراتی، سازمانی و قراردادی و ثبت وضعیت انطباق مستندات و اقدامات اصلاحی.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>کنترل انطباق</span></div></header>
<div className={styles.tabs}>{tabs.map(([k,l])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{l}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش کنترل":"ثبت کنترل انطباق"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد کنترل *"],["doc","کد سند *"],["title","عنوان سند *"],["reqCode","کد الزام *"],["reqTitle","عنوان الزام *"],["authority","مرجع الزام"],["owner","مسئول کنترل *"],["review","تاریخ بازبینی"],["due","مهلت اقدام"],["evidence","مرجع مستندات اثبات"],["closure","تاریخ رفع مغایرت"]].map(([k,l])=><label key={k}>{l}<input value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({reqType:"نوع الزام",control:"نوع کنترل",status:"وضعیت انطباق",risk:"سطح ریسک"}).map(([k,l])=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>یافته / مغایرت<textarea rows={2} value={form.finding} onChange={e=>set("finding",e.target.value)}/></label><label className={styles.full}>اقدام اصلاحی<textarea rows={2} value={form.corrective} onChange={e=>set("corrective",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className={styles.buttons}><button className={styles.primary} type="submit">{edit?"ذخیره تغییرات":"ثبت کنترل"}</button><button type="button" onClick={reset}>پاک‌سازی</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>Compliance Registry</small><h2>کنترل‌های انطباق</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد سند، الزام، عنوان یا مسئول کنترل..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["document-title"]||r.title}</b><small>{r.data["document-code"]} · {r.data["requirement-code"]} · {r.data["requirement-title"]}</small><span>{r.data["compliance-status"]} · ریسک: {r.data["risk-level"]} · مسئول: {r.data.owner}</span></div><div className={styles.actions}>{r.data["compliance-status"]==="در حال بررسی"&&<button onClick={()=>assess(r)}>ارزیابی</button>}{r.data["compliance-status"]==="غیرمنطبق"&&<button onClick={()=>correct(r)}>ثبت اصلاحات</button>}{["منطبق با اصلاحات","غیرمنطبق"].includes(r.data["compliance-status"])&&<button onClick={()=>close(r)}>بستن مغایرت</button>}{r.data["compliance-status"]!=="معاف"&&<button onClick={()=>waive(r)}>ثبت معافیت</button>}<button onClick={()=>editRow(r)}>ویرایش</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>کنترل انطباقی ثبت نشده است.</div>}</div></section></section></main>}