"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentApprovalsWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",doc:"",title:"",version:1,type:"بازبینی محتوا",requester:"",reviewer:"",approver:"",requestDate:"",reviewDate:"",decisionDate:"",decision:"",status:"پیش‌نویس",priority:"عادی",comments:"",conditions:"",nextReview:"",audit:"",notes:""};
const opts:any={type:["بازبینی محتوا","تأیید انتشار","تأیید اصلاحات","ابطال سند","بازبینی دوره‌ای"],decision:["تأیید","تأیید مشروط","رد","نیازمند اصلاح"],status:["پیش‌نویس","در انتظار بازبینی","در انتظار تأیید","تأیید شده","رد شده","نیازمند اصلاح","لغو شده"],priority:["عادی","مهم","فوری","بحرانی"]};
export default function DocumentApprovalsWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/42-document-approvals/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت گردش‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data.status===({draft:"پیش‌نویس",review:"در انتظار بازبینی",approve:"در انتظار تأیید",approved:"تأیید شده",rejected:"رد شده",revision:"نیازمند اصلاح"}as any)[tab]),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-approval",title:d.title,status:d.status,data:{"approval-code":d.code,"document-code":d.doc,"document-title":d.title,"document-version":Number(d.version||1),"workflow-type":d.type,requester:d.requester,reviewer:d.reviewer,approver:d.approver,"request-date":d.requestDate,"review-date":d.reviewDate,"decision-date":d.decisionDate,decision:d.decision,status:d.status,priority:d.priority,comments:d.comments,conditions:d.conditions,"next-review-date":d.nextReview,audit-reference:d.audit,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.doc.trim()||!form.title.trim()||!form.requester.trim())return setError("کد گردش، کد سند، عنوان سند و درخواست‌کننده الزامی است.");try{const r=await fetch(API+"/api/platform/modules/42-document-approvals/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/42-document-approvals/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:data["document-title"]||r.title,status:data.status||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["approval-code"]||"",doc:d["document-code"]||"",title:d["document-title"]||r.title,version:d["document-version"]||1,type:d["workflow-type"]||"بازبینی محتوا",requester:d.requester||"",reviewer:d.reviewer||"",approver:d.approver||"",requestDate:d["request-date"]||"",reviewDate:d["review-date"]||"",decisionDate:d["decision-date"]||"",decision:d.decision||"",status:d.status||"پیش‌نویس",priority:d.priority||"عادی",comments:d.comments||"",conditions:d.conditions||"",nextReview:d["next-review-date"]||"",audit:d["audit-reference"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const now=()=>new Date().toISOString();
const submit=(r:R)=>patch(r,{...r.data,status:"در انتظار بازبینی","request-date":r.data["request-date"]||now()});
const review=(r:R)=>patch(r,{...r.data,status:"در انتظار تأیید","review-date":now()});
const approve=(r:R)=>patch(r,{...r.data,status:"تأیید شده",decision:"تأیید","decision-date":now()});
const reject=(r:R)=>patch(r,{...r.data,status:"رد شده",decision:"رد","decision-date":now()});
const revise=(r:R)=>patch(r,{...r.data,status:"نیازمند اصلاح",decision:"نیازمند اصلاح","decision-date":now()});
const cancel=(r:R)=>patch(r,{...r.data,status:"لغو شده"});
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/42-document-approvals/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۲</small><h1>گردش تأیید و انتشار مستندات</h1><p>کنترل بازبینی، تأیید، اصلاح و انتشار نسخه‌های مستندات با مسیر تصمیم‌گیری قابل ردیابی.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>گردش فعال و ثبت‌شده</span></div></header>
<div className={styles.tabs}>{[["all","همه گردش‌ها"],["draft","پیش‌نویس"],["review","در انتظار بازبینی"],["approve","در انتظار تأیید"],["approved","تأیید شده"],["rejected","رد شده"],["revision","نیازمند اصلاح"]].map(([k,t])=><button className={tab===k?styles.active:""} key={k} onClick={()=>setTab(k)}>{t}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش گردش":"ایجاد گردش تأیید"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد گردش *"],["doc","کد سند *"],["title","عنوان سند *"],["version","نسخه سند"],["requester","درخواست‌کننده *"],["reviewer","بازبین"],["approver","تأییدکننده"],["requestDate","تاریخ درخواست"],["reviewDate","تاریخ بازبینی"],["decisionDate","تاریخ تصمیم"],["nextReview","تاریخ بازبینی بعدی"],["audit","مرجع ثبت رویداد"]].map(([k,l])=><label key={k}>{l}<input type={k==="version"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({type:"نوع گردش",decision:"نتیجه تصمیم",status:"وضعیت گردش",priority:"اولویت"}).map(([k,l])=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}><option value="">انتخاب کنید</option>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>نظر بازبین<textarea rows={2} value={form.comments} onChange={e=>set("comments",e.target.value)}/></label><label className={styles.full}>شرایط تأیید<textarea rows={2} value={form.conditions} onChange={e=>set("conditions",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary}>{edit?"ذخیره تغییرات":"ثبت گردش"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>Approval Lifecycle</small><h2>کارتابل تأیید مستندات</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد گردش، کد سند، عنوان یا درخواست‌کننده..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["document-title"]||r.title}</b><small>{r.data["approval-code"]||""} · سند {r.data["document-code"]||""} · نسخه {r.data["document-version"]||1}</small><span>{r.data["workflow-type"]||""} · {r.data.priority||""} · {r.data.status||r.status}</span></div><div className={styles.actions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>submit(r)}>ارسال بازبینی</button>}{r.data.status==="در انتظار بازبینی"&&<button onClick={()=>review(r)}>ثبت بازبینی</button>}{r.data.status==="در انتظار تأیید"&&<><button onClick={()=>approve(r)}>تأیید</button><button onClick={()=>revise(r)}>اصلاح</button><button onClick={()=>reject(r)}>رد</button></>}{!["تأیید شده","رد شده","لغو شده"].includes(r.data.status)&&<button onClick={()=>cancel(r)}>لغو</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>گردشی ثبت نشده است.</div>}</div></section></section></main>}