"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentAccessLogWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",doc:"",title:"",version:"",actor:"",actorType:"کاربر",org:"",action:"مشاهده",result:"موفق",date:"",ip:"",agent:"",source:"",reason:"",sensitivity:"داخلی",retention:"فعال",notes:""};
const opts:any={actorType:["کاربر","نقش","سرویس","سامانه","مهمان"],action:["مشاهده","دانلود","چاپ","اشتراک‌گذاری","ویرایش","تأیید","انتشار","بایگانی","بازگردانی","امحا","تلاش ناموفق"],result:["موفق","رد شده","ناموفق"],sensitivity:["عمومی","داخلی","محرمانه","بسیار محرمانه"],retention:["فعال","در بایگانی","منقضی","مجاز به حذف"]};
export default function DocumentAccessLogWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/47-document-access-log/records?page=1&pageSize=500&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت رویدادها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data["access-result"]===tab||r.data["retention-status"]===tab),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-access-log",title:d.title||d.doc||"رویداد دسترسی",status:"active",data:{"log-code":d.code,"document-code":d.doc,"document-title":d.title,version:d.version,actor:d.actor,"actor-type":d.actorType,organization:d.org,"action-type":d.action,"access-result":d.result,"access-date":d.date||new Date().toISOString(),"ip-address":d.ip,"user-agent":d.agent,"source-reference":d.source,reason:d.reason,sensitivity:d.sensitivity,"retention-status":d.retention,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.doc.trim()||!form.actor.trim())return setError("کد رویداد، کد سند و عامل دسترسی الزامی است.");try{const r=await fetch(API+"/api/platform/modules/47-document-access-log/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/47-document-access-log/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:"active",data:{...r.data,...data}})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد")}else await load()};
const editRow=(r:R)=>{const d:any=r.data;setEdit(r.id);setForm({code:d["log-code"]||"",doc:d["document-code"]||"",title:d["document-title"]||r.title,version:d.version||"",actor:d.actor||"",actorType:d["actor-type"]||"کاربر",org:d.organization||"",action:d["action-type"]||"مشاهده",result:d["access-result"]||"موفق",date:d["access-date"]||"",ip:d["ip-address"]||"",agent:d["user-agent"]||"",source:d["source-reference"]||"",reason:d.reason||"",sensitivity:d.sensitivity||"داخلی",retention:d["retention-status"]||"فعال",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/47-document-access-log/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
const tabs=[["all","همه"],["موفق","موفق"],["رد شده","رد شده"],["ناموفق","ناموفق"],["در بایگانی","بایگانی شده"],["مجاز به حذف","مجاز به حذف"]];
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۷</small><h1>ثبت و پایش دسترسی مستندات</h1><p>ثبت رویدادهای مشاهده، دانلود، چاپ، اشتراک‌گذاری و عملیات حساس روی مستندات با قابلیت پیگیری و نگهداری سوابق.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>رویداد ثبت‌شده</span></div></header>
<div className={styles.tabs}>{tabs.map(([k,l]:any)=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{l}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش رویداد":"ثبت رویداد دسترسی"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد رویداد *"],["doc","کد سند *"],["title","عنوان سند"],["version","نسخه"],["actor","کاربر / عامل *"],["org","سازمان / واحد"],["date","تاریخ و زمان"],["ip","نشانی IP"],["agent","مشخصات عامل"],["source","مرجع درخواست"],["reason","علت / توضیح"]].map(([k,l]:any)=><label key={k}>{l}<input value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({actorType:"نوع عامل",action:"نوع عملیات",result:"نتیجه دسترسی",sensitivity:"حساسیت سند",retention:"وضعیت نگهداری لاگ"}).map(([k,l]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className={styles.buttons}><button className={styles.primary} type="submit">{edit?"ذخیره تغییرات":"ثبت رویداد"}</button><button type="button" onClick={reset}>پاک‌سازی</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>Access Audit Registry</small><h2>رویدادهای دسترسی</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد سند، کاربر، IP یا عملیات..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["document-title"]||r.title}</b><small>{r.data["document-code"]} · {r.data.actor} · {r.data["action-type"]}</small><span>{r.data["access-result"]} · {r.data["access-date"]||"بدون زمان"} · {r.data["retention-status"]}</span></div><div className={styles.actions}>{r.data["retention-status"]==="فعال"&&<button onClick={()=>patch(r,{"retention-status":"در بایگانی"})}>بایگانی لاگ</button>}{r.data["retention-status"]==="در بایگانی"&&<button onClick={()=>patch(r,{"retention-status":"فعال"})}>تمدید نگهداری</button>}<button onClick={()=>editRow(r)}>ویرایش</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>رویدادی ثبت نشده است.</div>}</div></section></section></main>}