"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentDistributionWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",doc:"",title:"",version:"",type:"ابلاغ سازمانی",sender:"",recipient:"",recipientType:"",access:"مطالعه",channel:"داخل سامانه",sentAt:"",due:"",ack:"خیر",ackAt:"",status:"پیش‌نویس",priority:"عادی",tracking:"",description:"",notes:""};
const opts:any={type:["انتشار داخلی","ابلاغ سازمانی","ارسال برای واحد","ارسال برای فرد","اشتراک‌گذاری محدود","اعلام عمومی"],recipientType:["کاربر","واحد سازمانی","نقش","گروه","سازمان"],access:["مطالعه","دانلود","چاپ","ویرایش","مدیریت"],channel:["داخل سامانه","ایمیل","پیامک","لینک امن","ابلاغ سازمانی"],ack:["خیر","بله"],status:["پیش‌نویس","در انتظار ارسال","ارسال شده","دریافت شده","مشاهده شده","تأیید دریافت شده","منقضی شده","لغو شده"],priority:["عادی","مهم","فوری","بحرانی"]};
export default function DocumentDistributionWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/46-document-distribution/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت گردش‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data["distribution-status"]===tab),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-distribution",title:d.title||d.doc,status:"active",data:{"distribution-code":d.code,"document-code":d.doc,"document-title":d.title,version:d.version,"distribution-type":d.type,sender:d.sender,recipient:d.recipient,"recipient-type":d.recipientType,"access-level":d.access,"delivery-channel":d.channel,"sent-at":d.sentAt,"due-date":d.due,"ack-required":d.ack,"ack-at":d.ackAt,"distribution-status":d.status,priority:d.priority,"tracking-reference":d.tracking,description:d.description,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.doc.trim()||!form.title.trim()||!form.sender.trim()||!form.recipient.trim())return setError("کد گردش، کد سند، عنوان، ارسال‌کننده و گیرنده الزامی است.");try{const r=await fetch(API+"/api/platform/modules/46-document-distribution/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,status:string,extra:any={})=>{const d={...r.data,"distribution-status":status,...extra};const x=await fetch(API+"/api/platform/modules/46-document-distribution/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:"active",data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد")}else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["distribution-code"]||"",doc:d["document-code"]||"",title:d["document-title"]||r.title,version:d.version||"",type:d["distribution-type"]||"",sender:d.sender||"",recipient:d.recipient||"",recipientType:d["recipient-type"]||"",access:d["access-level"]||"",channel:d["delivery-channel"]||"",sentAt:d["sent-at"]||"",due:d["due-date"]||"",ack:d["ack-required"]||"خیر",ackAt:d["ack-at"]||"",status:d["distribution-status"]||"پیش‌نویس",priority:d.priority||"عادی",tracking:d["tracking-reference"]||"",description:d.description||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/46-document-distribution/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
const send=(r:R)=>patch(r,"ارسال شده",{"sent-at":new Date().toISOString(),"tracking-reference":r.data["tracking-reference"]||"DIST-"+r.id});
const resend=(r:R)=>patch(r,"ارسال شده",{"sent-at":new Date().toISOString(),"tracking-reference":"DIST-"+r.id+"-R"});
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۶</small><h1>گردش و توزیع مستندات</h1><p>ثبت، ارسال، پیگیری و تأیید دریافت اسناد با کنترل گیرنده، سطح دسترسی، مهلت اقدام و مرجع پیگیری.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>گردش ثبت‌شده</span></div></header>
<div className={styles.tabs}><button className={tab==="all"?styles.active:""} onClick={()=>setTab("all")}>همه</button>{opts.status.map((x:string)=><button key={x} className={tab===x?styles.active:""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش گردش":"ثبت گردش سند"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد گردش *"],["doc","کد سند *"],["title","عنوان سند *"],["version","نسخه سند"],["sender","ارسال‌کننده *"],["recipient","گیرنده *"],["sentAt","تاریخ ارسال"],["due","مهلت اقدام"],["ackAt","تاریخ تأیید دریافت"],["tracking","مرجع پیگیری"]].map(([k,l]:[string,string])=><label key={k}>{l}<input value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({type:"نوع توزیع",recipientType:"نوع گیرنده",access:"سطح دسترسی",channel:"کانال ابلاغ",ack:"نیازمند تأیید دریافت",status:"وضعیت گردش",priority:"اولویت"}).map(([k,l]:[string,string])=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>توضیحات<textarea rows={2} value={form.description} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className={styles.buttons}><button className={styles.primary} type="submit">{edit?"ذخیره تغییرات":"ثبت گردش"}</button><button type="button" onClick={reset}>پاک‌سازی</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>Distribution Registry</small><h2>گردش‌های مستندات</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد سند، عنوان، گیرنده یا مرجع پیگیری..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["document-title"]||r.title}</b><small>{r.data["document-code"]} · {r.data.recipient} · {r.data["recipient-type"]}</small><span>{r.data["distribution-status"]} · {r.data.priority} · {r.data["delivery-channel"]}</span></div><div className={styles.actions}>{r.data["distribution-status"]==="پیش‌نویس"&&<button onClick={()=>patch(r,"در انتظار ارسال")}>آماده ارسال</button>}{r.data["distribution-status"]==="در انتظار ارسال"&&<button onClick={()=>send(r)}>ارسال</button>}{["ارسال شده","دریافت شده","مشاهده شده"].includes(r.data["distribution-status"])&&<button onClick={()=>patch(r,"تأیید دریافت شده",{"ack-at":new Date().toISOString()})}>تأیید دریافت</button>}{["ارسال شده","دریافت شده","مشاهده شده"].includes(r.data["distribution-status"])&&<button onClick={()=>resend(r)}>ارسال مجدد</button>}<button onClick={()=>editRow(r)}>ویرایش</button>{r.data["distribution-status"]!=="لغو شده"&&<button onClick={()=>patch(r,"لغو شده")}>لغو</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>گردش مستندی ثبت نشده است.</div>}</div></section></section></main>}