"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentGovernanceWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",title:"",scope:"کل سازمان",scopeRef:"",owner:"",manager:"",policy:"",cycle:"فصلی",last:"",next:"",coverage:"",compliance:"",open:"0",high:"0",status:"پیش‌نویس",action:"",notes:""};
const opts:any={scope:["کل سازمان","واحد سازمانی","گروه اسناد","پوشه","نوع سند"],cycle:["ماهانه","فصلی","شش‌ماهه","سالانه","موردی"],status:["پیش‌نویس","فعال","در حال بازبینی","نیازمند اقدام","منطبق","تعلیق شده","مختومه"]};
export default function DocumentGovernanceWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/19-documents-governance/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت برنامه‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||(r.data as any)["governance-status"]===tab),[rows,tab]);
const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-governance",title:d.title||d.code,status:"active",data:{"governance-code":d.code,"governance-title":d.title,scope:d.scope,"scope-reference":d.scopeRef,owner:d.owner,manager:d.manager,"policy-reference":d.policy,"review-cycle":d.cycle,"last-review-date":d.last,"next-review-date":d.next,"coverage-percent":d.coverage,"compliance-percent":d.compliance,"open-findings":d.open,"high-risk-findings":d.high,"governance-status":d.status,"action-plan":d.action,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim()||!form.owner.trim())return setError("کد، عنوان و مالک حاکمیت الزامی است.");try{const r=await fetch(API+"/api/platform/modules/19-documents-governance/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/19-documents-governance/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:"active",data:{...r.data,...data}})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات ناموفق بود")}else await load()};
const editRow=(r:R)=>{const d:any=r.data;setEdit(r.id);setForm({code:d["governance-code"]||"",title:d["governance-title"]||r.title,scope:d.scope||"",scopeRef:d["scope-reference"]||"",owner:d.owner||"",manager:d.manager||"",policy:d["policy-reference"]||"",cycle:d["review-cycle"]||"",last:d["last-review-date"]||"",next:d["next-review-date"]||"",coverage:d["coverage-percent"]??"",compliance:d["compliance-percent"]??"",open:d["open-findings"]??"0",high:d["high-risk-findings"]??"0",status:d["governance-status"]||"پیش‌نویس",action:d["action-plan"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/19-documents-governance/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
const assess=(r:R)=>patch(r,{"governance-status":"در حال بازبینی","last-review-date":new Date().toISOString()});
const action=(r:R)=>patch(r,{"governance-status":"نیازمند اقدام"});
const close=(r:R)=>patch(r,{"governance-status":"مختومه"});
const activate=(r:R)=>patch(r,{"governance-status":"فعال"});
const tabs=[["all","همه"],["پیش‌نویس","پیش‌نویس"],["فعال","فعال"],["در حال بازبینی","بازبینی"],["نیازمند اقدام","نیازمند اقدام"],["منطبق","منطبق"],["مختومه","مختومه"]];
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۱۹</small><h1>مرکز حاکمیت مستندات</h1><p>مرکز کنترل پوشش، انطباق، ریسک و برنامه اقدام برای چرخه عمر مستندات سازمان.</p></div><div className={styles.metrics}><div><b>{rows.length.toLocaleString("fa-IR")}</b><span>برنامه</span></div><div><b>{rows.reduce((n,r)=>n+Number((r.data as any)["open-findings"]||0),0).toLocaleString("fa-IR")}</b><span>مغایرت باز</span></div></div></header>
<div className={styles.tabs}>{tabs.map(([k,l]:any)=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{l}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش برنامه":"تعریف برنامه حاکمیت"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد برنامه *"],["title","عنوان برنامه *"],["scopeRef","مرجع دامنه"],["owner","مالک حاکمیت *"],["manager","مسئول اجرا"],["policy","مرجع خط‌مشی"],["last","آخرین بازبینی"],["next","بازبینی بعدی"],["coverage","درصد پوشش"],["compliance","درصد انطباق"],["open","مغایرت‌های باز"],["high","مغایرت‌های پرریسک"]].map(([k,l]:any)=><label key={k}>{l}<input value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({scope:"دامنه حاکمیت",cycle:"دوره بازبینی",status:"وضعیت برنامه"}).map(([k,l]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>برنامه اقدام<textarea rows={2} value={form.action} onChange={e=>set("action",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className={styles.buttons}><button className={styles.primary} type="submit">{edit?"ذخیره تغییرات":"ثبت برنامه"}</button><button type="button" onClick={reset}>پاک‌سازی</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>Document Governance Registry</small><h2>برنامه‌های حاکمیت</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد، عنوان، مالک یا مرجع دامنه..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{(r.data as any)["governance-title"]||r.title}</b><small>{(r.data as any)["governance-code"]} · {r.data.scope} · مالک: {r.data.owner}</small><div className={styles.bars}><span>پوشش: {(r.data as any)["coverage-percent"]||0}%</span><span>انطباق: {(r.data as any)["compliance-percent"]||0}%</span><span>مغایرت باز: {(r.data as any)["open-findings"]||0}</span></div><strong>{(r.data as any)["governance-status"]}</strong></div><div className={styles.actions}>{(r.data as any)["governance-status"]==="پیش‌نویس"&&<button onClick={()=>activate(r)}>فعال‌سازی</button>}{(r.data as any)["governance-status"]==="فعال"&&<button onClick={()=>assess(r)}>شروع بازبینی</button>}{["در حال بازبینی","غیرمنطبق"].includes((r.data as any)["governance-status"])&&<button onClick={()=>action(r)}>نیازمند اقدام</button>}{(r.data as any)["governance-status"]==="نیازمند اقدام"&&<button onClick={()=>close(r)}>مختومه</button>}<button onClick={()=>editRow(r)}>ویرایش</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>برنامه حاکمیتی ثبت نشده است.</div>}</div></section></section></main>}