"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentSearchWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",title:"",query:"",doc:"",type:"",folder:"",tags:"",owner:"",access:"",from:"",to:"",version:"",status:"",sort:"ارتباط",limit:50,saved:"خیر",description:"",notes:""};
const opts:any={type:["دستورالعمل","آیین‌نامه","فرآیند","راهنما","خط‌مشی","قرارداد","گزارش","صورتجلسه","فرم","سایر"],access:["عمومی","کاربران واردشده","نقش‌محور","سازمانی","محرمانه"],status:["پیش‌نویس","فعال","نیازمند بازبینی","منسوخ","بایگانی شده"],sort:["ارتباط","تاریخ جدیدتر","تاریخ قدیمی‌تر","عنوان","کد سند"],saved:["خیر","بله"]};
export default function DocumentSearchWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/44-document-search/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت جستجوها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data["saved-search"]===(tab==="saved"?"بله":"خیر")),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-search",title:d.title||d.query||"جستجوی مستندات",status:"فعال",data:{"search-code":d.code,"search-title":d.title,"query":d.query,"document-code":d.doc,"document-type":d.type,folder:d.folder,tags:d.tags,owner:d.owner,"access-level":d.access,"date-from":d.from,"date-to":d.to,version:d.version?Number(d.version):null,status:d.status,"sort-by":d.sort,"result-limit":Number(d.limit||50),"saved-search":d.saved,description:d.description,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim())return setError("کد و عنوان جستجو الزامی است.");try{const r=await fetch(API+"/api/platform/modules/44-document-search/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/44-document-search/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:data["search-title"]||r.title,status:"فعال",data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["search-code"]||"",title:d["search-title"]||r.title,query:d.query||"",doc:d["document-code"]||"",type:d["document-type"]||"",folder:d.folder||"",tags:d.tags||"",owner:d.owner||"",access:d["access-level"]||"",from:d["date-from"]||"",to:d["date-to"]||"",version:d.version||"",status:d.status||"",sort:d["sort-by"]||"ارتباط",limit:d["result-limit"]||50,saved:d["saved-search"]||"خیر",description:d.description||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"search-code":String(r.data["search-code"]||"")+"-COPY","search-title":String(r.data["search-title"]||"")+" - نسخه جدید","saved-search":"خیر"};await fetch(API+"/api/platform/modules/44-document-search/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"document-search",title:d["search-title"],status:"فعال",data:d})});await load()};
const clear=()=>{setQ("");setForm({...empty});};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/44-document-search/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۴</small><h1>جستجو و بایگانی هوشمند مستندات</h1><p>مدیریت جستجوهای مستندات با فیلترهای ترکیبی، جستجوهای ذخیره‌شده و مرتب‌سازی قابل کنترل.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>جستجوی ثبت‌شده</span></div></header>
<div className={styles.tabs}><button className={tab==="all"?styles.active:""} onClick={()=>setTab("all")}>همه جستجوها</button><button className={tab==="saved"?styles.active:""} onClick={()=>setTab("saved")}>ذخیره‌شده</button><button className={tab==="temporary"?styles.active:""} onClick={()=>setTab("temporary")}>موقت</button></div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش جستجو":"تعریف جستجو"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد جستجو *"],["title","عنوان جستجو *"],["query","عبارت جستجو"],["doc","کد سند"],["folder","پوشه"],["tags","برچسب‌ها"],["owner","مالک"],["from","از تاریخ"],["to","تا تاریخ"],["version","نسخه"],["limit","حد نتایج"]].map(([k,l]:any)=><label key={k}>{l}<input type={k==="version"||k==="limit"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({type:"نوع سند",access:"سطح دسترسی",status:"وضعیت سند",sort:"مرتب‌سازی",saved:"جستجوی ذخیره‌شده"}).map(([k,l]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}><option value="">همه</option>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>توضیحات<textarea rows={2} value={form.description} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className={styles.buttons}><button type="submit" className={styles.primary}>{edit?"ذخیره تغییرات":"ثبت جستجو"}</button><button type="button" onClick={clear}>پاک‌سازی فیلترها</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>Search Registry</small><h2>جستجوهای ثبت‌شده</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="عنوان، عبارت، کد سند یا برچسب..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["search-title"]||r.title}</b><small>{r.data["search-code"]||""} · {r.data.query||"بدون عبارت"} · {r.data["sort-by"]||"ارتباط"}</small><span>{r.data["saved-search"]==="بله"?"ذخیره‌شده":"موقت"} · حد نتایج {r.data["result-limit"]||50}</span></div><div className={styles.actions}><button onClick={()=>editRow(r)}>ویرایش</button><button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>جستجویی ثبت نشده است.</div>}</div></section></section></main>}