"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentationWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",title:"",type:"راهنما",file:"",mime:"",size:"",date:"",owner:"",creator:"",version:1,entity:"",tags:"",folder:"",access:"کاربران واردشده",hash:"",status:"پیش‌نویس",ocr:"انجام نشده",description:"",notes:""};
const options:any={type:["دستورالعمل","آیین‌نامه","فرآیند","راهنما","خط‌مشی","قرارداد","گزارش","صورتجلسه","فرم","سایر"],access:["عمومی","کاربران واردشده","نقش‌محور","سازمانی","محرمانه"],status:["پیش‌نویس","فعال","نیازمند بازبینی","منسوخ","بایگانی شده"],ocr:["انجام نشده","در انتظار پردازش","پردازش شده","نیازمند بازبینی","ناموفق"]};
export default function DocumentationWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/41-documentation/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت مستندات ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const map:any={draft:"پیش‌نویس",active:"فعال",review:"نیازمند بازبینی",obsolete:"منسوخ",archived:"بایگانی شده"};
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data.status===map[tab]),[rows,tab]);
const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document",title:d.title,status:d.status,data:{"document-code":d.code,"document-title":d.title,"document-type":d.type,"file-reference":d.file,"mime-type":d.mime,"file-size":Number(d.size||0),"document-date":d.date,owner:d.owner,creator:d.creator,version:Number(d.version||1),"related-entity":d.entity,tags:d.tags,folder:d.folder,"access-level":d.access,hash:d.hash,status:d.status,"ocr-status":d.ocr,description:d.description,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim())return setError("کد و عنوان سند الزامی است.");try{const r=await fetch(API+"/api/platform/modules/41-documentation/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/41-documentation/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:data["document-title"]||r.title,status:data.status||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d:any=r.data;setEdit(r.id);setForm({code:d["document-code"]||"",title:(d as any)["document-title"]||r.title,type:d["document-type"]||"راهنما",file:d["file-reference"]||"",mime:d["mime-type"]||"",size:d["file-size"]||"",date:d["document-date"]||"",owner:d.owner||"",creator:d.creator||"",version:d.version||1,entity:d["related-entity"]||"",tags:d.tags||"",folder:d.folder||"",access:d["access-level"]||"کاربران واردشده",hash:d.hash||"",status:d.status||"پیش‌نویس",ocr:d["ocr-status"]||"انجام نشده",description:d.description||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"document-code":String((r.data as any)["document-code"]||"")+"-COPY","document-title":String((r.data as any)["document-title"]||"")+" - نسخه جدید",version:1,status:"پیش‌نویس"};await fetch(API+"/api/platform/modules/41-documentation/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"document",title:(d as any)["document-title"],status:"پیش‌نویس",data:d})});await load()};
const version=async(r:R)=>{const n=Number(r.data.version||1)+1;const d={...r.data,"document-code":String((r.data as any)["document-code"]||"")+"-V"+n,version:n,status:"پیش‌نویس"};await fetch(API+"/api/platform/modules/41-documentation/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"document",title:(d as any)["document-title"]||r.title,status:"پیش‌نویس",data:d})});await load()};
const publish=(r:R)=>patch(r,{...r.data,status:"فعال"}),archive=(r:R)=>patch(r,{...r.data,status:"بایگانی شده"}),ocr=(r:R)=>patch(r,{...r.data,"ocr-status":"در انتظار پردازش"});
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/41-documentation/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز فرمان · منوی ۴۱</small><h1>مستندات</h1><p>مرکز مدیریت دستورالعمل‌ها، آیین‌نامه‌ها، فرآیندها، راهنماها و اسناد سازمانی با نسخه‌بندی و کنترل چرخه عمر.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>سند ثبت‌شده</span></div></header>
<div className={styles.tabs}>{[["all","همه مستندات"],["draft","پیش‌نویس"],["active","فعال"],["review","نیازمند بازبینی"],["obsolete","منسوخ"],["archived","بایگانی"]].map(([k,t])=><button className={tab===k?styles.active:""} key={k} onClick={()=>setTab(k)}>{t}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش سند":"ثبت مستند جدید"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد سند *"],["title","عنوان سند *"],["file","مرجع فایل"],["mime","نوع فایل"],["size","حجم فایل"],["date","تاریخ سند"],["owner","مالک سند"],["creator","ایجادکننده"],["version","نسخه"],["entity","موجودیت مرتبط"],["tags","برچسب‌ها"],["folder","پوشه"],["hash","Hash فایل"]].map(([k,l]:any)=><label key={k}>{l}<input type={k==="version"||k==="size"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({type:"نوع سند",access:"سطح دسترسی",status:"وضعیت",ocr:"وضعیت OCR"}).map(([k,l]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{options[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>توضیحات<textarea rows={2} value={form.description} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary}>{edit?"ذخیره تغییرات":"ثبت مستند"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>Document Lifecycle</small><h2>مرکز مستندات</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="عنوان، کد، نوع، پوشه یا برچسب..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{(r.data as any)["document-title"]||r.title}</b><small>{(r.data as any)["document-code"]||""} · {(r.data as any)["document-type"]||""} · نسخه {r.data.version||1}</small><span>{r.data.folder||"بدون پوشه"} · {(r.data as any)["access-level"]||""} · {r.data.status||r.status}</span></div><div className={styles.actions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>publish(r)}>فعال‌سازی</button>}<button onClick={()=>ocr(r)}>ارسال OCR</button><button onClick={()=>version(r)}>نسخه جدید</button><button onClick={()=>duplicate(r)}>تکثیر</button>{r.data.status!=="بایگانی شده"&&<button onClick={()=>archive(r)}>بایگانی</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>مستندی ثبت نشده است.</div>}</div></section></section></main>}