"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentRetentionWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",doc:"",title:"",type:"",version:"",folder:"",retention:"",until:"",confidentiality:"",reason:"",archiveDate:"",disposalDate:"",method:"",status:"در انتظار بایگانی",approvedBy:"",approvalDate:"",disposalRef:"",description:"",notes:""};
const opts:any={type:["دستورالعمل","آیین‌نامه","فرآیند","راهنما","خط‌مشی","قرارداد","گزارش","صورتجلسه","فرم","سایر"],retention:["دائمی","بلندمدت","میان‌مدت","کوتاه‌مدت"],confidentiality:["عمومی","داخلی","محرمانه","بسیار محرمانه"],reason:["پایان اعتبار","جایگزینی نسخه","اتمام فرآیند","تصمیم سازمانی","نگهداری قانونی","سایر"],method:["حذف امن دیجیتال","امحای فیزیکی","تحویل به امحای مجاز","بدون امحا","سایر"],status:["در انتظار بایگانی","بایگانی شده","در انتظار بررسی امحا","مجاز به امحا","امحا شده","بازگردانی شده","متوقف شده"]};
export default function DocumentRetentionWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/45-document-retention/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت بایگانی ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data["archive-status"]===tab),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-retention",title:d.title||d.doc,status:"active",data:{"archive-code":d.code,"document-code":d.doc,"document-title":d.title,"document-type":d.type,version:d.version,"archive-folder":d.folder,"retention-class":d.retention,"retention-until":d.until,confidentiality:d.confidentiality,"archive-reason":d.reason,"archive-date":d.archiveDate,"disposal-date":d.disposalDate,"disposal-method":d.method,"archive-status":d.status,"approved-by":d.approvedBy,"approval-date":d.approvalDate,"disposal-reference":d.disposalRef,description:d.description,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.doc.trim()||!form.title.trim())return setError("کد بایگانی، کد سند و عنوان سند الزامی است.");try{const r=await fetch(API+"/api/platform/modules/45-document-retention/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,status:string,extra:any={})=>{const d={...r.data,"archive-status":status,...extra};const x=await fetch(API+"/api/platform/modules/45-document-retention/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:"active",data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد")}else await load()};
const editRow=(r:R)=>{const d:any=r.data;setEdit(r.id);setForm({code:d["archive-code"]||"",doc:d["document-code"]||"",title:d["document-title"]||r.title,type:d["document-type"]||"",version:d.version||"",folder:d["archive-folder"]||"",retention:d["retention-class"]||"",until:d["retention-until"]||"",confidentiality:d.confidentiality||"",reason:d["archive-reason"]||"",archiveDate:d["archive-date"]||"",disposalDate:d["disposal-date"]||"",method:d["disposal-method"]||"",status:d["archive-status"]||"در انتظار بایگانی",approvedBy:d["approved-by"]||"",approvalDate:d["approval-date"]||"",disposalRef:d["disposal-reference"]||"",description:d.description||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/45-document-retention/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
const editFields:any={type:"نوع سند",retention:"طبقه نگهداری",confidentiality:"محرمانگی",reason:"دلیل بایگانی",method:"روش امحا",status:"وضعیت بایگانی"};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۵</small><h1>بایگانی و امحای مستندات</h1><p>کنترل چرخه عمر سند از انتقال به بایگانی تا بررسی دوره نگهداری، بازگردانی و ثبت امحای مجاز.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>پرونده بایگانی</span></div></header>
<div className={styles.tabs}><button className={tab==="all"?styles.active:""} onClick={()=>setTab("all")}>همه</button>{opts.status.map((x:string)=><button key={x} className={tab===x?styles.active:""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش پرونده":"ثبت پرونده بایگانی"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد بایگانی *"],["doc","کد سند *"],["title","عنوان سند *"],["version","نسخه"],["folder","محل بایگانی"],["until","تاریخ پایان نگهداری"],["archiveDate","تاریخ بایگانی"],["disposalDate","تاریخ امحای برنامه‌ریزی‌شده"],["approvedBy","تأییدکننده"],["approvalDate","تاریخ تأیید"],["disposalRef","مرجع امحا"]].map(([k,l]:any)=><label key={k}>{l}<input value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries(editFields).map(([k,l]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}><option value="">انتخاب کنید</option>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>توضیحات<textarea rows={2} value={form.description} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className={styles.buttons}><button className={styles.primary} type="submit">{edit?"ذخیره تغییرات":"ثبت پرونده"}</button><button type="button" onClick={reset}>پاک‌سازی</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>Archive Registry</small><h2>پرونده‌های بایگانی</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد سند، عنوان، محل بایگانی..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["document-title"]||r.title}</b><small>{r.data["document-code"]} · {r.data["archive-code"]} · {r.data["retention-class"]}</small><span>{r.data["archive-status"]} · {r.data["archive-folder"]||"بدون محل بایگانی"}</span></div><div className={styles.actions}>{r.data["archive-status"]==="در انتظار بایگانی"&&<button onClick={()=>patch(r,"بایگانی شده",{"archive-date":new Date().toISOString()})}>بایگانی</button>}{r.data["archive-status"]==="بایگانی شده"&&<button onClick={()=>patch(r,"در انتظار بررسی امحا")}>بررسی امحا</button>}{r.data["archive-status"]==="در انتظار بررسی امحا"&&<button onClick={()=>patch(r,"مجاز به امحا",{"approved-by":"کاربر جاری","approval-date":new Date().toISOString()})}>مجاز به امحا</button>}{r.data["archive-status"]==="مجاز به امحا"&&<button onClick={()=>patch(r,"امحا شده",{"disposal-reference":"DISP-"+r.id,"disposal-date":new Date().toISOString()})}>ثبت امحا</button>}{(r.data["archive-status"]==="بایگانی شده"||r.data["archive-status"]==="امحا شده")&&<button onClick={()=>patch(r,"بازگردانی شده")}>بازگردانی</button>}<button onClick={()=>editRow(r)}>ویرایش</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>پرونده‌ای در این وضعیت ثبت نشده است.</div>}</div></section></section></main>}