"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentVersionsWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",doc:"",title:"",version:1,label:"",change:"ایجاد اولیه",summary:"",reference:"",by:"",created:"",effective:"",approval:"",file:"",hash:"",status:"پیش‌نویس",current:"خیر",notes:""};
const opts:any={change:["ایجاد اولیه","اصلاح محتوا","اصلاح ساختار","اصلاح حقوق دسترسی","اصلاح نگارشی","به‌روزرسانی دوره‌ای","بازگشت نسخه"],status:["پیش‌نویس","در انتظار تأیید","تأیید شده","نسخه جاری","منسوخ","بازگشت داده شده"],current:["بله","خیر"]};
export default function DocumentVersionsWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/43-document-versions/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت نسخه‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const map:any={draft:"پیش‌نویس",pending:"در انتظار تأیید",approved:"تأیید شده",current:"نسخه جاری",obsolete:"منسوخ",rollback:"بازگشت داده شده"};
const visible=useMemo(()=>rows.filter(r=>tab==="all"||(r.data as any)["version-status"]===map[tab]),[rows,tab]);
const set=(k:string,v:any)=>setForm((x:any)=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-version",title:d.title,status:d.status,data:{"version-code":d.code,"document-code":d.doc,"document-title":d.title,"version-number":Number(d.version||1),"version-label":d.label,"change-type":d.change,"change-summary":d.summary,"change-reference":d.reference,"created-by":d.by,"created-at":d.created,"effective-at":d.effective,"approval-code":d.approval,"file-reference":d.file,"file-hash":d.hash,"version-status":d.status,"is-current":d.current,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.doc.trim()||!form.title.trim())return setError("کد نسخه، کد سند و عنوان سند الزامی است.");try{const r=await fetch(API+"/api/platform/modules/43-document-versions/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/43-document-versions/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:data["document-title"]||r.title,status:data["version-status"]||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d:any=r.data;setEdit(r.id);setForm({code:d["version-code"]||"",doc:d["document-code"]||"",title:(d as any)["document-title"]||r.title,version:d["version-number"]||1,label:d["version-label"]||"",change:d["change-type"]||"اصلاح محتوا",summary:d["change-summary"]||"",reference:d["change-reference"]||"",by:d["created-by"]||"",created:d["created-at"]||"",effective:d["effective-at"]||"",approval:d["approval-code"]||"",file:d["file-reference"]||"",hash:d["file-hash"]||"",status:d["version-status"]||"پیش‌نویس",current:d["is-current"]||"خیر",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const now=()=>new Date().toISOString();
const submit=(r:R)=>patch(r,{...r.data,"version-status":"در انتظار تأیید"});
const approve=(r:R)=>patch(r,{...r.data,"version-status":"تأیید شده"});
const publish=async(r:R)=>{for(const x of rows.filter(z=>z.data["document-code"]===(r.data as any)["document-code"]&&z.id!==r.id&&z.data["version-status"]==="نسخه جاری"))await patch(x,{...x.data,"version-status":"منسوخ","is-current":"خیر"});await patch(r,{...r.data,"version-status":"نسخه جاری","is-current":"بله","effective-at":now()})};
const rollback=(r:R)=>patch(r,{...r.data,"version-status":"بازگشت داده شده","is-current":"خیر"});
const duplicate=async(r:R)=>{const n=Number((r.data as any)["version-number"]||1)+1,d={...r.data,"version-code":String((r.data as any)["version-code"]||"")+"-V"+n,"version-number":n,"version-status":"پیش‌نویس","is-current":"خیر","created-at":now()};await fetch(API+"/api/platform/modules/43-document-versions/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"document-version",title:(d as any)["document-title"]||r.title,status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/43-document-versions/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۳</small><h1>مدیریت نسخه‌های مستندات</h1><p>کنترل نسخه، تغییرات، تأیید و جاری‌سازی نسخه‌های مستندات با سابقه قابل ردیابی.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>نسخه ثبت‌شده</span></div></header>
<div className={styles.tabs}>{[["all","همه نسخه‌ها"],["draft","پیش‌نویس"],["pending","در انتظار تأیید"],["approved","تأیید شده"],["current","نسخه جاری"],["obsolete","منسوخ"],["rollback","بازگشت داده‌شده"]].map(([k,t])=><button className={tab===k?styles.active:""} key={k} onClick={()=>setTab(k)}>{t}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش نسخه":"ثبت نسخه مستند"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد نسخه *"],["doc","کد سند *"],["title","عنوان سند *"],["version","شماره نسخه"],["label","برچسب نسخه"],["reference","مرجع تغییر"],["by","ایجادکننده نسخه"],["created","تاریخ ایجاد"],["effective","تاریخ اجرا"],["approval","کد تأیید"],["file","مرجع فایل نسخه"],["hash","Hash فایل"]].map(([k,l]:any)=><label key={k}>{l}<input type={k==="version"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({change:"نوع تغییر",status:"وضعیت نسخه",current:"نسخه جاری"}).map(([k,l]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>خلاصه تغییرات<textarea rows={3} value={form.summary} onChange={e=>set("summary",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary}>{edit?"ذخیره تغییرات":"ثبت نسخه"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>Version Lifecycle</small><h2>دفتر نسخه‌ها</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد نسخه، کد سند، عنوان یا برچسب..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{(r.data as any)["document-title"]||r.title}</b><small>{(r.data as any)["document-code"]||""} · نسخه {(r.data as any)["version-number"]||1} · {(r.data as any)["version-label"]||"بدون برچسب"}</small><span>{(r.data as any)["change-type"]||""} · {(r.data as any)["version-status"]||r.status} · جاری: {(r.data as any)["is-current"]||"خیر"}</span></div><div className={styles.actions}><button onClick={()=>editRow(r)}>ویرایش</button>{(r.data as any)["version-status"]==="پیش‌نویس"&&<button onClick={()=>submit(r)}>ارسال تأیید</button>}{(r.data as any)["version-status"]==="در انتظار تأیید"&&<button onClick={()=>approve(r)}>تأیید</button>}{(r.data as any)["version-status"]==="تأیید شده"&&<button onClick={()=>publish(r)}>جاری‌سازی</button>}{(r.data as any)["version-status"]==="نسخه جاری"&&<button onClick={()=>rollback(r)}>بازگشت</button>}<button onClick={()=>duplicate(r)}>نسخه جدید</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>نسخه‌ای ثبت نشده است.</div>}</div></section></section></main>}