"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./DocumentAuditReportsWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",title:"",type:"ممیزی دسترسی",doc:"",scope:"یک سند",scopeRef:"",from:"",to:"",actor:"",event:"",result:"همه",risk:"عادی",status:"پیش‌نویس",generatedAt:"",generatedBy:"",ref:"",summary:"",recommendations:"",notes:""};
const opts:any={type:["ممیزی دسترسی","ممیزی تغییرات","ممیزی انتشار","ممیزی بایگانی","ممیزی امحا","ممیزی گردش سند","گزارش جامع"],scope:["یک سند","گروه اسناد","پوشه","واحد سازمانی","کل سازمان"],event:["مشاهده","دانلود","چاپ","اشتراک‌گذاری","ویرایش","تأیید","انتشار","بایگانی","بازگردانی","امحا","تلاش ناموفق"],result:["همه","موفق","رد شده","ناموفق"],risk:["عادی","کم","متوسط","زیاد","بحرانی"],status:["پیش‌نویس","در حال تولید","تولید شده","بازبینی شده","تأیید شده","آرشیو شده"]};
export default function DocumentAuditReportsWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/48-document-audit-reports/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت گزارش‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data["report-status"]===tab),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"document-audit-reports",title:d.title||d.code,status:"active",data:{"report-code":d.code,"report-title":d.title,"report-type":d.type,"document-code":d.doc,scope:d.scope,"scope-reference":d.scopeRef,"date-from":d.from,"date-to":d.to,actor:d.actor,"event-type":d.event,"result-filter":d.result,"risk-level":d.risk,"report-status":d.status,"generated-at":d.generatedAt,"generated-by":d.generatedBy,"result-reference":d.ref,"finding-summary":d.summary,recommendations:d.recommendations,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim()||!form.from.trim()||!form.to.trim())return setError("کد، عنوان و بازه زمانی گزارش الزامی است.");try{const r=await fetch(API+"/api/platform/modules/48-document-audit-reports/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,status:string,extra:any={})=>{const d={...r.data,"report-status":status,...extra};const x=await fetch(API+"/api/platform/modules/48-document-audit-reports/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:"active",data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات ناموفق بود")}else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["report-code"]||"",title:d["report-title"]||r.title,type:d["report-type"]||"",doc:d["document-code"]||"",scope:d.scope||"",scopeRef:d["scope-reference"]||"",from:d["date-from"]||"",to:d["date-to"]||"",actor:d.actor||"",event:d["event-type"]||"",result:d["result-filter"]||"همه",risk:d["risk-level"]||"عادی",status:d["report-status"]||"پیش‌نویس",generatedAt:d["generated-at"]||"",generatedBy:d["generated-by"]||"",ref:d["result-reference"]||"",summary:d["finding-summary"]||"",recommendations:d.recommendations||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/48-document-audit-reports/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
const generate=(r:R)=>patch(r,"تولید شده",{"generated-at":new Date().toISOString(),"generated-by":"کاربر جاری","result-reference":"AUDIT-"+r.id});
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۸</small><h1>گزارش‌های ممیزی مستندات</h1><p>تعریف و مدیریت گزارش‌های ممیزی برای دسترسی، تغییرات، انتشار، بایگانی، امحا و گردش مستندات.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>گزارش ممیزی</span></div></header>
<div className={styles.tabs}><button className={tab==="all"?styles.active:""} onClick={()=>setTab("all")}>همه</button>{opts.status.map((x:string)=><button key={x} className={tab===x?styles.active:""} onClick={()=>setTab(x)}>{x}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش گزارش":"تعریف گزارش ممیزی"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد گزارش *"],["title","عنوان گزارش *"],["doc","کد سند"],["scopeRef","مرجع دامنه"],["from","از تاریخ *"],["to","تا تاریخ *"],["actor","کاربر / عامل"],["generatedAt","تاریخ تولید"],["generatedBy","تولیدکننده"],["ref","مرجع نتایج"]].map(([k,l])=><label key={k}>{l}<input value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({type:"نوع گزارش",scope:"دامنه گزارش",event:"نوع رویداد",result:"نتیجه رویداد",risk:"سطح ریسک",status:"وضعیت گزارش"}).map(([k,l])=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>خلاصه یافته‌ها<textarea rows={2} value={form.summary} onChange={e=>set("summary",e.target.value)}/></label><label className={styles.full}>اقدامات پیشنهادی<textarea rows={2} value={form.recommendations} onChange={e=>set("recommendations",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><div className={styles.buttons}><button className={styles.primary} type="submit">{edit?"ذخیره تغییرات":"ثبت گزارش"}</button><button type="button" onClick={reset}>پاک‌سازی</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>Audit Report Registry</small><h2>گزارش‌های ممیزی</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="عنوان، کد سند، کاربر یا کد گزارش..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["report-title"]||r.title}</b><small>{r.data["report-code"]} · {r.data["report-type"]} · {r.data["risk-level"]}</small><span>{r.data["report-status"]} · {r.data["date-from"]} تا {r.data["date-to"]}</span></div><div className={styles.actions}>{r.data["report-status"]==="پیش‌نویس"&&<button onClick={()=>patch(r,"در حال تولید")}>شروع تولید</button>}{r.data["report-status"]==="در حال تولید"&&<button onClick={()=>generate(r)}>تولید گزارش</button>}{r.data["report-status"]==="تولید شده"&&<button onClick={()=>patch(r,"بازبینی شده")}>بازبینی</button>}{r.data["report-status"]==="بازبینی شده"&&<button onClick={()=>patch(r,"تأیید شده")}>تأیید</button>}{r.data["report-status"]==="تأیید شده"&&<button onClick={()=>patch(r,"آرشیو شده")}>بایگانی</button>}<button onClick={()=>editRow(r)}>ویرایش</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>گزارشی ثبت نشده است.</div>}</div></section></section></main>}