"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./FormBuilderWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const token=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه فرم‌ها"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]];
const blank={code:"",title:"",key:"",description:"",category:"عمومی",version:"1.0.0",schema:"",validation:"قابل تنظیم",access:"کاربران واردشده",submit:"ثبت مستقیم",status:"پیش‌نویس",published:"",owner:"",count:"0",notes:""};
export default function FormBuilderWorkspace(){
const[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...blank}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/32-form-builder/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"خطا در دریافت فرم‌ها");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>items.filter(r=>tab==="all"||String(r.data?.status)===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو"} as Record<string,string>)[tab]),[items,tab]);
const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...blank})};
const save=async()=>{setError("");if(["code","title","key"].some(k=>!String(form[k]??"").trim()))return setError("کد فرم، عنوان فرم و کلید فرم الزامی است.");setBusy(true);try{const data={"form-code":form.code,"form-title":form.title,"form-key":form.key,"description":form.description,"category":form.category,"version":form.version,"schema-reference":form.schema,"validation-mode":form.validation,"access-level":form.access,"submit-mode":form.submit,status:form.status,"published-at":form.published,"owner":form.owner,"submission-count":Number(form.count||0),notes:form.notes};const r=await fetch(API+"/api/platform/modules/32-form-builder/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:"form-definition",title:String(form.title),status:String(form.status),data})}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت فرم انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const patch=async(r:R,status:string)=>{const data={...r.data,status,...(status==="فعال"?{"published-at":new Date().toISOString().slice(0,10)}:{})};const x=await fetch(API+"/api/platform/modules/32-form-builder/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:r.record_type,title:r.title,status,data})});if(!x.ok){setError("عملیات انجام نشد");return}await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["form-code"]||"",title:d["form-title"]||"",key:d["form-key"]||"",description:d.description||"",category:d.category||"عمومی",version:d.version||"1.0.0",schema:d["schema-reference"]||"",validation:d["validation-mode"]||"قابل تنظیم",access:d["access-level"]||"کاربران واردشده",submit:d["submit-mode"]||"ثبت مستقیم",status:d.status||"پیش‌نویس",published:d["published-at"]||"",owner:d.owner||"",count:d["submission-count"]??0,notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/32-form-builder/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":token()}});await load()};
const duplicate=async(r:R)=>{const d={...r.data,"form-code":String(r.data["form-code"]||"")+"-COPY","form-key":String(r.data["form-key"]||"")+"-copy","form-title":String(r.data["form-title"]||"")+" - نسخه جدید",status:"پیش‌نویس","submission-count":0};await fetch(API+"/api/platform/modules/32-form-builder/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:"form-definition",title:d["form-title"],status:"پیش‌نویس",data:d})});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مدیریت محتوا و پلتفرم · ماژول ۳۲</small><h1>فرم‌ساز</h1><p>تعریف و مدیریت فرم‌های سازمانی با نسخه‌بندی، کنترل دسترسی و چرخه انتشار.</p></div><div className={styles.stat}><b>{items.length.toLocaleString("fa-IR")}</b><span>فرم</span></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{edit?"ویرایش فرم":"ساخت فرم جدید"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>
{[["code","کد فرم *"],["title","عنوان فرم *"],["key","کلید فرم *"],["version","نسخه"],["schema","مرجع ساختار فرم"],["owner","مالک فرم"]].map(([k,l])=><label key={k}>{l}<input value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}
<label>دسته‌بندی<select value={String(form.category)} onChange={e=>set("category",e.target.value)}>{["ثبت‌نام","اعتبار و تسهیلات","فروش","پشتیبانی","منابع انسانی","سازمانی","عمومی","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>اعتبارسنجی<select value={String(form.validation)} onChange={e=>set("validation",e.target.value)}>{["استاندارد","سخت‌گیرانه","قابل تنظیم"].map(x=><option key={x}>{x}</option>)}</select></label><label>سطح دسترسی<select value={String(form.access)} onChange={e=>set("access",e.target.value)}>{["عمومی","کاربران واردشده","نقش‌محور","سازمانی"].map(x=><option key={x}>{x}</option>)}</select></label><label>روش ارسال<select value={String(form.submit)} onChange={e=>set("submit",e.target.value)}>{["ثبت مستقیم","نیازمند بررسی","نیازمند تأیید"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","فعال","غیرفعال","آرشیو شده"].map(x=><option key={x}>{x}</option>)}</select></label><label>تاریخ انتشار<input type="date" value={String(form.published??"")} onChange={e=>set("published",e.target.value)}/></label><label className={styles.full}>توضیحات<textarea rows={2} value={String(form.description)} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary} disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت فرم"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>سوابق واقعی</small><h2>کتابخانه فرم‌ها</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد، عنوان یا کلید فرم..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.title}</b><small>{String(r.data?.["form-key"]||"")} · نسخه {String(r.data?.version||"")}</small><span>{String(r.data?.status||"")}</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data?.status==="پیش‌نویس"&&<button onClick={()=>patch(r,"فعال")}>انتشار</button>}{r.data?.status==="فعال"&&<button onClick={()=>patch(r,"غیرفعال")}>غیرفعال</button>}{r.data?.status==="غیرفعال"&&<button onClick={()=>patch(r,"فعال")}>فعال‌سازی</button>}<button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>فرمی ثبت نشده است.</div>}</div></section></section></main>}