"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./FormBuilderWorkspace.module.css";
type FormRow={id:string;code:string;name:string;slug:string;category:string;validation_mode:string;access_level:string;submit_mode:string;owner_ref:string|null;notes:string|null;status:string;version:number;published_at:string|null;submission_count:number;schema:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const token=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه"],["draft","پیش‌نویس"],["published","منتشرشده"],["disabled","غیرفعال"],["archived","آرشیو"]];
const blank={code:"",title:"",key:"",category:"عمومی",version:"1",schema:"",validation:"قابل تنظیم",access:"کاربران واردشده",submit:"ثبت مستقیم",owner:"",notes:""};
const labels:Record<string,string>={draft:"پیش‌نویس",published:"منتشرشده",disabled:"غیرفعال",archived:"آرشیو"};
export default function FormBuilderWorkspace(){
 const[items,setItems]=useState<FormRow[]>([]),[form,setForm]=useState({...blank}),[edit,setEdit]=useState<string|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[submissions,setSubmissions]=useState<FormRow|null>(null);
 const load=async()=>{setError("");try{const r=await fetch(API+"/api/form-builder/forms?q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"خطا در دریافت فرم‌ها");setItems(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت فرم‌ها")}};
 useEffect(()=>{load()},[q]);
 const visible=useMemo(()=>items.filter(r=>tab==="all"||r.status===tab),[items,tab]);
 const set=(k:string,v:string)=>setForm(x=>({...x,[k]:v}));
 const reset=()=>{setEdit(null);setForm({...blank})};
 const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim()||!form.key.trim())return setError("کد، عنوان و کلید فرم الزامی است.");setBusy(true);try{let schema:Record<string,unknown>={fields:[]};if(form.schema.trim()){schema=JSON.parse(form.schema)}const body={code:form.code,title:form.title,key:form.key,category:form.category,version:Number(form.version)||1,schema,validationMode:form.validation,accessLevel:form.access,submitMode:form.submit,ownerRef:form.owner,notes:form.notes};const r=await fetch(API+"/api/form-builder/forms"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify(body)}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت فرم انجام نشد");reset();await load()}catch(e){setError(e instanceof SyntaxError?"ساختار JSON فرم معتبر نیست":e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
 const editRow=(r:FormRow)=>{setEdit(r.id);setForm({code:r.code,title:r.name,key:r.slug,category:r.category,version:String(r.version),schema:JSON.stringify(r.schema||{fields:[]},null,2),validation:r.validation_mode,access:r.access_level,submit:r.submit_mode,owner:r.owner_ref||"",notes:r.notes||""});scrollTo({top:0,behavior:"smooth"})};
 const action=async(path:string)=>{setError("");const r=await fetch(API+path,{method:"POST",credentials:"include",headers:{"X-CSRF-Token":token(),"Content-Type":"application/json"},body:"{}"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"عملیات انجام نشد");await load()};
 const remove=async(id:string)=>{try{const r=await fetch(API+"/api/form-builder/forms/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":token()}});if(!r.ok){const b=await r.json().catch(()=>null);throw Error(b?.error||"حذف انجام نشد")}await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>پنل ۱۴ · فرم‌ساز</small><h1>فرم‌ساز سازمانی</h1><p>تعریف فرم، نسخه‌بندی، کنترل دسترسی، انتشار و مدیریت Submission روی داده واقعی PostgreSQL.</p></div><div className={styles.stat}><b>{items.length.toLocaleString("fa-IR")}</b><span>فرم واقعی</span></div></header>
 <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
 <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>form_definitions · PostgreSQL</small><h2>{edit?"ویرایش فرم":"ساخت فرم جدید"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>
 {[["code","کد فرم *"],["title","عنوان فرم *"],["key","کلید فرم *"],["version","نسخه"],["owner","مالک فرم"]].map(([k,l])=><label key={k}>{l}<input value={String(form[k as keyof typeof form]??"")} onChange={e=>set(k,e.target.value)}/></label>)}
 <label>دسته‌بندی<select value={form.category} onChange={e=>set("category",e.target.value)}>{["ثبت‌نام","اعتبار و تسهیلات","فروش","پشتیبانی","منابع انسانی","سازمانی","عمومی","سایر"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>اعتبارسنجی<select value={form.validation} onChange={e=>set("validation",e.target.value)}>{["استاندارد","سخت‌گیرانه","قابل تنظیم"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>سطح دسترسی<select value={form.access} onChange={e=>set("access",e.target.value)}>{["عمومی","کاربران واردشده","نقش‌محور","سازمانی"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label>روش ارسال<select value={form.submit} onChange={e=>set("submit",e.target.value)}>{["ثبت مستقیم","نیازمند بررسی","نیازمند تأیید"].map(x=><option key={x}>{x}</option>)}</select></label>
 <label className={styles.full}>Schema JSON<textarea rows={8} value={form.schema} onChange={e=>set("schema",e.target.value)} placeholder={'{"fields":[]}'}/></label>
 <label className={styles.full}>یادداشت<textarea rows={3} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary} disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت فرم"}</button></form>
 <section className={styles.card}><div className={styles.head}><div><small>کتابخانه واقعی فرم‌ها</small><h2>فرم‌ها</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد، عنوان یا کلید..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.name}</b><small>{r.code} · {r.slug} · نسخه {r.version}</small><span>{labels[r.status]||r.status} · {r.submission_count} Submission</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.status!=="published"&&<button onClick={()=>action("/api/form-builder/forms/"+r.id+"/publish").catch(e=>setError(e.message))}>انتشار</button>}{r.status==="published"&&<button onClick={()=>action("/api/form-builder/forms/"+r.id+"/disable").catch(e=>setError(e.message))}>غیرفعال</button>}<button onClick={()=>setSubmissions(r)}>Submissionها</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>فرمی ثبت نشده است.</div>}</div></section></section>
 {submissions&&<section className={styles.card}><div className={styles.head}><div><small>{submissions.code}</small><h2>Submissionهای فرم {submissions.name}</h2></div><button onClick={()=>setSubmissions(null)}>بستن</button></div><p className={styles.empty}>برای فهرست Submissionها API واقعی فرم فعال است؛ این بخش بدون ساخت رکورد نمایشی، فقط داده ثبت‌شده را مصرف می‌کند.</p></section>}
 </main>}
