"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./FrontendSectionsWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const blank:any={code:"",title:"",page:"",type:"هدر",template:"",block:"",order:0,visibility:"عمومی",responsive:"خودکار",status:"پیش‌نویس",version:1,content:"",notes:""};
const tabs=[["all","همه بخش‌ها"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]];
export default function FrontendSectionsWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...blank}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/37-frontend-sections/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت بخش‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||String(r.data.status)===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"}as any)[tab]).sort((a,b)=>String(a.data["page-code"]||"").localeCompare(String(b.data["page-code"]||""))||Number(a.data["order-index"]||0)-Number(b.data["order-index"]||0)),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...blank})};
const payload=(d=form)=>({recordType:"frontend-section",title:String(d.title),status:String(d.status),data:{"section-code":d.code,"section-title":d.title,"page-code":d.page,"section-type":d.type,"template-code":d.template,"block-reference":d.block,"order-index":Number(d.order||0),visibility:d.visibility,"responsive-mode":d.responsive,status:d.status,version:Number(d.version||1),"content-reference":d.content,notes:d.notes}});
const save=async()=>{setError("");if(!String(form.code).trim()||!String(form.title).trim()||!String(form.page).trim())return setError("کد بخش، عنوان و کد صفحه الزامی است.");setBusy(true);try{const r=await fetch(API+"/api/platform/modules/37-frontend-sections/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره بخش انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/37-frontend-sections/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:data.status||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["section-code"]||"",title:d["section-title"]||r.title,page:d["page-code"]||"",type:d["section-type"]||"هدر",template:d["template-code"]||"",block:d["block-reference"]||"",order:d["order-index"]??0,visibility:d.visibility||"عمومی",responsive:d["responsive-mode"]||"خودکار",status:d.status||"پیش‌نویس",version:d.version||1,content:d["content-reference"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"section-code":String(r.data["section-code"]||"")+"-COPY","section-title":String(r.data["section-title"]||"")+" - نسخه جدید",status:"پیش‌نویس",version:1,"order-index":Number(r.data["order-index"]||0)+1};await fetch(API+"/api/platform/modules/37-frontend-sections/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"frontend-section",title:d["section-title"],status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/37-frontend-sections/records/"+id,{method:"DELETE",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()}});await load()};
const move=async(r:R,d:number)=>patch(r,{...r.data,"order-index":Math.max(0,Number(r.data["order-index"]||0)+d)});
const action=async(r:R,status:string)=>patch(r,{...r.data,status});
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۳۷</small><h1>مدیریت بخش‌های فرانت‌اند</h1><p>مدیریت بخش‌های قابل استفاده در صفحات، نواحی نمایش، ترتیب، دسترسی و رفتار ریسپانسیو.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>بخش</span></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{edit?"ویرایش بخش":"ساخت بخش"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد بخش *"],["title","عنوان بخش *"],["page","کد صفحه *"],["template","قالب بخش"],["block","مرجع بلوک"],["order","ترتیب نمایش"],["version","نسخه"],["content","مرجع محتوا"]].map(([k,l]:any)=><label key={k}>{l}<input type={k==="order"||k==="version"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}
<label>نوع بخش<select value={form.type} onChange={e=>set("type",e.target.value)}>{["هدر","منوی اصلی","قهرمان","محتوای اصلی","کارت‌ها","فهرست","فراخوان اقدام","فرم","اعلان","فوتر","سفارشی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>سطح نمایش<select value={form.visibility} onChange={e=>set("visibility",e.target.value)}>{["عمومی","کاربران واردشده","نقش‌محور","سازمانی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>رفتار ریسپانسیو<select value={form.responsive} onChange={e=>set("responsive",e.target.value)}>{["خودکار","موبایل‌محور","دسکتاپ‌محور","سفارشی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>وضعیت<select value={form.status} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","فعال","غیرفعال","آرشیو شده"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary} disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت بخش"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>مدیریت ساختار فرانت‌اند</small><h2>بخش‌های ثبت‌شده</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد صفحه، عنوان یا نوع بخش..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["section-title"]||r.title}</b><small>{r.data["page-code"]||""} · {r.data["section-type"]||""} · {r.data["template-code"]||""}</small><span>{r.data.status||r.status} · ترتیب {String(r.data["order-index"]??0)}</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button><button onClick={()=>move(r,-1)}>↑</button><button onClick={()=>move(r,1)}>↓</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>action(r,"فعال")}>فعال‌سازی</button>}{r.data.status==="فعال"&&<button onClick={()=>action(r,"غیرفعال")}>غیرفعال</button>}<button onClick={()=>action(r,"آرشیو شده")}>آرشیو</button><button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>بخشی ثبت نشده است.</div>}</div></section></section></main>}