"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./FrontendNotificationsWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",title:"",type:"اطلاع‌رسانی",channel:"داخل سامانه",audience:"کاربران واردشده",event:"",route:"",message:"",priority:0,delivery:"فوری",status:"پیش‌نویس",scheduled:"",expires:"",read:"قابل خواندن",notes:""};
const opts:any={type:["اطلاع‌رسانی","موفقیت","هشدار","خطا","اقدام","سیستمی"],channel:["داخل سامانه","مرکز اعلان","پیامک","ایمیل","اعلان مرورگر","همه"],audience:["عمومی","کاربران واردشده","نقش‌محور","سازمانی","کاربر مشخص"],delivery:["فوری","صف ارسال","زمان‌بندی شده"],status:["پیش‌نویس","فعال","غیرفعال","آرشیو شده"],read:["قابل خواندن","نیازمند تأیید","خودکار"]};
export default function FrontendNotificationsWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/39-frontend-notifications/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت اعلان‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data.status===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"}as any)[tab]).sort((a,b)=>Number(a.data.priority||0)-Number(b.data.priority||0)),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"frontend-notification",title:d.title,status:d.status,data:{"notification-code":d.code,"notification-title":d.title,"notification-type":d.type,channel:d.channel,audience:d.audience,"trigger-event":d.event,"target-route":d.route,"message-reference":d.message,priority:Number(d.priority||0),"delivery-mode":d.delivery,status:d.status,"scheduled-at":d.scheduled,"expires-at":d.expires,"read-mode":d.read,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim())return setError("کد و عنوان اعلان الزامی است.");try{const r=await fetch(API+"/api/platform/modules/39-frontend-notifications/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/39-frontend-notifications/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:data["notification-title"]||r.title,status:data.status||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["notification-code"]||"",title:d["notification-title"]||r.title,type:d["notification-type"]||"اطلاع‌رسانی",channel:d.channel||"داخل سامانه",audience:d.audience||"کاربران واردشده",event:d["trigger-event"]||"",route:d["target-route"]||"",message:d["message-reference"]||"",priority:d.priority??0,delivery:d["delivery-mode"]||"فوری",status:d.status||"پیش‌نویس",scheduled:d["scheduled-at"]||"",expires:d["expires-at"]||"",read:d["read-mode"]||"قابل خواندن",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"notification-code":String(r.data["notification-code"]||"")+"-COPY","notification-title":String(r.data["notification-title"]||"")+" - نسخه جدید",status:"پیش‌نویس"};await fetch(API+"/api/platform/modules/39-frontend-notifications/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"frontend-notification",title:d["notification-title"],status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/39-frontend-notifications/records/"+id,{method:"DELETE",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()}});await load()};
const action=async(r:R,status:string)=>patch(r,{...r.data,status});
const schedule=async(r:R)=>patch(r,{...r.data,"delivery-mode":"زمان‌بندی شده",status:"فعال","scheduled-at":new Date().toISOString()});
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۳۹</small><h1>مدیریت اعلان‌های فرانت‌اند</h1><p>تعریف، انتشار و زمان‌بندی اعلان‌های واقعی سامانه برای کاربران و کانال‌های مختلف.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>اعلان</span></div></header>
<div className={styles.tabs}>{[["all","همه اعلان‌ها"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]].map(([k,t])=><button className={tab===k?styles.active:""} key={k} onClick={()=>setTab(k)}>{t}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش اعلان":"ساخت اعلان"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد اعلان *"],["title","عنوان اعلان *"],["event","رویداد محرک"],["route","مسیر مقصد"],["message","مرجع پیام"],["priority","اولویت"],["scheduled","زمان‌بندی ارسال"],["expires","زمان انقضا"]].map(([k,l]:[string,string])=><label key={k}>{l}<input type={k==="priority"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({type:"نوع اعلان",channel:"کانال نمایش",audience:"مخاطب",delivery:"نحوه ارسال",status:"وضعیت",read:"وضعیت خواندن"}).map(([k,l]:[string,string])=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary}>{edit?"ذخیره تغییرات":"ثبت اعلان"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>Notification Lifecycle</small><h2>اعلان‌های ثبت‌شده</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="عنوان، کانال، رویداد یا مسیر..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["notification-title"]||r.title}</b><small>{r.data["notification-type"]||""} · {r.data.channel||""} · {r.data.audience||""}</small><span>{r.data.status||r.status} · {r.data["delivery-mode"]||""}</span></div><div className={styles.actions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>action(r,"فعال")}>فعال‌سازی</button>}{r.data.status==="فعال"&&<button onClick={()=>action(r,"غیرفعال")}>غیرفعال</button>}<button onClick={()=>schedule(r)}>زمان‌بندی</button><button onClick={()=>action(r,"آرشیو شده")}>آرشیو</button><button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>اعلانی ثبت نشده است.</div>}</div></section></section></main>}