"use client";

import {useEffect,useState} from "react";
import styles from "./IdentityWorkspace.module.css";

type Data={users:any[];roles:any[];groups:any[];members:any[];permissions:any[];grants:any[];sessions:any[];logins:any[];policies:any[]};
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["users","کاربران و حساب‌ها"],["profiles","پروفایل کاربران"],["roles","نقش‌ها"],["groups","گروه‌های کاربری"],["permissions","مجوزها"],["policies","سیاست‌های امنیتی"],["auth","احراز هویت"],["twofa","احراز هویت دومرحله‌ای"],["sessions","نشست‌ها و دستگاه‌ها"],["audit","ورودها و ممیزی"]];
const empty:Data={users:[],roles:[],groups:[],members:[],permissions:[],grants:[],sessions:[],logins:[],policies:[]};

export default function IdentityWorkspace(){
 const [tab,setTab]=useState("users"),[d,setD]=useState<Data>(empty),[err,setErr]=useState(""),[saving,setSaving]=useState(false),[policyAccess,setPolicyAccess]=useState<boolean|null>(null);
 const [name,setName]=useState(""),[roleKey,setRoleKey]=useState("viewer"),[key,setKey]=useState(""),[selectedGroup,setSelectedGroup]=useState(""),[selectedUser,setSelectedUser]=useState("");
 const [canManageRoles,setCanManageRoles]=useState(false);
 const load=async()=>{
  setErr("");
  const r=await fetch(api+"/api/identity/overview",{credentials:"include"});
  const b=await r.json().catch(()=>null);
  if(!r.ok)throw Error(b?.error||"دریافت اطلاعات هویت و دسترسی ناموفق بود");
  let policies:any[]=[];let canReadPolicies=false;
  try{const sr=await fetch(api+"/api/security/overview",{credentials:"include"});if(sr.ok){const sb=await sr.json();policies=Array.isArray(sb.policies)?sb.policies:[];canReadPolicies=true;}}catch{}
  setPolicyAccess(canReadPolicies);setCanManageRoles(Boolean(b.access?.canManageRoles));setD({...empty,...b,policies});
  setRoleKey(current=>b.roles?.some((x:any)=>x.role_key===current)?current:(b.roles?.[0]?.role_key||"viewer"));
  setSelectedGroup(current=>b.groups?.some((x:any)=>String(x.id)===current)?current:(b.groups?.[0]?String(b.groups[0].id):""));
  setSelectedUser(current=>b.users?.some((x:any)=>String(x.id)===current)?current:(b.users?.[0]?String(b.users[0].id):""));
 };
 useEffect(()=>{const p=new URLSearchParams(location.search);const t=p.get("tab");if(t&&tabs.some(([k])=>k===t))setTab(t);void load().catch(e=>setErr(e.message))},[]);
 const request=async(path:string,method:string,body?:any)=>{
  setSaving(true);setErr("");
  try{const r=await fetch(api+path,{method,credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},...(body===undefined?{}:{body:JSON.stringify(body)})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"عملیات در سامانه ثبت نشد");await load();return true;}
  finally{setSaving(false)}
 };
 const has=(permission:string)=>d.grants.some(g=>g.role_key===roleKey&&g.permission_key===permission);
 const savePermissions=async()=>{try{await request("/api/identity/roles/"+encodeURIComponent(roleKey)+"/permissions","PUT",{permissionKeys:d.grants.filter(g=>g.role_key===roleKey).map(g=>g.permission_key)});}catch(e){setErr(e instanceof Error?e.message:"ذخیره مجوزها ناموفق بود")}};
 const saveRole=async()=>{if(!key.trim()||!name.trim())return setErr("شناسه و عنوان نقش الزامی است");try{await request("/api/identity/roles","POST",{roleKey:key.trim(),title:name.trim()});setKey("");setName("")}catch(e){setErr(e instanceof Error?e.message:"ثبت نقش ناموفق بود")}};
 const saveGroup=async()=>{if(!key.trim()||!name.trim())return setErr("شناسه و عنوان گروه الزامی است");try{await request("/api/identity/groups","POST",{groupKey:key.trim(),title:name.trim()});setKey("");setName("")}catch(e){setErr(e instanceof Error?e.message:"ثبت گروه ناموفق بود")}};
 const addMember=async()=>{if(!selectedGroup||!selectedUser)return setErr("گروه و کاربر را انتخاب کنید");try{await request("/api/identity/groups/"+encodeURIComponent(selectedGroup)+"/members","POST",{userId:selectedUser})}catch(e){setErr(e instanceof Error?e.message:"افزودن عضو ناموفق بود")}};
 const updateUser=async(id:string,body:any)=>{try{await request("/api/identity/users/"+encodeURIComponent(id),"PATCH",body)}catch(e){setErr(e instanceof Error?e.message:"به‌روزرسانی کاربر ناموفق بود")}};
 const removeMember=async(groupId:string|number,userId:string)=>{try{await request("/api/identity/groups/"+encodeURIComponent(String(groupId))+"/members/"+encodeURIComponent(userId),"DELETE")}catch(e){setErr(e instanceof Error?e.message:"حذف عضو از گروه ناموفق بود")}};
 const revoke=async(id:string)=>{try{await request("/api/identity/sessions/"+encodeURIComponent(id)+"/revoke","POST")}catch(e){setErr(e instanceof Error?e.message:"لغو نشست ناموفق بود")}};
 const togglePolicy=async(p:any)=>{try{await request("/api/security/policies/"+encodeURIComponent(p.policy_key),"PUT",{title:p.title,enabled:!p.enabled,config:p.config||{}})}catch(e){setErr(e instanceof Error?e.message:"تغییر سیاست امنیتی ناموفق بود")}};
 const activeSessions=d.sessions.filter(s=>!s.revoked_at);
 const twoFactorPolicies=d.policies.filter(p=>/mfa|2fa|two.factor|دومرحله/i.test(String(p.policy_key)+" "+String(p.title)));
 return <main className={styles.wrap} dir="rtl">
  <header><div><span>منوی مرکزی سازمان · ۰۳</span><h1>کاربران، نقش‌ها و دسترسی‌ها</h1><p>مدیریت یکپارچه هویت سازمانی بر پایه اطلاعات واقعی سامانه و پایگاه داده</p></div><button disabled={saving} onClick={()=>void load().catch(e=>setErr(e.message))}>به‌روزرسانی</button></header>
  <section className={styles.metrics}>{[["کاربران",d.users.length],["نقش‌ها",d.roles.length],["گروه‌ها",d.groups.length],["نشست‌های فعال",activeSessions.length]].map(([label,value])=><article key={String(label)}><span>{label}</span><strong>{value}</strong></article>)}</section>
  <nav aria-label="بخش‌های کاربران و دسترسی">{tabs.map(([k,t])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</nav>
  {err&&<div role="alert" className={styles.error}>{err}</div>}
  {tab==="users"&&<section className={styles.panel}><h2>کاربران و حساب‌ها</h2><p>نقش کاربر از رکورد واقعی سامانه تغییر می‌کند؛ ایجاد حساب جدید فقط از مسیر ثبت‌نام امن انجام می‌شود.</p>{d.users.map(u=><article key={u.id}><div><b>{u.full_name}</b><small>{u.email} · شناسه {u.id}</small></div>{canManageRoles?<><label>نقش <select aria-label={"نقش "+u.email} value={u.role} onChange={e=>void updateUser(u.id,{role:e.target.value})}>{d.roles.map(r=><option key={r.role_key} value={r.role_key}>{r.title} ({r.role_key})</option>)}</select></label><label>وضعیت <select aria-label={"وضعیت "+u.email} value={u.status} onChange={e=>void updateUser(u.id,{status:e.target.value})}><option value="active">فعال</option><option value="pending">در انتظار</option><option value="suspended">تعلیق‌شده</option></select></label></>:<span>نقش: {u.role} · {u.status}</span>}</article>)}{!d.users.length&&<p>کاربری برای نمایش وجود ندارد.</p>}</section>}
  {tab==="profiles"&&<section className={styles.panel}><h2>پروفایل کاربران</h2>{d.users.map(u=><article key={u.id}><div><b>{u.full_name}</b><small>{u.email}</small></div><div><span>نقش: {u.role}</span><small>وضعیت: {u.status} · ایجاد: {u.created_at?new Date(u.created_at).toLocaleDateString("fa-IR"):"ثبت نشده"}</small></div></article>)}{!d.users.length&&<p>پروفایلی برای نمایش وجود ندارد.</p>}</section>}
  {tab==="roles"&&<section className={styles.panel}><h2>نقش‌ها و مسئولیت‌ها</h2>{canManageRoles&&<div className={styles.form}><input aria-label="شناسه نقش" placeholder="شناسه نقش، مانند support_agent" value={key} onChange={e=>setKey(e.target.value)}/><input aria-label="عنوان نقش" placeholder="عنوان نقش" value={name} onChange={e=>setName(e.target.value)}/><button disabled={saving} onClick={()=>void saveRole()}>ثبت نقش</button></div>}{d.roles.map(r=><article key={r.role_key}><div><b>{r.title}</b><small>{r.role_key} · {r.user_count} کاربر</small></div><span>{r.is_system?"نقش سیستمی":"نقش سفارشی"} · {r.is_active?"فعال":"غیرفعال"}</span></article>)}</section>}
  {tab==="groups"&&<section className={styles.panel}><h2>گروه‌های کاربری و عضویت</h2><div className={styles.form}><input aria-label="شناسه گروه" placeholder="شناسه گروه، مانند finance_team" value={key} onChange={e=>setKey(e.target.value)}/><input aria-label="عنوان گروه" placeholder="عنوان گروه" value={name} onChange={e=>setName(e.target.value)}/><button disabled={saving} onClick={()=>void saveGroup()}>ثبت گروه</button></div><div className={styles.memberForm}><select aria-label="انتخاب گروه" value={selectedGroup} onChange={e=>setSelectedGroup(e.target.value)}><option value="">انتخاب گروه</option>{d.groups.map(g=><option key={g.id} value={String(g.id)}>{g.title}</option>)}</select><select aria-label="انتخاب کاربر" value={selectedUser} onChange={e=>setSelectedUser(e.target.value)}><option value="">انتخاب کاربر</option>{d.users.map(u=><option key={u.id} value={String(u.id)}>{u.full_name} · {u.email}</option>)}</select><button disabled={saving||!selectedGroup||!selectedUser} onClick={()=>void addMember()}>افزودن عضو به گروه</button></div>{d.groups.map(g=><div key={g.id}><article><div><b>{g.title}</b><small>{g.group_key}</small></div><span>{g.member_count} عضو · {g.is_active?"فعال":"غیرفعال"}</span></article>{d.members.filter(m=>String(m.group_id)===String(g.id)).map(m=><article key={m.user_id}><div><b>{m.full_name}</b><small>{m.email}</small></div><button disabled={saving} onClick={()=>void removeMember(g.id,m.user_id)}>حذف از گروه</button></article>)}</div>)}</section>}
  {tab==="permissions"&&<section className={styles.panel}><h2>کاتالوگ مجوزها و انتساب نقش</h2><div className={styles.toolbar}><label>نقش مورد بررسی <select value={roleKey} onChange={e=>setRoleKey(e.target.value)}>{d.roles.map(r=><option key={r.role_key} value={r.role_key}>{r.title} ({r.role_key})</option>)}</select></label><button disabled={saving||!roleKey||!canManageRoles} onClick={()=>void savePermissions()}>ذخیره مجوزهای نقش</button></div>{d.permissions.map(p=><article key={p.permission_key}><label className={styles.permission}><input type="checkbox" disabled={!canManageRoles} checked={has(p.permission_key)} onChange={e=>setD(current=>({...current,grants:e.target.checked?[...current.grants,{role_key:roleKey,permission_key:p.permission_key}]:current.grants.filter(g=>!(g.role_key===roleKey&&g.permission_key===p.permission_key))}))}/><span><b>{p.title}</b><small>{p.permission_key} · {p.module_key}</small></span></label><span>{p.action}</span></article>)}{!d.permissions.length&&<p>مجوزی در کاتالوگ ثبت نشده است.</p>}</section>}
  {tab==="policies"&&<section className={styles.panel}><h2>سیاست‌های امنیتی سازمان</h2>{policyAccess===false&&<p className={styles.notice}>سیاست‌های امنیتی برای نقش فعلی قابل مشاهده نیستند. این بخش فقط از API محافظت‌شدهٔ سامانه داده می‌گیرد.</p>}{policyAccess&&d.policies.map(p=><article key={p.policy_key}><div><b>{p.title}</b><small>{p.policy_key}</small></div><button disabled={saving} className={p.enabled?styles.enabled:styles.disabled} onClick={()=>void togglePolicy(p)}>{p.enabled?"فعال":"غیرفعال"}</button></article>)}{policyAccess&&d.policies.length===0&&<p>هنوز سیاست امنیتی ثبت نشده است.</p>}</section>}
  {tab==="auth"&&<section className={styles.panel}><h2>احراز هویت و ورود امن</h2><article><div><b>نشست‌های معتبر</b><small>نمایش و لغو نشست‌ها از API هویت</small></div><strong>{activeSessions.length}</strong></article><article><div><b>سیاست‌های ورود</b><small>کنترل از طریق سیاست‌های امنیتی دارای مجوز</small></div><span>{policyAccess===true?"قابل مشاهده":policyAccess===false?"نیازمند مجوز":"در حال بررسی"}</span></article><p>تنظیمات احراز هویت تنها وقتی فعال نشان داده می‌شوند که در سرویس امنیتی ثبت و قابل خواندن باشند.</p></section>}
  {tab==="twofa"&&<section className={styles.panel}><h2>احراز هویت دومرحله‌ای</h2>{policyAccess===false&&<p className={styles.notice}>دسترسی به تنظیم سیاست‌های احراز هویت دومرحله‌ای برای نقش فعلی مجاز نیست.</p>}{policyAccess&&twoFactorPolicies.map(p=><article key={p.policy_key}><div><b>{p.title}</b><small>{p.policy_key}</small></div><button disabled={saving} className={p.enabled?styles.enabled:styles.disabled} onClick={()=>void togglePolicy(p)}>{p.enabled?"فعال":"غیرفعال"}</button></article>)}{policyAccess&&twoFactorPolicies.length===0&&<p>سیاست مشخصی برای احراز هویت دومرحله‌ای در پایگاه داده پیدا نشد؛ این قابلیت به‌صورت پیش‌فرض فعال فرض نشده است.</p>}</section>}
  {tab==="sessions"&&<section className={styles.panel}><h2>نشست‌ها و دستگاه‌های مجاز</h2>{d.sessions.map(s=><article key={s.id}><div><b>{s.user_id} · {s.ip_address||"IP ثبت نشده"}</b><small>{s.user_agent||"دستگاه نامشخص"} · آخرین فعالیت: {s.last_seen_at?new Date(s.last_seen_at).toLocaleString("fa-IR"):"ثبت نشده"}</small></div>{s.revoked_at?<span>لغو شده</span>:<button disabled={saving} onClick={()=>void revoke(s.id)}>لغو نشست</button>}</article>)}{!d.sessions.length&&<p>نشستی برای نمایش وجود ندارد.</p>}</section>}
  {tab==="audit"&&<section className={styles.panel}><h2>تاریخچه ورود و ممیزی امنیتی</h2>{d.logins.map(l=><article key={l.id}><div><b>{l.email}</b><small>{l.ip_address||"IP ثبت نشده"} · {l.occurred_at?new Date(l.occurred_at).toLocaleString("fa-IR"):"زمان نامشخص"}{l.failure_reason?" · "+l.failure_reason:""}</small></div><span className={l.success?styles.enabled:styles.disabled}>{l.success?"ورود موفق":"ورود ناموفق"}</span></article>)}{!d.logins.length&&<p>رویداد ورودی برای نمایش وجود ندارد.</p>}</section>}
 </main>
}
