"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./IdentityVerificationWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه بررسی‌ها"],["ocr","پردازش OCR"],["review","نیازمند بازبینی"],["verified","تأییدشده"],["failed","ناموفق"]];
const initial={code:"",person:"",docType:"کارت ملی",docNo:"",file:"",ocr:"ثبت نشده",name:"",national:"",birth:"",verification:"در انتظار بررسی",reviewer:"",reviewDate:"",notes:""};

export default function IdentityVerificationWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/18-identity-verification/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت بررسی‌ها انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="ocr")a=a.filter(x=>["در انتظار پردازش","پردازش شده"].includes(String(x.data?.["ocr-status"]||"")));if(tab==="review")a=a.filter(x=>String(x.data?.["ocr-status"]||"")==="نیازمند بازبینی"||String(x.data?.["verification-status"]||"")==="نیازمند اصلاح");if(tab==="verified")a=a.filter(x=>x.data?.["verification-status"]==="تأیید شده");if(tab==="failed")a=a.filter(x=>x.data?.["ocr-status"]==="ناموفق"||x.data?.["verification-status"]==="رد شده");return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const save=async()=>{if(!String(form.code||"").trim()||!String(form.person||"").trim()||!String(form.file||"").trim())return setError("کد بررسی، شناسه شخص و مرجع فایل الزامی است.");setSaving(true);setError("");try{const data={"verification-code":form.code,"person-id":form.person,"document-type":form.docType,"document-number":form.docNo,"file-reference":form.file,"ocr-status":form.ocr,"extracted-name":form.name,"extracted-national-id":form.national,"extracted-birth-date":form.birth,"verification-status":form.verification,"reviewer":form.reviewer,"review-date":form.reviewDate,"review-notes":form.notes};const r=await fetch(API+"/api/platform/modules/18-identity-verification/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"identity-verification",title:String(form.code)+" / "+String(form.person),status:String(form.verification),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت بررسی انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["verification-code"]||"",person:d["person-id"]||"",docType:d["document-type"]||"کارت ملی",docNo:d["document-number"]||"",file:d["file-reference"]||"",ocr:d["ocr-status"]||"ثبت نشده",name:d["extracted-name"]||"",national:d["extracted-national-id"]||"",birth:d["extracted-birth-date"]||"",verification:d["verification-status"]||"در انتظار بررسی",reviewer:d.reviewer||"",reviewDate:d["review-date"]||"",notes:d["review-notes"]||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status?:string)=>{const d={...r.data,...changes};const x=await fetch(API+"/api/platform/modules/18-identity-verification/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:status||r.status,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const process=(r:R)=>patch(r,{"ocr-status":"در انتظار پردازش"});
 const verify=(r:R)=>patch(r,{"verification-status":"تأیید شده","review-date":new Date().toISOString().slice(0,10)}, "تأیید شده");
 const remove=async(id:number)=>{if(!confirm("این بررسی حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/18-identity-verification/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>هویت و مدارک · ماژول ۱۸</span><h1>احراز هویت و بررسی مدارک</h1><p>مدیریت مدارک هویتی و چرخه بررسی اطلاعات استخراج‌شده از اسناد.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>بررسی</small><b>{items.filter(x=>x.data?.["verification-status"]==="تأیید شده").length.toLocaleString("fa-IR")}</b><small>تأییدشده</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش بررسی":"ثبت بررسی مدرک"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد بررسی *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>شناسه شخص *<input value={String(form.person)} onChange={e=>set("person",e.target.value)}/></label>
    <label>نوع مدرک<select value={String(form.docType)} onChange={e=>set("docType",e.target.value)}>{["کارت ملی","شناسنامه","گواهینامه","پاسپورت","سند ثبتی","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>شماره مدرک<input value={String(form.docNo)} onChange={e=>set("docNo",e.target.value)}/></label>
    <label className={styles.full}>مرجع فایل *<input value={String(form.file)} onChange={e=>set("file",e.target.value)} placeholder="شناسه امن فایل"/></label>
    <label>وضعیت OCR<select value={String(form.ocr)} onChange={e=>set("ocr",e.target.value)}>{["ثبت نشده","در انتظار پردازش","پردازش شده","نیازمند بازبینی","ناموفق"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>وضعیت احراز<select value={String(form.verification)} onChange={e=>set("verification",e.target.value)}>{["در انتظار بررسی","تأیید شده","نیازمند اصلاح","رد شده"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>نام استخراج‌شده<input value={String(form.name)} onChange={e=>set("name",e.target.value)}/></label><label>کد ملی استخراج‌شده<input value={String(form.national)} onChange={e=>set("national",e.target.value)}/></label>
    <label>تاریخ تولد استخراج‌شده<input type="date" value={String(form.birth)} onChange={e=>set("birth",e.target.value)}/></label><label>بررسی‌کننده<input value={String(form.reviewer)} onChange={e=>set("reviewer",e.target.value)}/></label>
    <label>تاریخ بررسی<input type="date" value={String(form.reviewDate)} onChange={e=>set("reviewDate",e.target.value)}/></label>
    <label className={styles.full}>یادداشت بررسی<textarea rows={3} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت بررسی در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق ثبت‌شده</small><h2>صف بررسی مدارک</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد، شخص یا شماره مدرک..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["document-type"]||"")} · OCR: {String(r.data?.["ocr-status"]||"")} · {String(r.data?.["verification-status"]||"")}</small><span>{String(r.data?.["extracted-name"]||"اطلاعات استخراج نشده")} · {String(r.data?.["extracted-national-id"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{tab==="ocr"&&<button className={styles.process} onClick={()=>process(r)}>پردازش</button>}{(tab==="review"||tab==="all")&&<button className={styles.confirm} onClick={()=>verify(r)}>تأیید</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>موردی ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
