"use client";
import {useEffect,useState} from "react";
import styles from "./InventoryWarehouseWorkspace.module.css";
type W=Record<string,any>;
const api=async(path:string,init?:RequestInit)=>{const r=await fetch(path,{credentials:"include",...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"خطا در ارتباط با سامانه");return d};
export default function InventoryWarehouseWorkspace(){
 const [tab,setTab]=useState("dashboard"),[overview,setOverview]=useState<W>({}),[warehouses,setWarehouses]=useState<W[]>([]),[products,setProducts]=useState<W[]>([]),[stock,setStock]=useState<W[]>([]),[docs,setDocs]=useState<W[]>([]),[counts,setCounts]=useState<W[]>([]),[error,setError]=useState("");
 const [cat,setCat]=useState({code:"",name:""}),[unit,setUnit]=useState({code:"",name:"",factor:"1"});
 const [w,setW]=useState({code:"",name:"",address:""}),[p,setP]=useState({sku:"",name:"",barcode:"",minStock:"0",maxStock:"0",reorderPoint:"0"}),[doc,setDoc]=useState({documentNo:"",type:"receipt",sourceWarehouseId:"",targetWarehouseId:"",reason:""}),[item,setItem]=useState({productId:"",quantity:"1"}),[count,setCount]=useState({countNo:"",warehouseId:""});
 const load=async()=>{setError("");try{const [o,ws,cs,us,ps,s,ds,cts]=await Promise.all([api("/api/inventory/overview"),api("/api/inventory/warehouses"),api("/api/inventory/categories"),api("/api/inventory/units"),api("/api/inventory/products"),api("/api/inventory/stock"),api("/api/inventory/documents"),api("/api/inventory/counts")]);setOverview(o);setWarehouses(ws);setCategories(cs);setUnits(us);setProducts(ps);setStock(s);setDocs(ds);setCounts(cts)}catch(e:any){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const createCategory=async()=>{try{await api("/api/inventory/categories",{method:"POST",body:JSON.stringify(cat)});setCat({code:"",name:""});await load()}catch(e:any){setError(e.message)}};
 const createUnit=async()=>{try{await api("/api/inventory/units",{method:"POST",body:JSON.stringify(unit)});setUnit({code:"",name:"",factor:"1"});await load()}catch(e:any){setError(e.message)}};
 const addCountItem=async(id:string)=>{try{await api("/api/inventory/counts/"+id+"/items",{method:"POST",body:JSON.stringify({productId:item.productId,countedQuantity:item.quantity})});await load()}catch(e:any){setError(e.message)}};
 const approveCount=async(id:string)=>{try{await api("/api/inventory/counts/"+id+"/approve",{method:"POST",body:"{}"});await load()}catch(e:any){setError(e.message)}};
 const createWarehouse=async()=>{try{await api("/api/inventory/warehouses",{method:"POST",body:JSON.stringify(w)});setW({code:"",name:"",address:""});await load()}catch(e:any){setError(e.message)}};
 const createProduct=async()=>{try{await api("/api/inventory/products",{method:"POST",body:JSON.stringify(p)});setP({sku:"",name:"",barcode:"",minStock:"0",maxStock:"0",reorderPoint:"0"});await load()}catch(e:any){setError(e.message)}};
 const createDoc=async()=>{try{await api("/api/inventory/documents",{method:"POST",body:JSON.stringify({...doc,items:[item]})});setDoc({...doc,documentNo:""});await load()}catch(e:any){setError(e.message)}};
 const post=async(id:string)=>{try{await api("/api/inventory/documents/"+id+"/post",{method:"POST",body:"{}"});await load()}catch(e:any){setError(e.message)}};
 const createCount=async()=>{try{await api("/api/inventory/counts",{method:"POST",body:JSON.stringify(count)});setCount({countNo:"",warehouseId:""});await load()}catch(e:any){setError(e.message)}};
 const tabs=[["dashboard","داشبورد"],["warehouses","انبارها"],["categories","دسته‌بندی"],["units","واحدها"],["products","کالاها"],["documents","رسید و حواله"],["stock","موجودی لحظه‌ای"],["counts","انبارگردانی"],["reports","گزارش انبار"]];
 return <main className={styles.page} dir="rtl"><header><div><span>هسته مرکزی کسب‌وکار · منوی ۱۱</span><h1>انبار</h1><p>کنترل واقعی موجودی، رسید، حواله، انتقال و انبارگردانی</p></div><button onClick={load}>بازخوانی</button></header>
 {error&&<div className={styles.error}>{error}</div>}<nav>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>
 {tab==="dashboard"&&<section className={styles.cards}>{[["انبارها",overview.warehouses?.total],["کالاهای فعال",overview.products?.active],["موجودی",overview.stock?.total],["اسناد پیش‌نویس",overview.documents?.draft]].map(([a,b])=><article key={String(a)}><small>{a}</small><strong>{b??0}</strong></article>)}</section>}
 {tab==="warehouses"&&<section className={styles.panel}><h2>مدیریت انبارها</h2><div className={styles.form}><input placeholder="کد انبار" value={w.code} onChange={e=>setW({...w,code:e.target.value})}/><input placeholder="نام انبار" value={w.name} onChange={e=>setW({...w,name:e.target.value})}/><input placeholder="نشانی" value={w.address} onChange={e=>setW({...w,address:e.target.value})}/><button onClick={createWarehouse}>ثبت انبار</button></div><Table rows={warehouses} cols={["code","name","status","address"]}/></section>}
 {tab==="categories"&&<section className={styles.panel}><h2>دسته‌بندی کالا</h2><div className={styles.form}><input placeholder="کد دسته‌بندی" value={cat.code} onChange={e=>setCat({...cat,code:e.target.value})}/><input placeholder="نام دسته‌بندی" value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/><button onClick={createCategory}>ثبت دسته‌بندی</button></div><Table rows={categories} cols={["code","name"]}/></section>}
 {tab==="units"&&<section className={styles.panel}><h2>واحدهای کالا</h2><div className={styles.form}><input placeholder="کد واحد" value={unit.code} onChange={e=>setUnit({...unit,code:e.target.value})}/><input placeholder="نام واحد" value={unit.name} onChange={e=>setUnit({...unit,name:e.target.value})}/><input placeholder="ضریب تبدیل" type="number" value={unit.factor} onChange={e=>setUnit({...unit,factor:e.target.value})}/><button onClick={createUnit}>ثبت واحد</button></div><Table rows={units} cols={["code","name","factor"]}/></section>}
 {tab==="products"&&<section className={styles.panel}><h2>کالاها</h2><div className={styles.form}><input placeholder="SKU" value={p.sku} onChange={e=>setP({...p,sku:e.target.value})}/><input placeholder="نام کالا" value={p.name} onChange={e=>setP({...p,name:e.target.value})}/><input placeholder="بارکد" value={p.barcode} onChange={e=>setP({...p,barcode:e.target.value})}/><input placeholder="حداقل موجودی" value={p.minStock} onChange={e=>setP({...p,minStock:e.target.value})}/><button onClick={createProduct}>ثبت کالا</button></div><Table rows={products} cols={["sku","name","barcode","min_stock","reorder_point"]}/></section>}
 {tab==="documents"&&<section className={styles.panel}><h2>رسید، حواله و انتقال</h2><div className={styles.form}><input placeholder="شماره سند" value={doc.documentNo} onChange={e=>setDoc({...doc,documentNo:e.target.value})}/><select value={doc.type} onChange={e=>setDoc({...doc,type:e.target.value})}><option value="receipt">رسید</option><option value="issue">حواله</option><option value="transfer">انتقال</option><option value="adjustment">اصلاح موجودی</option></select><select value={doc.sourceWarehouseId} onChange={e=>setDoc({...doc,sourceWarehouseId:e.target.value})}><option value="">مبدأ</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={doc.targetWarehouseId} onChange={e=>setDoc({...doc,targetWarehouseId:e.target.value})}><option value="">مقصد</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={item.productId} onChange={e=>setItem({...item,productId:e.target.value})}><option value="">کالا</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input placeholder="مقدار" type="number" min="0.0001" value={item.quantity} onChange={e=>setItem({...item,quantity:e.target.value})}/><input placeholder="شرح" value={doc.reason} onChange={e=>setDoc({...doc,reason:e.target.value})}/><button onClick={createDoc}>ثبت پیش‌نویس</button></div><Table rows={docs} cols={["document_no","type","status","source_warehouse_name","target_warehouse_name"]} action={(x)=>x.status==="draft"?<button onClick={()=>post(x.id)}>قطعی‌سازی</button>:null}/></section>}
 {tab==="stock"&&<section className={styles.panel}><h2>موجودی لحظه‌ای</h2><Table rows={stock} cols={["warehouse_name","sku","product_name","quantity","reserved_quantity","reorder_point"]}/></section>}
 {tab==="counts"&&<section className={styles.panel}><h2>انبارگردانی</h2><div className={styles.form}><input placeholder="شماره انبارگردانی" value={count.countNo} onChange={e=>setCount({...count,countNo:e.target.value})}/><select value={count.warehouseId} onChange={e=>setCount({...count,warehouseId:e.target.value})}><option value="">انبار</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={createCount}>شروع انبارگردانی</button></div><Table rows={counts} cols={["count_no","warehouse_name","status","count_date"]} action={(x)=>x.status==="counting"?<><button onClick={()=>addCountItem(x.id)}>ثبت شمارش کالای انتخاب‌شده</button><button onClick={()=>approveCount(x.id)}>تأیید انبارگردانی</button></>:null}/></section>}
 {tab==="reports"&&<section className={styles.panel}><h2>گزارش انبار</h2><Table rows={stock.filter(x=>Number(x.quantity)<=Number(x.reorder_point))} cols={["warehouse_name","sku","product_name","quantity","reorder_point"]}/></section>}
 </main>
}
function Table({rows,cols,action}:{rows:W[];cols:string[];action?:(x:W)=>any}){return <div className={styles.table}>{rows.map(x=><div className={styles.row} key={x.id||x.document_no||x.sku}>{cols.map(c=><span key={c}><b>{c.replaceAll("_"," ")}</b>{String(x[c]??"")}</span>)}{action&&<span>{action(x)}</span>}</div>)}{!rows.length&&<div className={styles.empty}>داده‌ای ثبت نشده است.</div>}</div>}
