"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./LoanLedgerWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه عملیات"],["principal","اصل بدهی"],["interest","سود"],["penalty","جریمه"],["posted","ثبت نهایی"]];
const init={code:"",contract:"",borrower:"",date:"",type:"پرداخت اصل",ref:"",debit:"",credit:"",principal:"",interest:"",penalty:"",total:"",method:"واریز بانکی",status:"پیش‌نویس",postedBy:"",postedAt:"",notes:""};

export default function LoanLedgerWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...init}),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/24-loan-ledger/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت دفتر حساب انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>items.filter(r=>tab==="all"||tab==="posted"?(tab==="all"||r.data?.["posting-status"]==="ثبت شده"||r.data?.["posting-status"]==="تأیید شده"):String(r.data?.["transaction-type"]||"").includes(tab==="principal"?"اصل":tab==="interest"?"سود":"جریمه")),[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...init})};
 const balance=()=>{const p=Math.max(0,Number(form.principal||0)+Number(form.debit||0)-Number(form.credit||0));const total=p+Number(form.interest||0)+Number(form.penalty||0);set("principal",p);set("total",total)};
 const save=async()=>{const req=["code","contract","borrower","date","type"];if(req.some(k=>!String(form[k]||"").trim()))return setError("کد دفتر، قرارداد، بدهکار، تاریخ و نوع عملیات الزامی است.");setSaving(true);setError("");try{const data={"ledger-code":form.code,"contract-code":form.contract,"borrower-id":form.borrower,"transaction-date":form.date,"transaction-type":form.type,"reference-code":form.ref,"debit-amount":Number(form.debit||0),"credit-amount":Number(form.credit||0),"principal-balance":Number(form.principal||0),"interest-balance":Number(form.interest||0),"penalty-balance":Number(form.penalty||0),"total-balance":Number(form.total||0),"payment-method":form.method,"posting-status":form.status,"posted-by":form.postedBy,"posted-at":form.postedAt,notes:form.notes};const r=await fetch(API+"/api/platform/modules/24-loan-ledger/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"loan-ledger-entry",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت عملیات انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["ledger-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",date:d["transaction-date"]||"",type:d["transaction-type"]||"پرداخت اصل",ref:d["reference-code"]||"",debit:d["debit-amount"]??"",credit:d["credit-amount"]??"",principal:d["principal-balance"]??"",interest:d["interest-balance"]??"",penalty:d["penalty-balance"]??"",total:d["total-balance"]??"",method:d["payment-method"]||"واریز بانکی",status:d["posting-status"]||"پیش‌نویس",postedBy:d["posted-by"]||"",postedAt:d["posted-at"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status?:string)=>{const data={...r.data,...changes};const x=await fetch(API+"/api/platform/modules/24-loan-ledger/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:status||r.status,data})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const post=(r:R)=>patch(r,{"posting-status":"ثبت شده","posted-at":new Date().toISOString(), "posted-by":"کاربر جاری"},"ثبت شده");
 const reverse=(r:R)=>patch(r,{"posting-status":"برگشت خورده"},"برگشت خورده");
 const remove=async(id:number)=>{const x=await fetch(API+"/api/platform/modules/24-loan-ledger/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۴</span><h1>دفتر حساب تسهیلات و مانده تعهدات</h1><p>ثبت رویدادهای مالی تسهیلات و نگهداری مانده اصل، سود، جریمه و مانده کل قرارداد.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>رویداد ثبت‌شده</small><b>{items.filter(x=>["ثبت شده","تأیید شده"].includes(String(x.data?.["posting-status"]))).length.toLocaleString("fa-IR")}</b><small>ثبت نهایی</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش عملیات":"ثبت عملیات دفتر حساب"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد دفتر *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label><label>شناسه بدهکار *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label><label>تاریخ عملیات *<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label>
    <label>نوع عملیات *<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["پرداخت اصل","ثبت سود","پرداخت سود","جریمه","بخشودگی","تعدیل","تسویه","برگشت پرداخت","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>کد مرجع<input value={String(form.ref)} onChange={e=>set("ref",e.target.value)}/></label>
    <label>مبلغ بدهکار<input type="number" min="0" value={String(form.debit)} onChange={e=>set("debit",e.target.value)}/></label><label>مبلغ بستانکار<input type="number" min="0" value={String(form.credit)} onChange={e=>set("credit",e.target.value)}/></label>
    <label>مانده اصل<input type="number" min="0" value={String(form.principal)} onChange={e=>set("principal",e.target.value)}/></label><label>مانده سود<input type="number" min="0" value={String(form.interest)} onChange={e=>set("interest",e.target.value)}/></label>
    <label>مانده جریمه<input type="number" min="0" value={String(form.penalty)} onChange={e=>set("penalty",e.target.value)}/></label><label>مانده کل<input type="number" min="0" value={String(form.total)} onChange={e=>set("total",e.target.value)}/></label>
    <label>روش پرداخت<select value={String(form.method)} onChange={e=>set("method",e.target.value)}>{["واریز بانکی","انتقال داخلی","پرداخت نقدی","کسر از حساب","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت ثبت<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","ثبت شده","تأیید شده","برگشت خورده","باطل شده"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>ثبت‌کننده<input value={String(form.postedBy)} onChange={e=>set("postedBy",e.target.value)}/></label><label>زمان ثبت<input type="datetime-local" value={String(form.postedAt).slice(0,16)} onChange={e=>set("postedAt",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><div className={styles.formActions}><button type="button" className={styles.secondary} onClick={balance}>محاسبه مانده</button><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت در PostgreSQL"}</button></div></form>
   <section className={styles.card}><div className={styles.head}><div><small>دفتر ثبت رویدادهای واقعی</small><h2>گردش تسهیلات</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد دفتر، قرارداد یا بدهکار..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["transaction-type"]||"")} · بدهکار: {String(r.data?.["debit-amount"]||0)} · بستانکار: {String(r.data?.["credit-amount"]||0)}</small><span>مانده کل: {String(r.data?.["total-balance"]||0)} · {String(r.data?.["posting-status"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{r.data?.["posting-status"]==="پیش‌نویس"&&<button className={styles.post} onClick={()=>post(r)}>ثبت نهایی</button>}{r.data?.["posting-status"]==="ثبت شده"&&<button className={styles.reverse} onClick={()=>reverse(r)}>برگشت</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>رویدادی ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
