"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./LoanSettlementWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه تسویه‌ها"],["review","در حال بررسی"],["ready","آماده پرداخت"],["paid","پرداخت شده"],["final","تسویه نهایی"]];
const initial={code:"",contract:"",borrower:"",request:"",date:"",principal:"",interest:"",late:"",discount:"",other:"",total:"",reference:"",method:"واریز بانکی",type:"تسویه پیش از موعد",approval:"در انتظار بررسی",status:"درخواست اولیه",approvedBy:"",notes:""};

export default function LoanSettlementWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...initial}),[editing,setEditing]=useState<number|null>(null);
 const [q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/23-loan-settlement/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت تسویه‌ها انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>{let a=items;if(tab==="review")a=a.filter(x=>["درخواست اولیه","در حال بررسی"].includes(String(x.data?.["settlement-status"]||"")));if(tab==="ready")a=a.filter(x=>x.data?.["settlement-status"]==="آماده پرداخت");if(tab==="paid")a=a.filter(x=>x.data?.["settlement-status"]==="پرداخت شده");if(tab==="final")a=a.filter(x=>x.data?.["settlement-status"]==="تسویه نهایی");return a},[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...initial})};
 const calculateTotal=()=>{const total=Math.max(0,Number(form.principal||0)+Number(form.interest||0)+Number(form.late||0)+Number(form.other||0)-Number(form.discount||0));set("total",total)};
 const save=async()=>{if(!String(form.code||"").trim()||!String(form.contract||"").trim()||!String(form.borrower||"").trim()||!String(form.request||"").trim()||!String(form.date||"").trim())return setError("کد تسویه، قرارداد، بدهکار، تاریخ درخواست و تاریخ تسویه الزامی است.");setSaving(true);setError("");try{const data={"settlement-code":form.code,"contract-code":form.contract,"borrower-id":form.borrower,"request-date":form.request,"settlement-date":form.date,"outstanding-principal":Number(form.principal||0),"outstanding-interest":Number(form.interest||0),"late-fees":Number(form.late||0),"discount-amount":Number(form.discount||0),"other-charges":Number(form.other||0),"settlement-amount":Number(form.total||0),"payment-reference":form.reference,"payment-method":form.method,"settlement-type":form.type,"approval-status":form.approval,"settlement-status":form.status,"approved-by":form.approvedBy,notes:form.notes};const r=await fetch(API+"/api/platform/modules/23-loan-settlement/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"loan-settlement",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت تسویه انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["settlement-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",request:d["request-date"]||"",date:d["settlement-date"]||"",principal:d["outstanding-principal"]??"",interest:d["outstanding-interest"]??"",late:d["late-fees"]??"",discount:d["discount-amount"]??"",other:d["other-charges"]??"",total:d["settlement-amount"]??"",reference:d["payment-reference"]||"",method:d["payment-method"]||"واریز بانکی",type:d["settlement-type"]||"تسویه پیش از موعد",approval:d["approval-status"]||"در انتظار بررسی",status:d["settlement-status"]||"درخواست اولیه",approvedBy:d["approved-by"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status?:string)=>{const d={...r.data,...changes};const x=await fetch(API+"/api/platform/modules/23-loan-settlement/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:status||r.status,data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const review=(r:R)=>patch(r,{"settlement-status":"در حال بررسی"},"در حال بررسی");
 const approve=(r:R)=>patch(r,{"approval-status":"تأیید شده","settlement-status":"آماده پرداخت"},"آماده پرداخت");
 const settle=(r:R)=>patch(r,{"settlement-status":"تسویه نهایی","settlement-date":new Date().toISOString().slice(0,10)},"تسویه نهایی");
 const cancel=(r:R)=>patch(r,{"settlement-status":"لغو شده"},"لغو شده");
 const remove=async(id:number)=>{if(!confirm("این درخواست تسویه حذف شود؟"))return;const r=await fetch(API+"/api/platform/modules/23-loan-settlement/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۳</span><h1>تسویه و بازپرداخت پیش از موعد</h1><p>محاسبه مانده بدهی، تخفیف، هزینه‌ها و کنترل فرآیند تسویه قراردادهای تسهیلات.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>درخواست تسویه</small><b>{items.filter(x=>x.data?.["settlement-status"]==="تسویه نهایی").length.toLocaleString("fa-IR")}</b><small>نهایی‌شده</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش تسویه":"ثبت درخواست تسویه"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد تسویه *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label>
    <label>شناسه بدهکار *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label><label>تاریخ درخواست *<input type="date" value={String(form.request)} onChange={e=>set("request",e.target.value)}/></label>
    <label>تاریخ تسویه *<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label><label>نوع تسویه<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["تسویه پیش از موعد","تسویه در سررسید","تسویه کامل","تسویه توافقی"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>اصل بدهی باقیمانده<input type="number" min="0" value={String(form.principal)} onChange={e=>set("principal",e.target.value)}/></label><label>سود باقیمانده<input type="number" min="0" value={String(form.interest)} onChange={e=>set("interest",e.target.value)}/></label>
    <label>جرایم و وجه التزام<input type="number" min="0" value={String(form.late)} onChange={e=>set("late",e.target.value)}/></label><label>مبلغ تخفیف<input type="number" min="0" value={String(form.discount)} onChange={e=>set("discount",e.target.value)}/></label>
    <label>سایر هزینه‌ها<input type="number" min="0" value={String(form.other)} onChange={e=>set("other",e.target.value)}/></label><label>مبلغ نهایی تسویه<input type="number" min="0" value={String(form.total)} onChange={e=>set("total",e.target.value)}/></label>
    <label>مرجع پرداخت<input value={String(form.reference)} onChange={e=>set("reference",e.target.value)}/></label><label>روش پرداخت<select value={String(form.method)} onChange={e=>set("method",e.target.value)}>{["واریز بانکی","انتقال داخلی","پرداخت نقدی","سایر"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>وضعیت تأیید<select value={String(form.approval)} onChange={e=>set("approval",e.target.value)}>{["در انتظار بررسی","تأیید شده","رد شده","نیازمند اصلاح"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت تسویه<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["درخواست اولیه","در حال بررسی","آماده پرداخت","پرداخت شده","تسویه نهایی","لغو شده"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>تأییدکننده<input value={String(form.approvedBy)} onChange={e=>set("approvedBy",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><div className={styles.formActions}><button type="button" className={styles.secondary} onClick={calculateTotal}>محاسبه مبلغ تسویه</button><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت تسویه در PostgreSQL"}</button></div></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق ثبت‌شده</small><h2>صف تسویه</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد تسویه، قرارداد یا بدهکار..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["settlement-type"]||"")} · مبلغ نهایی: {String(r.data?.["settlement-amount"]||0)}</small><span>وضعیت: {String(r.data?.["settlement-status"]||"")} · تأیید: {String(r.data?.["approval-status"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{["درخواست اولیه"].includes(String(r.data?.["settlement-status"]||""))&&<button className={styles.review} onClick={()=>review(r)}>بررسی</button>}{r.data?.["settlement-status"]==="در حال بررسی"&&<button className={styles.approve} onClick={()=>approve(r)}>تأیید</button>}{r.data?.["settlement-status"]==="آماده پرداخت"&&<button className={styles.settle} onClick={()=>settle(r)}>ثبت تسویه</button>}{!["تسویه نهایی","لغو شده"].includes(String(r.data?.["settlement-status"]||""))&&<button className={styles.cancel} onClick={()=>cancel(r)}>لغو</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>درخواست تسویه‌ای ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
