"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./LoanDelinquencyWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه معوقات"],["open","باز"],["follow","در حال پیگیری"],["promise","تعهد پرداخت"],["legal","ارجاع حقوقی"]];
const init={code:"",contract:"",borrower:"",installment:"",due:"",overdue:"",days:"",principal:"",interest:"",penalty:"",total:"",risk:"متوسط",stage:"هشدار اولیه",contact:"تماس نشده",promiseDate:"",promiseAmount:"",legal:"",resolution:"باز",assigned:"",lastContact:"",nextAction:"",notes:""};
export default function LoanDelinquencyWorkspace(){
const[tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...init}),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
const load=async()=>{setLoading(true);try{const r=await fetch(API+"/api/platform/modules/27-loan-delinquency/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت معوقات انجام نشد");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setLoading(false)}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>items.filter(r=>{const s=String(r.data?.["resolution-status"]||"باز");return tab==="all"||tab==="open"?tab==="all"||s==="باز":tab==="follow"?s==="در حال پیگیری":tab==="promise"?s==="تعهد پرداخت":s==="ارجاع حقوقی"}),[items,tab]);
const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...init})};
const calc=()=>set("total",Number(form.principal||0)+Number(form.interest||0)+Number(form.penalty||0));
const save=async()=>{if(["code","contract","borrower","due","overdue"].some(k=>!String(form[k]||"").trim()))return setError("کد، قرارداد، بدهکار و تاریخ‌های سررسید و معوق الزامی است.");setSaving(true);try{const data={"delinquency-code":form.code,"contract-code":form.contract,"borrower-id":form.borrower,"installment-no":Number(form.installment||0),"due-date":form.due,"overdue-date":form.overdue,"days-overdue":Number(form.days||0),"principal-due":Number(form.principal||0),"interest-due":Number(form.interest||0),"penalty-amount":Number(form.penalty||0),"total-overdue":Number(form.total||0),"risk-level":form.risk,"collection-stage":form.stage,"contact-status":form.contact,"promise-date":form.promiseDate,"promise-amount":Number(form.promiseAmount||0),"legal-reference":form.legal,"resolution-status":form.resolution,"assigned-to":form.assigned,"last-contact-at":form.lastContact,"next-action-date":form.nextAction,"notes":form.notes};const r=await fetch(API+"/api/platform/modules/27-loan-delinquency/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"loan-delinquency",title:String(form.code)+" / "+String(form.contract),status:String(form.resolution),data})}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["delinquency-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",installment:d["installment-no"]??"",due:d["due-date"]||"",overdue:d["overdue-date"]||"",days:d["days-overdue"]??"",principal:d["principal-due"]??"",interest:d["interest-due"]??"",penalty:d["penalty-amount"]??"",total:d["total-overdue"]??"",risk:d["risk-level"]||"متوسط",stage:d["collection-stage"]||"هشدار اولیه",contact:d["contact-status"]||"تماس نشده",promiseDate:d["promise-date"]||"",promiseAmount:d["promise-amount"]??"",legal:d["legal-reference"]||"",resolution:d["resolution-status"]||"باز",assigned:d["assigned-to"]||"",lastContact:d["last-contact-at"]||"",nextAction:d["next-action-date"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
const patch=async(r:R,ch:Record<string,unknown>)=>{const d={...r.data,...ch};const x=await fetch(API+"/api/platform/modules/27-loan-delinquency/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:String(d["resolution-status"]||r.status),data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد");return}await load()};
const contact=(r:R)=>patch(r,{"resolution-status":"در حال پیگیری","contact-status":"تماس موفق","last-contact-at":new Date().toISOString()});
const promise=(r:R)=>patch(r,{"resolution-status":"تعهد پرداخت","contact-status":"تماس موفق","promise-date":new Date().toISOString().slice(0,10)});
const escalate=(r:R)=>patch(r,{"resolution-status":"در حال پیگیری","collection-stage":"ارجاع وصول"});
const legal=(r:R)=>patch(r,{"resolution-status":"ارجاع حقوقی","collection-stage":"اقدام حقوقی"});
const resolve=(r:R)=>patch(r,{"resolution-status":"مختومه"});
const remove=async(id:number)=>{const x=await fetch(API+"/api/platform/modules/27-loan-delinquency/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!x.ok){setError("حذف انجام نشد");return}await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۷</span><h1>مدیریت معوقات تسهیلات</h1><p>کنترل سررسیدهای معوق، پیگیری وصول، تعهد پرداخت و ارجاع مرحله‌ای پرونده‌ها.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>پرونده معوق</small><b>{items.filter(x=>x.data?.["resolution-status"]==="ارجاع حقوقی").length.toLocaleString("fa-IR")}</b><small>ارجاع حقوقی</small></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش پرونده معوق":"ثبت پرونده معوق"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
<div className={styles.fields}><label>کد پرونده *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label><label>شناسه بدهکار *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label><label>شماره قسط<input type="number" value={String(form.installment)} onChange={e=>set("installment",e.target.value)}/></label><label>تاریخ سررسید *<input type="date" value={String(form.due)} onChange={e=>set("due",e.target.value)}/></label><label>تاریخ شروع معوق *<input type="date" value={String(form.overdue)} onChange={e=>set("overdue",e.target.value)}/></label><label>روزهای تأخیر<input type="number" min="0" value={String(form.days)} onChange={e=>set("days",e.target.value)}/></label><label>اصل سررسیدشده<input type="number" min="0" value={String(form.principal)} onChange={e=>set("principal",e.target.value)}/></label><label>سود سررسیدشده<input type="number" min="0" value={String(form.interest)} onChange={e=>set("interest",e.target.value)}/></label><label>جریمه تأخیر<input type="number" min="0" value={String(form.penalty)} onChange={e=>set("penalty",e.target.value)}/></label><label>کل مبلغ معوق<input type="number" min="0" value={String(form.total)} onChange={e=>set("total",e.target.value)}/></label>
<label>سطح ریسک<select value={String(form.risk)} onChange={e=>set("risk",e.target.value)}>{["عادی","کم","متوسط","زیاد","بحرانی"].map(x=><option key={x}>{x}</option>)}</select></label><label>مرحله پیگیری<select value={String(form.stage)} onChange={e=>set("stage",e.target.value)}>{["هشدار اولیه","پیگیری تلفنی","اخطار رسمی","ارجاع وصول","اقدام حقوقی"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت تماس<select value={String(form.contact)} onChange={e=>set("contact",e.target.value)}>{["تماس نشده","تماس موفق","عدم پاسخ","شماره نامعتبر","نیازمند پیگیری مجدد"].map(x=><option key={x}>{x}</option>)}</select></label><label>تاریخ تعهد پرداخت<input type="date" value={String(form.promiseDate)} onChange={e=>set("promiseDate",e.target.value)}/></label><label>مبلغ تعهد پرداخت<input type="number" min="0" value={String(form.promiseAmount)} onChange={e=>set("promiseAmount",e.target.value)}/></label><label>مرجع حقوقی<input value={String(form.legal)} onChange={e=>set("legal",e.target.value)}/></label><label>وضعیت تعیین تکلیف<select value={String(form.resolution)} onChange={e=>set("resolution",e.target.value)}>{["باز","در حال پیگیری","تعهد پرداخت","تسویه شده","تقسیط مجدد","ارجاع حقوقی","مختومه"].map(x=><option key={x}>{x}</option>)}</select></label><label>مسئول پیگیری<input value={String(form.assigned)} onChange={e=>set("assigned",e.target.value)}/></label><label>اقدام بعدی<input type="date" value={String(form.nextAction)} onChange={e=>set("nextAction",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label></div>
<div className={styles.formActions}><button type="button" className={styles.secondary} onClick={calc}>محاسبه کل معوق</button><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت در PostgreSQL"}</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>سوابق واقعی</small><h2>صف پیگیری معوقات</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد پرونده، قرارداد یا بدهکار..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["days-overdue"]||0)} روز تأخیر · مبلغ معوق: {String(r.data?.["total-overdue"]||0)}</small><span>ریسک: {String(r.data?.["risk-level"]||"")} · وضعیت: {String(r.data?.["resolution-status"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{r.data?.["resolution-status"]==="باز"&&<button className={styles.follow} onClick={()=>contact(r)}>پیگیری</button>}{["باز","در حال پیگیری"].includes(String(r.data?.["resolution-status"]||""))&&<button className={styles.promise} onClick={()=>promise(r)}>تعهد پرداخت</button>}{!["ارجاع حقوقی","مختومه"].includes(String(r.data?.["resolution-status"]||""))&&<button className={styles.legal} onClick={()=>legal(r)}>حقوقی</button>}{!["مختومه"].includes(String(r.data?.["resolution-status"]||""))&&<button className={styles.close} onClick={()=>resolve(r)}>مختومه</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>پرونده معوقی ثبت نشده است.</div>}</div></section></section></main>}