"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./LoanReliefWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه درخواست‌ها"],["review","در حال بررسی"],["approved","تأیید شده"],["ready","آماده اجرا"],["done","اجرا شده"]];
const init={code:"",contract:"",borrower:"",date:"",type:"بخشودگی جریمه",principal:"",interest:"",penalty:"",requested:"",approved:"",remaining:"",reason:"",reference:"",level:"کارشناس",approval:"در انتظار بررسی",execution:"ثبت اولیه",approvedBy:"",approvedDate:"",executedBy:"",executedDate:"",accounting:"",notes:""};
export default function LoanReliefWorkspace(){
const[tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...init}),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/30-loan-relief/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت درخواست‌ها انجام نشد");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setLoading(false)}};useEffect(()=>{load()},[]);
const visible=useMemo(()=>items.filter(r=>{const s=String(r.data?.["execution-status"]||"ثبت اولیه");return tab==="all"||tab==="review"?tab==="all"||s==="در حال بررسی":tab==="approved"?s==="آماده اجرا"||r.data?.["approval-status"]==="تأیید شده":tab==="ready"?s==="آماده اجرا":s==="اجرا شده"}),[items,tab]);
const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...init})};
const calc=()=>set("remaining",Math.max(0,Number(form.principal||0)+Number(form.interest||0)+Number(form.penalty||0)-Number(form.approved||0)));
const save=async()=>{if(["code","contract","borrower","date","type","principal","requested","reason"].some(k=>!String(form[k]??"").trim()))return setError("اطلاعات اصلی درخواست الزامی است.");setSaving(true);try{const data={"request-code":form.code,"contract-code":form.contract,"borrower-id":form.borrower,"request-date":form.date,"request-type":form.type,"principal-amount":Number(form.principal||0),"interest-amount":Number(form.interest||0),"penalty-amount":Number(form.penalty||0),"requested-amount":Number(form.requested||0),"approved-amount":Number(form.approved||0),"remaining-amount":Number(form.remaining||0),"reason":form.reason,"reference":form.reference,"approval-level":form.level,"approval-status":form.approval,"execution-status":form.execution,"approved-by":form.approvedBy,"approved-date":form.approvedDate,"executed-by":form.executedBy,"executed-date":form.executedDate,"accounting-reference":form.accounting,"notes":form.notes};const r=await fetch(API+"/api/platform/modules/30-loan-relief/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"loan-relief",title:String(form.code)+" / "+String(form.contract),status:String(form.execution),data})}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["request-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",date:d["request-date"]||"",type:d["request-type"]||"بخشودگی جریمه",principal:d["principal-amount"]??"",interest:d["interest-amount"]??"",penalty:d["penalty-amount"]??"",requested:d["requested-amount"]??"",approved:d["approved-amount"]??"",remaining:d["remaining-amount"]??"",reason:d.reason||"",reference:d.reference||"",level:d["approval-level"]||"کارشناس",approval:d["approval-status"]||"در انتظار بررسی",execution:d["execution-status"]||"ثبت اولیه",approvedBy:d["approved-by"]||"",approvedDate:d["approved-date"]||"",executedBy:d["executed-by"]||"",executedDate:d["executed-date"]||"",accounting:d["accounting-reference"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
const patch=async(r:R,ch:Record<string,unknown>)=>{const d={...r.data,...ch};const x=await fetch(API+"/api/platform/modules/30-loan-relief/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:String(d["execution-status"]||r.status),data:d})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد");return}await load()};
const review=(r:R)=>patch(r,{"execution-status":"در حال بررسی"});
const approve=(r:R)=>patch(r,{"approval-status":"تأیید شده","execution-status":"آماده اجرا","approved-by":"کاربر جاری","approved-date":new Date().toISOString().slice(0,10)});
const execute=(r:R)=>patch(r,{"execution-status":"اجرا شده","executed-by":"کاربر جاری","executed-date":new Date().toISOString().slice(0,10)});
const reverse=(r:R)=>patch(r,{"execution-status":"برگشت خورده"});
const remove=async(id:number)=>{const x=await fetch(API+"/api/platform/modules/30-loan-relief/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!x.ok){setError("حذف انجام نشد");return}await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۳۰</span><h1>بخشودگی و امهال مطالبات تسهیلات</h1><p>مدیریت درخواست، تصویب و ثبت اجرای بخشودگی و امهال مطالبات با کنترل کامل گردش کار.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>درخواست</small><b>{items.filter(x=>x.data?.["execution-status"]==="آماده اجرا").length.toLocaleString("fa-IR")}</b><small>آماده اجرا</small></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش درخواست":"ثبت درخواست بخشودگی"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
<div className={styles.fields}><label>کد درخواست *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label><label>شناسه بدهکار *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label><label>تاریخ درخواست *<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label><label>نوع درخواست<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["بخشودگی جریمه","بخشودگی سود","امهال مطالبات","تعدیل بدهی","بخشودگی توافقی","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>اصل بدهی *<input type="number" min="0" value={String(form.principal)} onChange={e=>set("principal",e.target.value)}/></label><label>سود بدهی<input type="number" min="0" value={String(form.interest)} onChange={e=>set("interest",e.target.value)}/></label><label>جریمه بدهی<input type="number" min="0" value={String(form.penalty)} onChange={e=>set("penalty",e.target.value)}/></label><label>مبلغ درخواستی *<input type="number" min="0" value={String(form.requested)} onChange={e=>set("requested",e.target.value)}/></label><label>مبلغ مصوب<input type="number" min="0" value={String(form.approved)} onChange={e=>set("approved",e.target.value)}/></label><label>مانده پس از اجرا<input type="number" min="0" value={String(form.remaining)} onChange={e=>set("remaining",e.target.value)}/></label><label>سطح تصویب<select value={String(form.level)} onChange={e=>set("level",e.target.value)}>{["کارشناس","سرپرست","مدیریت اعتبارات","کمیته اعتباری","مدیریت ارشد"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت تصویب<select value={String(form.approval)} onChange={e=>set("approval",e.target.value)}>{["در انتظار بررسی","تأیید شده","رد شده","نیازمند اصلاح"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت اجرا<select value={String(form.execution)} onChange={e=>set("execution",e.target.value)}>{["ثبت اولیه","در حال بررسی","آماده اجرا","اجرا شده","برگشت خورده","لغو شده"].map(x=><option key={x}>{x}</option>)}</select></label><label>مرجع مستندات<input value={String(form.reference)} onChange={e=>set("reference",e.target.value)}/></label><label>تصویب‌کننده<input value={String(form.approvedBy)} onChange={e=>set("approvedBy",e.target.value)}/></label><label>مرجع ثبت مالی<input value={String(form.accounting)} onChange={e=>set("accounting",e.target.value)}/></label><label className={styles.full}>علت درخواست *<textarea rows={2} value={String(form.reason)} onChange={e=>set("reason",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label></div>
<div className={styles.formActions}><button type="button" className={styles.secondary} onClick={calc}>محاسبه مانده</button><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت در PostgreSQL"}</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>سوابق واقعی</small><h2>درخواست‌های بخشودگی</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد درخواست، قرارداد یا بدهکار..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>درخواستی: {String(r.data?.["requested-amount"]||0)} · مصوب: {String(r.data?.["approved-amount"]||0)}</small><span>اجرا: {String(r.data?.["execution-status"]||"")} · تصویب: {String(r.data?.["approval-status"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{r.data?.["execution-status"]==="ثبت اولیه"&&<button className={styles.review} onClick={()=>review(r)}>بررسی</button>}{r.data?.["execution-status"]==="در حال بررسی"&&<button className={styles.approve} onClick={()=>approve(r)}>تصویب</button>}{r.data?.["execution-status"]==="آماده اجرا"&&<button className={styles.execute} onClick={()=>execute(r)}>اجرای مصوبه</button>}{r.data?.["execution-status"]==="اجرا شده"&&<button className={styles.reverse} onClick={()=>reverse(r)}>برگشت اجرا</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>درخواستی ثبت نشده است.</div>}</div></section></section></main>}