"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./LoanRefundsWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه برگشت‌ها"],["review","در حال بررسی"],["approved","تأیید برای اجرا"],["processing","در حال پردازش"],["done","برگشت انجام شد"]];
const init={code:"",contract:"",borrower:"",original:"",date:"",amount:"",type:"برگشت کامل پرداخت",reason:"",method:"واریز بانکی",replacement:"",approval:"در انتظار بررسی",status:"درخواست اولیه",approvedBy:"",processedBy:"",processedAt:"",failure:"",notes:""};

export default function LoanRefundsWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...init}),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/25-loan-refunds/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت برگشت‌ها انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>items.filter(r=>tab==="all"||({"review":["در حال بررسی"],"approved":["تأیید برای اجرا"],"processing":["در حال پردازش"],"done":["برگشت انجام شد"]}[tab]||[]).includes(String(r.data?.["refund-status"]||""))),[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...init})};
 const save=async()=>{if(["code","contract","borrower","original","date","amount","reason"].some(k=>!String(form[k]||"").trim()))return setError("کد برگشت، قرارداد، بدهکار، مرجع اصلی، تاریخ، مبلغ و علت برگشت الزامی است.");setSaving(true);setError("");try{const data={"refund-code":form.code,"contract-code":form.contract,"borrower-id":form.borrower,"original-reference":form.original,"refund-date":form.date,"refund-amount":Number(form.amount||0),"refund-type":form.type,"reason":form.reason,"payment-method":form.method,"replacement-reference":form.replacement,"approval-status":form.approval,"refund-status":form.status,"approved-by":form.approvedBy,"processed-by":form.processedBy,"processed-at":form.processedAt,"failure-reason":form.failure,"notes":form.notes};const r=await fetch(API+"/api/platform/modules/25-loan-refunds/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"loan-refund",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت برگشت انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["refund-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",original:d["original-reference"]||"",date:d["refund-date"]||"",amount:d["refund-amount"]??"",type:d["refund-type"]||"برگشت کامل پرداخت",reason:d.reason||"",method:d["payment-method"]||"واریز بانکی",replacement:d["replacement-reference"]||"",approval:d["approval-status"]||"در انتظار بررسی",status:d["refund-status"]||"درخواست اولیه",approvedBy:d["approved-by"]||"",processedBy:d["processed-by"]||"",processedAt:d["processed-at"]||"",failure:d["failure-reason"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status:string)=>{const x=await fetch(API+"/api/platform/modules/25-loan-refunds/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status,data:{...r.data,...changes}})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const review=(r:R)=>patch(r,{"refund-status":"در حال بررسی"},"در حال بررسی");
 const approve=(r:R)=>patch(r,{"approval-status":"تأیید شده","refund-status":"تأیید برای اجرا","approved-by":"کاربر جاری"},"تأیید برای اجرا");
 const process=(r:R)=>patch(r,{"refund-status":"برگشت انجام شد","processed-by":"کاربر جاری","processed-at":new Date().toISOString()},"برگشت انجام شد");
 const cancel=(r:R)=>patch(r,{"refund-status":"لغو شده"},"لغو شده");
 const remove=async(id:number)=>{const x=await fetch(API+"/api/platform/modules/25-loan-refunds/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۵</span><h1>برگشت پرداخت و اصلاح تسهیلات</h1><p>مدیریت برگشت کامل یا جزئی، اصلاح ثبت‌ها و کنترل چرخه تأیید تا پردازش برگشت.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>درخواست برگشت</small><b>{items.filter(x=>x.data?.["refund-status"]==="برگشت انجام شد").length.toLocaleString("fa-IR")}</b><small>انجام‌شده</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش برگشت":"ثبت درخواست برگشت"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد برگشت *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label><label>شناسه بدهکار *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label><label>مرجع عملیات اصلی *<input value={String(form.original)} onChange={e=>set("original",e.target.value)}/></label>
    <label>تاریخ درخواست *<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label><label>مبلغ برگشت *<input type="number" min="0" value={String(form.amount)} onChange={e=>set("amount",e.target.value)}/></label>
    <label>نوع برگشت<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["برگشت کامل پرداخت","برگشت جزئی","اصلاح ثبت","برگشت کارمزد","برگشت جریمه","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>روش پرداخت اصلی<select value={String(form.method)} onChange={e=>set("method",e.target.value)}>{["واریز بانکی","انتقال داخلی","پرداخت نقدی","کسر از حساب","سایر"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label className={styles.full}>علت برگشت *<textarea rows={2} value={String(form.reason)} onChange={e=>set("reason",e.target.value)}/></label><label>مرجع عملیات اصلاحی<input value={String(form.replacement)} onChange={e=>set("replacement",e.target.value)}/></label>
    <label>وضعیت تأیید<select value={String(form.approval)} onChange={e=>set("approval",e.target.value)}>{["در انتظار بررسی","تأیید شده","رد شده","نیازمند اصلاح"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت برگشت<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["درخواست اولیه","در حال بررسی","تأیید برای اجرا","در حال پردازش","برگشت انجام شد","لغو شده","ناموفق"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>تأییدکننده<input value={String(form.approvedBy)} onChange={e=>set("approvedBy",e.target.value)}/></label><label>پردازش‌کننده<input value={String(form.processedBy)} onChange={e=>set("processedBy",e.target.value)}/></label><label>زمان پردازش<input type="datetime-local" value={String(form.processedAt).slice(0,16)} onChange={e=>set("processedAt",e.target.value)}/></label><label className={styles.full}>علت عدم موفقیت<textarea rows={2} value={String(form.failure)} onChange={e=>set("failure",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت در PostgreSQL"}</button></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق واقعی</small><h2>صف برگشت‌ها</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد برگشت، قرارداد یا مرجع..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["refund-type"]||"")} · مبلغ: {String(r.data?.["refund-amount"]||0)}</small><span>وضعیت: {String(r.data?.["refund-status"]||"")} · تأیید: {String(r.data?.["approval-status"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{r.data?.["refund-status"]==="درخواست اولیه"&&<button className={styles.review} onClick={()=>review(r)}>بررسی</button>}{r.data?.["refund-status"]==="در حال بررسی"&&<button className={styles.approve} onClick={()=>approve(r)}>تأیید</button>}{r.data?.["refund-status"]==="تأیید برای اجرا"&&<button className={styles.process} onClick={()=>process(r)}>پردازش</button>}{!["برگشت انجام شد","لغو شده"].includes(String(r.data?.["refund-status"]||""))&&<button className={styles.cancel} onClick={()=>cancel(r)}>لغو</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>درخواست برگشتی ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
