"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./LoanLegalCasesWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const tabs=[["all","همه پرونده‌ها"],["review","در حال بررسی"],["court","در حال رسیدگی"],["execution","اجرای حکم"],["closed","مختومه"]];
const blank={code:"",contract:"",borrower:"",delinquency:"",date:"",type:"مطالبه وجه",claim:"",paid:"",remaining:"",unit:"",lawyer:"",court:"",caseNo:"",courtDate:"",guarantee:"بدون اقدام",status:"ارجاع اولیه",nextDate:"",lastAction:"",resolution:"",notes:""};
const token=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
export default function LoanLegalCasesWorkspace(){
const[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...blank}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/31-loan-legal-cases/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"خطا در دریافت پرونده‌ها");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>items.filter(r=>{const s=String(r.data?.["case-status"]||"ارجاع اولیه");return tab==="all"||(tab==="review"&&s==="در حال بررسی حقوقی")||(tab==="court"&&s==="در حال رسیدگی")||(tab==="execution"&&s==="اجرای حکم")||(tab==="closed"&&s==="مختومه")}),[items,tab]);
const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...blank})};
const save=async()=>{setError("");if(["code","contract","borrower","date","claim"].some(k=>!String(form[k]??"").trim()))return setError("کد پرونده، قرارداد، بدهکار، تاریخ و مبلغ مطالبه الزامی است.");setBusy(true);try{const d={"case-code":form.code,"contract-code":form.contract,"borrower-id":form.borrower,"delinquency-code":form.delinquency,"referral-date":form.date,"legal-type":form.type,"claim-amount":Number(form.claim||0),"paid-amount":Number(form.paid||0),"remaining-amount":Number(form.remaining||0),"legal-unit":form.unit,"lawyer":form.lawyer,"court-reference":form.court,"case-number":form.caseNo,"court-date":form.courtDate,"guarantee-action":form.guarantee,"case-status":form.status,"next-action-date":form.nextDate,"last-action":form.lastAction,"resolution-reference":form.resolution,"notes":form.notes};const r=await fetch(API+"/api/platform/modules/31-loan-legal-cases/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:"loan-legal-case",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data:d})}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const patch=async(r:R,d:Record<string,unknown>)=>{const data={...r.data,...d};const x=await fetch(API+"/api/platform/modules/31-loan-legal-cases/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:String(data["case-status"]),data})});if(!x.ok){setError("عملیات انجام نشد");return}await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["case-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",delinquency:d["delinquency-code"]||"",date:d["referral-date"]||"",type:d["legal-type"]||"مطالبه وجه",claim:d["claim-amount"]??"",paid:d["paid-amount"]??"",remaining:d["remaining-amount"]??"",unit:d["legal-unit"]||"",lawyer:d.lawyer||"",court:d["court-reference"]||"",caseNo:d["case-number"]||"",courtDate:d["court-date"]||"",guarantee:d["guarantee-action"]||"بدون اقدام",status:d["case-status"]||"ارجاع اولیه",nextDate:d["next-action-date"]||"",lastAction:d["last-action"]||"",resolution:d["resolution-reference"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/31-loan-legal-cases/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":token()}});await load()};
const action=(r:R,s:string)=>patch(r,{"case-status":s,"last-action":s+" | "+new Date().toISOString().slice(0,10)});
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>اعتبار و تسهیلات · ماژول ۳۱</small><h1>پرونده‌های حقوقی مطالبات تسهیلات</h1><p>کارتابل حقوقی مطالبات، پیگیری قضایی، اجرای تعهدات و ثبت نتیجه پرونده.</p></div><div className={styles.stat}><b>{items.length.toLocaleString("fa-IR")}</b><span>پرونده</span></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button className={tab===k?styles.active:""} key={k} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{edit?"ویرایش پرونده":"ثبت پرونده حقوقی"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div>
<div className={styles.fields}>{[["code","کد پرونده *"],["contract","کد قرارداد *"],["borrower","شناسه بدهکار *"],["delinquency","کد معوقه"],["date","تاریخ ارجاع *"],["claim","مبلغ مطالبه *"],["paid","مبلغ وصول‌شده"],["remaining","مانده مطالبه"],["unit","واحد حقوقی"],["lawyer","نماینده حقوقی"],["court","مرجع قضایی"],["caseNo","شماره پرونده قضایی"],["courtDate","تاریخ رسیدگی"],["nextDate","تاریخ اقدام بعدی"],["resolution","مرجع نتیجه"]].map(([k,l])=><label key={k}>{l}<input type={k.includes("date")||k==="courtDate"||k==="nextDate"?"date":k==="claim"||k==="paid"||k==="remaining"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}<label>نوع پرونده<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["مطالبه وجه","اجرای وثیقه","مطالبه از ضامن","چک و سفته","اعتراض به تعهد","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>اقدام نسبت به وثیقه<select value={String(form.guarantee)} onChange={e=>set("guarantee",e.target.value)}>{["بدون اقدام","درخواست اجرا","مزایده","توقیف","آزادسازی","سایر"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت پرونده<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["ارجاع اولیه","در حال بررسی حقوقی","ثبت قضایی","در حال رسیدگی","اجرای حکم","توافق و سازش","وصول شده","مختومه","منصرف شده"].map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.full}>آخرین اقدام<textarea rows={2} value={String(form.lastAction)} onChange={e=>set("lastAction",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label></div>
<div className={styles.actions}><button type="submit" disabled={busy} className={styles.primary}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت پرونده"}</button></div></form>
<section className={styles.card}><div className={styles.head}><div><small>سوابق واقعی</small><h2>کارتابل پرونده‌ها</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد پرونده، قرارداد یا بدهکار..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.title}</b><small>مطالبه: {String(r.data?.["claim-amount"]||0)} · مانده: {String(r.data?.["remaining-amount"]||0)}</small><span>{String(r.data?.["case-status"]||"")}</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data?.["case-status"]==="ارجاع اولیه"&&<button onClick={()=>action(r,"در حال بررسی حقوقی")}>شروع بررسی</button>}{r.data?.["case-status"]==="در حال بررسی حقوقی"&&<button onClick={()=>action(r,"ثبت قضایی")}>ثبت قضایی</button>}{r.data?.["case-status"]==="ثبت قضایی"&&<button onClick={()=>action(r,"در حال رسیدگی")}>پیگیری رسیدگی</button>}{r.data?.["case-status"]==="در حال رسیدگی"&&<button onClick={()=>action(r,"اجرای حکم")}>اجرای حکم</button>}{r.data?.["case-status"]==="اجرای حکم"&&<button onClick={()=>action(r,"وصول شده")}>ثبت وصول</button>}{["در حال بررسی حقوقی","ثبت قضایی","در حال رسیدگی"].includes(String(r.data?.["case-status"]))&&<button onClick={()=>action(r,"توافق و سازش")}>ثبت سازش</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>پرونده‌ای ثبت نشده است.</div>}</div></section></section></main>}