"use client";

import {useEffect,useMemo,useState} from "react";
import styles from "./LoanClosureWorkspace.module.css";

type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه پرونده‌ها"],["review","در حال بررسی"],["ready","آماده خاتمه"],["closed","مختومه"],["action","نیازمند اقدام"]];
const init={code:"",contract:"",borrower:"",request:"",date:"",type:"تسویه کامل",principal:"",interest:"",penalty:"",final:"",collateral:"در انتظار آزادسازی",guarantee:"در انتظار آزادسازی",release:"",approval:"در انتظار بررسی",status:"درخواست اولیه",approvedBy:"",closedBy:"",closedAt:"",notes:""};

export default function LoanClosureWorkspace(){
 const [tab,setTab]=useState("all"),[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...init}),[editing,setEditing]=useState<number|null>(null),[q,setQ]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const r=await fetch(API+"/api/platform/modules/26-loan-closure/records?page=1&pageSize=200&q="+encodeURIComponent(q),{credentials:"include"});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"دریافت پرونده‌های خاتمه انجام نشد.");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا در دریافت اطلاعات")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>items.filter(r=>{const s=String(r.data?.["closure-status"]||"");return tab==="all"||tab==="review"?tab==="all"||s==="در حال بررسی":tab==="ready"?s==="آماده خاتمه":tab==="closed"?s==="مختومه":s==="نیازمند اقدام"}),[items,tab]);
 const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEditing(null);setForm({...init})};
 const calc=()=>set("final",Math.max(0,Number(form.principal||0)+Number(form.interest||0)+Number(form.penalty||0)));
 const save=async()=>{if(["code","contract","borrower","request","type"].some(k=>!String(form[k]||"").trim()))return setError("کد خاتمه، قرارداد، بدهکار، تاریخ درخواست و نوع خاتمه الزامی است.");setSaving(true);setError("");try{const data={"closure-code":form.code,"contract-code":form.contract,"borrower-id":form.borrower,"closure-request-date":form.request,"closure-date":form.date,"closure-type":form.type,"principal-balance":Number(form.principal||0),"interest-balance":Number(form.interest||0),"penalty-balance":Number(form.penalty||0),"final-balance":Number(form.final||0),"collateral-status":form.collateral,"guarantee-status":form.guarantee,"release-reference":form.release,"approval-status":form.approval,"closure-status":form.status,"approved-by":form.approvedBy,"closed-by":form.closedBy,"closed-at":form.closedAt,"notes":form.notes};const r=await fetch(API+"/api/platform/modules/26-loan-closure/records"+(editing?"/"+editing:""),{method:editing?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"loan-closure",title:String(form.code)+" / "+String(form.contract),status:String(form.status),data})});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت خاتمه انجام نشد.");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا در ثبت")}finally{setSaving(false)}};
 const edit=(r:R)=>{const d=r.data||{};setEditing(r.id);setForm({code:d["closure-code"]||"",contract:d["contract-code"]||"",borrower:d["borrower-id"]||"",request:d["closure-request-date"]||"",date:d["closure-date"]||"",type:d["closure-type"]||"تسویه کامل",principal:d["principal-balance"]??"",interest:d["interest-balance"]??"",penalty:d["penalty-balance"]??"",final:d["final-balance"]??"",collateral:d["collateral-status"]||"در انتظار آزادسازی",guarantee:d["guarantee-status"]||"در انتظار آزادسازی",release:d["release-reference"]||"",approval:d["approval-status"]||"در انتظار بررسی",status:d["closure-status"]||"درخواست اولیه",approvedBy:d["approved-by"]||"",closedBy:d["closed-by"]||"",closedAt:d["closed-at"]||"",notes:d.notes||""});window.scrollTo({top:0,behavior:"smooth"})};
 const patch=async(r:R,changes:Record<string,unknown>,status:string)=>{const x=await fetch(API+"/api/platform/modules/26-loan-closure/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status,data:{...r.data,...changes}})});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"عملیات انجام نشد.");return}await load()};
 const review=(r:R)=>patch(r,{"closure-status":"در حال بررسی"},"در حال بررسی");
 const approve=(r:R)=>patch(r,{"approval-status":"تأیید شده","closure-status":"آماده خاتمه","approved-by":"کاربر جاری"},"آماده خاتمه");
 const release=(r:R)=>patch(r,{"collateral-status":"آزادسازی کامل","guarantee-status":"آزادسازی کامل","closure-status":"آماده خاتمه","release-reference":"ثبت داخلی آزادسازی"},"آماده خاتمه");
 const close=async(r:R)=>{const now=new Date().toISOString();await patch(r,{"closure-status":"مختومه","closure-date":now.slice(0,10),"closed-by":"کاربر جاری","closed-at":now},"مختومه")};
 const cancel=(r:R)=>patch(r,{"closure-status":"لغو شده"},"لغو شده");
 const remove=async(id:number)=>{const x=await fetch(API+"/api/platform/modules/26-loan-closure/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!x.ok){const b=await x.json().catch(()=>null);setError(b?.error||"حذف انجام نشد.");return}await load()};
 return <main className={styles.page} dir="rtl">
  <header className={styles.hero}><div><span>اعتبار و تسهیلات · ماژول ۲۶</span><h1>بستن تسهیلات و آزادسازی تعهدات</h1><p>کنترل خاتمه قرارداد، تسویه مانده، آزادسازی وثایق و ضمانت‌ها و ثبت نهایی پرونده.</p></div><div className={styles.stats}><b>{items.length.toLocaleString("fa-IR")}</b><small>پرونده خاتمه</small><b>{items.filter(x=>x.data?.["closure-status"]==="مختومه").length.toLocaleString("fa-IR")}</b><small>مختومه</small></div></header>
  <nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
  <section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{editing?"ویرایش پرونده":"ثبت درخواست خاتمه"}</h2></div>{editing&&<button type="button" onClick={reset}>انصراف</button>}</div>
   <div className={styles.fields}>
    <label>کد خاتمه *<input value={String(form.code)} onChange={e=>set("code",e.target.value)}/></label><label>کد قرارداد *<input value={String(form.contract)} onChange={e=>set("contract",e.target.value)}/></label><label>شناسه بدهکار *<input value={String(form.borrower)} onChange={e=>set("borrower",e.target.value)}/></label><label>تاریخ درخواست *<input type="date" value={String(form.request)} onChange={e=>set("request",e.target.value)}/></label>
    <label>نوع خاتمه<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["تسویه کامل","اتمام مدت قرارداد","فسخ قرارداد","تسویه توافقی","ابطال قرارداد"].map(x=><option key={x}>{x}</option>)}</select></label><label>تاریخ خاتمه<input type="date" value={String(form.date)} onChange={e=>set("date",e.target.value)}/></label>
    <label>مانده اصل<input type="number" min="0" value={String(form.principal)} onChange={e=>set("principal",e.target.value)}/></label><label>مانده سود<input type="number" min="0" value={String(form.interest)} onChange={e=>set("interest",e.target.value)}/></label><label>مانده جریمه<input type="number" min="0" value={String(form.penalty)} onChange={e=>set("penalty",e.target.value)}/></label><label>مانده نهایی<input type="number" min="0" value={String(form.final)} onChange={e=>set("final",e.target.value)}/></label>
    <label>وضعیت وثایق<select value={String(form.collateral)} onChange={e=>set("collateral",e.target.value)}>{["در انتظار آزادسازی","آزادسازی کامل","آزادسازی جزئی","بدون وثیقه","دارای مانده تعهد"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت ضمانت‌ها<select value={String(form.guarantee)} onChange={e=>set("guarantee",e.target.value)}>{["در انتظار آزادسازی","آزادسازی کامل","آزادسازی جزئی","بدون ضامن","دارای مانده تعهد"].map(x=><option key={x}>{x}</option>)}</select></label>
    <label>مرجع آزادسازی<input value={String(form.release)} onChange={e=>set("release",e.target.value)}/></label><label>وضعیت تأیید<select value={String(form.approval)} onChange={e=>set("approval",e.target.value)}>{["در انتظار بررسی","تأیید شده","رد شده","نیازمند اصلاح"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت خاتمه<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["درخواست اولیه","در حال بررسی","آماده خاتمه","مختومه","نیازمند اقدام","لغو شده"].map(x=><option key={x}>{x}</option>)}</select></label><label>تأییدکننده<input value={String(form.approvedBy)} onChange={e=>set("approvedBy",e.target.value)}/></label><label>مختومه‌کننده<input value={String(form.closedBy)} onChange={e=>set("closedBy",e.target.value)}/></label><label>زمان خاتمه<input type="datetime-local" value={String(form.closedAt).slice(0,16)} onChange={e=>set("closedAt",e.target.value)}/></label>
    <label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label>
   </div><div className={styles.formActions}><button type="button" className={styles.secondary} onClick={calc}>محاسبه مانده نهایی</button><button className={styles.primary} disabled={saving}>{saving?"در حال ذخیره...":editing?"ذخیره تغییرات":"ثبت در PostgreSQL"}</button></div></form>
   <section className={styles.card}><div className={styles.head}><div><small>سوابق واقعی</small><h2>صف خاتمه تسهیلات</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="جستجو در کد خاتمه، قرارداد یا بدهکار..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{loading?<div className={styles.empty}>در حال دریافت داده واقعی...</div>:visible.map(r=><article className={styles.row} key={r.id}><div><b>{r.title}</b><small>{String(r.data?.["closure-type"]||"")} · مانده نهایی: {String(r.data?.["final-balance"]||0)}</small><span>وضعیت: {String(r.data?.["closure-status"]||"")} · وثایق: {String(r.data?.["collateral-status"]||"")}</span></div><div className={styles.actions}><button onClick={()=>edit(r)}>ویرایش</button>{r.data?.["closure-status"]==="درخواست اولیه"&&<button className={styles.review} onClick={()=>review(r)}>بررسی</button>}{r.data?.["closure-status"]==="در حال بررسی"&&<button className={styles.approve} onClick={()=>approve(r)}>تأیید</button>}{r.data?.["closure-status"]==="آماده خاتمه"&&<><button className={styles.release} onClick={()=>release(r)}>آزادسازی</button><button className={styles.close} onClick={()=>close(r)}>خاتمه نهایی</button></>}{!["مختومه","لغو شده"].includes(String(r.data?.["closure-status"]||""))&&<button className={styles.cancel} onClick={()=>cancel(r)}>لغو</button>}<button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!loading&&!visible.length&&<div className={styles.empty}>پرونده خاتمه‌ای ثبت نشده است.</div>}</div></section>
  </section>
 </main>
}
