"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./MenuBuilderWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,unknown>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const token=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["all","همه منوها"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]];
const blank={code:"",title:"",key:"",parent:"",type:"زیرمنو",route:"",icon:"",order:"0",access:"کاربران واردشده",visibility:"نمایش داده شود",status:"پیش‌نویس",target:"همین صفحه",permission:"",description:"",notes:""};
export default function MenuBuilderWorkspace(){
const[items,setItems]=useState<R[]>([]),[form,setForm]=useState<Record<string,unknown>>({...blank}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/15-menu-builder/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"خطا در دریافت منوها");setItems(b?.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>items.filter(r=>tab==="all"||String(r.data?.status)===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"} as Record<string,string>)[tab]),[items,tab]);
const set=(k:string,v:unknown)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...blank})};
const save=async()=>{setError("");if(["code","title","key","type","order"].some(k=>!String(form[k]??"").trim()))return setError("کد، عنوان، کلید، نوع و ترتیب منو الزامی است.");setBusy(true);try{const data={"menu-code":form.code,"menu-title":form.title,"menu-key":form.key,"parent-code":form.parent,"menu-type":form.type,route:form.route,icon:form.icon,"order-index":Number(form.order||0),"access-level":form.access,visibility:form.visibility,status:form.status,target:form.target,permission:form.permission,description:form.description,notes:form.notes};const r=await fetch(API+"/api/platform/modules/15-menu-builder/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:"menu-definition",title:String(form.title),status:String(form.status),data})}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ثبت منو انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const patch=async(r:R,status:string)=>{const data={...r.data,status,...(status==="فعال"?{}:{})};const x=await fetch(API+"/api/platform/modules/15-menu-builder/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:r.record_type,title:r.title,status,data})});if(!x.ok){setError("عملیات انجام نشد");return}await load()};
const reorder=async(r:R,delta:number)=>{const n=Math.max(0,Number(r.data["order-index"]||0)+delta);const data={...r.data,"order-index":n};const x=await fetch(API+"/api/platform/modules/15-menu-builder/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:r.status,data})});if(!x.ok){setError("تنظیم ترتیب انجام نشد");return}await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["menu-code"]||"",title:d["menu-title"]||"",key:d["menu-key"]||"",parent:d["parent-code"]||"",type:d["menu-type"]||"زیرمنو",route:d.route||"",icon:d.icon||"",order:d["order-index"]??0,access:d["access-level"]||"کاربران واردشده",visibility:d.visibility||"نمایش داده شود",status:d.status||"پیش‌نویس",target:d.target||"همین صفحه",permission:d.permission||"",description:d.description||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/15-menu-builder/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":token()}});await load()};
const duplicate=async(r:R)=>{const d={...r.data,"menu-code":String(r.data["menu-code"]||"")+"-COPY","menu-key":String(r.data["menu-key"]||"")+"-copy","menu-title":String(r.data["menu-title"]||"")+" - نسخه جدید",status:"پیش‌نویس","order-index":Number(r.data["order-index"]||0)+1};await fetch(API+"/api/platform/modules/15-menu-builder/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":token()},body:JSON.stringify({recordType:"menu-definition",title:d["menu-title"],status:"پیش‌نویس",data:d})});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۳۳</small><h1>مدیریت منوی مرکزی سازمان</h1><p>تعریف ساختار منو، زیرمنو، مسیرها، ترتیب نمایش و کنترل دسترسی بدون تغییر مستقیم کد.</p></div><div className={styles.stat}><b>{items.length.toLocaleString("fa-IR")}</b><span>آیتم منو</span></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{edit?"ویرایش آیتم":"ساخت آیتم منو"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>
{[["code","کد منو *"],["title","عنوان منو *"],["key","کلید منو *"],["parent","کد منوی والد"],["route","مسیر"],["icon","آیکون"],["order","ترتیب نمایش *"],["permission","مجوز موردنیاز"]].map(([k,l])=><label key={k}>{l}<input type={k==="order"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}
<label>نوع منو<select value={String(form.type)} onChange={e=>set("type",e.target.value)}>{["گروه اصلی","زیرمنو","صفحه","عملیات"].map(x=><option key={x}>{x}</option>)}</select></label><label>سطح دسترسی<select value={String(form.access)} onChange={e=>set("access",e.target.value)}>{["عمومی","کاربران واردشده","نقش‌محور","سازمانی"].map(x=><option key={x}>{x}</option>)}</select></label><label>نمایش<select value={String(form.visibility)} onChange={e=>set("visibility",e.target.value)}>{["نمایش داده شود","مخفی","فقط موبایل","فقط دسکتاپ"].map(x=><option key={x}>{x}</option>)}</select></label><label>نحوه بازشدن<select value={String(form.target)} onChange={e=>set("target",e.target.value)}>{["همین صفحه","صفحه جدید","پنجره داخلی"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت<select value={String(form.status)} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","فعال","غیرفعال","آرشیو شده"].map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.full}>توضیحات<textarea rows={2} value={String(form.description)} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={String(form.notes)} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary} disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت آیتم منو"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>ساختار قابل مدیریت</small><h2>آیتم‌های منو</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد، عنوان، کلید یا مسیر..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.sort((a,b)=>Number(a.data["order-index"]||0)-Number(b.data["order-index"]||0)).map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.title}</b><small>{String(r.data["menu-key"]||"")} · والد: {String(r.data["parent-code"]||"ریشه")}</small><span>{String(r.data.status||"")} · ترتیب {String(r.data["order-index"]||0)}</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button><button onClick={()=>reorder(r,-1)}>↑</button><button onClick={()=>reorder(r,1)}>↓</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>patch(r,"فعال")}>انتشار</button>}{r.data.status==="فعال"&&<button onClick={()=>patch(r,"غیرفعال")}>غیرفعال</button>}{r.data.status==="غیرفعال"&&<button onClick={()=>patch(r,"فعال")}>فعال‌سازی</button>}<button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>آیتم منویی ثبت نشده است.</div>}</div></section></section></main>}