"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./NavigationRulesWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",title:"",menu:"",page:"",section:"",audience:"عمومی",condition:"بدون شرط",reference:"",priority:0,display:"نمایش",target:"همان صفحه",status:"پیش‌نویس",from:"",to:"",notes:""};
const options={audience:["عمومی","کاربران واردشده","کاربران مهمان","نقش‌محور","سازمانی"],condition:["بدون شرط","مجوز","نقش","سازمان","وضعیت کاربر","ترکیبی"],display:["نمایش","مخفی","نمایش مشروط","فقط موبایل","فقط دسکتاپ"],target:["همان صفحه","صفحه جدید","پنجره داخلی","مسیر خارجی"],status:["پیش‌نویس","فعال","غیرفعال","آرشیو شده"]};
export default function NavigationRulesWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[q,setQ]=useState(""),[tab,setTab]=useState("all"),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/38-navigation-rules/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت قواعد ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data.status===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"}as any)[tab]).sort((a,b)=>Number(a.data.priority||0)-Number(b.data.priority||0)),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v})); const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"navigation-rule",title:d.title,status:d.status,data:{"rule-code":d.code,"rule-title":d.title,"menu-code":d.menu,"page-code":d.page,"section-code":d.section,audience:d.audience,"condition-type":d.condition,"condition-reference":d.reference,priority:Number(d.priority||0),"display-mode":d.display,"target-mode":d.target,status:d.status,"effective-from":d.from,"effective-to":d.to,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim()||!form.menu.trim())return setError("کد قاعده، عنوان و کد منو الزامی است.");try{const r=await fetch(API+"/api/platform/modules/38-navigation-rules/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/38-navigation-rules/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:data["rule-title"]||r.title,status:data.status||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d:any=r.data;setEdit(r.id);setForm({code:d["rule-code"]||"",title:d["rule-title"]||r.title,menu:d["menu-code"]||"",page:d["page-code"]||"",section:d["section-code"]||"",audience:d.audience||"عمومی",condition:d["condition-type"]||"بدون شرط",reference:d["condition-reference"]||"",priority:d.priority??0,display:d["display-mode"]||"نمایش",target:d["target-mode"]||"همان صفحه",status:d.status||"پیش‌نویس",from:d["effective-from"]||"",to:d["effective-to"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"rule-code":String(r.data["rule-code"]||"")+"-COPY","rule-title":String(r.data["rule-title"]||"")+" - نسخه جدید",status:"پیش‌نویس",priority:Number(r.data.priority||0)+1};await fetch(API+"/api/platform/modules/38-navigation-rules/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"navigation-rule",title:d["rule-title"],status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/38-navigation-rules/records/"+id,{method:"DELETE",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()}});await load()};
const action=async(r:R,status:string)=>patch(r,{...r.data,status});
const move=async(r:R,n:number)=>patch(r,{...r.data,priority:Math.max(0,Number(r.data.priority||0)+n)});
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۳۸</small><h1>قواعد نمایش و ناوبری فرانت‌اند</h1><p>کنترل واقعی نمایش منوها و صفحات بر اساس مخاطب، مجوز، نقش، سازمان و شرایط اجرایی.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>قاعده</span></div></header>
<div className={styles.tabs}>{[["all","همه"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]].map(([k,t])=><button className={tab===k?styles.active:""} key={k} onClick={()=>setTab(k)}>{t}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش قاعده":"تعریف قاعده"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد قاعده *"],["title","عنوان قاعده *"],["menu","کد منو *"],["page","کد صفحه"],["section","کد بخش"],["reference","مرجع شرط"],["priority","اولویت"],["from","شروع اعتبار"],["to","پایان اعتبار"]].map(([k,l]:any)=><label key={k}>{l}<input type={k==="priority"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({audience:"مخاطب",condition:"نوع شرط",display:"نحوه نمایش",target:"نحوه بازشدن",status:"وضعیت"}).map(([k,l]:any)=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{(options as any)[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary}>{edit?"ذخیره تغییرات":"ثبت قاعده"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>Runtime Navigation Policy</small><h2>قواعد ثبت‌شده</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="منو، صفحه، عنوان یا مرجع شرط..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["rule-title"]||r.title}</b><small>منو: {r.data["menu-code"]||"-"} · صفحه: {r.data["page-code"]||"-"} · بخش: {r.data["section-code"]||"-"}</small><span>{r.data.condition||r.data["condition-type"]} · اولویت {String(r.data.priority??0)} · {r.data.status||r.status}</span></div><div className={styles.actions}><button onClick={()=>editRow(r)}>ویرایش</button><button onClick={()=>move(r,-1)}>↑</button><button onClick={()=>move(r,1)}>↓</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>action(r,"فعال")}>فعال</button>}{r.data.status==="فعال"&&<button onClick={()=>action(r,"غیرفعال")}>غیرفعال</button>}<button onClick={()=>action(r,"آرشیو شده")}>آرشیو</button><button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>قاعده‌ای ثبت نشده است.</div>}</div></section></section></main>}