"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./NotificationTemplatesWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const empty:any={code:"",title:"",key:"",type:"اطلاع‌رسانی",channel:"داخل سامانه",subject:"",body:"",vars:"",locale:"fa-IR",version:1,status:"پیش‌نویس",published:"",owner:"",description:"",notes:""};
const opts:any={type:["اطلاع‌رسانی","موفقیت","هشدار","خطا","اقدام","سیستمی"],channel:["داخل سامانه","مرکز اعلان","پیامک","ایمیل","اعلان مرورگر"],locale:["fa-IR","en-US","ar"],status:["پیش‌نویس","فعال","غیرفعال","آرشیو شده"]};
export default function NotificationTemplatesWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...empty}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/40-notification-templates/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت قالب‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||r.data.status===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"}as any)[tab]),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...empty})};
const payload=(d=form)=>({recordType:"notification-template",title:d.title,status:d.status,data:{"template-code":d.code,"template-title":d.title,"template-key":d.key,"notification-type":d.type,channel:d.channel,"subject-reference":d.subject,"body-reference":d.body,"variables-reference":d.vars,locale:d.locale,version:Number(d.version||1),status:d.status,"published-at":d.published,owner:d.owner,description:d.description,notes:d.notes}});
const save=async()=>{setError("");if(!form.code.trim()||!form.title.trim()||!form.key.trim()||!form.body.trim())return setError("کد، عنوان، کلید و مرجع متن قالب الزامی است.");try{const r=await fetch(API+"/api/platform/modules/40-notification-templates/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/40-notification-templates/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:data["template-title"]||r.title,status:data.status||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["template-code"]||"",title:d["template-title"]||r.title,key:d["template-key"]||"",type:d["notification-type"]||"اطلاع‌رسانی",channel:d.channel||"داخل سامانه",subject:d["subject-reference"]||"",body:d["body-reference"]||"",vars:d["variables-reference"]||"",locale:d.locale||"fa-IR",version:d.version||1,status:d.status||"پیش‌نویس",published:d["published-at"]||"",owner:d.owner||"",description:d.description||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"template-code":String(r.data["template-code"]||"")+"-COPY","template-key":String(r.data["template-key"]||"")+"-copy","template-title":String(r.data["template-title"]||"")+" - نسخه جدید",version:1,status:"پیش‌نویس","published-at":null};await fetch(API+"/api/platform/modules/40-notification-templates/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"notification-template",title:d["template-title"],status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/40-notification-templates/records/"+id,{method:"DELETE",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()}});await load()};
const publish=async(r:R)=>patch(r,{...r.data,status:"فعال","published-at":new Date().toISOString()});
const disable=async(r:R)=>patch(r,{...r.data,status:"غیرفعال"});
const version=async(r:R)=>{const d={...r.data,"template-code":String(r.data["template-code"]||"")+"-V"+(Number(r.data.version||1)+1),"template-key":String(r.data["template-key"]||"")+"-v"+(Number(r.data.version||1)+1),version:Number(r.data.version||1)+1,status:"پیش‌نویس","published-at":null};await fetch(API+"/api/platform/modules/40-notification-templates/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"notification-template",title:d["template-title"]||r.title,status:"پیش‌نویس",data:d})});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۴۰</small><h1>قالب‌های اعلان فرانت‌اند</h1><p>مدیریت نسخه، کانال، زبان و چرخه انتشار قالب‌های اعلان سامانه.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>قالب</span></div></header>
<div className={styles.tabs}>{[["all","همه قالب‌ها"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]].map(([k,t])=><button className={tab===k?styles.active:""} key={k} onClick={()=>setTab(k)}>{t}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>PostgreSQL واقعی</small><h2>{edit?"ویرایش قالب":"ساخت قالب اعلان"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد قالب *"],["title","عنوان قالب *"],["key","کلید قالب *"],["subject","مرجع عنوان"],["body","مرجع متن *"],["vars","مرجع متغیرها"],["version","نسخه"],["published","زمان انتشار"],["owner","مالک"]].map(([k,l])=><label key={k}>{l}<input type={k==="version"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}{Object.entries({type:"نوع اعلان",channel:"کانال",locale:"زبان",status:"وضعیت"}).map(([k,l])=><label key={k}>{l}<select value={form[k]} onChange={e=>set(k,e.target.value)}>{opts[k].map((x:string)=><option key={x}>{x}</option>)}</select></label>)}<label className={styles.full}>توضیحات<textarea rows={2} value={form.description} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary}>{edit?"ذخیره تغییرات":"ثبت قالب"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>Notification Template Lifecycle</small><h2>قالب‌های ثبت‌شده</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="عنوان، کلید، نوع یا کانال..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["template-title"]||r.title}</b><small>{r.data["template-key"]||""} · {r.data.locale||""} · {r.data.channel||""}</small><span>نسخه {String(r.data.version||1)} · {r.data.status||r.status}</span></div><div className={styles.actions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>publish(r)}>انتشار</button>}{r.data.status==="فعال"&&<button onClick={()=>disable(r)}>غیرفعال</button>}<button onClick={()=>version(r)}>نسخه جدید</button><button onClick={()=>duplicate(r)}>تکثیر</button><button onClick={()=>patch(r,{...r.data,status:"آرشیو شده"})}>آرشیو</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>قالبی ثبت نشده است.</div>}</div></section></section></main>}