"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./PageBlockEditorWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const blank:any={code:"",page:"",title:"",type:"عنوان و متن",zone:"محتوای اصلی",order:0,content:"",visibility:"نمایش داده شود",responsive:"خودکار",status:"پیش‌نویس",version:1,settings:"",notes:""};
const tabs=[["all","همه بلوک‌ها"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]];
export default function PageBlockEditorWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...blank}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/35-page-block-editor/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت بلوک‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||String(r.data.status)===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"}as any)[tab]).sort((a,b)=>String(a.data["page-code"]||"").localeCompare(String(b.data["page-code"]||""))||Number(a.data["order-index"]||0)-Number(b.data["order-index"]||0)),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...blank})};
const payload=(data=form)=>({recordType:"page-block",title:String(data.title),status:String(data.status),data:{"block-code":data.code,"page-code":data.page,"block-title":data.title,"block-type":data.type,zone:data.zone,"order-index":Number(data.order||0),"content-reference":data.content,visibility:data.visibility,"responsive-mode":data.responsive,status:data.status,version:Number(data.version||1),"settings-reference":data.settings,notes:data.notes}});
const save=async()=>{setError("");if(!String(form.code).trim()||!String(form.page).trim()||!String(form.title).trim())return setError("کد بلوک، کد صفحه و عنوان بلوک الزامی است.");setBusy(true);try{const r=await fetch(API+"/api/platform/modules/35-page-block-editor/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره بلوک انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const patch=async(r:R,data:any)=>{const x=await fetch(API+"/api/platform/modules/35-page-block-editor/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status:data.status||r.status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const action=async(r:R,status:string)=>patch(r,{...r.data,status,...(status==="فعال"?{}:{})});
const move=async(r:R,d:number)=>patch(r,{...r.data,"order-index":Math.max(0,Number(r.data["order-index"]||0)+d)});
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["block-code"]||"",page:d["page-code"]||"",title:d["block-title"]||r.title,type:d["block-type"]||"عنوان و متن",zone:d.zone||"محتوای اصلی",order:d["order-index"]??0,content:d["content-reference"]||"",visibility:d.visibility||"نمایش داده شود",responsive:d["responsive-mode"]||"خودکار",status:d.status||"پیش‌نویس",version:d.version||1,settings:d["settings-reference"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"block-code":String(r.data["block-code"]||"")+"-COPY","block-title":String(r.data["block-title"]||"")+" - نسخه جدید",status:"پیش‌نویس",version:1,"order-index":Number(r.data["order-index"]||0)+1};await fetch(API+"/api/platform/modules/35-page-block-editor/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"page-block",title:d["block-title"],status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/35-page-block-editor/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۳۵</small><h1>ویرایشگر بلوک‌های صفحات</h1><p>چیدمان ساختاری صفحات، نواحی محتوا، ترتیب نمایش و رفتار ریسپانسیو را مدیریت کنید.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>بلوک</span></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{edit?"ویرایش بلوک":"افزودن بلوک"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد بلوک *"],["page","کد صفحه *"],["title","عنوان بلوک *"],["order","ترتیب نمایش"],["content","مرجع محتوا"],["version","نسخه"],["settings","مرجع تنظیمات"]].map(([k,l])=><label key={k}>{l}<input type={k==="order"||k==="version"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}
<label>نوع بلوک<select value={form.type} onChange={e=>set("type",e.target.value)}>{["عنوان و متن","تصویر","گالری","کارت","آمار","جدول","فرم","دکمه","فراخوان اقدام","تب‌ها","آکاردئون","HTML","فاصله‌گذار","سفارشی"].map(x=><option key={x}>{x}</option>)}</select></label><label>ناحیه صفحه<select value={form.zone} onChange={e=>set("zone",e.target.value)}>{["هدر","محتوای اصلی","ستون راست","ستون چپ","بین محتوا","سایدبار","فوتر"].map(x=><option key={x}>{x}</option>)}</select></label><label>نمایش<select value={form.visibility} onChange={e=>set("visibility",e.target.value)}>{["نمایش داده شود","مخفی","فقط موبایل","فقط دسکتاپ"].map(x=><option key={x}>{x}</option>)}</select></label><label>رفتار ریسپانسیو<select value={form.responsive} onChange={e=>set("responsive",e.target.value)}>{["خودکار","فشرده در موبایل","حفظ ساختار","مخفی در موبایل"].map(x=><option key={x}>{x}</option>)}</select></label><label>وضعیت<select value={form.status} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","فعال","غیرفعال","آرشیو شده"].map(x=><option key={x}>{x}</option>)}</select></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary} disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت بلوک"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>چیدمان صفحه</small><h2>بلوک‌های ثبت‌شده</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="کد صفحه، عنوان یا نوع بلوک..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.data["block-title"]||r.title}</b><small>{r.data["page-code"]||""} · {r.data["block-type"]||""} · {r.data.zone||""}</small><span>{r.data.status||r.status} · ترتیب {String(r.data["order-index"]??0)}</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button><button onClick={()=>move(r,-1)}>↑</button><button onClick={()=>move(r,1)}>↓</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>action(r,"فعال")}>فعال‌سازی</button>}{r.data.status==="فعال"&&<button onClick={()=>action(r,"غیرفعال")}>غیرفعال</button>}<button onClick={()=>duplicate(r)}>تکثیر</button><button onClick={()=>action(r,"آرشیو شده")}>آرشیو</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>بلوک صفحه‌ای ثبت نشده است.</div>}</div></section></section></main>}