"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./PageBuilderWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const blank:any={code:"",title:"",key:"",route:"",type:"داشبورد",template:"",version:1,definition:"",visibility:"کاربران واردشده",status:"پیش‌نویس",published:"",owner:"",seoTitle:"",seoDescription:"",notes:""};
const tabs=[["all","همه صفحات"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]];
export default function PageBuilderWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...blank}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/34-page-builder/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت صفحات ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||String(r.data.status)===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"}as any)[tab]),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...blank})};
const payload=()=>({recordType:"page-definition",title:String(form.title),status:String(form.status),data:{"page-code":form.code,"page-title":form.title,"page-key":form.key,route:form.route,"page-type":form.type,template:form.template,version:Number(form.version||1),"definition-reference":form.definition,visibility:form.visibility,status:form.status,"published-at":form.published,owner:form.owner,"seo-title":form.seoTitle,"seo-description":form.seoDescription,notes:form.notes}});
const save=async()=>{setError("");if(!String(form.code).trim()||!String(form.title).trim()||!String(form.key).trim()||!String(form.route).trim())return setError("کد، عنوان، کلید و مسیر صفحه الزامی است.");setBusy(true);try{const r=await fetch(API+"/api/platform/modules/34-page-builder/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره صفحه انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const action=async(r:R,status:string,extra:any={})=>{const data={...r.data,status,...extra};const x=await fetch(API+"/api/platform/modules/34-page-builder/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d:any=r.data;setEdit(r.id);setForm({code:d["page-code"]||"",title:d["page-title"]||r.title,key:d["page-key"]||"",route:d.route||"",type:d["page-type"]||"داشبورد",template:d.template||"",version:d.version||1,definition:d["definition-reference"]||"",visibility:d.visibility||"کاربران واردشده",status:d.status||"پیش‌نویس",published:d["published-at"]||"",owner:d.owner||"",seoTitle:d["seo-title"]||"",seoDescription:d["seo-description"]||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"page-code":String(r.data["page-code"]||"")+"-COPY","page-key":String(r.data["page-key"]||"")+"-copy","page-title":String(r.data["page-title"]||"")+" - نسخه جدید",version:1,status:"پیش‌نویس","published-at":""};await fetch(API+"/api/platform/modules/34-page-builder/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"page-definition",title:d["page-title"],status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/34-page-builder/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۳۴</small><h1>صفحه‌ساز و مدیریت صفحات</h1><p>مدیریت تعریف صفحه، مسیر، نسخه، وضعیت انتشار و متادیتای واقعی صفحات سامانه.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>صفحه</span></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{edit?"ویرایش صفحه":"ساخت صفحه"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>
{[["code","کد صفحه *"],["title","عنوان صفحه *"],["key","کلید صفحه *"],["route","مسیر صفحه *"],["template","قالب پایه"],["version","نسخه"],["definition","مرجع تعریف صفحه"],["owner","مالک صفحه"],["seoTitle","عنوان SEO"]].map(([k,l]:any)=><label key={k}>{l}<input type={k==="version"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}
<label>نوع صفحه<select value={form.type} onChange={e=>set("type",e.target.value)}>{["داخلی","فرود","داشبورد","اطلاعاتی","سازمانی","سایر"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>سطح نمایش<select value={form.visibility} onChange={e=>set("visibility",e.target.value)}>{["عمومی","کاربران واردشده","نقش‌محور","سازمانی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>وضعیت<select value={form.status} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","فعال","غیرفعال","آرشیو شده"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label className={styles.full}>توضیحات SEO<textarea rows={2} value={form.seoDescription} onChange={e=>set("seoDescription",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary} disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت صفحه"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>چرخه انتشار</small><h2>صفحات سامانه</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="عنوان، کلید یا مسیر..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.title}</b><small>{r.data.route||"بدون مسیر"} · نسخه {r.data.version||1}</small><span>{r.data.status||r.status} · {r.data["page-type"]||""}</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>action(r,"فعال",{"published-at":new Date().toISOString()})}>انتشار</button>}{r.data.status==="فعال"&&<button onClick={()=>action(r,"غیرفعال")}>غیرفعال</button>}{r.data.status==="غیرفعال"&&<button onClick={()=>action(r,"فعال")}>فعال‌سازی</button>}<button onClick={()=>action(r,"آرشیو شده")}>آرشیو</button><button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>صفحه‌ای ثبت نشده است.</div>}</div></section></section></main>}