"use client";
import{useEffect,useMemo,useState}from"react";
import styles from"./PageTemplatesWorkspace.module.css";
type R={id:number;record_type:string;title:string;status:string;data:Record<string,any>};
const API=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map((x:any)=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const blank:any={code:"",title:"",key:"",type:"عمومی",layout:"تمام‌عرض",header:"استاندارد",footer:"استاندارد",blocks:"",responsive:"خودکار",version:1,status:"پیش‌نویس",published:"",owner:"",description:"",notes:""};
const tabs=[["all","همه قالب‌ها"],["draft","پیش‌نویس"],["active","فعال"],["disabled","غیرفعال"],["archived","آرشیو"]];
export default function PageTemplatesWorkspace(){
const[rows,setRows]=useState<R[]>([]),[form,setForm]=useState({...blank}),[edit,setEdit]=useState<number|null>(null),[tab,setTab]=useState("all"),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
const load=async()=>{try{const r=await fetch(API+"/api/platform/modules/36-page-templates/records?page=1&pageSize=300&q="+encodeURIComponent(q),{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b?.error||"دریافت قالب‌ها ناموفق بود");setRows(b.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}};
useEffect(()=>{load()},[]);
const visible=useMemo(()=>rows.filter(r=>tab==="all"||String(r.data.status)===({draft:"پیش‌نویس",active:"فعال",disabled:"غیرفعال",archived:"آرشیو شده"}as any)[tab]),[rows,tab]);
const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));const reset=()=>{setEdit(null);setForm({...blank})};
const payload=(d=form)=>({recordType:"page-template",title:String(d.title),status:String(d.status),data:{"template-code":d.code,"template-title":d.title,"template-key":d.key,"template-type":d.type,"layout-mode":d.layout,"header-mode":d.header,"footer-mode":d.footer,"block-definition-reference":d.blocks,"responsive-mode":d.responsive,version:Number(d.version||1),status:d.status,"published-at":d.published,owner:d.owner,description:d.description,notes:d.notes}});
const save=async()=>{setError("");if(!String(form.code).trim()||!String(form.title).trim()||!String(form.key).trim())return setError("کد، عنوان و کلید قالب الزامی است.");setBusy(true);try{const r=await fetch(API+"/api/platform/modules/36-page-templates/records"+(edit?"/"+edit:""),{method:edit?"PATCH":"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(payload())}),b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"ذخیره قالب انجام نشد");reset();await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}};
const action=async(r:R,status:string)=>{const data={...r.data,status,...(status==="فعال"?{"published-at":new Date().toISOString()}:{})};const x=await fetch(API+"/api/platform/modules/36-page-templates/records/"+r.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:r.record_type,title:r.title,status,data})});if(!x.ok)setError("عملیات انجام نشد");else await load()};
const editRow=(r:R)=>{const d=r.data;setEdit(r.id);setForm({code:d["template-code"]||"",title:d["template-title"]||r.title,key:d["template-key"]||"",type:d["template-type"]||"عمومی",layout:d["layout-mode"]||"تمام‌عرض",header:d["header-mode"]||"استاندارد",footer:d["footer-mode"]||"استاندارد",blocks:d["block-definition-reference"]||"",responsive:d["responsive-mode"]||"خودکار",version:d.version||1,status:d.status||"پیش‌نویس",published:d["published-at"]||"",owner:d.owner||"",description:d.description||"",notes:d.notes||""});scrollTo({top:0,behavior:"smooth"})};
const duplicate=async(r:R)=>{const d={...r.data,"template-code":String(r.data["template-code"]||"")+"-COPY","template-key":String(r.data["template-key"]||"")+"-copy","template-title":String(r.data["template-title"]||"")+" - نسخه جدید",version:1,status:"پیش‌نویس","published-at":""};await fetch(API+"/api/platform/modules/36-page-templates/records",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({recordType:"page-template",title:d["template-title"],status:"پیش‌نویس",data:d})});await load()};
const remove=async(id:number)=>{await fetch(API+"/api/platform/modules/36-page-templates/records/"+id,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});await load()};
return <main className={styles.page} dir="rtl"><header className={styles.hero}><div><small>مرکز مدیریت نگار آذین فدک · ماژول ۳۶</small><h1>مدیریت قالب‌های صفحات</h1><p>تعریف ساختار پایه صفحات، چیدمان، هدر، فوتر، رفتار ریسپانسیو و چرخه انتشار قالب‌ها.</p></div><div className={styles.stat}><b>{rows.length.toLocaleString("fa-IR")}</b><span>قالب</span></div></header>
<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>{error&&<div className={styles.error}>{error}</div>}
<section className={styles.grid}><form className={styles.card} onSubmit={e=>{e.preventDefault();save()}}><div className={styles.head}><div><small>ثبت واقعی در PostgreSQL</small><h2>{edit?"ویرایش قالب":"ساخت قالب"}</h2></div>{edit&&<button type="button" onClick={reset}>انصراف</button>}</div><div className={styles.fields}>{[["code","کد قالب *"],["title","عنوان قالب *"],["key","کلید قالب *"],["blocks","مرجع تعریف بلوک‌ها"],["version","نسخه"],["owner","مالک قالب"]].map(([k,l]:[string,string])=><label key={k}>{l}<input type={k==="version"?"number":"text"} value={String(form[k]??"")} onChange={e=>set(k,e.target.value)}/></label>)}
<label>نوع قالب<select value={form.type} onChange={e=>set("type",e.target.value)}>{["عمومی","داشبورد","فرود","اطلاعاتی","سازمانی","فهرست","جزئیات","سفارشی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>الگوی چیدمان<select value={form.layout} onChange={e=>set("layout",e.target.value)}>{["تمام‌عرض","دو ستونه","سه ستونه","سایدبار راست","سایدبار چپ","سفارشی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>هدر<select value={form.header} onChange={e=>set("header",e.target.value)}>{["استاندارد","فشرده","بدون هدر","سفارشی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>فوتر<select value={form.footer} onChange={e=>set("footer",e.target.value)}>{["استاندارد","فشرده","بدون فوتر","سفارشی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>رفتار ریسپانسیو<select value={form.responsive} onChange={e=>set("responsive",e.target.value)}>{["خودکار","موبایل‌محور","دسکتاپ‌محور","سفارشی"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label>وضعیت<select value={form.status} onChange={e=>set("status",e.target.value)}>{["پیش‌نویس","فعال","غیرفعال","آرشیو شده"].map((x:any)=><option key={x}>{x}</option>)}</select></label><label className={styles.full}>توضیحات<textarea rows={2} value={form.description} onChange={e=>set("description",e.target.value)}/></label><label className={styles.full}>یادداشت<textarea rows={2} value={form.notes} onChange={e=>set("notes",e.target.value)}/></label></div><button className={styles.primary} disabled={busy}>{busy?"در حال ذخیره...":edit?"ذخیره تغییرات":"ثبت قالب"}</button></form>
<section className={styles.card}><div className={styles.head}><div><small>چرخه انتشار قالب</small><h2>قالب‌های سامانه</h2></div><button onClick={load}>به‌روزرسانی</button></div><div className={styles.search}><input placeholder="عنوان، کلید یا نوع قالب..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><button onClick={load}>جستجو</button></div><div className={styles.list}>{visible.map(r=><article className={styles.row} key={r.id}><div className={styles.info}><b>{r.title}</b><small>{r.data["template-key"]||""} · {r.data["template-type"]||""} · {r.data["layout-mode"]||""}</small><span>{r.data.status||r.status} · نسخه {String(r.data.version||1)}</span></div><div className={styles.rowActions}><button onClick={()=>editRow(r)}>ویرایش</button>{r.data.status==="پیش‌نویس"&&<button onClick={()=>action(r,"فعال")}>انتشار</button>}{r.data.status==="فعال"&&<button onClick={()=>action(r,"غیرفعال")}>غیرفعال</button>}{r.data.status==="غیرفعال"&&<button onClick={()=>action(r,"فعال")}>فعال‌سازی</button>}<button onClick={()=>action(r,"آرشیو شده")}>آرشیو</button><button onClick={()=>duplicate(r)}>تکثیر</button><button className={styles.danger} onClick={()=>remove(r.id)}>حذف</button></div></article>)}{!visible.length&&<div className={styles.empty}>قالبی ثبت نشده است.</div>}</div></section></section></main>}