"use client";
import {useEffect,useState} from "react";
import styles from "./PurchasingSupplyWorkspace.module.css";
type A=Record<string,any>;
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
async function req(path:string,opt:RequestInit={}){const r=await fetch(api+path,{credentials:"include",...opt,headers:{"Content-Type":"application/json","X-CSRF-Token":csrf(),...(opt.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"عملیات ناموفق بود");return b}
const labels:A={draft:"پیش‌نویس",submitted:"ارسال‌شده",approved:"تأییدشده",rejected:"ردشده",rfq:"در استعلام",ordered:"سفارش‌شده",closed:"بسته",cancelled:"لغوشده",sent:"ارسال‌شده",quoting:"در دریافت پیشنهاد",compared:"قابل مقایسه",selected:"انتخاب‌شده",partially_received:"دریافت ناقص",received:"دریافت کامل",invoiced:"فاکتور شده",paid:"پرداخت‌شده",requested:"درخواست‌شده",shipped:"ارسال برگشت",credited:"بستانکار شد",active:"فعال",expired:"منقضی"};
export default function PurchasingSupplyWorkspace(){
 const [d,setD]=useState<A>({suppliers:[],requests:[],rfqs:[],quotes:[],orders:[],receipts:[],invoices:[],payments:[],returns:[],evaluations:[],contracts:[],events:[]}),[tab,setTab]=useState("dashboard"),[err,setErr]=useState(""),[saving,setSaving]=useState(false);
 const [supplier,setSupplier]=useState<A>({code:"",name:"",phone:"",email:"",paymentTermsDays:"0"}),[request,setRequest]=useState<A>({productName:"",sku:"",quantity:"1",unit:"عدد",estimatedUnitPrice:"0",department:"",requiredDate:""});
 const [rfq,setRfq]=useState<A>({requestId:"",supplierIds:[],deadline:""}),[quote,setQuote]=useState<A>({rfqId:"",supplierId:"",productName:"",quantity:"1",unitPrice:"0",taxRate:"0",deliveryDays:"0",qualityScore:"0"});
 const [order,setOrder]=useState<A>({supplierId:"",productName:"",sku:"",quantity:"1",unitPrice:"0",taxRate:"0",expectedDate:""}),[pay,setPay]=useState<A>({invoiceId:"",amount:"",method:"bank",referenceNo:""}),[ret,setRet]=useState<A>({orderId:"",amount:"",reason:""});
 const load=async()=>{try{setErr("");setD(await req("/api/purchasing/overview"))}catch(e){setErr(e instanceof Error?e.message:"خطا")}};useEffect(()=>{load()},[]);
 const save=async(path:string,b:A)=>{setSaving(true);try{await req(path,{method:"POST",body:JSON.stringify(b)});await load()}catch(e){setErr(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const tabs=[["dashboard","داشبورد خرید"],["requests","درخواست خرید"],["rfq","استعلام"],["quotes","مقایسه پیشنهادها"],["orders","سفارش خرید"],["receipts","دریافت کالا"],["invoices","فاکتور خرید"],["returns","برگشت خرید"],["suppliers","تأمین‌کنندگان"],["evaluations","ارزیابی تأمین‌کنندگان"],["contracts","قرارداد تأمین"],["reports","گزارش خرید"]];
 const goStatus=async(path:string,status:string)=>{try{await req(path,{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setErr(e instanceof Error?e.message:"خطا")}};
 return <main className={styles.root} dir="rtl"><header className={styles.header}><div><span>هسته خرید و تأمین</span><h1>مرکز خرید و تأمین</h1><p>چرخه واقعی درخواست، استعلام، مقایسه، سفارش، دریافت، فاکتور، پرداخت، برگشت و ارزیابی تأمین‌کننده.</p></div><div className={styles.metrics}><b>{d.requests.length}</b><small>درخواست</small><b>{d.orders.length}</b><small>سفارش</small><b>{d.invoices.length}</b><small>فاکتور</small><b>{d.suppliers.length}</b><small>تأمین‌کننده</small></div></header>{err&&<div className={styles.error}>{err}</div>}<nav className={styles.tabs}>{tabs.map(x=><button key={x[0]} className={tab===x[0]?styles.active:""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>
 {tab==="dashboard"&&<section className={styles.grid}><article className={styles.panel}><h2>چرخه خرید</h2><div className={styles.flow}>درخواست ← تأیید ← استعلام ← پیشنهادها ← انتخاب تأمین‌کننده ← سفارش ← دریافت ← کنترل ← فاکتور ← پرداخت ← برگشت</div></article><article className={styles.panel}><h2>کنترل‌های اصلی</h2><p>دریافت بیش از مقدار سفارش مجاز نیست.</p><p>فاکتور فقط پس از دریافت کامل صادر می‌شود.</p><p>اثر مالی تا ثبت در دفتر مالی در وضعیت «در انتظار حسابداری» باقی می‌ماند.</p></article></section>}
 {tab==="suppliers"&&<section className={styles.panel}><h2>تأمین‌کننده جدید</h2><div className={styles.form}>{Object.keys(supplier).map(k=><label key={k}>{k}<input value={supplier[k]} onChange={e=>setSupplier({...supplier,[k]:e.target.value})}/></label>)}</div><button disabled={saving} onClick={()=>save("/api/purchasing/suppliers",supplier)}>ثبت تأمین‌کننده</button><div className={styles.list}>{d.suppliers.map((x:any)=><div className={styles.row} key={x.id}><b>{x.name}</b><span>{x.code} · {x.phone||"-"} · {labels[x.status]}</span></div>)}</div></section>}
 {tab==="requests"&&<section className={styles.panel}><h2>درخواست خرید جدید</h2><div className={styles.form}>{Object.keys(request).map(k=><label key={k}>{k}<input value={request[k]} onChange={e=>setRequest({...request,[k]:e.target.value})}/></label>)}</div><button disabled={saving} onClick={()=>save("/api/purchasing/requests",{items:[{productName:request.productName,sku:request.sku,quantity:Number(request.quantity),unit:request.unit,estimatedUnitPrice:Number(request.estimatedUnitPrice)}],department:request.department,requiredDate:request.requiredDate})}>ثبت درخواست</button><div className={styles.list}>{d.requests.map((x:any)=><div className={styles.row} key={x.id}><b>{x.request_no}</b><span>{x.department||"-"} · {labels[x.status]}</span><div className={styles.actions}>{x.status==="draft"&&<button onClick={()=>goStatus("/api/purchasing/requests/"+x.id+"/status","submitted")}>ارسال</button>}{x.status==="submitted"&&<button onClick={()=>goStatus("/api/purchasing/requests/"+x.id+"/status","approved")}>تأیید</button>}{x.status==="approved"&&<button onClick={()=>goStatus("/api/purchasing/requests/"+x.id+"/status","rfq")}>ورود به استعلام</button>}</div></div>)}</div></section>}
 {tab==="rfq"&&<section className={styles.panel}><h2>استعلام از تأمین‌کنندگان</h2><div className={styles.form}><label>درخواست<select value={rfq.requestId} onChange={e=>setRfq({...rfq,requestId:e.target.value})}><option value="">انتخاب</option>{d.requests.filter((x:any)=>x.status==="approved").map((x:any)=><option key={x.id} value={x.id}>{x.request_no}</option>)}</select></label><label>تأمین‌کنندگان<select multiple value={rfq.supplierIds} onChange={e=>setRfq({...rfq,supplierIds:Array.from(e.target.selectedOptions).map(x=>x.value)})}>{d.suppliers.filter((x:any)=>x.status==="active").map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>مهلت<input type="date" value={rfq.deadline} onChange={e=>setRfq({...rfq,deadline:e.target.value})}/></label></div><button disabled={saving} onClick={()=>save("/api/purchasing/rfqs",rfq)}>ثبت استعلام</button><div className={styles.list}>{d.rfqs.map((x:any)=><div className={styles.row} key={x.id}><b>{x.rfq_no}</b><span>{x.request_no} · {labels[x.status]}</span></div>)}</div></section>}
 {tab==="quotes"&&<section className={styles.panel}><h2>دریافت و مقایسه پیشنهاد</h2><div className={styles.form}><label>استعلام<select value={quote.rfqId} onChange={e=>setQuote({...quote,rfqId:e.target.value})}><option value="">انتخاب</option>{d.rfqs.map((x:any)=><option key={x.id} value={x.id}>{x.rfq_no}</option>)}</select></label><label>تأمین‌کننده<select value={quote.supplierId} onChange={e=>setQuote({...quote,supplierId:e.target.value})}><option value="">انتخاب</option>{d.suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>قلم<input value={quote.productName} onChange={e=>setQuote({...quote,productName:e.target.value})}/></label><label>تعداد<input type="number" value={quote.quantity} onChange={e=>setQuote({...quote,quantity:e.target.value})}/></label><label>قیمت واحد<input type="number" value={quote.unitPrice} onChange={e=>setQuote({...quote,unitPrice:e.target.value})}/></label><label>مالیات %<input type="number" value={quote.taxRate} onChange={e=>setQuote({...quote,taxRate:e.target.value})}/></label><label>زمان تحویل<input type="number" value={quote.deliveryDays} onChange={e=>setQuote({...quote,deliveryDays:e.target.value})}/></label></div><button disabled={saving} onClick={()=>save("/api/purchasing/quotes",{...quote,items:[{productName:quote.productName,quantity:Number(quote.quantity),unitPrice:Number(quote.unitPrice),taxRate:Number(quote.taxRate)}]})}>ثبت پیشنهاد</button><div className={styles.list}>{d.quotes.map((x:any)=><div className={styles.row} key={x.id}><b>{x.supplier_name}</b><span>{x.rfq_no} · {Number(x.total).toLocaleString("fa-IR")} · تحویل {x.delivery_days} روز · {labels[x.status]}</span><button onClick={()=>goStatus("/api/purchasing/rfqs/"+x.id+"/select","selected")}>انتخاب تأمین‌کننده</button></div>)}</div></section>}
 {tab==="orders"&&<section className={styles.panel}><h2>سفارش خرید</h2><div className={styles.form}><label>تأمین‌کننده<select value={order.supplierId} onChange={e=>setOrder({...order,supplierId:e.target.value})}><option value="">انتخاب</option>{d.suppliers.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{["productName","sku","quantity","unitPrice","taxRate","expectedDate"].map(k=><label key={k}>{k}<input value={order[k]} onChange={e=>setOrder({...order,[k]:e.target.value})}/></label>)}</div><button disabled={saving} onClick={()=>save("/api/purchasing/orders",{...order,quantity:Number(order.quantity),unitPrice:Number(order.unitPrice),taxRate:Number(order.taxRate)})}>ثبت سفارش</button><div className={styles.list}>{d.orders.map((x:any)=><div className={styles.row} key={x.id}><b>{x.order_no}</b><span>{x.supplier_name} · {Number(x.total).toLocaleString("fa-IR")} · {labels[x.status]}</span><div className={styles.actions}>{x.status==="draft"&&<button onClick={()=>goStatus("/api/purchasing/orders/"+x.id+"/status","approved")}>تأیید</button>}{x.status==="approved"&&<button onClick={()=>goStatus("/api/purchasing/orders/"+x.id+"/status","sent")}>ارسال به تأمین‌کننده</button>}{x.status==="received"&&<button onClick={()=>req("/api/purchasing/invoices",{method:"POST",body:JSON.stringify({orderId:x.id})}).then(load).catch(e=>setErr(e.message))}>ثبت فاکتور</button>}</div></div>)}</div></section>}
 {tab==="receipts"&&<section className={styles.panel}><h2>دریافت کالا</h2><div className={styles.list}>{d.orders.filter((x:any)=>["sent","partially_received"].includes(x.status)).map((x:any)=><div className={styles.row} key={x.id}><b>{x.order_no}</b><span>{x.supplier_name} · آماده دریافت</span><button onClick={async()=>{try{const it=await req("/api/purchasing/overview");const items=it.orders.find((o:any)=>o.id===x.id);setErr("برای دریافت دقیق، شناسه قلم سفارش باید از API دریافت شود.")}catch(e){setErr(e instanceof Error?e.message:"خطا")}}}>بررسی</button></div>)}</div></section>}
 {tab==="invoices"&&<section className={styles.panel}><h2>فاکتور خرید و پرداخت</h2><div className={styles.form}><label>فاکتور<select value={pay.invoiceId} onChange={e=>setPay({...pay,invoiceId:e.target.value})}><option value="">انتخاب</option>{d.invoices.map((x:any)=><option key={x.id} value={x.id}>{x.invoice_no} · {x.supplier_name}</option>)}</select></label><label>مبلغ پرداخت<input type="number" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})}/></label><label>مرجع<input value={pay.referenceNo} onChange={e=>setPay({...pay,referenceNo:e.target.value})}/></label></div><button disabled={saving} onClick={()=>req("/api/purchasing/invoices/"+pay.invoiceId+"/payments",{method:"POST",body:JSON.stringify({amount:Number(pay.amount),method:pay.method,referenceNo:pay.referenceNo})}).then(load).catch(e=>setErr(e.message))}>ثبت پرداخت</button><div className={styles.list}>{d.invoices.map((x:any)=><div className={styles.row} key={x.id}><b>{x.invoice_no}</b><span>{x.supplier_name} · {Number(x.total).toLocaleString("fa-IR")} · پرداخت {Number(x.paid_total).toLocaleString("fa-IR")} · {labels[x.status]}</span></div>)}</div></section>}
 {tab==="returns"&&<section className={styles.panel}><h2>برگشت خرید</h2><div className={styles.form}><label>سفارش<select value={ret.orderId} onChange={e=>setRet({...ret,orderId:e.target.value})}><option value="">انتخاب</option>{d.orders.map((x:any)=><option key={x.id} value={x.id}>{x.order_no}</option>)}</select></label><label>مبلغ<input type="number" value={ret.amount} onChange={e=>setRet({...ret,amount:e.target.value})}/></label><label>علت<input value={ret.reason} onChange={e=>setRet({...ret,reason:e.target.value})}/></label></div><button disabled={saving} onClick={()=>save("/api/purchasing/returns",ret)}>ثبت برگشت</button><div className={styles.list}>{d.returns.map((x:any)=><div className={styles.row} key={x.id}><b>{x.return_no}</b><span>{x.order_no} · {Number(x.amount).toLocaleString("fa-IR")} · {labels[x.status]}</span></div>)}</div></section>}
 {tab==="evaluations"&&<section className={styles.panel}><h2>ارزیابی تأمین‌کننده</h2><div className={styles.form}><label>تأمین‌کننده<select value={""} onChange={()=>{}}><option>انتخاب در رکورد</option>{d.suppliers.map((x:any)=><option key={x.id}>{x.name}</option>)}</select></label></div><div className={styles.list}>{d.evaluations.map((x:any)=><div className={styles.row} key={x.id}><b>{x.supplier_name}</b><span>امتیاز {x.total_score}</span></div>)}</div></section>}
 {tab==="contracts"&&<section className={styles.panel}><h2>قرارداد تأمین</h2><div className={styles.list}>{d.contracts.map((x:any)=><div className={styles.row} key={x.id}><b>{x.contract_no}</b><span>{x.supplier_name} · {x.title} · {labels[x.status]}</span></div>)}</div></section>}
 {tab==="reports"&&<section className={styles.grid}><article className={styles.panel}><h2>گزارش خرید</h2><p>درخواست‌ها: {d.requests.length}</p><p>استعلام‌ها: {d.rfqs.length}</p><p>پیشنهادها: {d.quotes.length}</p><p>سفارش‌ها: {d.orders.length}</p><p>دریافت‌ها: {d.receipts.length}</p><p>فاکتورها: {d.invoices.length}</p><p>پرداخت‌ها: {d.payments.length}</p><p>برگشت‌ها: {d.returns.length}</p></article><article className={styles.panel}><h2>رویدادهای کنترل</h2>{d.events.slice(0,20).map((x:any)=><p key={x.id}>{x.entity_type} · {x.from_status||"ایجاد"} → {x.to_status||"-"} · {new Date(x.created_at).toLocaleString("fa-IR")}</p>)}</article></section>}
 </main>
}