"use client";
import {useEffect,useMemo,useState} from "react";
import styles from "./SalesWorkspace.module.css";
type Any=Record<string,any>;
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
async function req(path:string,opt:RequestInit={}){const r=await fetch(api+path,{credentials:"include",...opt,headers:{"Content-Type":"application/json","X-CSRF-Token":csrf(),...(opt.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"عملیات ناموفق بود");return b}
const labels:any={draft:"پیش‌نویس",pending_credit:"در انتظار کنترل اعتبار",confirmed:"تأییدشده",reserved:"رزرو موجودی",delivering:"در ارسال",delivered:"تحویل‌شده",invoiced:"فاکتور شده",cancelled:"لغوشده",returned:"مرجوعی",issued:"صادرشده",partially_paid:"نیمه‌دریافت",paid:"تسویه‌شده",requested:"درخواست‌شده",approved:"تأییدشده",received:"دریافت‌شده",inspected:"بازرسی‌شده",refunded:"مسترد",rejected:"ردشده"};
export default function SalesWorkspace(){
 const [data,setData]=useState<any>({partners:[],products:[],quotes:[],orders:[],invoices:[],payments:[],returns:[],commissions:[],targets:[],events:[]});
 const [tab,setTab]=useState("dashboard"),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [partner,setPartner]=useState({code:"",name:"",phone:"",email:"",creditLimit:"0"});
 const [product,setProduct]=useState({sku:"",name:"",unit:"عدد",salePrice:"0",taxRate:"0",discountRate:"0",stockAvailable:"0"});
 const [order,setOrder]=useState({partnerId:"",productId:"",quantity:"1",unitPrice:"",discountRate:"0",taxRate:"0",dueDate:"",notes:""});
 const [quote,setQuote]=useState({partnerId:"",productId:"",quantity:"1",unitPrice:"",discountRate:"0",taxRate:"0",validUntil:"",notes:""});
 const [pay,setPay]=useState({invoiceId:"",amount:"",method:"bank",referenceNo:""});
 const [ret,setRet]=useState({invoiceId:"",amount:"",reason:""});
 const load=async()=>{try{setError("");setData(await req("/api/sales/overview"))}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 useEffect(()=>{load()},[]);
 const save=async(path:string,body:any)=>{setSaving(true);try{await req(path,{method:"POST",body:JSON.stringify(body)});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const createQuote=async()=>{if(!quote.partnerId||!quote.productId)return setError("مشتری و کالا را انتخاب کنید");await save("/api/sales/quotes",{partnerId:quote.partnerId,items:[{productId:quote.productId,quantity:Number(quote.quantity),unitPrice:quote.unitPrice?Number(quote.unitPrice):undefined,discountRate:Number(quote.discountRate),taxRate:Number(quote.taxRate)}],validUntil:quote.validUntil,notes:quote.notes})};
 const createOrder=async()=>{if(!order.partnerId||!order.productId)return setError("مشتری و کالا را انتخاب کنید");await save("/api/sales/orders",{partnerId:order.partnerId,items:[{productId:order.productId,quantity:Number(order.quantity),unitPrice:order.unitPrice?Number(order.unitPrice):undefined,discountRate:Number(order.discountRate),taxRate:Number(order.taxRate)}],dueDate:order.dueDate,notes:order.notes})};
 const invoice=async(o:any)=>save("/api/sales/invoices",{orderId:o.id});
 const payment=async()=>save("/api/sales/invoices/"+pay.invoiceId+"/payments",{amount:Number(pay.amount),method:pay.method,referenceNo:pay.referenceNo});
 const returnInvoice=async()=>save("/api/sales/returns",ret);
 const change=async(id:string,status:string)=>{try{await req("/api/sales/orders/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 const tabs=[["dashboard","داشبورد فروش"],["partners","مشتریان"],["quotes","پیش‌فاکتورها"],["pricing","قیمت‌گذاری"],["products","کالاها"],["orders","سفارش‌ها"],["invoices","فاکتورها"],["returns","برگشت"],["targets","اهداف"],["commissions","پورسانت"],["events","کنترل و رویدادها"]];
 const summary={orders:data.orders.length,invoices:data.invoices.length,revenue:data.invoices.reduce((a:x, i:any)=>a+Number(i.total||0),0),receipts:data.payments.reduce((a:number,i:any)=>a+Number(i.amount||0),0)};
 return <main className={styles.root} dir="rtl"><header className={styles.header}><div><span>هسته فروش و درآمد</span><h1>مرکز فروش</h1><p>از مشتری و قیمت‌گذاری تا سفارش، تحویل، فاکتور، دریافت و مرجوعی، با رویدادهای واقعی پایگاه داده.</p></div><div className={styles.kpis}><b>{summary.orders}</b><small>سفارش</small><b>{summary.invoices}</b><small>فاکتور</small><b>{summary.revenue.toLocaleString("fa-IR")}</b><small>فروش</small><b>{summary.receipts.toLocaleString("fa-IR")}</b><small>دریافت</small></div></header>
 {error&&<div className={styles.error}>{error}</div>}<nav className={styles.tabs}>{tabs.map(x=><button className={tab===x[0]?styles.active:""} onClick={()=>setTab(x[0])} key={x[0]}>{x[1]}</button>)}</nav>
 {tab==="dashboard"&&<section className={styles.grid}><article className={styles.panel}><h2>چرخه فروش</h2><div className={styles.flow}>مشتری ← پیش‌فاکتور ← سفارش ← کنترل اعتبار ← رزرو موجودی ← تحویل ← فاکتور ← دریافت ← مرجوعی</div></article><article className={styles.panel}><h2>وضعیت سفارش‌ها</h2>{Object.entries(labels).filter(([k])=>data.orders.some((x:any)=>x.status===k)).map(([k,v])=><p key={k}><b>{data.orders.filter((x:any)=>x.status===k).length}</b> {v}</p>)}</article></section>}
 {tab==="partners"&&<section className={styles.panel}><h2>مشتری جدید</h2><div className={styles.form}>{Object.keys(partner).map(k=><label key={k}>{k}<input value={(partner as any)[k]} onChange={e=>setPartner({...partner,[k]:e.target.value})}/></label>)}</div><button onClick={()=>save("/api/sales/partners",partner)} disabled={saving}>ثبت مشتری</button><div className={styles.list}>{data.partners.map((x:any)=><div className={styles.row} key={x.id}><b>{x.name}</b><span>{x.code} · {x.phone||"-"}</span></div>)}</div></section>}
 {tab==="products"&&<section className={styles.panel}><h2>کالای جدید</h2><div className={styles.form}>{Object.keys(product).map(k=><label key={k}>{k}<input value={(product as any)[k]} onChange={e=>setProduct({...product,[k]:e.target.value})}/></label>)}</div><button onClick={()=>save("/api/sales/products",product)} disabled={saving}>ثبت کالا</button><div className={styles.list}>{data.products.map((x:any)=><div className={styles.row} key={x.id}><b>{x.name}</b><span>{x.sku} · موجودی {x.stock_available}</span></div>)}</div></section>}
 {tab==="quotes"&&<section className={styles.panel}><h2>پیش‌فاکتور</h2><div className={styles.form}><label>مشتری<select value={quote.partnerId} onChange={e=>setQuote({...quote,partnerId:e.target.value})}><option value="">انتخاب</option>{data.partners.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>کالا<select value={quote.productId} onChange={e=>setQuote({...quote,productId:e.target.value})}><option value="">انتخاب</option>{data.products.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>تعداد<input type="number" value={quote.quantity} onChange={e=>setQuote({...quote,quantity:e.target.value})}/></label><label>قیمت واحد<input type="number" value={quote.unitPrice} onChange={e=>setQuote({...quote,unitPrice:e.target.value})}/></label><label>تخفیف %<input type="number" value={quote.discountRate} onChange={e=>setQuote({...quote,discountRate:e.target.value})}/></label><label>مالیات %<input type="number" value={quote.taxRate} onChange={e=>setQuote({...quote,taxRate:e.target.value})}/></label></div><button onClick={createQuote} disabled={saving}>ثبت پیش‌فاکتور</button><div className={styles.list}>{data.quotes.map((x:any)=><div className={styles.row} key={x.id}><div><b>{x.quote_no}</b><span>{x.partner_name} · {Number(x.total).toLocaleString("fa-IR")} · {labels[x.status]}</span></div><div className={styles.actions}>{x.status==="draft"&&<button onClick={()=>req("/api/sales/quotes/"+x.id+"/status",{method:"PATCH",body:JSON.stringify({status:"submitted"})}).then(load).catch(e=>setError(e.message))}>ارسال برای تأیید</button>}{x.status==="submitted"&&<button onClick={()=>req("/api/sales/quotes/"+x.id+"/status",{method:"PATCH",body:JSON.stringify({status:"approved"})}).then(load).catch(e=>setError(e.message))}>تأیید</button>}{x.status==="approved"&&<button onClick={()=>req("/api/sales/quotes/"+x.id+"/convert",{method:"POST",body:"{}"}).then(load).catch(e=>setError(e.message))}>تبدیل به سفارش</button>}</div></div>)}</div></section>}
 {tab==="pricing"&&<section className={styles.panel}><h2>قیمت‌گذاری</h2><div className={styles.list}>{data.products.map((x:any)=><div className={styles.row} key={x.id}><b>{x.name}</b><span>قیمت فروش {Number(x.sale_price).toLocaleString("fa-IR")} · تخفیف پایه {x.discount_rate}% · مالیات {x.tax_rate}%</span></div>)}</div></section>}
 {tab==="orders"&&<section className={styles.panel}><h2>سفارش جدید</h2><div className={styles.form}><label>مشتری<select value={order.partnerId} onChange={e=>setOrder({...order,partnerId:e.target.value})}><option value="">انتخاب</option>{data.partners.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>کالا<select value={order.productId} onChange={e=>setOrder({...order,productId:e.target.value})}><option value="">انتخاب</option>{data.products.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>تعداد<input type="number" value={order.quantity} onChange={e=>setOrder({...order,quantity:e.target.value})}/></label><label>قیمت واحد<input type="number" value={order.unitPrice} onChange={e=>setOrder({...order,unitPrice:e.target.value})}/></label><label>تخفیف %<input type="number" value={order.discountRate} onChange={e=>setOrder({...order,discountRate:e.target.value})}/></label><label>مالیات %<input type="number" value={order.taxRate} onChange={e=>setOrder({...order,taxRate:e.target.value})}/></label></div><button onClick={createOrder} disabled={saving}>ثبت سفارش</button><div className={styles.list}>{data.orders.map((x:any)=><div className={styles.row} key={x.id}><div><b>{x.order_no}</b><span>{x.partner_name} · {Number(x.total).toLocaleString("fa-IR")} · {labels[x.status]}</span></div><div className={styles.actions}>{(["pending_credit","confirmed","reserved","delivering","delivered"].filter(s=>{const m:any={draft:["pending_credit"],pending_credit:["confirmed"],confirmed:["reserved"],reserved:["delivering"],delivering:["delivered"]};return (m[x.status]||[]).includes(s)})).map(s=><button key={s} onClick={()=>change(x.id,s)}>{labels[s]}</button>)}{x.status==="delivered"&&<button onClick={()=>invoice(x)}>صدور فاکتور</button>}</div></div>)}</div></section>}
 {tab==="invoices"&&<section className={styles.panel}><h2>فاکتورها</h2><div className={styles.form}><label>فاکتور<select value={pay.invoiceId} onChange={e=>setPay({...pay,invoiceId:e.target.value})}><option value="">انتخاب</option>{data.invoices.map((x:any)=><option key={x.id} value={x.id}>{x.invoice_no} · {x.partner_name}</option>)}</select></label><label>مبلغ دریافت<input type="number" value={pay.amount} onChange={e=>setPay({...pay,amount:e.target.value})}/></label><label>روش<select value={pay.method} onChange={e=>setPay({...pay,method:e.target.value})}><option value="bank">بانک</option><option value="cash">صندوق</option><option value="card">کارت</option><option value="wallet">کیف پول</option><option value="credit">اعتبار</option></select></label><label>مرجع<input value={pay.referenceNo} onChange={e=>setPay({...pay,referenceNo:e.target.value})}/></label></div><button onClick={payment} disabled={saving}>ثبت دریافت</button><div className={styles.list}>{data.invoices.map((x:any)=><div className={styles.row} key={x.id}><b>{x.invoice_no}</b><span>{x.partner_name} · {Number(x.total).toLocaleString("fa-IR")} · دریافت {Number(x.paid_total).toLocaleString("fa-IR")} · {labels[x.status]}</span></div>)}</div></section>}
 {tab==="returns"&&<section className={styles.panel}><h2>برگشت فروش</h2><div className={styles.form}><label>فاکتور<select value={ret.invoiceId} onChange={e=>setRet({...ret,invoiceId:e.target.value})}><option value="">انتخاب</option>{data.invoices.map((x:any)=><option key={x.id} value={x.id}>{x.invoice_no}</option>)}</select></label><label>مبلغ<input type="number" value={ret.amount} onChange={e=>setRet({...ret,amount:e.target.value})}/></label><label>علت<input value={ret.reason} onChange={e=>setRet({...ret,reason:e.target.value})}/></label></div><button onClick={returnInvoice} disabled={saving}>ثبت درخواست برگشت</button><div className={styles.list}>{data.returns.map((x:any)=><div className={styles.row} key={x.id}><b>{x.return_no}</b><span>{x.invoice_no} · {Number(x.amount).toLocaleString("fa-IR")} · {labels[x.status]}</span></div>)}</div></section>}
 {tab==="targets"&&<section className={styles.panel}><h2>اهداف فروش</h2><div className={styles.list}>{data.targets.map((x:any)=><div className={styles.row} key={x.id}><b>{x.name}</b><span>{x.period_start} تا {x.period_end} · هدف {Number(x.target_amount).toLocaleString("fa-IR")}</span></div>)}</div></section>}
 {tab==="commissions"&&<section className={styles.panel}><h2>پورسانت فروش</h2><div className={styles.list}>{data.commissions.map((x:any)=><div className={styles.row} key={x.id}><b>{Number(x.amount).toLocaleString("fa-IR")}</b><span>{x.rate}% · پایه {Number(x.base_amount).toLocaleString("fa-IR")} · {labels[x.status]||x.status}</span></div>)}</div></section>} {tab==="events"&&<section className={styles.panel}><h2>Audit Trail فروش</h2><div className={styles.list}>{data.events.slice(0,100).map((x:any)=><div className={styles.row} key={x.id}><b>{x.entity_type}</b><span>{x.from_status||"ایجاد"} ← {x.to_status||"-"} · {x.event_type} · {new Date(x.created_at).toLocaleString("fa-IR")}</span></div>)}</div></section>}
 </main>}
