"use client";
import {useEffect,useState} from "react";
import styles from "./SLAWorkspace.module.css";
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,""),csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["sla-1","تعهدات خدمت"],["sla-2","سطح سرویس"],["sla-3","زمان پاسخ"],["sla-4","زمان حل"],["sla-5","نقض تعهد"]];
export default function SLAWorkspace(){const [tab,setTab]=useState("sla-1"),[d,setD]=useState<any>({commitments:[],levels:[],responsePolicies:[],resolutionPolicies:[],breaches:[]}),[error,setError]=useState(""),[busy,setBusy]=useState(false),[commitmentId,setCommitmentId]=useState(""),[key,setKey]=useState(""),[title,setTitle]=useState(""),[serviceType,setServiceType]=useState(""),[response,setResponse]=useState("60"),[resolution,setResolution]=useState("1440"),[levelKey,setLevelKey]=useState(""),[levelTitle,setLevelTitle]=useState(""),[trigger,setTrigger]=useState(""),[action,setAction]=useState("");
 const load=async()=>{const r=await fetch(api+"/api/sla/overview",{credentials:"include"});const b=await r.json();if(!r.ok)throw Error(b.error||"خطا");setD(b)};useEffect(()=>{const p=new URLSearchParams(location.search);setTab(p.get("tab")||"sla-1");load().catch(e=>setError(e.message))},[]);
 const post=async(path:string,body:any)=>{setBusy(true);setError("");try{const r=await fetch(api+path,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(body)});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"عملیات انجام نشد");await load();return b}catch(e){setError(e instanceof Error?e.message:"خطا");throw e}finally{setBusy(false)}};
 const del=async(path:string)=>{const r=await fetch(api+path,{method:"DELETE",credentials:"include",headers:{"X-CSRF-Token":csrf()}});if(!r.ok){const b=await r.json().catch(()=>null);throw Error(b?.error||"حذف انجام نشد")}await load()};
 return <main className={styles.wrap} dir="rtl"><header><div><span>منوی مرکزی سازمان · ۰۷</span><h1>تعهدات خدمت</h1><p>مدیریت سطح خدمت، زمان پاسخ، زمان حل و کنترل نقض تعهدات</p></div><button onClick={()=>load()}>به‌روزرسانی</button></header><nav>{tabs.map(([k,t])=><a className={tab===k?styles.active:""} href={"/modules/?code=07-sla&tab="+k} key={k}>{t}</a>)}</nav>{error&&<div className={styles.error}>{error}</div>}
 {tab==="sla-1"&&<section className={styles.grid}><div className={styles.panel}><h2>تعهد خدمت جدید</h2><div className={styles.form}><input placeholder="شناسه تعهد" value={key} onChange={e=>setKey(e.target.value)}/><input placeholder="عنوان" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="نوع خدمت" value={serviceType} onChange={e=>setServiceType(e.target.value)}/><input type="number" placeholder="دقیقه پاسخ" value={response} onChange={e=>setResponse(e.target.value)}/><input type="number" placeholder="دقیقه حل" value={resolution} onChange={e=>setResolution(e.target.value)}/><button disabled={busy} onClick={()=>post("/api/sla/commitments",{commitmentKey:key,title,serviceType,responseMinutes:Number(response),resolutionMinutes:Number(resolution)})}>ثبت تعهد</button></div></div><div className={styles.panel}><h2>تعهدات ثبت‌شده</h2>{d.commitments.map((x:any)=><article key={x.id}><div><b>{x.title}</b><small>{x.commitment_key} · {x.service_type} · پاسخ {x.response_minutes}دقیقه · حل {x.resolution_minutes}دقیقه · {x.status}</small></div><button className={styles.danger} onClick={()=>del("/api/sla/commitments/"+x.id)}>حذف</button></article>)}</div></section>}
 {tab==="sla-2"&&<section className={styles.grid}><div className={styles.panel}><h2>سطح سرویس جدید</h2><select value={commitmentId} onChange={e=>setCommitmentId(e.target.value)}><option value="">تعهد را انتخاب کنید</option>{d.commitments.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><div className={styles.form}><input placeholder="کلید سطح" value={levelKey} onChange={e=>setLevelKey(e.target.value)}/><input placeholder="عنوان سطح" value={levelTitle} onChange={e=>setLevelTitle(e.target.value)}/><input type="number" placeholder="زمان پاسخ" value={response} onChange={e=>setResponse(e.target.value)}/><input type="number" placeholder="زمان حل" value={resolution} onChange={e=>setResolution(e.target.value)}/><button onClick={()=>post("/api/sla/commitments/"+commitmentId+"/levels",{levelKey,title:levelTitle,responseMinutes:Number(response),resolutionMinutes:Number(resolution)})}>ثبت سطح سرویس</button></div></div><div className={styles.panel}><h2>سطوح ثبت‌شده</h2>{d.levels.map((x:any)=><article key={x.id}><span>{x.commitment_title}</span><span>{x.title} · پاسخ {x.response_minutes} · حل {x.resolution_minutes}</span><button className={styles.danger} onClick={()=>del("/api/sla/levels/"+x.id)}>حذف</button></article>)}</div></section>}
 {tab==="sla-3"&&<section className={styles.panel}><h2>سیاست زمان پاسخ</h2><select value={commitmentId} onChange={e=>setCommitmentId(e.target.value)}><option value="">تعهد را انتخاب کنید</option>{d.commitments.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><div className={styles.form}><input placeholder="محرک، مثل نزدیک‌شدن به سررسید" value={trigger} onChange={e=>setTrigger(e.target.value)}/><input placeholder="نوع اقدام" value={action} onChange={e=>setAction(e.target.value)}/><input type="number" placeholder="بعد از چند دقیقه" value={response} onChange={e=>setResponse(e.target.value)}/><button onClick={()=>post("/api/sla/response-policies",{commitmentId,triggerKey:trigger,actionType:action,afterMinutes:Number(response)})}>ثبت سیاست پاسخ</button></div>{d.responsePolicies.map((x:any)=><article key={x.id}><span>{x.commitment_title}</span><span>{x.trigger_key} · {x.action_type} · {x.after_minutes} دقیقه</span><button className={styles.danger} onClick={()=>del("/api/sla/response-policies/"+x.id)}>حذف</button></article>)}</section>}
 {tab==="sla-4"&&<section className={styles.panel}><h2>سیاست زمان حل</h2><select value={commitmentId} onChange={e=>setCommitmentId(e.target.value)}><option value="">تعهد را انتخاب کنید</option>{d.commitments.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select><div className={styles.form}><input placeholder="محرک، مثل عبور از زمان حل" value={trigger} onChange={e=>setTrigger(e.target.value)}/><input placeholder="نوع اقدام" value={action} onChange={e=>setAction(e.target.value)}/><input type="number" placeholder="بعد از چند دقیقه" value={resolution} onChange={e=>setResolution(e.target.value)}/><button onClick={()=>post("/api/sla/resolution-policies",{commitmentId,triggerKey:trigger,actionType:action,afterMinutes:Number(resolution)})}>ثبت سیاست حل</button></div>{d.resolutionPolicies.map((x:any)=><article key={x.id}><span>{x.commitment_title}</span><span>{x.trigger_key} · {x.action_type} · {x.after_minutes} دقیقه</span><button className={styles.danger} onClick={()=>del("/api/sla/resolution-policies/"+x.id)}>حذف</button></article>)}</section>}
 {tab==="sla-5"&&<section className={styles.panel}><h2>نقض تعهدات</h2>{d.breaches.map((x:any)=><article key={x.id}><div><b>{x.commitment_title}</b><small>{x.case_type} · {x.case_id} · هدف {new Date(x.target_at).toLocaleString("fa-IR")} · {x.status}</small></div>{x.status!=="resolved"&&<button onClick={()=>post("/api/sla/breaches/"+x.id+"/status",{status:"resolved"})}>ثبت حل‌شده</button>}</article>)}{!d.breaches.length&&<div>نقض تعهد ثبت‌شده‌ای وجود ندارد.</div>}</section>}
 </main>;}
