"use client";
import {useEffect,useState} from "react";
import styles from "./SmartCalendarWorkspace.module.css";
type Data={calendars:any[];holidays:any[];events:any[];deadlines:any[];plans:any[]};
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
const tabs=[["smart-calendar-1","تقویم کاری"],["smart-calendar-2","تعطیلات"],["smart-calendar-3","رویدادها"],["smart-calendar-4","سررسیدها"],["smart-calendar-5","برنامه‌ریزی"]];
export default function SmartCalendarWorkspace(){
 const [tab,setTab]=useState("smart-calendar-1"),[d,setD]=useState<Data>({calendars:[],holidays:[],events:[],deadlines:[],plans:[]}),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const [title,setTitle]=useState(""),[date,setDate]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[text,setText]=useState("");
 const load=async()=>{const r=await fetch(api+"/api/smart-calendar/overview",{credentials:"include"});const b=await r.json();if(!r.ok)throw Error(b.error||"خطا");setD(b)};
 useEffect(()=>{const p=new URLSearchParams(location.search);setTab(p.get("tab")||"smart-calendar-1");load().catch(e=>setError(e.message))},[]);
 const post=async(path:string,body:any)=>{setSaving(true);setError("");try{const r=await fetch(api+path,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error||"ثبت انجام نشد");setTitle("");setDate("");setStart("");setEnd("");setText("");await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const status=async(path:string,value:string)=>{const r=await fetch(api+path,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json","X-CSRF-Token":csrf()},body:JSON.stringify({status:value})});if(!r.ok){const b=await r.json().catch(()=>null);setError(b?.error||"تغییر وضعیت انجام نشد");return}load()};
 const form=(kind:string)=><div className={styles.form}>{<input placeholder="عنوان" value={title} onChange={e=>setTitle(e.target.value)}/>}<input placeholder={kind==="holiday"?"تاریخ YYYY-MM-DD":"تاریخ و زمان شروع"} value={date} onChange={e=>setDate(e.target.value)}/>{kind==="event"&&<input placeholder="تاریخ و زمان پایان" value={end} onChange={e=>setEnd(e.target.value)}/>} {kind==="plan"&&<input placeholder="ساعت شروع" value={start} onChange={e=>setStart(e.target.value)}/>}<input placeholder="توضیحات" value={text} onChange={e=>setText(e.target.value)}/><button disabled={saving} onClick={()=>kind==="holiday"?post("/api/smart-calendar/holidays",{date,title,notes:text}):kind==="event"?post("/api/smart-calendar/events",{title,startAt:date,endAt:end,description:text}):post("/api/smart-calendar/plans",{title,planDate:date,startTime:start,notes:text})}>ثبت واقعی</button></div>;
 return <main className={styles.wrap} dir="rtl"><header><div><span>منوی مرکزی سازمان · ۰۵</span><h1>تقویم هوشمند</h1><p>تقویم کاری، تعطیلات، رویدادها، سررسیدها و برنامه‌ریزی سازمانی</p></div><button onClick={()=>load()}>به‌روزرسانی</button></header><nav>{tabs.map(([k,t])=><a className={tab===k?styles.active:""} href={"/modules/?code=05-smart-calendar&tab="+k} key={k}>{t}</a>)}</nav>{error&&<div className={styles.error}>{error}</div>}
 {tab==="smart-calendar-1"&&<section className={styles.grid}><div className={styles.panel}><h2>تقویم کاری پیش‌فرض</h2>{d.calendars.map(c=><article key={c.id}><b>{c.title}</b><small>{c.timezone} · {c.day_start} تا {c.day_end}</small></article>)}{!d.calendars.length&&<p>تقویم کاری هنوز تعریف نشده است.</p>}<div className={styles.form}><input placeholder="شناسه تقویم" id="ck"/><input placeholder="عنوان تقویم" id="ct"/><button onClick={()=>post("/api/smart-calendar/calendars",{calendarKey:(document.getElementById("ck") as HTMLInputElement).value,title:(document.getElementById("ct") as HTMLInputElement).value,isDefault:d.calendars.length===0})}>ایجاد تقویم کاری</button></div></div><div className={styles.panel}><h2>وضعیت امروز</h2><div className={styles.stats}><strong>{d.events.length}<small>رویداد</small></strong><strong>{d.deadlines.filter(x=>x.status!=="completed").length}<small>سررسید باز</small></strong><strong>{d.plans.length}<small>برنامه</small></strong></div></div></section>}
 {tab==="smart-calendar-2"&&<section className={styles.panel}><h2>تعطیلات و استثناهای کاری</h2>{form("holiday")}{d.holidays.map(x=><article key={x.id}><b>{x.title}</b><span>{x.holiday_date} · {x.holiday_type}</span></article>)}</section>}
 {tab==="smart-calendar-3"&&<section className={styles.panel}><h2>رویدادها</h2>{form("event")}{d.events.map(x=><article key={x.id}><div><b>{x.title}</b><small>{new Date(x.start_at).toLocaleString("fa-IR")} تا {new Date(x.end_at).toLocaleString("fa-IR")}</small></div><button onClick={()=>status("/api/smart-calendar/events/"+x.id+"/status",x.status==="cancelled"?"scheduled":"cancelled")}>{x.status==="cancelled"?"فعال‌سازی":"لغو رویداد"}</button></article>)}</section>}
 {tab==="smart-calendar-4"&&<section className={styles.panel}><h2>سررسیدها</h2>{d.deadlines.map(x=><article key={x.id}><div><b>{x.title}</b><small>{new Date(x.due_at).toLocaleString("fa-IR")} · اولویت {x.priority}</small></div><button disabled={x.status==="completed"} onClick={()=>status("/api/smart-calendar/deadlines/"+x.id+"/status","completed")}>{x.status==="completed"?"انجام‌شده":"ثبت انجام‌شدن"}</button></article>)}</section>}
 {tab==="smart-calendar-5"&&<section className={styles.panel}><h2>برنامه‌ریزی</h2>{form("plan")}{d.plans.map(x=><article key={x.id}><div><b>{x.title}</b><small>{x.plan_date} · {x.start_time||"بدون ساعت"} · {x.status}</small></div></article>)}</section>}
 </main>;
}