"use client";
import {useEffect,useState} from "react";
import styles from "./TreasuryBankWorkspace.module.css";
type Bank={id:string;bank_name:string;account_title:string;account_number:string;iban?:string;currency:string;current_balance:string;status:string};
type Receipt={id:string;receipt_no:string;receipt_date:string;amount:string;payer_name:string;status:string;bank_name:string};
type Payment={id:string;payment_no:string;payment_date:string;amount:string;payee_name:string;status:string;bank_name:string};
type Tx={id:string;transaction_date:string;reference_no:string;description:string;amount:string;direction:string;reconciliation_status:string;bank_name:string};
type Cash={id:string;code:string;title:string;current_balance:string;status:string};
const api=(process.env.NEXT_PUBLIC_API_BASE_URL||process.env.NEXT_PUBLIC_API_URL||"").replace(/\/$/,"");
const csrf=()=>document.cookie.split(";").map(x=>x.trim()).find(x=>x.startsWith("naf_csrf="))?.slice(9)||"";
async function req(path:string,opt:RequestInit={}){const r=await fetch(api+path,{credentials:"include",...opt,headers:{"Content-Type":"application/json","X-CSRF-Token":csrf(),...(opt.headers||{})}});const b=await r.json().catch(()=>null);if(!r.ok)throw Error(b?.error||"عملیات ناموفق بود");return b}
export default function TreasuryBankWorkspace(){
 const [tab,setTab]=useState("accounts"),[banks,setBanks]=useState<Bank[]>([]),[receipts,setReceipts]=useState<Receipt[]>([]),[payments,setPayments]=useState<Payment[]>([]),[tx,setTx]=useState<Tx[]>([]),[cash,setCash]=useState<Cash[]>([]),[error,setError]=useState(""),[saving,setSaving]=useState(false);
 const today=new Date().toISOString().slice(0,10);
 const [bank,setBank]=useState({bankName:"",accountTitle:"",accountNumber:"",iban:"",accountType:"current",branchName:"",openingBalance:"0"});
 const [receipt,setReceipt]=useState({bankAccountId:"",receiptNo:"",receiptDate:today,amount:"",payerName:"",referenceNo:"",method:"bank_transfer",description:""});
 const [payment,setPayment]=useState({bankAccountId:"",paymentNo:"",paymentDate:today,amount:"",payeeName:"",referenceNo:"",method:"bank_transfer",description:""});
 const [cashForm,setCashForm]=useState({code:"",title:"",openingBalance:"0",maxBalance:""});
 const [movement,setMovement]=useState({cashboxId:"",movementNo:"",movementDate:today,amount:"",direction:"in",description:""});
 const [recon,setRecon]=useState({bankAccountId:"",transactionDate:today,referenceNo:"",description:"",amount:"",direction:"credit",statementBalance:""});
 const load=async()=>{try{setError("");const x=await req("/api/treasury-bank/overview");setBanks(x.banks||[]);setReceipts(x.receipts||[]);setPayments(x.payments||[]);setTx(x.transactions||[]);setCash(x.cashboxes||[]);if(!receipt.bankAccountId&&x.banks?.[0])setReceipt(v=>({...v,bankAccountId:x.banks[0].id}));if(!payment.bankAccountId&&x.banks?.[0])setPayment(v=>({...v,bankAccountId:x.banks[0].id}));}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 useEffect(()=>{const q=new URLSearchParams(location.search).get("tab");const m:any={"treasury-bank-1":"accounts","treasury-bank-2":"receipts","treasury-bank-3":"payments","treasury-bank-4":"reconciliation","treasury-bank-5":"cash"};if(q&&m[q])setTab(m[q]);load()},[]);
 const post=async(path:string,data:any)=>{setSaving(true);try{await req(path,{method:"POST",body:JSON.stringify(data)});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setSaving(false)}};
 const receiptStatus=async(id:string,status:string)=>{try{await req("/api/treasury-bank/receipts/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 const paymentStatus=async(id:string,status:string)=>{try{await req("/api/treasury-bank/payments/"+id+"/status",{method:"PATCH",body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}};
 const tabs=[["accounts","حساب‌های بانکی"],["receipts","دریافت‌ها"],["payments","پرداخت‌ها"],["reconciliation","مغایرت بانکی"],["cash","تنخواه"]];
 return <main className={styles.workspace} dir="rtl"><header className={styles.header}><div><span>هسته خزانه</span><h1>خزانه و بانک</h1><p>کنترل حساب‌های بانکی، جریان دریافت و پرداخت، مغایرت‌گیری و تنخواه با ثبت واقعی.</p></div><div className={styles.metric}>{banks.length} حساب بانکی</div></header>{error&&<div className={styles.error}>{error}</div>}<nav className={styles.tabs}>{tabs.map(([k,t])=><button key={k} className={tab===k?styles.active:""} onClick={()=>setTab(k)}>{t}</button>)}</nav>
 {tab==="accounts"&&<section className={styles.grid}><article className={styles.panel}><h2>افزودن حساب بانکی</h2><div className={styles.form}><label>نام بانک<input value={bank.bankName} onChange={e=>setBank({...bank,bankName:e.target.value})}/></label><label>عنوان حساب<input value={bank.accountTitle} onChange={e=>setBank({...bank,accountTitle:e.target.value})}/></label><label>شماره حساب<input value={bank.accountNumber} onChange={e=>setBank({...bank,accountNumber:e.target.value})}/></label><label>شبا<input value={bank.iban} onChange={e=>setBank({...bank,iban:e.target.value})}/></label><label>نوع حساب<select value={bank.accountType} onChange={e=>setBank({...bank,accountType:e.target.value})}><option value="current">جاری</option><option value="savings">پس‌انداز</option><option value="deposit">سپرده</option><option value="card">کارت</option></select></label><label>مانده افتتاحیه<input type="number" value={bank.openingBalance} onChange={e=>setBank({...bank,openingBalance:e.target.value})}/></label></div><button className={styles.primary} disabled={saving} onClick={()=>post("/api/treasury-bank/accounts",bank)}>ثبت حساب</button></article><article className={styles.panel}><h2>حساب‌های سازمان</h2>{banks.map(b=><div className={styles.card} key={b.id}><div><strong>{b.bank_name} · {b.account_title}</strong><small>{b.account_number} · {b.status}</small></div><b>{Number(b.current_balance).toLocaleString("fa-IR")} {b.currency}</b></div>)}</article></section>}
 {tab==="receipts"&&<section className={styles.grid}><article className={styles.panel}><h2>ثبت دریافت</h2><div className={styles.form}><label>حساب بانکی<select value={receipt.bankAccountId} onChange={e=>setReceipt({...receipt,bankAccountId:e.target.value})}>{banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} · {b.account_title}</option>)}</select></label><label>شماره دریافت<input value={receipt.receiptNo} onChange={e=>setReceipt({...receipt,receiptNo:e.target.value})}/></label><label>تاریخ<input type="date" value={receipt.receiptDate} onChange={e=>setReceipt({...receipt,receiptDate:e.target.value})}/></label><label>مبلغ<input type="number" value={receipt.amount} onChange={e=>setReceipt({...receipt,amount:e.target.value})}/></label><label>پرداخت‌کننده<input value={receipt.payerName} onChange={e=>setReceipt({...receipt,payerName:e.target.value})}/></label><label>مرجع<input value={receipt.referenceNo} onChange={e=>setReceipt({...receipt,referenceNo:e.target.value})}/></label></div><button className={styles.primary} onClick={()=>post("/api/treasury-bank/receipts",receipt)}>ثبت دریافت</button></article><article className={styles.panel}><h2>چرخه دریافت</h2>{receipts.map(x=><div className={styles.card} key={x.id}><div><strong>{x.receipt_no} · {x.payer_name}</strong><small>{x.receipt_date} · {x.bank_name} · {x.status}</small></div><div className={styles.actions}>{x.status==="pending"&&<><button onClick={()=>receiptStatus(x.id,"confirmed")}>تأیید</button><button onClick={()=>receiptStatus(x.id,"cancelled")}>لغو</button></>}</div><b>{Number(x.amount).toLocaleString("fa-IR")}</b></div>)}</article></section>}
 {tab==="payments"&&<section className={styles.grid}><article className={styles.panel}><h2>درخواست پرداخت</h2><div className={styles.form}><label>حساب بانکی<select value={payment.bankAccountId} onChange={e=>setPayment({...payment,bankAccountId:e.target.value})}>{banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} · {b.account_title}</option>)}</select></label><label>شماره پرداخت<input value={payment.paymentNo} onChange={e=>setPayment({...payment,paymentNo:e.target.value})}/></label><label>تاریخ<input type="date" value={payment.paymentDate} onChange={e=>setPayment({...payment,paymentDate:e.target.value})}/></label><label>مبلغ<input type="number" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>دریافت‌کننده<input value={payment.payeeName} onChange={e=>setPayment({...payment,payeeName:e.target.value})}/></label><label>مرجع<input value={payment.referenceNo} onChange={e=>setPayment({...payment,referenceNo:e.target.value})}/></label></div><button className={styles.primary} onClick={()=>post("/api/treasury-bank/payments",payment)}>ثبت درخواست</button></article><article className={styles.panel}><h2>گردش پرداخت</h2>{payments.map(x=><div className={styles.card} key={x.id}><div><strong>{x.payment_no} · {x.payee_name}</strong><small>{x.payment_date} · {x.bank_name} · {x.status}</small></div><div className={styles.actions}>{x.status==="pending"&&<button onClick={()=>paymentStatus(x.id,"approved")}>تأیید</button>}{x.status==="approved"&&<button onClick={()=>paymentStatus(x.id,"paid")}>پرداخت قطعی</button>}{["pending","approved"].includes(x.status)&&<button onClick={()=>paymentStatus(x.id,"cancelled")}>لغو</button>}</div><b>{Number(x.amount).toLocaleString("fa-IR")}</b></div>)}</article></section>}
 {tab==="reconciliation"&&<section className={styles.grid}><article className={styles.panel}><h2>ثبت گردش صورت‌حساب</h2><div className={styles.form}><label>حساب بانکی<select value={recon.bankAccountId} onChange={e=>setRecon({...recon,bankAccountId:e.target.value})}>{banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} · {b.account_title}</option>)}</select></label><label>تاریخ<input type="date" value={recon.transactionDate} onChange={e=>setRecon({...recon,transactionDate:e.target.value})}/></label><label>مرجع<input value={recon.referenceNo} onChange={e=>setRecon({...recon,referenceNo:e.target.value})}/></label><label>مبلغ<input type="number" value={recon.amount} onChange={e=>setRecon({...recon,amount:e.target.value})}/></label><label>نوع<select value={recon.direction} onChange={e=>setRecon({...recon,direction:e.target.value})}><option value="credit">بستانکار</option><option value="debit">بدهکار</option></select></label><label className={styles.full}>شرح<input value={recon.description} onChange={e=>setRecon({...recon,description:e.target.value})}/></label></div><button className={styles.primary} onClick={()=>post("/api/treasury-bank/transactions",recon)}>ثبت تراکنش</button></article><article className={styles.panel}><h2>اقلام مغایرت</h2>{tx.map(x=><div className={styles.card} key={x.id}><div><strong>{x.reference_no||"بدون مرجع"} · {x.bank_name}</strong><small>{x.transaction_date} · {x.description||"بدون شرح"} · {x.reconciliation_status}</small></div><div className={styles.actions}>{x.reconciliation_status!=="matched"&&<button onClick={async()=>{await req("/api/treasury-bank/transactions/"+x.id+"/reconcile",{method:"PATCH",body:JSON.stringify({status:"matched"})});load()}}>تطبیق</button>}{x.reconciliation_status==="unmatched"&&<button onClick={async()=>{await req("/api/treasury-bank/transactions/"+x.id+"/reconcile",{method:"PATCH",body:JSON.stringify({status:"ignored"})});load()}}>نادیده</button>}</div><b>{Number(x.amount).toLocaleString("fa-IR")}</b></div>)}</article></section>}
 {tab==="cash"&&<section className={styles.grid}><article className={styles.panel}><h2>تعریف تنخواه</h2><div className={styles.form}><label>کد<input value={cashForm.code} onChange={e=>setCashForm({...cashForm,code:e.target.value})}/></label><label>عنوان<input value={cashForm.title} onChange={e=>setCashForm({...cashForm,title:e.target.value})}/></label><label>موجودی افتتاحیه<input type="number" value={cashForm.openingBalance} onChange={e=>setCashForm({...cashForm,openingBalance:e.target.value})}/></label><label>سقف تنخواه<input type="number" value={cashForm.maxBalance} onChange={e=>setCashForm({...cashForm,maxBalance:e.target.value})}/></label></div><button className={styles.primary} onClick={()=>post("/api/treasury-bank/cashboxes",cashForm)}>ایجاد تنخواه</button><h3>ثبت گردش تنخواه</h3><div className={styles.form}><label>تنخواه<select value={movement.cashboxId} onChange={e=>setMovement({...movement,cashboxId:e.target.value})}>{cash.map(c=><option key={c.id} value={c.id}>{c.code} · {c.title}</option>)}</select></label><label>تاریخ<input type="date" value={movement.movementDate} onChange={e=>setMovement({...movement,movementDate:e.target.value})}/></label><label>مبلغ<input type="number" value={movement.amount} onChange={e=>setMovement({...movement,amount:e.target.value})}/></label><label>نوع<select value={movement.direction} onChange={e=>setMovement({...movement,direction:e.target.value})}><option value="in">دریافت</option><option value="out">پرداخت</option></select></label></div><button className={styles.secondary} onClick={()=>post("/api/treasury-bank/cashboxes/"+movement.cashboxId+"/movements",movement)}>ثبت گردش</button></article><article className={styles.panel}><h2>تنخواه‌های فعال</h2>{cash.map(c=><div className={styles.card} key={c.id}><div><strong>{c.code} · {c.title}</strong><small>{c.status}</small></div><b>{Number(c.current_balance).toLocaleString("fa-IR")}</b></div>)}</article></section>}</main>
}