import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "دیجی‌پی | پیش‌نمایش قالب خدمات مالی دیجیتال",
  description: "پیش‌نمایش مستقل و راست‌چین خدمات پرداخت، اعتبار خرید و راهکارهای پذیرندگان. شرایط مالی باید از سرویس‌های رسمی و تأییدشده دریافت شوند.",
  robots: { index: false, follow: false }
};

const services = [
  { icon: "↗", title: "پرداخت‌های روزمره", text: "مسیرهای پرداخت را با تجربه‌ای روشن، ساده و سازگار با موبایل دنبال کنید.", href: "#payments" },
  { icon: "▤", title: "اعتبار خرید", text: "شرایط و مدارک را پیش از درخواست بررسی کنید؛ نمایش پیشنهاد به سرویس تأییدشده وابسته است.", href: "#credit" },
  { icon: "▦", title: "راهکار پذیرندگان", text: "اطلاعات خدمات کسب‌وکار و مسیرهای پذیرندگی را در یک نقطه پیدا کنید.", href: "#business" },
  { icon: "♡", title: "خدمات و پشتیبانی", text: "راهنمایی، مدارک و راه‌های ارتباطی را بدون ادعاهای مبهم پیدا کنید.", href: "#support" }
];

export default function DigipayTemplatePreview() {
  return (
    <main dir="rtl" className="dp-shell">
      <style>{`
        .dp-shell{--dp-ink:#17233b;--dp-muted:#64748b;--dp-line:#e4eaf2;--dp-blue:#155eef;--dp-teal:#14b8a6;min-height:100vh;background:#f7f9fc;color:var(--dp-ink);font-family:Vazirmatn,IRANSansX,system-ui,sans-serif}
        .dp-shell *{box-sizing:border-box}.dp-shell a{text-decoration:none}
        .dp-wrap{width:min(1160px,calc(100% - 40px));margin-inline:auto}
        .dp-top{background:#12213d;color:#dce8ff;font-size:12px}.dp-top .dp-wrap{min-height:38px;display:flex;align-items:center;justify-content:space-between;gap:16px}
        .dp-header{background:#fff;border-bottom:1px solid var(--dp-line)}.dp-header-row{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:24px}
        .dp-brand{display:flex;align-items:center;gap:12px;color:var(--dp-ink)}.dp-mark{width:44px;height:44px;display:grid;place-items:center;border-radius:15px;background:linear-gradient(145deg,var(--dp-blue),#2848a7);color:white;font-size:23px;font-weight:900;box-shadow:0 8px 20px #155eef25}.dp-brand b,.dp-brand small{display:block}.dp-brand b{font-size:23px;letter-spacing:-.7px}.dp-brand small{margin-top:2px;color:var(--dp-muted);font-size:10px}
        .dp-nav{display:flex;align-items:center;gap:24px;flex-wrap:wrap}.dp-nav a{color:#46556c;font-size:12px;font-weight:650}.dp-actions{display:flex;align-items:center;gap:9px}.dp-btn{display:inline-flex;align-items:center;justify-content:center;min-height:42px;padding:0 17px;border-radius:12px;font-size:12px;font-weight:800}.dp-btn-ghost{border:1px solid #d7e1ef;color:#263752;background:white}.dp-btn-primary{background:var(--dp-blue);color:white;box-shadow:0 7px 18px #155eef28}
        .dp-hero{position:relative;overflow:hidden;margin-top:28px;border-radius:28px;background:linear-gradient(115deg,#142342 0%,#1d3e76 56%,#087f8c 100%);color:#fff}.dp-hero:before,.dp-hero:after{content:"";position:absolute;border:1px solid #ffffff20;border-radius:50%;pointer-events:none}.dp-hero:before{width:460px;height:460px;left:-120px;top:-250px}.dp-hero:after{width:300px;height:300px;left:80px;bottom:-220px}
        .dp-hero-grid{position:relative;display:grid;grid-template-columns:1.15fr .85fr;align-items:center;gap:30px;padding:clamp(28px,6vw,76px)}.dp-eyebrow{display:inline-flex;align-items:center;gap:9px;color:#9cf2e4;font-size:12px;font-weight:800}.dp-dot{width:7px;height:7px;border-radius:50%;background:var(--dp-teal);box-shadow:0 0 0 5px #14b8a626}.dp-hero h1{max-width:650px;margin:18px 0;font-size:clamp(32px,4.3vw,54px);line-height:1.5;letter-spacing:-1.2px;font-weight:900}.dp-hero h1 span{color:#80f0df}.dp-hero p{max-width:610px;color:#d5e1f5;font-size:14px;line-height:2.1}.dp-hero-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:26px}.dp-hero .dp-btn-primary{background:#fff;color:#18366b;box-shadow:none}.dp-hero .dp-btn-ghost{border-color:#ffffff50;background:#ffffff0c;color:white}.dp-note{margin-top:18px;color:#b8c9e4;font-size:10px;line-height:1.9}
        .dp-visual{position:relative;display:grid;place-items:center;min-height:300px}.dp-orbit{position:absolute;width:min(100%,310px);aspect-ratio:1;border:1px solid #ffffff27;border-radius:50%}.dp-orbit:after{content:"";position:absolute;inset:30px;border:1px solid #ffffff20;border-radius:50%}.dp-card{position:relative;width:min(260px,90%);padding:23px;border:1px solid #ffffff55;border-radius:24px;background:linear-gradient(145deg,#ffffff2c,#ffffff0b);box-shadow:0 30px 70px #07152d55;backdrop-filter:blur(12px);transform:rotate(-3deg)}.dp-card-top{display:flex;justify-content:space-between;align-items:center;color:#e6f1ff;font-size:10px}.dp-card-icon{display:grid;place-items:center;width:100px;height:100px;margin:26px auto 18px;border-radius:29px;background:linear-gradient(145deg,#40dfd0,#1683e9);box-shadow:0 16px 30px #07152d44;font-size:48px;font-weight:900}.dp-card b,.dp-card small{display:block;text-align:center}.dp-card b{font-size:15px}.dp-card small{margin-top:7px;color:#d2e1f6;font-size:10px}
        .dp-services{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:24px auto 64px}.dp-service{padding:23px;border:1px solid var(--dp-line);border-radius:19px;background:#fff;transition:transform .18s,border-color .18s}.dp-service:hover{transform:translateY(-3px);border-color:#b8caff}.dp-service-icon{display:grid;place-items:center;width:45px;height:45px;border-radius:14px;background:#eaf1ff;color:var(--dp-blue);font-size:22px}.dp-service h2{margin:18px 0 9px;font-size:16px}.dp-service p{min-height:68px;margin:0;color:var(--dp-muted);font-size:12px;line-height:2}.dp-service a{display:inline-flex;align-items:center;gap:8px;margin-top:15px;color:var(--dp-blue);font-size:12px;font-weight:800}
        .dp-section{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:0 auto 24px}.dp-info{padding:clamp(24px,4vw,42px);border:1px solid var(--dp-line);border-radius:22px;background:#fff}.dp-info h2{margin:0 0 12px;font-size:23px}.dp-info p{margin:0;color:var(--dp-muted);font-size:13px;line-height:2.1}.dp-info ul{padding-right:19px;color:#42516a;font-size:12px;line-height:2.2}.dp-info .dp-btn{margin-top:12px}
        .dp-footer{margin-top:60px;background:#12213d;color:#d7e4f8}.dp-footer-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:30px;padding:40px 0}.dp-footer b{display:block;margin-bottom:12px;color:#fff}.dp-footer p,.dp-footer a{color:#b7c7df;font-size:12px;line-height:2}.dp-footer-links{display:grid;gap:6px}.dp-legal{padding:16px 0;border-top:1px solid #ffffff1b;color:#9eb1cf;font-size:10px;line-height:1.9}
        @media(max-width:900px){.dp-nav{display:none}.dp-hero-grid{grid-template-columns:1fr .7fr}.dp-services{grid-template-columns:repeat(2,minmax(0,1fr))}.dp-visual{min-height:240px}.dp-card{padding:17px}.dp-card-icon{width:80px;height:80px;margin:18px auto;font-size:38px}}
        @media(max-width:620px){.dp-wrap{width:calc(100% - 28px)}.dp-top .dp-wrap{font-size:10px}.dp-header-row{min-height:68px;gap:8px}.dp-mark{width:38px;height:38px;border-radius:12px}.dp-brand b{font-size:19px}.dp-brand small{font-size:9px}.dp-actions{gap:6px}.dp-btn{min-height:39px;padding:0 11px;font-size:11px}.dp-actions .dp-btn-ghost{display:none}.dp-hero{margin-top:14px;border-radius:21px}.dp-hero-grid{grid-template-columns:1fr;padding:27px 22px 22px;gap:5px}.dp-hero h1{font-size:32px;line-height:1.55}.dp-hero p{font-size:12px}.dp-visual{min-height:205px}.dp-orbit{width:200px}.dp-card{width:190px;padding:13px;border-radius:18px}.dp-card-icon{width:62px;height:62px;border-radius:19px;margin:13px auto;font-size:30px}.dp-card b{font-size:12px}.dp-services{gap:9px;margin:14px auto 42px}.dp-service{padding:15px;border-radius:15px}.dp-service h2{font-size:14px}.dp-service p{font-size:11px;min-height:90px}.dp-section{grid-template-columns:1fr;gap:12px}.dp-info h2{font-size:20px}.dp-footer-grid{grid-template-columns:1fr;gap:18px;padding:28px 0}.dp-footer-grid>div:not(:first-child){padding-top:14px;border-top:1px solid #ffffff1b}}
        @media(prefers-reduced-motion:reduce){.dp-service{transition:none}.dp-service:hover{transform:none}}
      `}</style>
      <div className="dp-top"><div className="dp-wrap"><span>خدمات مالی دیجیتال با اطلاعات روشن</span><span>پیش‌نمایش قالب مستقل · بدون پیشنهاد مالی ساختگی</span></div></div>
      <header className="dp-header"><div className="dp-wrap dp-header-row">
        <Link href="/store/digipay" className="dp-brand" aria-label="صفحه اصلی پیش‌نمایش دیجی‌پی"><span className="dp-mark">د</span><span><b>دیجی‌پی</b><small>پرداخت و خدمات مالی دیجیتال</small></span></Link>
        <nav className="dp-nav" aria-label="ناوبری خدمات"><a href="#payments">پرداخت</a><a href="#credit">اعتبار خرید</a><a href="#business">پذیرندگان</a><a href="#support">راهنما و پشتیبانی</a></nav>
        <div className="dp-actions"><Link className="dp-btn dp-btn-ghost" href="/register?brand=digipay">ثبت‌نام</Link><Link className="dp-btn dp-btn-primary" href="/login?brand=digipay">ورود به حساب</Link></div>
      </div></header>
      <div className="dp-wrap">
        <section className="dp-hero">
          <div className="dp-hero-grid">
            <div><span className="dp-eyebrow"><i className="dp-dot" />خدمات مالی، با مسیر روشن</span><h1>پرداخت ساده‌تر،<br/><span>تصمیم آگاهانه‌تر.</span></h1><p>مسیرهای پرداخت، خدمات اعتباری و راهکارهای پذیرندگان را در یک تجربه منظم دنبال کنید. جزئیات مالی و شرایط هر خدمت باید از سرویس رسمی و تأییدشده نمایش داده شود.</p><div className="dp-hero-actions"><Link className="dp-btn dp-btn-primary" href="/login?brand=digipay">ورود و ادامه <span aria-hidden="true">←</span></Link><a className="dp-btn dp-btn-ghost" href="#services">مشاهده خدمات</a></div><div className="dp-note">این صفحه پیش‌نمایش طراحی است. نرخ، سقف اعتبار، کارمزد یا زمان تأیید بدون اتصال به سرویس رسمی نمایش داده نمی‌شود.</div></div>
            <div className="dp-visual" aria-hidden="true"><div className="dp-orbit"/><div className="dp-card"><div className="dp-card-top"><span>DIGITAL SERVICES</span><span>● ● ●</span></div><div className="dp-card-icon">د</div><b>پرداخت و اعتبار</b><small>یک تجربه دیجیتال، چند مسیر روشن</small></div></div>
          </div>
        </section>
        <section id="services" className="dp-services" aria-label="دسته‌بندی خدمات">{services.map(service=><article key={service.title} className="dp-service"><span className="dp-service-icon" aria-hidden="true">{service.icon}</span><h2>{service.title}</h2><p>{service.text}</p><a href={service.href}>اطلاعات بیشتر <span aria-hidden="true">←</span></a></article>)}</section>
        <section className="dp-section">
          <article className="dp-info" id="payments"><h2>پرداخت، بدون پیچیدگی اضافه</h2><p>برای تجربه پرداخت، ابتدا وارد حساب شوید و فقط روش‌هایی را انتخاب کنید که در حساب و منطقه شما فعال هستند. وضعیت پرداخت باید از درگاه واقعی دریافت شود.</p><ul><li>نمایش وضعیت بر اساس پاسخ سرویس پرداخت</li><li>پیگیری شفاف تراکنش و رسید</li><li>عدم نمایش تراکنش یا مانده ساختگی</li></ul><Link className="dp-btn dp-btn-primary" href="/login?brand=digipay">ورود برای ادامه</Link></article>
          <article className="dp-info" id="credit"><h2>اعتبار خرید و خدمات اعتباری</h2><p>پیش از ارسال درخواست، شرایط، مدارک، هزینه‌ها و ضوابط بازپرداخت باید قابل مشاهده باشند. این پیش‌نمایش هیچ نرخ یا سقف اعتباری را از خود تولید نمی‌کند.</p><ul><li>شرایط و مدارک مصوب</li><li>نمایش هزینه‌ها پیش از تأیید نهایی</li><li>پیگیری درخواست فقط از سامانه واقعی</li></ul><Link className="dp-btn dp-btn-ghost" href="/pay/apply">مسیر درخواست اعتبار</Link></article>
          <article className="dp-info" id="business"><h2>راهکارهای پذیرندگان</h2><p>کسب‌وکارها به اطلاعات روشن درباره پذیرندگی، تسویه و پشتیبانی نیاز دارند. شرایط همکاری و زمان‌بندی تسویه باید از قرارداد و سرویس مصوب خوانده شود.</p><ul><li>ثبت درخواست پذیرندگی از مسیر واقعی</li><li>شفافیت قرارداد و کارمزدها</li><li>گزارش‌های متصل به تراکنش‌های ثبت‌شده</li></ul><Link className="dp-btn dp-btn-ghost" href="/register?brand=digipay">شروع ثبت‌نام</Link></article>
          <article className="dp-info" id="support"><h2>پشتیبانی و اعتماد</h2><p>دسترسی به راهنما، شرایط استفاده، حریم خصوصی و مسیر پیگیری از اجزای اصلی خدمات مالی است. اطلاعات تماس نهایی باید از تنظیمات تأییدشده کسب‌وکار بیاید.</p><ul><li>شرایط و حریم خصوصی</li><li>مسیر پیگیری درخواست و پرداخت</li><li>اطلاعات تماس تأییدشده</li></ul><Link className="dp-btn dp-btn-ghost" href="/login?brand=digipay">ورود به حساب</Link></article>
        </section>
      </div>
      <footer className="dp-footer"><div className="dp-wrap dp-footer-grid"><div><b>دیجی‌پی · پیش‌نمایش قالب</b><p>تجربه راست‌چین و واکنش‌گرا برای خدمات مالی دیجیتال. هویت بصری این نمونه مستقل است و به معنی وابستگی یا تأیید رسمی برند نیست.</p></div><div><b>خدمات</b><div className="dp-footer-links"><a href="#payments">پرداخت</a><a href="#credit">اعتبار خرید</a><a href="#business">راهکار پذیرندگان</a></div></div><div><b>حساب و راهنما</b><div className="dp-footer-links"><Link href="/login?brand=digipay">ورود</Link><Link href="/register?brand=digipay">ثبت‌نام</Link><a href="#support">پشتیبانی</a></div></div></div><div className="dp-wrap dp-legal">پیش‌نمایش طراحی؛ نمایش خدمات واقعی، هزینه‌ها و شرایط مالی منوط به اتصال به سرویس رسمی و انتشار محتوای تأییدشده است.</div></footer>
    </main>
  );
}
