import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "نگار آذین فدک | پیش‌نمایش پورتال سازمانی",
  description: "قالب سازمانی راست‌چین برای معرفی پلتفرم‌ها، خدمات و حاکمیت فرایندها.",
  robots: { index: false, follow: false }
};

const pillars = [
  { icon: "◈", title: "فرایندهای یکپارچه", text: "معرفی مسیرهای کاری و خدمات سازمانی در یک نقطه مشخص." },
  { icon: "⌘", title: "حاکمیت و دسترسی", text: "توضیح نقش‌ها، مسئولیت‌ها و کنترل دسترسی بدون ادعای امنیت تأییدنشده." },
  { icon: "▤", title: "اسناد و اطلاعات", text: "دسترسی ساختاریافته به اسناد و داده‌های ثبت‌شده در سامانه‌های متصل." }
];

export default function NafCorporatePreview() {
  return <main dir="rtl" className="naf-page">
    <style>{`
      .naf-page{--naf-ink:#182337;--naf-muted:#637084;--naf-line:#e1e7ef;--naf-blue:#2349a5;--naf-gold:#d9b66f;min-height:100vh;background:#f7f8fb;color:var(--naf-ink);font-family:Vazirmatn,IRANSansX,system-ui,sans-serif}
      .naf-page *{box-sizing:border-box}.naf-page a{text-decoration:none}.naf-wrap{width:min(1160px,calc(100% - 40px));margin:auto}
      .naf-top{background:#17243b;color:#d8e3f8;font-size:11px}.naf-top .naf-wrap{min-height:36px;display:flex;align-items:center;justify-content:space-between;gap:12px}
      .naf-header{background:#fff;border-bottom:1px solid var(--naf-line)}.naf-header-row{min-height:82px;display:flex;align-items:center;justify-content:space-between;gap:22px}.naf-brand{display:flex;align-items:center;gap:12px;color:var(--naf-ink)}.naf-mark{display:grid;place-items:center;width:46px;height:46px;border-radius:15px;background:linear-gradient(145deg,#2b4fa7,#142a61);color:#fff;font-size:22px;font-weight:900}.naf-brand b,.naf-brand small{display:block}.naf-brand b{font-size:18px}.naf-brand small{margin-top:4px;color:var(--naf-muted);font-size:10px}.naf-nav{display:flex;gap:22px;flex-wrap:wrap}.naf-nav a{font-size:12px;color:#526078;font-weight:700}.naf-btn{display:inline-flex;align-items:center;justify-content:center;min-height:43px;padding:0 17px;border-radius:12px;font-size:12px;font-weight:800}.naf-primary{background:var(--naf-blue);color:#fff}.naf-secondary{border:1px solid #d6dfed;color:var(--naf-ink);background:#fff}
      .naf-hero{position:relative;overflow:hidden;margin-top:28px;border-radius:28px;background:linear-gradient(118deg,#17243d 0%,#203e7e 70%,#3155a3 100%);color:#fff}.naf-hero:after{content:"";position:absolute;width:520px;height:520px;left:-180px;top:-330px;border:1px solid #ffffff20;border-radius:50%;box-shadow:0 0 0 45px #ffffff08,0 0 0 95px #ffffff05}.naf-hero-inner{position:relative;z-index:1;padding:clamp(30px,6vw,76px);max-width:900px}.naf-eyebrow{display:inline-flex;align-items:center;gap:10px;color:#f1d99c;font-size:12px;font-weight:800}.naf-eyebrow i{width:7px;height:7px;border-radius:50%;background:var(--naf-gold)}.naf-hero h1{font-size:clamp(32px,4.8vw,56px);line-height:1.65;letter-spacing:-1px;margin:18px 0}.naf-hero h1 em{font-style:normal;color:#f1d99c}.naf-hero p{max-width:720px;color:#d5e0f4;font-size:14px;line-height:2.2}.naf-actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:26px}.naf-hero .naf-primary{background:var(--naf-gold);color:#17243b}.naf-hero .naf-secondary{background:#ffffff0b;border-color:#ffffff55;color:#fff}.naf-note{margin-top:18px;color:#b8c8e4;font-size:10px;line-height:2}
      .naf-intro{text-align:center;margin:58px 0 24px}.naf-intro small{font-size:11px;font-weight:800;color:var(--naf-blue)}.naf-intro h2{margin:9px 0;font-size:clamp(23px,3vw,32px)}.naf-intro p{max-width:700px;margin:auto;color:var(--naf-muted);font-size:12px;line-height:2.1}
      .naf-pillars{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.naf-pillar{padding:26px;border:1px solid var(--naf-line);border-radius:20px;background:#fff}.naf-pillar i{display:grid;place-items:center;width:46px;height:46px;border-radius:14px;background:#edf1fc;color:var(--naf-blue);font-size:23px;font-style:normal}.naf-pillar h3{margin:19px 0 9px;font-size:17px}.naf-pillar p{margin:0;color:var(--naf-muted);font-size:12px;line-height:2}
      .naf-bottom{display:grid;grid-template-columns:1fr auto;align-items:center;gap:20px;margin:28px 0 64px;padding:30px;border:1px solid #dbe2f2;border-radius:22px;background:#fff}.naf-bottom h2{font-size:20px;margin:0 0 8px}.naf-bottom p{margin:0;color:var(--naf-muted);font-size:12px;line-height:2}
      .naf-footer{background:#17243b;color:#d9e4f8}.naf-footer-grid{display:grid;grid-template-columns:1.5fr 1fr 1fr;gap:28px;padding:38px 0}.naf-footer b{display:block;color:#fff;margin-bottom:12px}.naf-footer p,.naf-footer a{color:#b8c7df;font-size:12px;line-height:2}.naf-footer-links{display:grid;gap:6px}.naf-legal{padding:15px 0;border-top:1px solid #ffffff1b;color:#a7b8d3;font-size:10px;line-height:1.9}
      @media(max-width:800px){.naf-nav{display:none}.naf-pillars{grid-template-columns:1fr}.naf-pillar{display:grid;grid-template-columns:50px 1fr;column-gap:16px}.naf-pillar i{grid-row:span 2}.naf-pillar h3{margin:0 0 5px}.naf-bottom{grid-template-columns:1fr}}
      @media(max-width:560px){.naf-wrap{width:calc(100% - 28px)}.naf-top{font-size:9px}.naf-header-row{min-height:70px;gap:8px}.naf-mark{width:38px;height:38px}.naf-brand b{font-size:15px}.naf-brand small{font-size:9px}.naf-header-row>.naf-btn{padding:0 10px;font-size:10px}.naf-hero{margin-top:14px;border-radius:21px}.naf-hero-inner{padding:28px 22px}.naf-hero h1{font-size:32px}.naf-hero p{font-size:12px}.naf-intro{margin-top:40px}.naf-pillar{padding:20px}.naf-bottom{padding:22px;margin-bottom:40px}.naf-bottom a{width:100%}.naf-footer-grid{grid-template-columns:1fr;gap:16px;padding:28px 0}.naf-footer-grid>div:not(:first-child){padding-top:14px;border-top:1px solid #ffffff1b}}
    `}</style>
    <div className="naf-top"><div className="naf-wrap"><span>پلتفرم بیزینس نگار آذین فدک ایران</span><span>پیش‌نمایش پورتال سازمانی</span></div></div>
    <header className="naf-header"><div className="naf-wrap naf-header-row"><Link href="/store/naf" className="naf-brand"><span className="naf-mark">ن</span><span><b>نگار آذین فدک</b><small>پلتفرم یکپارچه خدمات سازمانی</small></span></Link><nav className="naf-nav" aria-label="ناوبری سازمان"><a href="#platform">پلتفرم</a><a href="#services">خدمات سازمانی</a><a href="#governance">حاکمیت و امنیت</a></nav><Link className="naf-btn naf-primary" href="/login?brand=naf">ورود به مرکز مدیریت</Link></div></header>
    <div className="naf-wrap"><section className="naf-hero" id="platform"><div className="naf-hero-inner"><span className="naf-eyebrow"><i/>سامانه یکپارچه مدیریت کسب‌وکار</span><h1>یکپارچگی فرایندها،<br/><em>شفافیت در عملیات.</em></h1><p>پلتفرم بیزینس نگار آذین فدک ایران برای سامان‌دهی خدمات، اطلاعات و گردش‌کارهای سازمانی طراحی شده است. تجربه نهایی باید بر پایه قابلیت‌های فعال و دسترسی‌های واقعی هر کاربر نمایش داده شود.</p><div className="naf-actions"><Link className="naf-btn naf-primary" href="/login?brand=naf">ورود به مرکز مدیریت ←</Link><a className="naf-btn naf-secondary" href="#services">مشاهده حوزه‌های خدمات</a></div><div className="naf-note">این صفحه پیش‌نمایش رابط کاربری است؛ آمار عملکرد، گواهی‌ها و ادعاهای انطباق فقط پس از تأیید مستندات منتشر می‌شوند.</div></div></section>
    <section id="services"><div className="naf-intro"><small>معماری سازمانی</small><h2>خدمات در ساختاری روشن و قابل توسعه</h2><p>هر حوزه به سامانه عملیاتی و مجوزهای تعریف‌شده متصل می‌شود؛ این صفحه اطلاعات مالی یا آماری نمایشی تولید نمی‌کند.</p></div><div className="naf-pillars">{pillars.map(p=><article className="naf-pillar" key={p.title}><i aria-hidden="true">{p.icon}</i><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>
    <section className="naf-bottom" id="governance"><div><h2>دسترسی بر اساس نقش و مسئولیت</h2><p>ورود، مجوزها و عملیات حساس باید از هسته احراز هویت و کنترل دسترسی سامانه خوانده شوند. این پیش‌نمایش به‌تنهایی مجوزی ایجاد نمی‌کند.</p></div><Link className="naf-btn naf-primary" href="/login?brand=naf">ورود امن به سامانه</Link></section></div>
    <footer className="naf-footer"><div className="naf-wrap naf-footer-grid"><div><b>نگار آذین فدک ایران</b><p>پیش‌نمایش پورتال سازمانی برای معرفی سامانه‌ها و خدمات. محتوای رسمی و قابلیت‌های منتشرشده باید توسط سازمان تأیید شوند.</p></div><div><b>حوزه‌ها</b><div className="naf-footer-links"><a href="#platform">پلتفرم</a><a href="#services">خدمات</a></div></div><div><b>حساب و راهنما</b><div className="naf-footer-links"><Link href="/login?brand=naf">ورود</Link><Link href="/register?brand=naf">ثبت‌نام</Link></div></div></div><div className="naf-wrap naf-legal">پیش‌نمایش طراحی؛ دسترسی به بخش‌های سازمانی تابع احراز هویت و مجوزهای واقعی است.</div></footer>
  </main>;
}
