import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "وام‌سیتی | پیش‌نمایش خدمات اعتباری",
  description: "پیش‌نمایش قالب مستقل برای معرفی و پیگیری خدمات اعتباری؛ بدون نرخ، اقساط یا شرایط مالی ساختگی.",
  robots: { index: false, follow: false }
};

const stages = [
  ["۰۱", "بررسی شرایط", "شرایط احراز و مدارک موردنیاز را از اطلاعات رسمی محصول بررسی کنید."],
  ["۰۲", "ثبت درخواست", "اطلاعات فقط از مسیر احراز هویت و فرم متصل به سامانه واقعی ارسال می‌شود."],
  ["۰۳", "پیگیری وضعیت", "وضعیت درخواست باید از سرویس واقعی دریافت شود، نه از داده نمایشی."]
];

export default function VamcityTemplatePreview() {
  return <main dir="rtl" className="vc-page">
    <style>{`
      .vc-page{--vc-ink:#152d37;--vc-muted:#60737b;--vc-line:#dce8e8;--vc-green:#087f72;--vc-lime:#c9f36a;min-height:100vh;background:#f5f8f7;color:var(--vc-ink);font-family:Vazirmatn,IRANSansX,system-ui,sans-serif}
      .vc-page *{box-sizing:border-box}.vc-page a{text-decoration:none}.vc-wrap{width:min(1120px,calc(100% - 40px));margin:auto}
      .vc-top{background:#102f37;color:#cfe8e3;font-size:11px}.vc-top .vc-wrap{min-height:36px;display:flex;justify-content:space-between;align-items:center;gap:12px}
      .vc-header{background:#fff;border-bottom:1px solid var(--vc-line)}.vc-header-row{min-height:78px;display:flex;align-items:center;justify-content:space-between;gap:20px}.vc-brand{display:flex;align-items:center;gap:11px;color:var(--vc-ink)}.vc-mark{display:grid;place-items:center;width:43px;height:43px;border-radius:14px;background:var(--vc-green);color:white;font-size:22px;font-weight:900}.vc-brand b,.vc-brand small{display:block}.vc-brand b{font-size:21px;letter-spacing:.4px}.vc-brand small{margin-top:3px;color:var(--vc-muted);font-size:10px}.vc-nav{display:flex;gap:22px;flex-wrap:wrap}.vc-nav a{color:#4c646a;font-size:12px;font-weight:700}.vc-btn{display:inline-flex;align-items:center;justify-content:center;min-height:43px;padding:0 17px;border-radius:12px;font-size:12px;font-weight:800}.vc-primary{background:var(--vc-green);color:white}.vc-secondary{border:1px solid #d1dfdf;background:white;color:var(--vc-ink)}
      .vc-hero{position:relative;overflow:hidden;margin-top:28px;border-radius:28px;background:linear-gradient(125deg,#12333b,#075f5b 70%,#087f72);color:white}.vc-hero:after{content:"";position:absolute;width:420px;height:420px;left:-140px;bottom:-270px;border:1px solid #ffffff24;border-radius:50%;box-shadow:0 0 0 35px #ffffff08,0 0 0 75px #ffffff06}.vc-hero-grid{position:relative;z-index:1;display:grid;grid-template-columns:1.15fr .85fr;align-items:center;gap:34px;padding:clamp(28px,6vw,70px)}.vc-eyebrow{display:inline-flex;align-items:center;gap:9px;color:var(--vc-lime);font-size:12px;font-weight:800}.vc-eyebrow i{width:7px;height:7px;border-radius:50%;background:var(--vc-lime)}.vc-hero h1{font-size:clamp(32px,4.5vw,54px);line-height:1.55;letter-spacing:-1px;margin:18px 0}.vc-hero h1 em{font-style:normal;color:var(--vc-lime)}.vc-hero p{max-width:610px;color:#d1e7e2;font-size:14px;line-height:2.1}.vc-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:25px}.vc-hero .vc-primary{background:var(--vc-lime);color:#18372f}.vc-hero .vc-secondary{background:#ffffff0c;color:white;border-color:#ffffff55}.vc-disclaimer{font-size:10px!important;color:#b8d6d0!important;margin-top:18px}.vc-art{min-height:285px;display:grid;place-items:center;position:relative}.vc-ring{width:min(100%,290px);aspect-ratio:1;border:1px solid #ffffff35;border-radius:50%;display:grid;place-items:center}.vc-ring:before{content:"";position:absolute;width:220px;height:220px;border:1px solid #ffffff24;border-radius:50%}.vc-doc{position:relative;width:220px;padding:24px;border-radius:22px;background:#f8fff5;color:#183b38;box-shadow:0 28px 60px #082b2b55;transform:rotate(3deg)}.vc-doc small,.vc-doc strong,.vc-doc span{display:block}.vc-doc small{color:#648079;font-size:10px}.vc-doc strong{margin:24px 0 18px;font-size:18px}.vc-doc span{padding-top:13px;border-top:1px solid #dce9df;color:#60766f;font-size:10px;line-height:1.8}.vc-doc i{position:absolute;left:20px;top:20px;color:var(--vc-green);font-size:24px;font-style:normal}
      .vc-section-head{text-align:center;margin:58px 0 24px}.vc-section-head small{color:var(--vc-green);font-weight:800;font-size:11px}.vc-section-head h2{font-size:clamp(22px,3vw,32px);margin:9px 0}.vc-section-head p{max-width:650px;margin:auto;color:var(--vc-muted);font-size:12px;line-height:2}
      .vc-stages{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.vc-stage{padding:25px;border:1px solid var(--vc-line);border-radius:20px;background:white}.vc-stage i{display:grid;place-items:center;width:45px;height:45px;border-radius:14px;background:#e5f5ed;color:var(--vc-green);font-size:13px;font-weight:900;font-style:normal}.vc-stage h3{margin:20px 0 9px;font-size:17px}.vc-stage p{margin:0;color:var(--vc-muted);font-size:12px;line-height:2}
      .vc-trust{display:grid;grid-template-columns:1fr auto;align-items:center;gap:24px;margin:28px 0 64px;padding:30px;border:1px solid #d5e7d7;border-radius:22px;background:#edf7eb}.vc-trust h2{margin:0 0 9px;font-size:20px}.vc-trust p{margin:0;color:#506d60;font-size:12px;line-height:2}.vc-trust a{white-space:nowrap}
      .vc-footer{background:#102f37;color:#d6e7e3}.vc-footer-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:30px;padding:38px 0}.vc-footer b{display:block;margin-bottom:12px;color:white}.vc-footer p,.vc-footer a{color:#b5ceca;font-size:12px;line-height:2}.vc-footer-links{display:grid;gap:6px}.vc-legal{padding:15px 0;border-top:1px solid #ffffff1b;color:#a7c2bd;font-size:10px;line-height:1.9}
      @media(max-width:800px){.vc-nav{display:none}.vc-hero-grid{grid-template-columns:1fr .7fr}.vc-art{min-height:230px}.vc-doc{width:190px;padding:19px}.vc-doc strong{font-size:15px}.vc-stages{grid-template-columns:1fr}.vc-stage{display:grid;grid-template-columns:48px 1fr;column-gap:16px}.vc-stage i{grid-row:span 2}.vc-stage h3{margin:0 0 5px}.vc-trust{grid-template-columns:1fr}}
      @media(max-width:560px){.vc-wrap{width:calc(100% - 28px)}.vc-top{font-size:9px}.vc-header-row{min-height:68px}.vc-mark{width:37px;height:37px}.vc-brand b{font-size:18px}.vc-brand small{font-size:9px}.vc-header-row>.vc-btn{padding:0 11px;font-size:10px}.vc-hero{margin-top:14px;border-radius:21px}.vc-hero-grid{grid-template-columns:1fr;padding:27px 21px 20px;gap:0}.vc-hero h1{font-size:32px}.vc-hero p{font-size:12px}.vc-art{min-height:210px}.vc-ring{width:195px}.vc-ring:before{width:150px;height:150px}.vc-doc{width:175px;padding:16px}.vc-doc strong{margin:18px 0 14px}.vc-section-head{margin-top:40px}.vc-stage{padding:20px}.vc-trust{padding:22px;margin-bottom:40px}.vc-trust a{width:100%}.vc-footer-grid{grid-template-columns:1fr;gap:16px;padding:28px 0}.vc-footer-grid>div:not(:first-child){padding-top:14px;border-top:1px solid #ffffff1b}}
    `}</style>
    <div className="vc-top"><div className="vc-wrap"><span>وام‌سیتی · پیش‌نمایش قالب خدمات اعتباری</span><span>شرایط مالی فقط از منبع رسمی</span></div></div>
    <header className="vc-header"><div className="vc-wrap vc-header-row"><Link href="/store/vamcity" className="vc-brand"><span className="vc-mark">V</span><span><b>VAMCITY</b><small>اعتبار و تسهیلات</small></span></Link><nav className="vc-nav" aria-label="ناوبری"><a href="#steps">مراحل درخواست</a><a href="#disclosure">شرایط و شفافیت</a><a href="#support">راهنما</a></nav><Link className="vc-btn vc-secondary" href="/login?brand=vamcity">ورود به حساب</Link></div></header>
    <div className="vc-wrap"><section className="vc-hero"><div className="vc-hero-grid"><div><span className="vc-eyebrow"><i/>مسیر روشن خدمات اعتباری</span><h1>تصمیم آگاهانه،<br/><em>قدم‌به‌قدم.</em></h1><p>شرایط را بررسی کنید، مدارک موردنیاز را بشناسید و درخواست خود را از مسیر رسمی پیگیری کنید. جزئیات هر محصول باید پیش از اقدام، روشن و قابل بررسی باشد.</p><div className="vc-actions"><Link className="vc-btn vc-primary" href="/pay/apply">بررسی مسیر درخواست ←</Link><a className="vc-btn vc-secondary" href="#steps">مشاهده مراحل</a></div><p className="vc-disclaimer">این صفحه پیش‌نمایش طراحی است؛ هیچ نرخ، مبلغ قسط، سقف اعتبار یا زمان تأیید ساختگی نمایش داده نمی‌شود.</p></div><div className="vc-art" aria-hidden="true"><div className="vc-ring"><div className="vc-doc"><small>VAMCITY · SERVICE</small><i>◈</i><strong>شرایط روشن،<br/>انتخاب آگاهانه</strong><span>مدارک · شرایط · پیگیری</span></div></div></div></div></section>
    <section id="steps"><div className="vc-section-head"><small>فرایند خدمات</small><h2>از بررسی شرایط تا پیگیری درخواست</h2><p>هر مرحله باید به اطلاعات رسمی و وضعیت واقعی سامانه متصل باشد؛ این صفحه صرفاً ساختار تجربه کاربری را نشان می‌دهد.</p></div><div className="vc-stages">{stages.map(([number,title,description])=><article className="vc-stage" key={number}><i>{number}</i><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="vc-trust" id="disclosure"><div><h2>شفافیت پیش از هر تصمیم مالی</h2><p>هزینه‌ها، نرخ‌ها، ضوابط احراز، مدارک و برنامه بازپرداخت باید از محصول رسمی و به‌روز دریافت شوند. تأیید درخواست نیز تنها پس از پاسخ سامانه معتبر است.</p></div><Link className="vc-btn vc-primary" href="/login?brand=vamcity" id="support">ورود و پیگیری</Link></section></div>
    <footer className="vc-footer"><div className="vc-wrap vc-footer-grid"><div><b>VAMCITY · پیش‌نمایش قالب</b><p>قالب مستقل و واکنش‌گرا برای معرفی خدمات اعتباری؛ استفاده از اطلاعات مالی رسمی و مجاز الزامی است.</p></div><div><b>اطلاعات</b><div className="vc-footer-links"><a href="#steps">مراحل درخواست</a><a href="#disclosure">شرایط و شفافیت</a></div></div><div><b>حساب و راهنما</b><div className="vc-footer-links"><Link href="/login?brand=vamcity">ورود</Link><Link href="/register?brand=vamcity">ثبت‌نام</Link></div></div></div><div className="vc-wrap vc-legal">پیش‌نمایش طراحی؛ شرایط اعتباری واقعی فقط پس از اتصال به سرویس رسمی نمایش داده می‌شوند.</div></footer>
  </main>;
}
