"use client";
import {useEffect,useState} from "react";
import {api} from "../../../../lib/api";

export default function SellerSurface({params}:{params:{id:string}}){
 const sellerId=params.id;
 const [tab,setTab]=useState("domains"),[domains,setDomains]=useState<any[]>([]),[licenses,setLicenses]=useState<any[]>([]),[permissions,setPermissions]=useState<any[]>([]),[hostname,setHostname]=useState(""),[licenseNo,setLicenseNo]=useState(""),[licenseType,setLicenseType]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){try{const [d,l,p]=await Promise.all([api<any>(`/api/marketplace/sellers/${sellerId}/domains`),api<any>(`/api/marketplace/sellers/${sellerId}/licenses`),api<any>(`/api/marketplace/sellers/${sellerId}/permissions`)]);setDomains(d.items||[]);setLicenses(l.items||[]);setPermissions(p.items||[])}catch(e){setError(e instanceof Error?e.message:"خطا")}}
 useEffect(()=>{load()},[sellerId]);
 async function addDomain(){setBusy(true);setError("");try{await api(`/api/marketplace/sellers/${sellerId}/domains`,{method:"POST",body:JSON.stringify({hostname,isPrimary:domains.length===0})});setHostname("");await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function addLicense(){setBusy(true);setError("");try{await api(`/api/marketplace/sellers/${sellerId}/licenses`,{method:"POST",body:JSON.stringify({licenseType,licenseNo,status:"pending"})});setLicenseType("");setLicenseNo("");await load()}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setBusy(false)}}
 async function savePermissions(){setBusy(true);try{await api(`/api/marketplace/sellers/${sellerId}/permissions`,{method:"PUT",body:JSON.stringify({items:permissions})});await load()}finally{setBusy(false)}}
 return <section><div className="page-head"><div><span className="eyebrow">پروفایل عملیاتی فروشنده</span><h1>دامنه، مجوز و دسترسی</h1></div><a className="back-link" href="/marketplace/sellers">فروشندگان</a></div>{error&&<div className="error">{error}</div>}
 <div className="tabs"><button className={tab==="domains"?"primary":""} onClick={()=>setTab("domains")}>دامنه‌ها</button><button className={tab==="licenses"?"primary":""} onClick={()=>setTab("licenses")}>مجوزها</button><button className={tab==="permissions"?"primary":""} onClick={()=>setTab("permissions")}>دسترسی‌ها</button></div>
 {tab==="domains"&&<div className="platform-panel"><div className="platform-form"><label>دامنه سفارشی<input value={hostname} onChange={e=>setHostname(e.target.value)} placeholder="shop.example.ir"/></label><button className="primary" disabled={busy||!hostname} onClick={addDomain}>ثبت دامنه</button></div><div className="record-list">{domains.map(d=><div className="record-row" key={d.id}><div><strong>{d.hostname}</strong><small>{d.verification_status} · {d.ssl_mode}</small></div>{d.verification_status==="pending"&&<span className="pill">کد تأیید: {d.verification_token}</span>}</div>)}</div></div>}
 {tab==="licenses"&&<div className="platform-panel"><div className="platform-form"><label>نوع مجوز<input value={licenseType} onChange={e=>setLicenseType(e.target.value)} placeholder="جواز کسب"/></label><label>شماره مجوز<input value={licenseNo} onChange={e=>setLicenseNo(e.target.value)}/></label><button className="primary" disabled={busy||!licenseType||!licenseNo} onClick={addLicense}>ثبت مجوز</button></div><div className="record-list">{licenses.map(x=><div className="record-row" key={x.id}><div><strong>{x.license_type}</strong><small>{x.license_no} · {x.status}</small></div></div>)}</div></div>}
 {tab==="permissions"&&<div className="platform-panel"><p className="muted">دسترسی‌ها در سطح فروشنده نگهداری می‌شوند و به مستاجر دیگر نشت نمی‌کنند.</p>{["catalog.manage","orders.manage","pages.manage","forms.manage","domain.manage","licenses.manage","settlements.view"].map(code=>{const found=permissions.find(x=>x.permission===code);return <label className="platform-row" key={code}><span>{code}</span><input type="checkbox" checked={Boolean(found?.enabled)} onChange={e=>setPermissions(v=>[...v.filter(x=>x.permission!==code),{permission:code,enabled:e.target.checked}])}/></label>})}<button className="primary" disabled={busy} onClick={savePermissions}>ذخیره دسترسی‌ها</button></div>}
 </section>;
}
