create table if not exists platform_modules(
  id smallint primary key,
  code text not null unique,
  title text not null,
  core text not null,
  parent_id smallint references platform_modules(id),
  sort_order smallint not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into platform_modules(id,code,title,core,parent_id,sort_order) values
(1,'governance','حاکمیت و ساختار سازمانی','core',null,1),
(2,'identity','هویت، کاربران و امنیت','core',null,2),
(3,'master-data','داده‌های پایه سازمان','core',null,3),
(4,'customer-360','مشتری 360','core',null,4),
(5,'smart-calendar','تقویم سازمانی هوشمند','core',null,5),
(6,'business-rules','موتور قوانین کسب‌وکار','core',null,6),
(7,'sla','موتور SLA','core',null,7),
(8,'accounting-finance','حسابداری و مالی','finance',null,8),
(9,'treasury-bank','خزانه و بانک','finance',null,9),
(10,'wallet-ledger','کیف پول و دفتر تراکنش','finance',null,10),
(11,'credit-facilities','اعتبار و تسهیلات','credit',null,11),
(12,'credit-scoring','موتور اعتبارسنجی','credit',null,12),
(13,'loans-contracts','وام و قرارداد','credit',null,13),
(14,'installments','اقساط','credit',null,14),
(15,'collections','وصول مطالبات','credit',null,15),
(16,'sales-trade','فروش و تجارت','commerce',null,16),
(17,'marketplace','Marketplace','commerce',null,17),
(18,'delivery-logistics','تحویل و لجستیک','commerce',null,18),
(19,'commission','کمیسیون','commerce',null,19),
(20,'settlement','تسویه','commerce',null,20),
(21,'payments','پرداخت','commerce',null,21),
(22,'providers-integrations','مرکز ارائه‌دهندگان و یکپارچه‌سازی','commerce',null,22),
(23,'communications','مرکز ارتباطات','communication',null,23),
(24,'events-notifications','موتور رویداد و اعلان','communication',null,24),
(25,'crm','CRM','communication',null,25),
(26,'contact-center','مرکز تماس','communication',null,26),
(27,'tickets-support','تیکت و پشتیبانی','communication',null,27),
(28,'documents-office','اسناد و اتوماسیون اداری','documents-content',null,28),
(29,'digital-binder','زونکن دیجیتال','documents-content',null,29),
(30,'web-domain','مدیریت وب‌سایت و دامنه','documents-content',null,30),
(31,'page-builder','صفحه‌ساز','documents-content',null,31),
(32,'form-builder','فرم‌ساز','documents-content',null,32),
(33,'content-management','مدیریت محتوا','documents-content',null,33),
(34,'negar-ai','هوش نگار','documents-content',null,34),
(35,'human-resources','منابع انسانی','organization',null,35),
(36,'projects-operations','پروژه و عملیات','organization',null,36),
(37,'reports-analytics','گزارش و تحلیل','organization',null,37),
(38,'command-center','مرکز فرماندهی','command-platform',null,38),
(39,'monitoring-events','مانیتورینگ و رخدادها','command-platform',null,39),
(40,'audit-control','حسابرسی و کنترل','command-platform',null,40),
(41,'documentation','مستندات','command-platform',null,41),
(42,'api-integration','API و یکپارچه‌سازی','command-platform',null,42),
(43,'infrastructure-data','زیرساخت و داده','command-platform',null,43),
(44,'mobile-app','اپلیکیشن موبایل','command-platform',null,44),
(45,'quality-lifecycle','کیفیت و چرخه توسعه','command-platform',null,45)
on conflict (id) do update set
  code=excluded.code,
  title=excluded.title,
  core=excluded.core,
  sort_order=excluded.sort_order,
  is_active=excluded.is_active;
