-- Dynamic field definitions for all 45 modules
create table if not exists module_field_definitions(
  id bigserial primary key,
  module_id smallint not null references platform_modules(id) on delete cascade,
  field_key text not null,
  title text not null,
  field_type text not null check(field_type in ('text','textarea','number','date','datetime','boolean','select')),
  required boolean not null default false,
  sort_order smallint not null default 0,
  options jsonb not null default '{}'::jsonb,
  unique(module_id,field_key)
);

insert into module_field_definitions(module_id,field_key,title,field_type,required,sort_order,options) values
(1,'governance','کد واحد','text',true,10,'{}'::jsonb),
(1,'governance_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(1,'governance_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(2,'identity','ایمیل','text',true,10,'{}'::jsonb),
(2,'identity_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(2,'identity_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(3,'master-data','کد','text',true,10,'{}'::jsonb),
(3,'master-data_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(3,'master-data_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(4,'customer-360','کد ملی','text',true,10,'{}'::jsonb),
(4,'customer-360_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(4,'customer-360_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(5,'smart-calendar','تاریخ','date',true,10,'{}'::jsonb),
(5,'smart-calendar_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(5,'smart-calendar_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(6,'business-rules','شرط','textarea',true,10,'{}'::jsonb),
(6,'business-rules_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(6,'business-rules_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(7,'sla','مدت پاسخ','number',true,10,'{}'::jsonb),
(7,'sla_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(7,'sla_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(8,'accounting-finance','کد حساب','text',true,10,'{}'::jsonb),
(8,'accounting-finance_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(8,'accounting-finance_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(9,'treasury-bank','شماره حساب','text',true,10,'{}'::jsonb),
(9,'treasury-bank_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(9,'treasury-bank_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(10,'wallet-ledger','شناسه کیف','text',true,10,'{}'::jsonb),
(10,'wallet-ledger_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(10,'wallet-ledger_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(11,'credit-facilities','سقف اعتبار','number',true,10,'{}'::jsonb),
(11,'credit-facilities_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(11,'credit-facilities_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(12,'credit-scoring','امتیاز','number',true,10,'{}'::jsonb),
(12,'credit-scoring_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(12,'credit-scoring_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(13,'loans-contracts','مبلغ قرارداد','number',true,10,'{}'::jsonb),
(13,'loans-contracts_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(13,'loans-contracts_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(14,'installments','تعداد اقساط','number',true,10,'{}'::jsonb),
(14,'installments_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(14,'installments_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(15,'collections','وضعیت وصول','select',true,10,'{}'::jsonb),
(15,'collections_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(15,'collections_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(16,'sales-trade','شماره سفارش','text',true,10,'{}'::jsonb),
(16,'sales-trade_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(16,'sales-trade_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(17,'marketplace','قیمت','number',true,10,'{}'::jsonb),
(17,'marketplace_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(17,'marketplace_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(18,'delivery-logistics','تاریخ تحویل','date',true,10,'{}'::jsonb),
(18,'delivery-logistics_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(18,'delivery-logistics_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(19,'commission','درصد','number',true,10,'{}'::jsonb),
(19,'commission_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(19,'commission_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(20,'settlement','مبلغ تسویه','number',true,10,'{}'::jsonb),
(20,'settlement_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(20,'settlement_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(21,'payments','مبلغ پرداخت','number',true,10,'{}'::jsonb),
(21,'payments_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(21,'payments_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(22,'providers-integrations','نشانی سرویس','text',true,10,'{}'::jsonb),
(22,'providers-integrations_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(22,'providers-integrations_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(23,'communications','گیرنده','text',true,10,'{}'::jsonb),
(23,'communications_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(23,'communications_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(24,'events-notifications','نوع اعلان','select',true,10,'{}'::jsonb),
(24,'events-notifications_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(24,'events-notifications_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(25,'crm','نام مخاطب','text',true,10,'{}'::jsonb),
(25,'crm_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(25,'crm_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(26,'contact-center','شماره تماس','text',true,10,'{}'::jsonb),
(26,'contact-center_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(26,'contact-center_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(27,'tickets-support','اولویت','select',true,10,'{}'::jsonb),
(27,'tickets-support_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(27,'tickets-support_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(28,'documents-office','شماره سند','text',true,10,'{}'::jsonb),
(28,'documents-office_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(28,'documents-office_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(29,'digital-binder','کد پرونده','text',true,10,'{}'::jsonb),
(29,'digital-binder_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(29,'digital-binder_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(30,'web-domain','نام دامنه','text',true,10,'{}'::jsonb),
(30,'web-domain_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(30,'web-domain_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(31,'page-builder','مسیر صفحه','text',true,10,'{}'::jsonb),
(31,'page-builder_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(31,'page-builder_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(32,'form-builder','شناسه فرم','text',true,10,'{}'::jsonb),
(32,'form-builder_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(32,'form-builder_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(33,'content-management','عنوان محتوا','text',true,10,'{}'::jsonb),
(33,'content-management_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(33,'content-management_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(34,'negar-ai','نوع درخواست','select',true,10,'{}'::jsonb),
(34,'negar-ai_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(34,'negar-ai_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(35,'human-resources','کد پرسنلی','text',true,10,'{}'::jsonb),
(35,'human-resources_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(35,'human-resources_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(36,'projects-operations','کد پروژه','text',true,10,'{}'::jsonb),
(36,'projects-operations_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(36,'projects-operations_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(37,'reports-analytics','بازه گزارش','date',true,10,'{}'::jsonb),
(37,'reports-analytics_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(37,'reports-analytics_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(38,'command-center','نوع فرمان','select',true,10,'{}'::jsonb),
(38,'command-center_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(38,'command-center_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(39,'monitoring-events','سطح رخداد','select',true,10,'{}'::jsonb),
(39,'monitoring-events_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(39,'monitoring-events_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(40,'audit-control','مرجع','text',true,10,'{}'::jsonb),
(40,'audit-control_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(40,'audit-control_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(41,'documentation','کد مستند','text',true,10,'{}'::jsonb),
(41,'documentation_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(41,'documentation_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(42,'api-integration','نام کلاینت','text',true,10,'{}'::jsonb),
(42,'api-integration_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(42,'api-integration_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(43,'infrastructure-data','نشانی','text',true,10,'{}'::jsonb),
(43,'infrastructure-data_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(43,'infrastructure-data_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(44,'mobile-app','شناسه دستگاه','text',true,10,'{}'::jsonb),
(44,'mobile-app_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(44,'mobile-app_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb),
(45,'quality-lifecycle','امتیاز کیفیت','number',true,10,'{}'::jsonb),
(45,'quality-lifecycle_notes','توضیحات','textarea',false,20,'{}'::jsonb),
(45,'quality-lifecycle_status','وضعیت','select',true,30,'{"options":["active","pending","closed"]}'::jsonb)
on conflict(module_id,field_key) do update set title=excluded.title,field_type=excluded.field_type,required=excluded.required,sort_order=excluded.sort_order,options=excluded.options;

create index if not exists idx_module_field_definitions_module on module_field_definitions(module_id,sort_order);
create index if not exists idx_module_records_data_gin on module_records using gin(data);
