-- Real operational child menus and domain fields for modules 02..50.
-- Child menus remain in the canonical backend menu tree. Each child opens the same
-- tenant-safe CRUD runtime with its own record_type/tab, so navigation is functional.
insert into menu_items(menu_key,parent_id,title,path,sort_order,permission,children,is_active)
select v.menu_key,p.id,v.title,v.path,v.sort_order,v.permission,v.children,true
from (values
('02-identity:1','کاربران','/modules/?code=02-identity&tab=identity-1',1,'modules:02-identity:read','["کاربران","نقش‌ها","گروه‌های کاربری","مجوزها","ورود و نشست‌ها"]:'::jsonb),
('02-identity:2','نقش‌ها','/modules/?code=02-identity&tab=identity-2',2,'modules:02-identity:read','["کاربران","نقش‌ها","گروه‌های کاربری","مجوزها","ورود و نشست‌ها"]:'::jsonb),
('02-identity:3','گروه‌های کاربری','/modules/?code=02-identity&tab=identity-3',3,'modules:02-identity:read','["کاربران","نقش‌ها","گروه‌های کاربری","مجوزها","ورود و نشست‌ها"]:'::jsonb),
('02-identity:4','مجوزها','/modules/?code=02-identity&tab=identity-4',4,'modules:02-identity:read','["کاربران","نقش‌ها","گروه‌های کاربری","مجوزها","ورود و نشست‌ها"]:'::jsonb),
('02-identity:5','ورود و نشست‌ها','/modules/?code=02-identity&tab=identity-5',5,'modules:02-identity:read','["کاربران","نقش‌ها","گروه‌های کاربری","مجوزها","ورود و نشست‌ها"]:'::jsonb),
('03-master-data:1','تعاریف پایه','/modules/?code=03-master-data&tab=master-data-1',1,'modules:03-master-data:read','["تعاریف پایه","کدها و شناسه‌ها","دسته‌بندی‌ها","واحدها","سوابق تغییر"]:'::jsonb),
('03-master-data:2','کدها و شناسه‌ها','/modules/?code=03-master-data&tab=master-data-2',2,'modules:03-master-data:read','["تعاریف پایه","کدها و شناسه‌ها","دسته‌بندی‌ها","واحدها","سوابق تغییر"]:'::jsonb),
('03-master-data:3','دسته‌بندی‌ها','/modules/?code=03-master-data&tab=master-data-3',3,'modules:03-master-data:read','["تعاریف پایه","کدها و شناسه‌ها","دسته‌بندی‌ها","واحدها","سوابق تغییر"]:'::jsonb),
('03-master-data:4','واحدها','/modules/?code=03-master-data&tab=master-data-4',4,'modules:03-master-data:read','["تعاریف پایه","کدها و شناسه‌ها","دسته‌بندی‌ها","واحدها","سوابق تغییر"]:'::jsonb),
('03-master-data:5','سوابق تغییر','/modules/?code=03-master-data&tab=master-data-5',5,'modules:03-master-data:read','["تعاریف پایه","کدها و شناسه‌ها","دسته‌بندی‌ها","واحدها","سوابق تغییر"]:'::jsonb),
('04-customer-360:1','پرونده مشتری','/modules/?code=04-customer-360&tab=customer-360-1',1,'modules:04-customer-360:read','["پرونده مشتری","مشخصات هویتی","تعاملات","سوابق خرید","نمای مالی"]:'::jsonb),
('04-customer-360:2','مشخصات هویتی','/modules/?code=04-customer-360&tab=customer-360-2',2,'modules:04-customer-360:read','["پرونده مشتری","مشخصات هویتی","تعاملات","سوابق خرید","نمای مالی"]:'::jsonb),
('04-customer-360:3','تعاملات','/modules/?code=04-customer-360&tab=customer-360-3',3,'modules:04-customer-360:read','["پرونده مشتری","مشخصات هویتی","تعاملات","سوابق خرید","نمای مالی"]:'::jsonb),
('04-customer-360:4','سوابق خرید','/modules/?code=04-customer-360&tab=customer-360-4',4,'modules:04-customer-360:read','["پرونده مشتری","مشخصات هویتی","تعاملات","سوابق خرید","نمای مالی"]:'::jsonb),
('04-customer-360:5','نمای مالی','/modules/?code=04-customer-360&tab=customer-360-5',5,'modules:04-customer-360:read','["پرونده مشتری","مشخصات هویتی","تعاملات","سوابق خرید","نمای مالی"]:'::jsonb),
('05-smart-calendar:1','تقویم کاری','/modules/?code=05-smart-calendar&tab=smart-calendar-1',1,'modules:05-smart-calendar:read','["تقویم کاری","تعطیلات","رویدادها","سررسیدها","برنامه‌ریزی"]:'::jsonb),
('05-smart-calendar:2','تعطیلات','/modules/?code=05-smart-calendar&tab=smart-calendar-2',2,'modules:05-smart-calendar:read','["تقویم کاری","تعطیلات","رویدادها","سررسیدها","برنامه‌ریزی"]:'::jsonb),
('05-smart-calendar:3','رویدادها','/modules/?code=05-smart-calendar&tab=smart-calendar-3',3,'modules:05-smart-calendar:read','["تقویم کاری","تعطیلات","رویدادها","سررسیدها","برنامه‌ریزی"]:'::jsonb),
('05-smart-calendar:4','سررسیدها','/modules/?code=05-smart-calendar&tab=smart-calendar-4',4,'modules:05-smart-calendar:read','["تقویم کاری","تعطیلات","رویدادها","سررسیدها","برنامه‌ریزی"]:'::jsonb),
('05-smart-calendar:5','برنامه‌ریزی','/modules/?code=05-smart-calendar&tab=smart-calendar-5',5,'modules:05-smart-calendar:read','["تقویم کاری","تعطیلات","رویدادها","سررسیدها","برنامه‌ریزی"]:'::jsonb),
('06-business-rules:1','قواعد','/modules/?code=06-business-rules&tab=business-rules-1',1,'modules:06-business-rules:read','["قواعد","شرایط","اقدامات","اولویت اجرا","نسخه قواعد"]:'::jsonb),
('06-business-rules:2','شرایط','/modules/?code=06-business-rules&tab=business-rules-2',2,'modules:06-business-rules:read','["قواعد","شرایط","اقدامات","اولویت اجرا","نسخه قواعد"]:'::jsonb),
('06-business-rules:3','اقدامات','/modules/?code=06-business-rules&tab=business-rules-3',3,'modules:06-business-rules:read','["قواعد","شرایط","اقدامات","اولویت اجرا","نسخه قواعد"]:'::jsonb),
('06-business-rules:4','اولویت اجرا','/modules/?code=06-business-rules&tab=business-rules-4',4,'modules:06-business-rules:read','["قواعد","شرایط","اقدامات","اولویت اجرا","نسخه قواعد"]:'::jsonb),
('06-business-rules:5','نسخه قواعد','/modules/?code=06-business-rules&tab=business-rules-5',5,'modules:06-business-rules:read','["قواعد","شرایط","اقدامات","اولویت اجرا","نسخه قواعد"]:'::jsonb),
('07-sla:1','تعهدات خدمت','/modules/?code=07-sla&tab=sla-1',1,'modules:07-sla:read','["تعهدات خدمت","سطح سرویس","زمان پاسخ","زمان حل","نقض تعهد"]:'::jsonb),
('07-sla:2','سطح سرویس','/modules/?code=07-sla&tab=sla-2',2,'modules:07-sla:read','["تعهدات خدمت","سطح سرویس","زمان پاسخ","زمان حل","نقض تعهد"]:'::jsonb),
('07-sla:3','زمان پاسخ','/modules/?code=07-sla&tab=sla-3',3,'modules:07-sla:read','["تعهدات خدمت","سطح سرویس","زمان پاسخ","زمان حل","نقض تعهد"]:'::jsonb),
('07-sla:4','زمان حل','/modules/?code=07-sla&tab=sla-4',4,'modules:07-sla:read','["تعهدات خدمت","سطح سرویس","زمان پاسخ","زمان حل","نقض تعهد"]:'::jsonb),
('07-sla:5','نقض تعهد','/modules/?code=07-sla&tab=sla-5',5,'modules:07-sla:read','["تعهدات خدمت","سطح سرویس","زمان پاسخ","زمان حل","نقض تعهد"]:'::jsonb),
('08-accounting-finance:1','دفتر حساب‌ها','/modules/?code=08-accounting-finance&tab=accounting-finance-1',1,'modules:08-accounting-finance:read','["دفتر حساب‌ها","اسناد حسابداری","دوره‌های مالی","مرکز هزینه","گزارش مالی"]:'::jsonb),
('08-accounting-finance:2','اسناد حسابداری','/modules/?code=08-accounting-finance&tab=accounting-finance-2',2,'modules:08-accounting-finance:read','["دفتر حساب‌ها","اسناد حسابداری","دوره‌های مالی","مرکز هزینه","گزارش مالی"]:'::jsonb),
('08-accounting-finance:3','دوره‌های مالی','/modules/?code=08-accounting-finance&tab=accounting-finance-3',3,'modules:08-accounting-finance:read','["دفتر حساب‌ها","اسناد حسابداری","دوره‌های مالی","مرکز هزینه","گزارش مالی"]:'::jsonb),
('08-accounting-finance:4','مرکز هزینه','/modules/?code=08-accounting-finance&tab=accounting-finance-4',4,'modules:08-accounting-finance:read','["دفتر حساب‌ها","اسناد حسابداری","دوره‌های مالی","مرکز هزینه","گزارش مالی"]:'::jsonb),
('08-accounting-finance:5','گزارش مالی','/modules/?code=08-accounting-finance&tab=accounting-finance-5',5,'modules:08-accounting-finance:read','["دفتر حساب‌ها","اسناد حسابداری","دوره‌های مالی","مرکز هزینه","گزارش مالی"]:'::jsonb),
('09-treasury-bank:1','حساب‌های بانکی','/modules/?code=09-treasury-bank&tab=treasury-bank-1',1,'modules:09-treasury-bank:read','["حساب‌های بانکی","دریافت‌ها","پرداخت‌ها","مغایرت بانکی","تنخواه"]:'::jsonb),
('09-treasury-bank:2','دریافت‌ها','/modules/?code=09-treasury-bank&tab=treasury-bank-2',2,'modules:09-treasury-bank:read','["حساب‌های بانکی","دریافت‌ها","پرداخت‌ها","مغایرت بانکی","تنخواه"]:'::jsonb),
('09-treasury-bank:3','پرداخت‌ها','/modules/?code=09-treasury-bank&tab=treasury-bank-3',3,'modules:09-treasury-bank:read','["حساب‌های بانکی","دریافت‌ها","پرداخت‌ها","مغایرت بانکی","تنخواه"]:'::jsonb),
('09-treasury-bank:4','مغایرت بانکی','/modules/?code=09-treasury-bank&tab=treasury-bank-4',4,'modules:09-treasury-bank:read','["حساب‌های بانکی","دریافت‌ها","پرداخت‌ها","مغایرت بانکی","تنخواه"]:'::jsonb),
('09-treasury-bank:5','تنخواه','/modules/?code=09-treasury-bank&tab=treasury-bank-5',5,'modules:09-treasury-bank:read','["حساب‌های بانکی","دریافت‌ها","پرداخت‌ها","مغایرت بانکی","تنخواه"]:'::jsonb),
('10-wallet-ledger:1','کیف پول‌ها','/modules/?code=10-wallet-ledger&tab=wallet-ledger-1',1,'modules:10-wallet-ledger:read','["کیف پول‌ها","گردش کیف پول","دفترکل","بستانکاری","بدهکاری"]:'::jsonb),
('10-wallet-ledger:2','گردش کیف پول','/modules/?code=10-wallet-ledger&tab=wallet-ledger-2',2,'modules:10-wallet-ledger:read','["کیف پول‌ها","گردش کیف پول","دفترکل","بستانکاری","بدهکاری"]:'::jsonb),
('10-wallet-ledger:3','دفترکل','/modules/?code=10-wallet-ledger&tab=wallet-ledger-3',3,'modules:10-wallet-ledger:read','["کیف پول‌ها","گردش کیف پول","دفترکل","بستانکاری","بدهکاری"]:'::jsonb),
('10-wallet-ledger:4','بستانکاری','/modules/?code=10-wallet-ledger&tab=wallet-ledger-4',4,'modules:10-wallet-ledger:read','["کیف پول‌ها","گردش کیف پول","دفترکل","بستانکاری","بدهکاری"]:'::jsonb),
('10-wallet-ledger:5','بدهکاری','/modules/?code=10-wallet-ledger&tab=wallet-ledger-5',5,'modules:10-wallet-ledger:read','["کیف پول‌ها","گردش کیف پول","دفترکل","بستانکاری","بدهکاری"]:'::jsonb),
('11-credit-facilities:1','محصولات اعتباری','/modules/?code=11-credit-facilities&tab=credit-facilities-1',1,'modules:11-credit-facilities:read','["محصولات اعتباری","سقف اعتبار","درخواست اعتبار","مصوبه اعتبار","پرونده اعتباری"]:'::jsonb),
('11-credit-facilities:2','سقف اعتبار','/modules/?code=11-credit-facilities&tab=credit-facilities-2',2,'modules:11-credit-facilities:read','["محصولات اعتباری","سقف اعتبار","درخواست اعتبار","مصوبه اعتبار","پرونده اعتباری"]:'::jsonb),
('11-credit-facilities:3','درخواست اعتبار','/modules/?code=11-credit-facilities&tab=credit-facilities-3',3,'modules:11-credit-facilities:read','["محصولات اعتباری","سقف اعتبار","درخواست اعتبار","مصوبه اعتبار","پرونده اعتباری"]:'::jsonb),
('11-credit-facilities:4','مصوبه اعتبار','/modules/?code=11-credit-facilities&tab=credit-facilities-4',4,'modules:11-credit-facilities:read','["محصولات اعتباری","سقف اعتبار","درخواست اعتبار","مصوبه اعتبار","پرونده اعتباری"]:'::jsonb),
('11-credit-facilities:5','پرونده اعتباری','/modules/?code=11-credit-facilities&tab=credit-facilities-5',5,'modules:11-credit-facilities:read','["محصولات اعتباری","سقف اعتبار","درخواست اعتبار","مصوبه اعتبار","پرونده اعتباری"]:'::jsonb),
('12-credit-scoring:1','مدل امتیازدهی','/modules/?code=12-credit-scoring&tab=credit-scoring-1',1,'modules:12-credit-scoring:read','["مدل امتیازدهی","پارامترها","درخواست امتیاز","نتیجه ارزیابی","تاریخچه امتیاز"]:'::jsonb),
('12-credit-scoring:2','پارامترها','/modules/?code=12-credit-scoring&tab=credit-scoring-2',2,'modules:12-credit-scoring:read','["مدل امتیازدهی","پارامترها","درخواست امتیاز","نتیجه ارزیابی","تاریخچه امتیاز"]:'::jsonb),
('12-credit-scoring:3','درخواست امتیاز','/modules/?code=12-credit-scoring&tab=credit-scoring-3',3,'modules:12-credit-scoring:read','["مدل امتیازدهی","پارامترها","درخواست امتیاز","نتیجه ارزیابی","تاریخچه امتیاز"]:'::jsonb),
('12-credit-scoring:4','نتیجه ارزیابی','/modules/?code=12-credit-scoring&tab=credit-scoring-4',4,'modules:12-credit-scoring:read','["مدل امتیازدهی","پارامترها","درخواست امتیاز","نتیجه ارزیابی","تاریخچه امتیاز"]:'::jsonb),
('12-credit-scoring:5','تاریخچه امتیاز','/modules/?code=12-credit-scoring&tab=credit-scoring-5',5,'modules:12-credit-scoring:read','["مدل امتیازدهی","پارامترها","درخواست امتیاز","نتیجه ارزیابی","تاریخچه امتیاز"]:'::jsonb),
('13-loans-contracts:1','قراردادهای وام','/modules/?code=13-loans-contracts&tab=loans-contracts-1',1,'modules:13-loans-contracts:read','["قراردادهای وام","تسهیلات فعال","وثایق","ضامنین","فسخ و خاتمه"]:'::jsonb),
('13-loans-contracts:2','تسهیلات فعال','/modules/?code=13-loans-contracts&tab=loans-contracts-2',2,'modules:13-loans-contracts:read','["قراردادهای وام","تسهیلات فعال","وثایق","ضامنین","فسخ و خاتمه"]:'::jsonb),
('13-loans-contracts:3','وثایق','/modules/?code=13-loans-contracts&tab=loans-contracts-3',3,'modules:13-loans-contracts:read','["قراردادهای وام","تسهیلات فعال","وثایق","ضامنین","فسخ و خاتمه"]:'::jsonb),
('13-loans-contracts:4','ضامنین','/modules/?code=13-loans-contracts&tab=loans-contracts-4',4,'modules:13-loans-contracts:read','["قراردادهای وام","تسهیلات فعال","وثایق","ضامنین","فسخ و خاتمه"]:'::jsonb),
('13-loans-contracts:5','فسخ و خاتمه','/modules/?code=13-loans-contracts&tab=loans-contracts-5',5,'modules:13-loans-contracts:read','["قراردادهای وام","تسهیلات فعال","وثایق","ضامنین","فسخ و خاتمه"]:'::jsonb),
('14-installments:1','برنامه اقساط','/modules/?code=14-installments&tab=installments-1',1,'modules:14-installments:read','["برنامه اقساط","سررسیدها","دریافت اقساط","معوقه‌ها","تسویه اقساط"]:'::jsonb),
('14-installments:2','سررسیدها','/modules/?code=14-installments&tab=installments-2',2,'modules:14-installments:read','["برنامه اقساط","سررسیدها","دریافت اقساط","معوقه‌ها","تسویه اقساط"]:'::jsonb),
('14-installments:3','دریافت اقساط','/modules/?code=14-installments&tab=installments-3',3,'modules:14-installments:read','["برنامه اقساط","سررسیدها","دریافت اقساط","معوقه‌ها","تسویه اقساط"]:'::jsonb),
('14-installments:4','معوقه‌ها','/modules/?code=14-installments&tab=installments-4',4,'modules:14-installments:read','["برنامه اقساط","سررسیدها","دریافت اقساط","معوقه‌ها","تسویه اقساط"]:'::jsonb),
('14-installments:5','تسویه اقساط','/modules/?code=14-installments&tab=installments-5',5,'modules:14-installments:read','["برنامه اقساط","سررسیدها","دریافت اقساط","معوقه‌ها","تسویه اقساط"]:'::jsonb),
('15-collections:1','پرونده وصول','/modules/?code=15-collections&tab=collections-1',1,'modules:15-collections:read','["پرونده وصول","پیگیری بدهکار","وعده پرداخت","اقدامات وصول","گزارش معوقات"]:'::jsonb),
('15-collections:2','پیگیری بدهکار','/modules/?code=15-collections&tab=collections-2',2,'modules:15-collections:read','["پرونده وصول","پیگیری بدهکار","وعده پرداخت","اقدامات وصول","گزارش معوقات"]:'::jsonb),
('15-collections:3','وعده پرداخت','/modules/?code=15-collections&tab=collections-3',3,'modules:15-collections:read','["پرونده وصول","پیگیری بدهکار","وعده پرداخت","اقدامات وصول","گزارش معوقات"]:'::jsonb),
('15-collections:4','اقدامات وصول','/modules/?code=15-collections&tab=collections-4',4,'modules:15-collections:read','["پرونده وصول","پیگیری بدهکار","وعده پرداخت","اقدامات وصول","گزارش معوقات"]:'::jsonb),
('15-collections:5','گزارش معوقات','/modules/?code=15-collections&tab=collections-5',5,'modules:15-collections:read','["پرونده وصول","پیگیری بدهکار","وعده پرداخت","اقدامات وصول","گزارش معوقات"]:'::jsonb),
('16-sales-trade:1','فروش','/modules/?code=16-sales-trade&tab=sales-trade-1',1,'modules:16-sales-trade:read','["فروش","پیش‌فاکتورها","سفارش‌ها","فاکتورها","بازگشت فروش"]:'::jsonb),
('16-sales-trade:2','پیش‌فاکتورها','/modules/?code=16-sales-trade&tab=sales-trade-2',2,'modules:16-sales-trade:read','["فروش","پیش‌فاکتورها","سفارش‌ها","فاکتورها","بازگشت فروش"]:'::jsonb),
('16-sales-trade:3','سفارش‌ها','/modules/?code=16-sales-trade&tab=sales-trade-3',3,'modules:16-sales-trade:read','["فروش","پیش‌فاکتورها","سفارش‌ها","فاکتورها","بازگشت فروش"]:'::jsonb),
('16-sales-trade:4','فاکتورها','/modules/?code=16-sales-trade&tab=sales-trade-4',4,'modules:16-sales-trade:read','["فروش","پیش‌فاکتورها","سفارش‌ها","فاکتورها","بازگشت فروش"]:'::jsonb),
('16-sales-trade:5','بازگشت فروش','/modules/?code=16-sales-trade&tab=sales-trade-5',5,'modules:16-sales-trade:read','["فروش","پیش‌فاکتورها","سفارش‌ها","فاکتورها","بازگشت فروش"]:'::jsonb),
('17-marketplace:1','کالاها و خدمات','/modules/?code=17-marketplace&tab=marketplace-1',1,'modules:17-marketplace:read','["کالاها و خدمات","آگهی‌ها","فروشندگان","سفارش بازارگاه","کمیسیون بازارگاه"]:'::jsonb),
('17-marketplace:2','آگهی‌ها','/modules/?code=17-marketplace&tab=marketplace-2',2,'modules:17-marketplace:read','["کالاها و خدمات","آگهی‌ها","فروشندگان","سفارش بازارگاه","کمیسیون بازارگاه"]:'::jsonb),
('17-marketplace:3','فروشندگان','/modules/?code=17-marketplace&tab=marketplace-3',3,'modules:17-marketplace:read','["کالاها و خدمات","آگهی‌ها","فروشندگان","سفارش بازارگاه","کمیسیون بازارگاه"]:'::jsonb),
('17-marketplace:4','سفارش بازارگاه','/modules/?code=17-marketplace&tab=marketplace-4',4,'modules:17-marketplace:read','["کالاها و خدمات","آگهی‌ها","فروشندگان","سفارش بازارگاه","کمیسیون بازارگاه"]:'::jsonb),
('17-marketplace:5','کمیسیون بازارگاه','/modules/?code=17-marketplace&tab=marketplace-5',5,'modules:17-marketplace:read','["کالاها و خدمات","آگهی‌ها","فروشندگان","سفارش بازارگاه","کمیسیون بازارگاه"]:'::jsonb),
('18-delivery-logistics:1','سفارش تحویل','/modules/?code=18-delivery-logistics&tab=delivery-logistics-1',1,'modules:18-delivery-logistics:read','["سفارش تحویل","برنامه ارسال","ناوگان","رهگیری","تحویل موفق"]:'::jsonb),
('18-delivery-logistics:2','برنامه ارسال','/modules/?code=18-delivery-logistics&tab=delivery-logistics-2',2,'modules:18-delivery-logistics:read','["سفارش تحویل","برنامه ارسال","ناوگان","رهگیری","تحویل موفق"]:'::jsonb),
('18-delivery-logistics:3','ناوگان','/modules/?code=18-delivery-logistics&tab=delivery-logistics-3',3,'modules:18-delivery-logistics:read','["سفارش تحویل","برنامه ارسال","ناوگان","رهگیری","تحویل موفق"]:'::jsonb),
('18-delivery-logistics:4','رهگیری','/modules/?code=18-delivery-logistics&tab=delivery-logistics-4',4,'modules:18-delivery-logistics:read','["سفارش تحویل","برنامه ارسال","ناوگان","رهگیری","تحویل موفق"]:'::jsonb),
('18-delivery-logistics:5','تحویل موفق','/modules/?code=18-delivery-logistics&tab=delivery-logistics-5',5,'modules:18-delivery-logistics:read','["سفارش تحویل","برنامه ارسال","ناوگان","رهگیری","تحویل موفق"]:'::jsonb),
('19-commission:1','قواعد کمیسیون','/modules/?code=19-commission&tab=commission-1',1,'modules:19-commission:read','["قواعد کمیسیون","طرف‌های مشمول","محاسبه کمیسیون","تأیید کمیسیون","گزارش کمیسیون"]:'::jsonb),
('19-commission:2','طرف‌های مشمول','/modules/?code=19-commission&tab=commission-2',2,'modules:19-commission:read','["قواعد کمیسیون","طرف‌های مشمول","محاسبه کمیسیون","تأیید کمیسیون","گزارش کمیسیون"]:'::jsonb),
('19-commission:3','محاسبه کمیسیون','/modules/?code=19-commission&tab=commission-3',3,'modules:19-commission:read','["قواعد کمیسیون","طرف‌های مشمول","محاسبه کمیسیون","تأیید کمیسیون","گزارش کمیسیون"]:'::jsonb),
('19-commission:4','تأیید کمیسیون','/modules/?code=19-commission&tab=commission-4',4,'modules:19-commission:read','["قواعد کمیسیون","طرف‌های مشمول","محاسبه کمیسیون","تأیید کمیسیون","گزارش کمیسیون"]:'::jsonb),
('19-commission:5','گزارش کمیسیون','/modules/?code=19-commission&tab=commission-5',5,'modules:19-commission:read','["قواعد کمیسیون","طرف‌های مشمول","محاسبه کمیسیون","تأیید کمیسیون","گزارش کمیسیون"]:'::jsonb),
('20-settlement:1','تسویه‌ها','/modules/?code=20-settlement&tab=settlement-1',1,'modules:20-settlement:read','["تسویه‌ها","صورتحساب طرفین","کسر کمیسیون","تأیید تسویه","گزارش تسویه"]:'::jsonb),
('20-settlement:2','صورتحساب طرفین','/modules/?code=20-settlement&tab=settlement-2',2,'modules:20-settlement:read','["تسویه‌ها","صورتحساب طرفین","کسر کمیسیون","تأیید تسویه","گزارش تسویه"]:'::jsonb),
('20-settlement:3','کسر کمیسیون','/modules/?code=20-settlement&tab=settlement-3',3,'modules:20-settlement:read','["تسویه‌ها","صورتحساب طرفین","کسر کمیسیون","تأیید تسویه","گزارش تسویه"]:'::jsonb),
('20-settlement:4','تأیید تسویه','/modules/?code=20-settlement&tab=settlement-4',4,'modules:20-settlement:read','["تسویه‌ها","صورتحساب طرفین","کسر کمیسیون","تأیید تسویه","گزارش تسویه"]:'::jsonb),
('20-settlement:5','گزارش تسویه','/modules/?code=20-settlement&tab=settlement-5',5,'modules:20-settlement:read','["تسویه‌ها","صورتحساب طرفین","کسر کمیسیون","تأیید تسویه","گزارش تسویه"]:'::jsonb),
('21-payments:1','درخواست پرداخت','/modules/?code=21-payments&tab=payments-1',1,'modules:21-payments:read','["درخواست پرداخت","پرداخت‌ها","درگاه‌ها","بازگشت وجه","مغایرت پرداخت"]:'::jsonb),
('21-payments:2','پرداخت‌ها','/modules/?code=21-payments&tab=payments-2',2,'modules:21-payments:read','["درخواست پرداخت","پرداخت‌ها","درگاه‌ها","بازگشت وجه","مغایرت پرداخت"]:'::jsonb),
('21-payments:3','درگاه‌ها','/modules/?code=21-payments&tab=payments-3',3,'modules:21-payments:read','["درخواست پرداخت","پرداخت‌ها","درگاه‌ها","بازگشت وجه","مغایرت پرداخت"]:'::jsonb),
('21-payments:4','بازگشت وجه','/modules/?code=21-payments&tab=payments-4',4,'modules:21-payments:read','["درخواست پرداخت","پرداخت‌ها","درگاه‌ها","بازگشت وجه","مغایرت پرداخت"]:'::jsonb),
('21-payments:5','مغایرت پرداخت','/modules/?code=21-payments&tab=payments-5',5,'modules:21-payments:read','["درخواست پرداخت","پرداخت‌ها","درگاه‌ها","بازگشت وجه","مغایرت پرداخت"]:'::jsonb),
('22-providers-integrations:1','تأمین‌کنندگان سرویس','/modules/?code=22-providers-integrations&tab=providers-integrations-1',1,'modules:22-providers-integrations:read','["تأمین‌کنندگان سرویس","اتصال‌ها","کلیدها و دسترسی‌ها","سلامت اتصال","لاگ سرویس"]:'::jsonb),
('22-providers-integrations:2','اتصال‌ها','/modules/?code=22-providers-integrations&tab=providers-integrations-2',2,'modules:22-providers-integrations:read','["تأمین‌کنندگان سرویس","اتصال‌ها","کلیدها و دسترسی‌ها","سلامت اتصال","لاگ سرویس"]:'::jsonb),
('22-providers-integrations:3','کلیدها و دسترسی‌ها','/modules/?code=22-providers-integrations&tab=providers-integrations-3',3,'modules:22-providers-integrations:read','["تأمین‌کنندگان سرویس","اتصال‌ها","کلیدها و دسترسی‌ها","سلامت اتصال","لاگ سرویس"]:'::jsonb),
('22-providers-integrations:4','سلامت اتصال','/modules/?code=22-providers-integrations&tab=providers-integrations-4',4,'modules:22-providers-integrations:read','["تأمین‌کنندگان سرویس","اتصال‌ها","کلیدها و دسترسی‌ها","سلامت اتصال","لاگ سرویس"]:'::jsonb),
('22-providers-integrations:5','لاگ سرویس','/modules/?code=22-providers-integrations&tab=providers-integrations-5',5,'modules:22-providers-integrations:read','["تأمین‌کنندگان سرویس","اتصال‌ها","کلیدها و دسترسی‌ها","سلامت اتصال","لاگ سرویس"]:'::jsonb),
('23-communications:1','پیام‌ها','/modules/?code=23-communications&tab=communications-1',1,'modules:23-communications:read','["پیام‌ها","ارسال گروهی","الگوهای پیام","کانال‌ها","گزارش ارسال"]:'::jsonb),
('23-communications:2','ارسال گروهی','/modules/?code=23-communications&tab=communications-2',2,'modules:23-communications:read','["پیام‌ها","ارسال گروهی","الگوهای پیام","کانال‌ها","گزارش ارسال"]:'::jsonb),
('23-communications:3','الگوهای پیام','/modules/?code=23-communications&tab=communications-3',3,'modules:23-communications:read','["پیام‌ها","ارسال گروهی","الگوهای پیام","کانال‌ها","گزارش ارسال"]:'::jsonb),
('23-communications:4','کانال‌ها','/modules/?code=23-communications&tab=communications-4',4,'modules:23-communications:read','["پیام‌ها","ارسال گروهی","الگوهای پیام","کانال‌ها","گزارش ارسال"]:'::jsonb),
('23-communications:5','گزارش ارسال','/modules/?code=23-communications&tab=communications-5',5,'modules:23-communications:read','["پیام‌ها","ارسال گروهی","الگوهای پیام","کانال‌ها","گزارش ارسال"]:'::jsonb),
('24-events-notifications:1','رویدادها','/modules/?code=24-events-notifications&tab=events-notifications-1',1,'modules:24-events-notifications:read','["رویدادها","اعلان‌ها","قواعد اعلان","صف ارسال","تاریخچه ارسال"]:'::jsonb),
('24-events-notifications:2','اعلان‌ها','/modules/?code=24-events-notifications&tab=events-notifications-2',2,'modules:24-events-notifications:read','["رویدادها","اعلان‌ها","قواعد اعلان","صف ارسال","تاریخچه ارسال"]:'::jsonb),
('24-events-notifications:3','قواعد اعلان','/modules/?code=24-events-notifications&tab=events-notifications-3',3,'modules:24-events-notifications:read','["رویدادها","اعلان‌ها","قواعد اعلان","صف ارسال","تاریخچه ارسال"]:'::jsonb),
('24-events-notifications:4','صف ارسال','/modules/?code=24-events-notifications&tab=events-notifications-4',4,'modules:24-events-notifications:read','["رویدادها","اعلان‌ها","قواعد اعلان","صف ارسال","تاریخچه ارسال"]:'::jsonb),
('24-events-notifications:5','تاریخچه ارسال','/modules/?code=24-events-notifications&tab=events-notifications-5',5,'modules:24-events-notifications:read','["رویدادها","اعلان‌ها","قواعد اعلان","صف ارسال","تاریخچه ارسال"]:'::jsonb),
('25-crm:1','سرنخ‌ها','/modules/?code=25-crm&tab=crm-1',1,'modules:25-crm:read','["سرنخ‌ها","مخاطبان","فرصت‌ها","پیگیری فروش","قیف ارتباط"]:'::jsonb),
('25-crm:2','مخاطبان','/modules/?code=25-crm&tab=crm-2',2,'modules:25-crm:read','["سرنخ‌ها","مخاطبان","فرصت‌ها","پیگیری فروش","قیف ارتباط"]:'::jsonb),
('25-crm:3','فرصت‌ها','/modules/?code=25-crm&tab=crm-3',3,'modules:25-crm:read','["سرنخ‌ها","مخاطبان","فرصت‌ها","پیگیری فروش","قیف ارتباط"]:'::jsonb),
('25-crm:4','پیگیری فروش','/modules/?code=25-crm&tab=crm-4',4,'modules:25-crm:read','["سرنخ‌ها","مخاطبان","فرصت‌ها","پیگیری فروش","قیف ارتباط"]:'::jsonb),
('25-crm:5','قیف ارتباط','/modules/?code=25-crm&tab=crm-5',5,'modules:25-crm:read','["سرنخ‌ها","مخاطبان","فرصت‌ها","پیگیری فروش","قیف ارتباط"]:'::jsonb),
('26-contact-center:1','تماس‌ها','/modules/?code=26-contact-center&tab=contact-center-1',1,'modules:26-contact-center:read','["تماس‌ها","صف‌های تماس","اپراتورها","تماس‌های از دست‌رفته","کیفیت تماس"]:'::jsonb),
('26-contact-center:2','صف‌های تماس','/modules/?code=26-contact-center&tab=contact-center-2',2,'modules:26-contact-center:read','["تماس‌ها","صف‌های تماس","اپراتورها","تماس‌های از دست‌رفته","کیفیت تماس"]:'::jsonb),
('26-contact-center:3','اپراتورها','/modules/?code=26-contact-center&tab=contact-center-3',3,'modules:26-contact-center:read','["تماس‌ها","صف‌های تماس","اپراتورها","تماس‌های از دست‌رفته","کیفیت تماس"]:'::jsonb),
('26-contact-center:4','تماس‌های از دست‌رفته','/modules/?code=26-contact-center&tab=contact-center-4',4,'modules:26-contact-center:read','["تماس‌ها","صف‌های تماس","اپراتورها","تماس‌های از دست‌رفته","کیفیت تماس"]:'::jsonb),
('26-contact-center:5','کیفیت تماس','/modules/?code=26-contact-center&tab=contact-center-5',5,'modules:26-contact-center:read','["تماس‌ها","صف‌های تماس","اپراتورها","تماس‌های از دست‌رفته","کیفیت تماس"]:'::jsonb),
('27-tickets-support:1','تیکت‌ها','/modules/?code=27-tickets-support&tab=tickets-support-1',1,'modules:27-tickets-support:read','["تیکت‌ها","صف پشتیبانی","اولویت‌ها","SLA پشتیبانی","رضایت پس از حل"]:'::jsonb),
('27-tickets-support:2','صف پشتیبانی','/modules/?code=27-tickets-support&tab=tickets-support-2',2,'modules:27-tickets-support:read','["تیکت‌ها","صف پشتیبانی","اولویت‌ها","SLA پشتیبانی","رضایت پس از حل"]:'::jsonb),
('27-tickets-support:3','اولویت‌ها','/modules/?code=27-tickets-support&tab=tickets-support-3',3,'modules:27-tickets-support:read','["تیکت‌ها","صف پشتیبانی","اولویت‌ها","SLA پشتیبانی","رضایت پس از حل"]:'::jsonb),
('27-tickets-support:4','SLA پشتیبانی','/modules/?code=27-tickets-support&tab=tickets-support-4',4,'modules:27-tickets-support:read','["تیکت‌ها","صف پشتیبانی","اولویت‌ها","SLA پشتیبانی","رضایت پس از حل"]:'::jsonb),
('27-tickets-support:5','رضایت پس از حل','/modules/?code=27-tickets-support&tab=tickets-support-5',5,'modules:27-tickets-support:read','["تیکت‌ها","صف پشتیبانی","اولویت‌ها","SLA پشتیبانی","رضایت پس از حل"]:'::jsonb),
('28-documents-office:1','دبیرخانه','/modules/?code=28-documents-office&tab=documents-office-1',1,'modules:28-documents-office:read','["دبیرخانه","نامه‌های وارده","نامه‌های صادره","ارجاع‌ها","بایگانی اسناد"]:'::jsonb),
('28-documents-office:2','نامه‌های وارده','/modules/?code=28-documents-office&tab=documents-office-2',2,'modules:28-documents-office:read','["دبیرخانه","نامه‌های وارده","نامه‌های صادره","ارجاع‌ها","بایگانی اسناد"]:'::jsonb),
('28-documents-office:3','نامه‌های صادره','/modules/?code=28-documents-office&tab=documents-office-3',3,'modules:28-documents-office:read','["دبیرخانه","نامه‌های وارده","نامه‌های صادره","ارجاع‌ها","بایگانی اسناد"]:'::jsonb),
('28-documents-office:4','ارجاع‌ها','/modules/?code=28-documents-office&tab=documents-office-4',4,'modules:28-documents-office:read','["دبیرخانه","نامه‌های وارده","نامه‌های صادره","ارجاع‌ها","بایگانی اسناد"]:'::jsonb),
('28-documents-office:5','بایگانی اسناد','/modules/?code=28-documents-office&tab=documents-office-5',5,'modules:28-documents-office:read','["دبیرخانه","نامه‌های وارده","نامه‌های صادره","ارجاع‌ها","بایگانی اسناد"]:'::jsonb),
('29-digital-binder:1','زونکن‌ها','/modules/?code=29-digital-binder&tab=digital-binder-1',1,'modules:29-digital-binder:read','["زونکن‌ها","پرونده‌ها","ضمائم","دسترسی پرونده","سوابق نسخه"]:'::jsonb),
('29-digital-binder:2','پرونده‌ها','/modules/?code=29-digital-binder&tab=digital-binder-2',2,'modules:29-digital-binder:read','["زونکن‌ها","پرونده‌ها","ضمائم","دسترسی پرونده","سوابق نسخه"]:'::jsonb),
('29-digital-binder:3','ضمائم','/modules/?code=29-digital-binder&tab=digital-binder-3',3,'modules:29-digital-binder:read','["زونکن‌ها","پرونده‌ها","ضمائم","دسترسی پرونده","سوابق نسخه"]:'::jsonb),
('29-digital-binder:4','دسترسی پرونده','/modules/?code=29-digital-binder&tab=digital-binder-4',4,'modules:29-digital-binder:read','["زونکن‌ها","پرونده‌ها","ضمائم","دسترسی پرونده","سوابق نسخه"]:'::jsonb),
('29-digital-binder:5','سوابق نسخه','/modules/?code=29-digital-binder&tab=digital-binder-5',5,'modules:29-digital-binder:read','["زونکن‌ها","پرونده‌ها","ضمائم","دسترسی پرونده","سوابق نسخه"]:'::jsonb),
('30-web-domain:1','دامنه‌ها','/modules/?code=30-web-domain&tab=web-domain-1',1,'modules:30-web-domain:read','["دامنه‌ها","DNS","گواهی‌ها","تمدیدها","وضعیت سرویس"]:'::jsonb),
('30-web-domain:2','DNS','/modules/?code=30-web-domain&tab=web-domain-2',2,'modules:30-web-domain:read','["دامنه‌ها","DNS","گواهی‌ها","تمدیدها","وضعیت سرویس"]:'::jsonb),
('30-web-domain:3','گواهی‌ها','/modules/?code=30-web-domain&tab=web-domain-3',3,'modules:30-web-domain:read','["دامنه‌ها","DNS","گواهی‌ها","تمدیدها","وضعیت سرویس"]:'::jsonb),
('30-web-domain:4','تمدیدها','/modules/?code=30-web-domain&tab=web-domain-4',4,'modules:30-web-domain:read','["دامنه‌ها","DNS","گواهی‌ها","تمدیدها","وضعیت سرویس"]:'::jsonb),
('30-web-domain:5','وضعیت سرویس','/modules/?code=30-web-domain&tab=web-domain-5',5,'modules:30-web-domain:read','["دامنه‌ها","DNS","گواهی‌ها","تمدیدها","وضعیت سرویس"]:'::jsonb),
('31-page-builder:1','صفحات','/modules/?code=31-page-builder&tab=page-builder-1',1,'modules:31-page-builder:read','["صفحات","بلوک‌ها","نسخه‌های صفحه","انتشار","پیش‌نمایش"]:'::jsonb),
('31-page-builder:2','بلوک‌ها','/modules/?code=31-page-builder&tab=page-builder-2',2,'modules:31-page-builder:read','["صفحات","بلوک‌ها","نسخه‌های صفحه","انتشار","پیش‌نمایش"]:'::jsonb),
('31-page-builder:3','نسخه‌های صفحه','/modules/?code=31-page-builder&tab=page-builder-3',3,'modules:31-page-builder:read','["صفحات","بلوک‌ها","نسخه‌های صفحه","انتشار","پیش‌نمایش"]:'::jsonb),
('31-page-builder:4','انتشار','/modules/?code=31-page-builder&tab=page-builder-4',4,'modules:31-page-builder:read','["صفحات","بلوک‌ها","نسخه‌های صفحه","انتشار","پیش‌نمایش"]:'::jsonb),
('31-page-builder:5','پیش‌نمایش','/modules/?code=31-page-builder&tab=page-builder-5',5,'modules:31-page-builder:read','["صفحات","بلوک‌ها","نسخه‌های صفحه","انتشار","پیش‌نمایش"]:'::jsonb),
('32-form-builder:1','فرم‌ها','/modules/?code=32-form-builder&tab=form-builder-1',1,'modules:32-form-builder:read','["فرم‌ها","فیلدها","اعتبارسنجی","نسخه فرم","ارسال‌های فرم"]:'::jsonb),
('32-form-builder:2','فیلدها','/modules/?code=32-form-builder&tab=form-builder-2',2,'modules:32-form-builder:read','["فرم‌ها","فیلدها","اعتبارسنجی","نسخه فرم","ارسال‌های فرم"]:'::jsonb),
('32-form-builder:3','اعتبارسنجی','/modules/?code=32-form-builder&tab=form-builder-3',3,'modules:32-form-builder:read','["فرم‌ها","فیلدها","اعتبارسنجی","نسخه فرم","ارسال‌های فرم"]:'::jsonb),
('32-form-builder:4','نسخه فرم','/modules/?code=32-form-builder&tab=form-builder-4',4,'modules:32-form-builder:read','["فرم‌ها","فیلدها","اعتبارسنجی","نسخه فرم","ارسال‌های فرم"]:'::jsonb),
('32-form-builder:5','ارسال‌های فرم','/modules/?code=32-form-builder&tab=form-builder-5',5,'modules:32-form-builder:read','["فرم‌ها","فیلدها","اعتبارسنجی","نسخه فرم","ارسال‌های فرم"]:'::jsonb),
('33-content-management:1','محتوا','/modules/?code=33-content-management&tab=content-management-1',1,'modules:33-content-management:read','["محتوا","دسته‌بندی","رسانه","انتشار","نسخه محتوا"]:'::jsonb),
('33-content-management:2','دسته‌بندی','/modules/?code=33-content-management&tab=content-management-2',2,'modules:33-content-management:read','["محتوا","دسته‌بندی","رسانه","انتشار","نسخه محتوا"]:'::jsonb),
('33-content-management:3','رسانه','/modules/?code=33-content-management&tab=content-management-3',3,'modules:33-content-management:read','["محتوا","دسته‌بندی","رسانه","انتشار","نسخه محتوا"]:'::jsonb),
('33-content-management:4','انتشار','/modules/?code=33-content-management&tab=content-management-4',4,'modules:33-content-management:read','["محتوا","دسته‌بندی","رسانه","انتشار","نسخه محتوا"]:'::jsonb),
('33-content-management:5','نسخه محتوا','/modules/?code=33-content-management&tab=content-management-5',5,'modules:33-content-management:read','["محتوا","دسته‌بندی","رسانه","انتشار","نسخه محتوا"]:'::jsonb),
('34-negar-ai:1','درخواست‌های هوشمند','/modules/?code=34-negar-ai&tab=negar-ai-1',1,'modules:34-negar-ai:read','["درخواست‌های هوشمند","صف پردازش","الگوها","نتایج","گزارش مصرف"]:'::jsonb),
('34-negar-ai:2','صف پردازش','/modules/?code=34-negar-ai&tab=negar-ai-2',2,'modules:34-negar-ai:read','["درخواست‌های هوشمند","صف پردازش","الگوها","نتایج","گزارش مصرف"]:'::jsonb),
('34-negar-ai:3','الگوها','/modules/?code=34-negar-ai&tab=negar-ai-3',3,'modules:34-negar-ai:read','["درخواست‌های هوشمند","صف پردازش","الگوها","نتایج","گزارش مصرف"]:'::jsonb),
('34-negar-ai:4','نتایج','/modules/?code=34-negar-ai&tab=negar-ai-4',4,'modules:34-negar-ai:read','["درخواست‌های هوشمند","صف پردازش","الگوها","نتایج","گزارش مصرف"]:'::jsonb),
('34-negar-ai:5','گزارش مصرف','/modules/?code=34-negar-ai&tab=negar-ai-5',5,'modules:34-negar-ai:read','["درخواست‌های هوشمند","صف پردازش","الگوها","نتایج","گزارش مصرف"]:'::jsonb),
('35-human-resources:1','کارکنان','/modules/?code=35-human-resources&tab=human-resources-1',1,'modules:35-human-resources:read','["کارکنان","پرونده پرسنلی","واحدها","حضور و غیاب","مرخصی‌ها"]:'::jsonb),
('35-human-resources:2','پرونده پرسنلی','/modules/?code=35-human-resources&tab=human-resources-2',2,'modules:35-human-resources:read','["کارکنان","پرونده پرسنلی","واحدها","حضور و غیاب","مرخصی‌ها"]:'::jsonb),
('35-human-resources:3','واحدها','/modules/?code=35-human-resources&tab=human-resources-3',3,'modules:35-human-resources:read','["کارکنان","پرونده پرسنلی","واحدها","حضور و غیاب","مرخصی‌ها"]:'::jsonb),
('35-human-resources:4','حضور و غیاب','/modules/?code=35-human-resources&tab=human-resources-4',4,'modules:35-human-resources:read','["کارکنان","پرونده پرسنلی","واحدها","حضور و غیاب","مرخصی‌ها"]:'::jsonb),
('35-human-resources:5','مرخصی‌ها','/modules/?code=35-human-resources&tab=human-resources-5',5,'modules:35-human-resources:read','["کارکنان","پرونده پرسنلی","واحدها","حضور و غیاب","مرخصی‌ها"]:'::jsonb),
('36-projects-operations:1','پروژه‌ها','/modules/?code=36-projects-operations&tab=projects-operations-1',1,'modules:36-projects-operations:read','["پروژه‌ها","وظایف","برنامه زمان‌بندی","منابع پروژه","گزارش پیشرفت"]:'::jsonb),
('36-projects-operations:2','وظایف','/modules/?code=36-projects-operations&tab=projects-operations-2',2,'modules:36-projects-operations:read','["پروژه‌ها","وظایف","برنامه زمان‌بندی","منابع پروژه","گزارش پیشرفت"]:'::jsonb),
('36-projects-operations:3','برنامه زمان‌بندی','/modules/?code=36-projects-operations&tab=projects-operations-3',3,'modules:36-projects-operations:read','["پروژه‌ها","وظایف","برنامه زمان‌بندی","منابع پروژه","گزارش پیشرفت"]:'::jsonb),
('36-projects-operations:4','منابع پروژه','/modules/?code=36-projects-operations&tab=projects-operations-4',4,'modules:36-projects-operations:read','["پروژه‌ها","وظایف","برنامه زمان‌بندی","منابع پروژه","گزارش پیشرفت"]:'::jsonb),
('36-projects-operations:5','گزارش پیشرفت','/modules/?code=36-projects-operations&tab=projects-operations-5',5,'modules:36-projects-operations:read','["پروژه‌ها","وظایف","برنامه زمان‌بندی","منابع پروژه","گزارش پیشرفت"]:'::jsonb),
('37-reports-analytics:1','گزارش‌ها','/modules/?code=37-reports-analytics&tab=reports-analytics-1',1,'modules:37-reports-analytics:read','["گزارش‌ها","داشبوردها","شاخص‌ها","فیلترها","خروجی‌ها"]:'::jsonb),
('37-reports-analytics:2','داشبوردها','/modules/?code=37-reports-analytics&tab=reports-analytics-2',2,'modules:37-reports-analytics:read','["گزارش‌ها","داشبوردها","شاخص‌ها","فیلترها","خروجی‌ها"]:'::jsonb),
('37-reports-analytics:3','شاخص‌ها','/modules/?code=37-reports-analytics&tab=reports-analytics-3',3,'modules:37-reports-analytics:read','["گزارش‌ها","داشبوردها","شاخص‌ها","فیلترها","خروجی‌ها"]:'::jsonb),
('37-reports-analytics:4','فیلترها','/modules/?code=37-reports-analytics&tab=reports-analytics-4',4,'modules:37-reports-analytics:read','["گزارش‌ها","داشبوردها","شاخص‌ها","فیلترها","خروجی‌ها"]:'::jsonb),
('37-reports-analytics:5','خروجی‌ها','/modules/?code=37-reports-analytics&tab=reports-analytics-5',5,'modules:37-reports-analytics:read','["گزارش‌ها","داشبوردها","شاخص‌ها","فیلترها","خروجی‌ها"]:'::jsonb),
('38-command-center:1','فرمان‌ها','/modules/?code=38-command-center&tab=command-center-1',1,'modules:38-command-center:read','["فرمان‌ها","اقدامات مدیریتی","صف عملیات","تأیید فرمان","تاریخچه اجرا"]:'::jsonb),
('38-command-center:2','اقدامات مدیریتی','/modules/?code=38-command-center&tab=command-center-2',2,'modules:38-command-center:read','["فرمان‌ها","اقدامات مدیریتی","صف عملیات","تأیید فرمان","تاریخچه اجرا"]:'::jsonb),
('38-command-center:3','صف عملیات','/modules/?code=38-command-center&tab=command-center-3',3,'modules:38-command-center:read','["فرمان‌ها","اقدامات مدیریتی","صف عملیات","تأیید فرمان","تاریخچه اجرا"]:'::jsonb),
('38-command-center:4','تأیید فرمان','/modules/?code=38-command-center&tab=command-center-4',4,'modules:38-command-center:read','["فرمان‌ها","اقدامات مدیریتی","صف عملیات","تأیید فرمان","تاریخچه اجرا"]:'::jsonb),
('38-command-center:5','تاریخچه اجرا','/modules/?code=38-command-center&tab=command-center-5',5,'modules:38-command-center:read','["فرمان‌ها","اقدامات مدیریتی","صف عملیات","تأیید فرمان","تاریخچه اجرا"]:'::jsonb),
('39-monitoring-events:1','رخدادها','/modules/?code=39-monitoring-events&tab=monitoring-events-1',1,'modules:39-monitoring-events:read','["رخدادها","سلامت سرویس","هشدارها","شاخص‌های پایش","تاریخچه رخداد"]:'::jsonb),
('39-monitoring-events:2','سلامت سرویس','/modules/?code=39-monitoring-events&tab=monitoring-events-2',2,'modules:39-monitoring-events:read','["رخدادها","سلامت سرویس","هشدارها","شاخص‌های پایش","تاریخچه رخداد"]:'::jsonb),
('39-monitoring-events:3','هشدارها','/modules/?code=39-monitoring-events&tab=monitoring-events-3',3,'modules:39-monitoring-events:read','["رخدادها","سلامت سرویس","هشدارها","شاخص‌های پایش","تاریخچه رخداد"]:'::jsonb),
('39-monitoring-events:4','شاخص‌های پایش','/modules/?code=39-monitoring-events&tab=monitoring-events-4',4,'modules:39-monitoring-events:read','["رخدادها","سلامت سرویس","هشدارها","شاخص‌های پایش","تاریخچه رخداد"]:'::jsonb),
('39-monitoring-events:5','تاریخچه رخداد','/modules/?code=39-monitoring-events&tab=monitoring-events-5',5,'modules:39-monitoring-events:read','["رخدادها","سلامت سرویس","هشدارها","شاخص‌های پایش","تاریخچه رخداد"]:'::jsonb),
('40-audit-control:1','بررسی‌ها','/modules/?code=40-audit-control&tab=audit-control-1',1,'modules:40-audit-control:read','["بررسی‌ها","ردیابی تغییرات","کنترل‌های داخلی","یافته‌ها","اقدامات اصلاحی"]:'::jsonb),
('40-audit-control:2','ردیابی تغییرات','/modules/?code=40-audit-control&tab=audit-control-2',2,'modules:40-audit-control:read','["بررسی‌ها","ردیابی تغییرات","کنترل‌های داخلی","یافته‌ها","اقدامات اصلاحی"]:'::jsonb),
('40-audit-control:3','کنترل‌های داخلی','/modules/?code=40-audit-control&tab=audit-control-3',3,'modules:40-audit-control:read','["بررسی‌ها","ردیابی تغییرات","کنترل‌های داخلی","یافته‌ها","اقدامات اصلاحی"]:'::jsonb),
('40-audit-control:4','یافته‌ها','/modules/?code=40-audit-control&tab=audit-control-4',4,'modules:40-audit-control:read','["بررسی‌ها","ردیابی تغییرات","کنترل‌های داخلی","یافته‌ها","اقدامات اصلاحی"]:'::jsonb),
('40-audit-control:5','اقدامات اصلاحی','/modules/?code=40-audit-control&tab=audit-control-5',5,'modules:40-audit-control:read','["بررسی‌ها","ردیابی تغییرات","کنترل‌های داخلی","یافته‌ها","اقدامات اصلاحی"]:'::jsonb),
('41-documentation:1','مستندات','/modules/?code=41-documentation&tab=documentation-1',1,'modules:41-documentation:read','["مستندات","نسخه‌ها","دستورالعمل‌ها","راهنماها","تأیید مستند"]:'::jsonb),
('41-documentation:2','نسخه‌ها','/modules/?code=41-documentation&tab=documentation-2',2,'modules:41-documentation:read','["مستندات","نسخه‌ها","دستورالعمل‌ها","راهنماها","تأیید مستند"]:'::jsonb),
('41-documentation:3','دستورالعمل‌ها','/modules/?code=41-documentation&tab=documentation-3',3,'modules:41-documentation:read','["مستندات","نسخه‌ها","دستورالعمل‌ها","راهنماها","تأیید مستند"]:'::jsonb),
('41-documentation:4','راهنماها','/modules/?code=41-documentation&tab=documentation-4',4,'modules:41-documentation:read','["مستندات","نسخه‌ها","دستورالعمل‌ها","راهنماها","تأیید مستند"]:'::jsonb),
('41-documentation:5','تأیید مستند','/modules/?code=41-documentation&tab=documentation-5',5,'modules:41-documentation:read','["مستندات","نسخه‌ها","دستورالعمل‌ها","راهنماها","تأیید مستند"]:'::jsonb),
('42-api-integration:1','کلاینت‌ها','/modules/?code=42-api-integration&tab=api-integration-1',1,'modules:42-api-integration:read','["کلاینت‌ها","Endpointها","مجوز دسترسی","کلیدهای API","لاگ فراخوانی"]:'::jsonb),
('42-api-integration:2','Endpointها','/modules/?code=42-api-integration&tab=api-integration-2',2,'modules:42-api-integration:read','["کلاینت‌ها","Endpointها","مجوز دسترسی","کلیدهای API","لاگ فراخوانی"]:'::jsonb),
('42-api-integration:3','مجوز دسترسی','/modules/?code=42-api-integration&tab=api-integration-3',3,'modules:42-api-integration:read','["کلاینت‌ها","Endpointها","مجوز دسترسی","کلیدهای API","لاگ فراخوانی"]:'::jsonb),
('42-api-integration:4','کلیدهای API','/modules/?code=42-api-integration&tab=api-integration-4',4,'modules:42-api-integration:read','["کلاینت‌ها","Endpointها","مجوز دسترسی","کلیدهای API","لاگ فراخوانی"]:'::jsonb),
('42-api-integration:5','لاگ فراخوانی','/modules/?code=42-api-integration&tab=api-integration-5',5,'modules:42-api-integration:read','["کلاینت‌ها","Endpointها","مجوز دسترسی","کلیدهای API","لاگ فراخوانی"]:'::jsonb),
('43-infrastructure-data:1','منابع زیرساخت','/modules/?code=43-infrastructure-data&tab=infrastructure-data-1',1,'modules:43-infrastructure-data:read','["منابع زیرساخت","پایگاه‌های داده","فضای ذخیره‌سازی","پشتیبان‌گیری","سلامت زیرساخت"]:'::jsonb),
('43-infrastructure-data:2','پایگاه‌های داده','/modules/?code=43-infrastructure-data&tab=infrastructure-data-2',2,'modules:43-infrastructure-data:read','["منابع زیرساخت","پایگاه‌های داده","فضای ذخیره‌سازی","پشتیبان‌گیری","سلامت زیرساخت"]:'::jsonb),
('43-infrastructure-data:3','فضای ذخیره‌سازی','/modules/?code=43-infrastructure-data&tab=infrastructure-data-3',3,'modules:43-infrastructure-data:read','["منابع زیرساخت","پایگاه‌های داده","فضای ذخیره‌سازی","پشتیبان‌گیری","سلامت زیرساخت"]:'::jsonb),
('43-infrastructure-data:4','پشتیبان‌گیری','/modules/?code=43-infrastructure-data&tab=infrastructure-data-4',4,'modules:43-infrastructure-data:read','["منابع زیرساخت","پایگاه‌های داده","فضای ذخیره‌سازی","پشتیبان‌گیری","سلامت زیرساخت"]:'::jsonb),
('43-infrastructure-data:5','سلامت زیرساخت','/modules/?code=43-infrastructure-data&tab=infrastructure-data-5',5,'modules:43-infrastructure-data:read','["منابع زیرساخت","پایگاه‌های داده","فضای ذخیره‌سازی","پشتیبان‌گیری","سلامت زیرساخت"]:'::jsonb),
('44-mobile-app:1','دستگاه‌ها','/modules/?code=44-mobile-app&tab=mobile-app-1',1,'modules:44-mobile-app:read','["دستگاه‌ها","نسخه‌های اپ","ثبت دستگاه","اعلان همراه","نشست‌های همراه"]:'::jsonb),
('44-mobile-app:2','نسخه‌های اپ','/modules/?code=44-mobile-app&tab=mobile-app-2',2,'modules:44-mobile-app:read','["دستگاه‌ها","نسخه‌های اپ","ثبت دستگاه","اعلان همراه","نشست‌های همراه"]:'::jsonb),
('44-mobile-app:3','ثبت دستگاه','/modules/?code=44-mobile-app&tab=mobile-app-3',3,'modules:44-mobile-app:read','["دستگاه‌ها","نسخه‌های اپ","ثبت دستگاه","اعلان همراه","نشست‌های همراه"]:'::jsonb),
('44-mobile-app:4','اعلان همراه','/modules/?code=44-mobile-app&tab=mobile-app-4',4,'modules:44-mobile-app:read','["دستگاه‌ها","نسخه‌های اپ","ثبت دستگاه","اعلان همراه","نشست‌های همراه"]:'::jsonb),
('44-mobile-app:5','نشست‌های همراه','/modules/?code=44-mobile-app&tab=mobile-app-5',5,'modules:44-mobile-app:read','["دستگاه‌ها","نسخه‌های اپ","ثبت دستگاه","اعلان همراه","نشست‌های همراه"]:'::jsonb),
('45-quality-lifecycle:1','کنترل کیفیت','/modules/?code=45-quality-lifecycle&tab=quality-lifecycle-1',1,'modules:45-quality-lifecycle:read','["کنترل کیفیت","چک‌لیست‌ها","ایرادها","اقدامات اصلاحی","چرخه عمر"]:'::jsonb),
('45-quality-lifecycle:2','چک‌لیست‌ها','/modules/?code=45-quality-lifecycle&tab=quality-lifecycle-2',2,'modules:45-quality-lifecycle:read','["کنترل کیفیت","چک‌لیست‌ها","ایرادها","اقدامات اصلاحی","چرخه عمر"]:'::jsonb),
('45-quality-lifecycle:3','ایرادها','/modules/?code=45-quality-lifecycle&tab=quality-lifecycle-3',3,'modules:45-quality-lifecycle:read','["کنترل کیفیت","چک‌لیست‌ها","ایرادها","اقدامات اصلاحی","چرخه عمر"]:'::jsonb),
('45-quality-lifecycle:4','اقدامات اصلاحی','/modules/?code=45-quality-lifecycle&tab=quality-lifecycle-4',4,'modules:45-quality-lifecycle:read','["کنترل کیفیت","چک‌لیست‌ها","ایرادها","اقدامات اصلاحی","چرخه عمر"]:'::jsonb),
('45-quality-lifecycle:5','چرخه عمر','/modules/?code=45-quality-lifecycle&tab=quality-lifecycle-5',5,'modules:45-quality-lifecycle:read','["کنترل کیفیت","چک‌لیست‌ها","ایرادها","اقدامات اصلاحی","چرخه عمر"]:'::jsonb),
('46-risk-compliance:1','ثبت ریسک','/modules/?code=46-risk-compliance&tab=risk-compliance-1',1,'modules:46-risk-compliance:read','["ثبت ریسک","ارزیابی ریسک","کنترل‌های داخلی","اقدامات اصلاحی","انطباق مقررات"]:'::jsonb),
('46-risk-compliance:2','ارزیابی ریسک','/modules/?code=46-risk-compliance&tab=risk-compliance-2',2,'modules:46-risk-compliance:read','["ثبت ریسک","ارزیابی ریسک","کنترل‌های داخلی","اقدامات اصلاحی","انطباق مقررات"]:'::jsonb),
('46-risk-compliance:3','کنترل‌های داخلی','/modules/?code=46-risk-compliance&tab=risk-compliance-3',3,'modules:46-risk-compliance:read','["ثبت ریسک","ارزیابی ریسک","کنترل‌های داخلی","اقدامات اصلاحی","انطباق مقررات"]:'::jsonb),
('46-risk-compliance:4','اقدامات اصلاحی','/modules/?code=46-risk-compliance&tab=risk-compliance-4',4,'modules:46-risk-compliance:read','["ثبت ریسک","ارزیابی ریسک","کنترل‌های داخلی","اقدامات اصلاحی","انطباق مقررات"]:'::jsonb),
('46-risk-compliance:5','انطباق مقررات','/modules/?code=46-risk-compliance&tab=risk-compliance-5',5,'modules:46-risk-compliance:read','["ثبت ریسک","ارزیابی ریسک","کنترل‌های داخلی","اقدامات اصلاحی","انطباق مقررات"]:'::jsonb),
('47-branch-network:1','شعب','/modules/?code=47-branch-network&tab=branch-network-1',1,'modules:47-branch-network:read','["شعب","مدیریت شعب","مدیران شعب","عملکرد شعب","گزارش شبکه"]:'::jsonb),
('47-branch-network:2','مدیریت شعب','/modules/?code=47-branch-network&tab=branch-network-2',2,'modules:47-branch-network:read','["شعب","مدیریت شعب","مدیران شعب","عملکرد شعب","گزارش شبکه"]:'::jsonb),
('47-branch-network:3','مدیران شعب','/modules/?code=47-branch-network&tab=branch-network-3',3,'modules:47-branch-network:read','["شعب","مدیریت شعب","مدیران شعب","عملکرد شعب","گزارش شبکه"]:'::jsonb),
('47-branch-network:4','عملکرد شعب','/modules/?code=47-branch-network&tab=branch-network-4',4,'modules:47-branch-network:read','["شعب","مدیریت شعب","مدیران شعب","عملکرد شعب","گزارش شبکه"]:'::jsonb),
('47-branch-network:5','گزارش شبکه','/modules/?code=47-branch-network&tab=branch-network-5',5,'modules:47-branch-network:read','["شعب","مدیریت شعب","مدیران شعب","عملکرد شعب","گزارش شبکه"]:'::jsonb),
('48-procurement-supply:1','تأمین‌کنندگان','/modules/?code=48-procurement-supply&tab=procurement-supply-1',1,'modules:48-procurement-supply:read','["تأمین‌کنندگان","درخواست تأمین","استعلام قیمت","قرارداد تأمین","تسویه تأمین‌کنندگان"]:'::jsonb),
('48-procurement-supply:2','درخواست تأمین','/modules/?code=48-procurement-supply&tab=procurement-supply-2',2,'modules:48-procurement-supply:read','["تأمین‌کنندگان","درخواست تأمین","استعلام قیمت","قرارداد تأمین","تسویه تأمین‌کنندگان"]:'::jsonb),
('48-procurement-supply:3','استعلام قیمت','/modules/?code=48-procurement-supply&tab=procurement-supply-3',3,'modules:48-procurement-supply:read','["تأمین‌کنندگان","درخواست تأمین","استعلام قیمت","قرارداد تأمین","تسویه تأمین‌کنندگان"]:'::jsonb),
('48-procurement-supply:4','قرارداد تأمین','/modules/?code=48-procurement-supply&tab=procurement-supply-4',4,'modules:48-procurement-supply:read','["تأمین‌کنندگان","درخواست تأمین","استعلام قیمت","قرارداد تأمین","تسویه تأمین‌کنندگان"]:'::jsonb),
('48-procurement-supply:5','تسویه تأمین‌کنندگان','/modules/?code=48-procurement-supply&tab=procurement-supply-5',5,'modules:48-procurement-supply:read','["تأمین‌کنندگان","درخواست تأمین","استعلام قیمت","قرارداد تأمین","تسویه تأمین‌کنندگان"]:'::jsonb),
('49-customer-experience:1','مشتری 360','/modules/?code=49-customer-experience&tab=customer-experience-1',1,'modules:49-customer-experience:read','["مشتری 360","نظرسنجی","امتیاز رضایت","باشگاه مشتریان","سفر مشتری"]:'::jsonb),
('49-customer-experience:2','نظرسنجی','/modules/?code=49-customer-experience&tab=customer-experience-2',2,'modules:49-customer-experience:read','["مشتری 360","نظرسنجی","امتیاز رضایت","باشگاه مشتریان","سفر مشتری"]:'::jsonb),
('49-customer-experience:3','امتیاز رضایت','/modules/?code=49-customer-experience&tab=customer-experience-3',3,'modules:49-customer-experience:read','["مشتری 360","نظرسنجی","امتیاز رضایت","باشگاه مشتریان","سفر مشتری"]:'::jsonb),
('49-customer-experience:4','باشگاه مشتریان','/modules/?code=49-customer-experience&tab=customer-experience-4',4,'modules:49-customer-experience:read','["مشتری 360","نظرسنجی","امتیاز رضایت","باشگاه مشتریان","سفر مشتری"]:'::jsonb),
('49-customer-experience:5','سفر مشتری','/modules/?code=49-customer-experience&tab=customer-experience-5',5,'modules:49-customer-experience:read','["مشتری 360","نظرسنجی","امتیاز رضایت","باشگاه مشتریان","سفر مشتری"]:'::jsonb),
('50-service-lifecycle:1','نسخه‌ها','/modules/?code=50-service-lifecycle&tab=service-lifecycle-1',1,'modules:50-service-lifecycle:read','["نسخه‌ها","برنامه انتشار","محیط‌ها","تأیید انتشار","استقرار"]:'::jsonb),
('50-service-lifecycle:2','برنامه انتشار','/modules/?code=50-service-lifecycle&tab=service-lifecycle-2',2,'modules:50-service-lifecycle:read','["نسخه‌ها","برنامه انتشار","محیط‌ها","تأیید انتشار","استقرار"]:'::jsonb),
('50-service-lifecycle:3','محیط‌ها','/modules/?code=50-service-lifecycle&tab=service-lifecycle-3',3,'modules:50-service-lifecycle:read','["نسخه‌ها","برنامه انتشار","محیط‌ها","تأیید انتشار","استقرار"]:'::jsonb),
('50-service-lifecycle:4','تأیید انتشار','/modules/?code=50-service-lifecycle&tab=service-lifecycle-4',4,'modules:50-service-lifecycle:read','["نسخه‌ها","برنامه انتشار","محیط‌ها","تأیید انتشار","استقرار"]:'::jsonb),
('50-service-lifecycle:5','استقرار','/modules/?code=50-service-lifecycle&tab=service-lifecycle-5',5,'modules:50-service-lifecycle:read','["نسخه‌ها","برنامه انتشار","محیط‌ها","تأیید انتشار","استقرار"]:'::jsonb)
) v(menu_key,title,path,sort_order,permission,children)
join menu_items p on p.path='/modules/?code='||split_part(v.menu_key,':',1)
where not exists(select 1 from menu_items x where x.menu_key=v.menu_key);

insert into module_field_definitions(module_id,field_key,title,field_type,required,sort_order,options)
select m.id,v.field_key,v.title,v.field_type,v.required,v.sort_order,v.options::jsonb
from (values
('02-identity','02-identity-field-1','ایمیل','text',true,10,'{}'::jsonb),
('02-identity','02-identity-field-2','نقش','text',true,20,'{}'::jsonb),
('02-identity','02-identity-field-3','وضعیت حساب','text',true,30,'{}'::jsonb),
('02-identity','02-identity-field-4','تاریخ آخرین ورود','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('03-master-data','03-master-data-field-1','نوع داده','text',true,10,'{}'::jsonb),
('03-master-data','03-master-data-field-2','کد','text',true,20,'{}'::jsonb),
('03-master-data','03-master-data-field-3','عنوان','text',true,30,'{}'::jsonb),
('03-master-data','03-master-data-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('04-customer-360','04-customer-360-field-1','کد مشتری','text',true,10,'{}'::jsonb),
('04-customer-360','04-customer-360-field-2','کد ملی','text',true,20,'{}'::jsonb),
('04-customer-360','04-customer-360-field-3','نام نمایشی','text',true,30,'{}'::jsonb),
('04-customer-360','04-customer-360-field-4','وضعیت مشتری','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('05-smart-calendar','05-smart-calendar-field-1','عنوان رویداد','text',true,10,'{}'::jsonb),
('05-smart-calendar','05-smart-calendar-field-2','تاریخ شروع','text',true,20,'{}'::jsonb),
('05-smart-calendar','05-smart-calendar-field-3','تاریخ پایان','text',true,30,'{}'::jsonb),
('05-smart-calendar','05-smart-calendar-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('06-business-rules','06-business-rules-field-1','کد قاعده','text',true,10,'{}'::jsonb),
('06-business-rules','06-business-rules-field-2','شرط اجرا','text',true,20,'{}'::jsonb),
('06-business-rules','06-business-rules-field-3','اولویت','text',true,30,'{}'::jsonb),
('06-business-rules','06-business-rules-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('07-sla','07-sla-field-1','کد SLA','text',true,10,'{}'::jsonb),
('07-sla','07-sla-field-2','زمان پاسخ','text',true,20,'{}'::jsonb),
('07-sla','07-sla-field-3','زمان حل','text',true,30,'{}'::jsonb),
('07-sla','07-sla-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('08-accounting-finance','08-accounting-finance-field-1','کد حساب','text',true,10,'{}'::jsonb),
('08-accounting-finance','08-accounting-finance-field-2','نوع حساب','text',true,20,'{}'::jsonb),
('08-accounting-finance','08-accounting-finance-field-3','دوره مالی','text',true,30,'{}'::jsonb),
('08-accounting-finance','08-accounting-finance-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('09-treasury-bank','09-treasury-bank-field-1','بانک','text',true,10,'{}'::jsonb),
('09-treasury-bank','09-treasury-bank-field-2','شماره حساب','text',true,20,'{}'::jsonb),
('09-treasury-bank','09-treasury-bank-field-3','شماره شبا','text',true,30,'{}'::jsonb),
('09-treasury-bank','09-treasury-bank-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('10-wallet-ledger','10-wallet-ledger-field-1','شناسه کیف پول','text',true,10,'{}'::jsonb),
('10-wallet-ledger','10-wallet-ledger-field-2','مالک','text',true,20,'{}'::jsonb),
('10-wallet-ledger','10-wallet-ledger-field-3','مبلغ','text',true,30,'{}'::jsonb),
('10-wallet-ledger','10-wallet-ledger-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('11-credit-facilities','11-credit-facilities-field-1','کد اعتبار','text',true,10,'{}'::jsonb),
('11-credit-facilities','11-credit-facilities-field-2','سقف','text',true,20,'{}'::jsonb),
('11-credit-facilities','11-credit-facilities-field-3','نوع اعتبار','text',true,30,'{}'::jsonb),
('11-credit-facilities','11-credit-facilities-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('12-credit-scoring','12-credit-scoring-field-1','شناسه ارزیابی','text',true,10,'{}'::jsonb),
('12-credit-scoring','12-credit-scoring-field-2','امتیاز','text',true,20,'{}'::jsonb),
('12-credit-scoring','12-credit-scoring-field-3','تصمیم','text',true,30,'{}'::jsonb),
('12-credit-scoring','12-credit-scoring-field-4','تاریخ ارزیابی','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('13-loans-contracts','13-loans-contracts-field-1','شماره قرارداد','text',true,10,'{}'::jsonb),
('13-loans-contracts','13-loans-contracts-field-2','وام‌گیرنده','text',true,20,'{}'::jsonb),
('13-loans-contracts','13-loans-contracts-field-3','اصل وام','text',true,30,'{}'::jsonb),
('13-loans-contracts','13-loans-contracts-field-4','نرخ','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('14-installments','14-installments-field-1','شماره قرارداد','text',true,10,'{}'::jsonb),
('14-installments','14-installments-field-2','تعداد اقساط','text',true,20,'{}'::jsonb),
('14-installments','14-installments-field-3','دوره','text',true,30,'{}'::jsonb),
('14-installments','14-installments-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('15-collections','15-collections-field-1','شماره پرونده','text',true,10,'{}'::jsonb),
('15-collections','15-collections-field-2','مبلغ بدهی','text',true,20,'{}'::jsonb),
('15-collections','15-collections-field-3','مسئول پیگیری','text',true,30,'{}'::jsonb),
('15-collections','15-collections-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('16-sales-trade','16-sales-trade-field-1','شماره سفارش','text',true,10,'{}'::jsonb),
('16-sales-trade','16-sales-trade-field-2','مشتری','text',true,20,'{}'::jsonb),
('16-sales-trade','16-sales-trade-field-3','مبلغ','text',true,30,'{}'::jsonb),
('16-sales-trade','16-sales-trade-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('17-marketplace','17-marketplace-field-1','شناسه کالا','text',true,10,'{}'::jsonb),
('17-marketplace','17-marketplace-field-2','عنوان','text',true,20,'{}'::jsonb),
('17-marketplace','17-marketplace-field-3','قیمت','text',true,30,'{}'::jsonb),
('17-marketplace','17-marketplace-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('18-delivery-logistics','18-delivery-logistics-field-1','شماره سفارش','text',true,10,'{}'::jsonb),
('18-delivery-logistics','18-delivery-logistics-field-2','گیرنده','text',true,20,'{}'::jsonb),
('18-delivery-logistics','18-delivery-logistics-field-3','تاریخ تحویل','text',true,30,'{}'::jsonb),
('18-delivery-logistics','18-delivery-logistics-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('19-commission','19-commission-field-1','کد قاعده','text',true,10,'{}'::jsonb),
('19-commission','19-commission-field-2','نرخ','text',true,20,'{}'::jsonb),
('19-commission','19-commission-field-3','مبنای محاسبه','text',true,30,'{}'::jsonb),
('19-commission','19-commission-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('20-settlement','20-settlement-field-1','شماره تسویه','text',true,10,'{}'::jsonb),
('20-settlement','20-settlement-field-2','طرف حساب','text',true,20,'{}'::jsonb),
('20-settlement','20-settlement-field-3','مبلغ','text',true,30,'{}'::jsonb),
('20-settlement','20-settlement-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('21-payments','21-payments-field-1','شماره پرداخت','text',true,10,'{}'::jsonb),
('21-payments','21-payments-field-2','مبلغ','text',true,20,'{}'::jsonb),
('21-payments','21-payments-field-3','روش پرداخت','text',true,30,'{}'::jsonb),
('21-payments','21-payments-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('22-providers-integrations','22-providers-integrations-field-1','کد سرویس','text',true,10,'{}'::jsonb),
('22-providers-integrations','22-providers-integrations-field-2','نشانی سرویس','text',true,20,'{}'::jsonb),
('22-providers-integrations','22-providers-integrations-field-3','نوع اتصال','text',true,30,'{}'::jsonb),
('22-providers-integrations','22-providers-integrations-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('23-communications','23-communications-field-1','گیرنده','text',true,10,'{}'::jsonb),
('23-communications','23-communications-field-2','کانال','text',true,20,'{}'::jsonb),
('23-communications','23-communications-field-3','موضوع','text',true,30,'{}'::jsonb),
('23-communications','23-communications-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('24-events-notifications','24-events-notifications-field-1','نوع رویداد','text',true,10,'{}'::jsonb),
('24-events-notifications','24-events-notifications-field-2','نوع اعلان','text',true,20,'{}'::jsonb),
('24-events-notifications','24-events-notifications-field-3','گیرنده','text',true,30,'{}'::jsonb),
('24-events-notifications','24-events-notifications-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('25-crm','25-crm-field-1','شماره سرنخ','text',true,10,'{}'::jsonb),
('25-crm','25-crm-field-2','نام مخاطب','text',true,20,'{}'::jsonb),
('25-crm','25-crm-field-3','تلفن','text',true,30,'{}'::jsonb),
('25-crm','25-crm-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('26-contact-center','26-contact-center-field-1','شماره تماس','text',true,10,'{}'::jsonb),
('26-contact-center','26-contact-center-field-2','کانال','text',true,20,'{}'::jsonb),
('26-contact-center','26-contact-center-field-3','اپراتور','text',true,30,'{}'::jsonb),
('26-contact-center','26-contact-center-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('27-tickets-support','27-tickets-support-field-1','شماره تیکت','text',true,10,'{}'::jsonb),
('27-tickets-support','27-tickets-support-field-2','موضوع','text',true,20,'{}'::jsonb),
('27-tickets-support','27-tickets-support-field-3','اولویت','text',true,30,'{}'::jsonb),
('27-tickets-support','27-tickets-support-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('28-documents-office','28-documents-office-field-1','شماره سند','text',true,10,'{}'::jsonb),
('28-documents-office','28-documents-office-field-2','نوع سند','text',true,20,'{}'::jsonb),
('28-documents-office','28-documents-office-field-3','عنوان','text',true,30,'{}'::jsonb),
('28-documents-office','28-documents-office-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('29-digital-binder','29-digital-binder-field-1','شماره پرونده','text',true,10,'{}'::jsonb),
('29-digital-binder','29-digital-binder-field-2','عنوان پرونده','text',true,20,'{}'::jsonb),
('29-digital-binder','29-digital-binder-field-3','مالک','text',true,30,'{}'::jsonb),
('29-digital-binder','29-digital-binder-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('30-web-domain','30-web-domain-field-1','دامنه','text',true,10,'{}'::jsonb),
('30-web-domain','30-web-domain-field-2','ارائه‌دهنده','text',true,20,'{}'::jsonb),
('30-web-domain','30-web-domain-field-3','تاریخ انقضا','text',true,30,'{}'::jsonb),
('30-web-domain','30-web-domain-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('31-page-builder','31-page-builder-field-1','مسیر صفحه','text',true,10,'{}'::jsonb),
('31-page-builder','31-page-builder-field-2','عنوان صفحه','text',true,20,'{}'::jsonb),
('31-page-builder','31-page-builder-field-3','نسخه','text',true,30,'{}'::jsonb),
('31-page-builder','31-page-builder-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('32-form-builder','32-form-builder-field-1','شناسه فرم','text',true,10,'{}'::jsonb),
('32-form-builder','32-form-builder-field-2','نام فرم','text',true,20,'{}'::jsonb),
('32-form-builder','32-form-builder-field-3','نسخه','text',true,30,'{}'::jsonb),
('32-form-builder','32-form-builder-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('33-content-management','33-content-management-field-1','عنوان محتوا','text',true,10,'{}'::jsonb),
('33-content-management','33-content-management-field-2','دسته‌بندی','text',true,20,'{}'::jsonb),
('33-content-management','33-content-management-field-3','تاریخ انتشار','text',true,30,'{}'::jsonb),
('33-content-management','33-content-management-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('34-negar-ai','34-negar-ai-field-1','شماره درخواست','text',true,10,'{}'::jsonb),
('34-negar-ai','34-negar-ai-field-2','نوع درخواست','text',true,20,'{}'::jsonb),
('34-negar-ai','34-negar-ai-field-3','وضعیت پردازش','text',true,30,'{}'::jsonb),
('34-negar-ai','34-negar-ai-field-4','تاریخ ثبت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('35-human-resources','35-human-resources-field-1','کد پرسنلی','text',true,10,'{}'::jsonb),
('35-human-resources','35-human-resources-field-2','نام کامل','text',true,20,'{}'::jsonb),
('35-human-resources','35-human-resources-field-3','واحد','text',true,30,'{}'::jsonb),
('35-human-resources','35-human-resources-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('36-projects-operations','36-projects-operations-field-1','کد پروژه','text',true,10,'{}'::jsonb),
('36-projects-operations','36-projects-operations-field-2','نام پروژه','text',true,20,'{}'::jsonb),
('36-projects-operations','36-projects-operations-field-3','مسئول','text',true,30,'{}'::jsonb),
('36-projects-operations','36-projects-operations-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('37-reports-analytics','37-reports-analytics-field-1','کد گزارش','text',true,10,'{}'::jsonb),
('37-reports-analytics','37-reports-analytics-field-2','نام گزارش','text',true,20,'{}'::jsonb),
('37-reports-analytics','37-reports-analytics-field-3','بازه','text',true,30,'{}'::jsonb),
('37-reports-analytics','37-reports-analytics-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('38-command-center','38-command-center-field-1','شماره فرمان','text',true,10,'{}'::jsonb),
('38-command-center','38-command-center-field-2','نوع فرمان','text',true,20,'{}'::jsonb),
('38-command-center','38-command-center-field-3','مسئول','text',true,30,'{}'::jsonb),
('38-command-center','38-command-center-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('39-monitoring-events','39-monitoring-events-field-1','نوع رخداد','text',true,10,'{}'::jsonb),
('39-monitoring-events','39-monitoring-events-field-2','شدت','text',true,20,'{}'::jsonb),
('39-monitoring-events','39-monitoring-events-field-3','پیام','text',true,30,'{}'::jsonb),
('39-monitoring-events','39-monitoring-events-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('40-audit-control','40-audit-control-field-1','مرجع بررسی','text',true,10,'{}'::jsonb),
('40-audit-control','40-audit-control-field-2','نوع کنترل','text',true,20,'{}'::jsonb),
('40-audit-control','40-audit-control-field-3','مسئول','text',true,30,'{}'::jsonb),
('40-audit-control','40-audit-control-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('41-documentation','41-documentation-field-1','کد مستند','text',true,10,'{}'::jsonb),
('41-documentation','41-documentation-field-2','عنوان','text',true,20,'{}'::jsonb),
('41-documentation','41-documentation-field-3','نسخه','text',true,30,'{}'::jsonb),
('41-documentation','41-documentation-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('42-api-integration','42-api-integration-field-1','نام کلاینت','text',true,10,'{}'::jsonb),
('42-api-integration','42-api-integration-field-2','Scope','text',true,20,'{}'::jsonb),
('42-api-integration','42-api-integration-field-3','نسخه API','text',true,30,'{}'::jsonb),
('42-api-integration','42-api-integration-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('43-infrastructure-data','43-infrastructure-data-field-1','کد منبع','text',true,10,'{}'::jsonb),
('43-infrastructure-data','43-infrastructure-data-field-2','نوع منبع','text',true,20,'{}'::jsonb),
('43-infrastructure-data','43-infrastructure-data-field-3','نشانی','text',true,30,'{}'::jsonb),
('43-infrastructure-data','43-infrastructure-data-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('44-mobile-app','44-mobile-app-field-1','شناسه دستگاه','text',true,10,'{}'::jsonb),
('44-mobile-app','44-mobile-app-field-2','سکو','text',true,20,'{}'::jsonb),
('44-mobile-app','44-mobile-app-field-3','نسخه','text',true,30,'{}'::jsonb),
('44-mobile-app','44-mobile-app-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('45-quality-lifecycle','45-quality-lifecycle-field-1','شماره کنترل','text',true,10,'{}'::jsonb),
('45-quality-lifecycle','45-quality-lifecycle-field-2','عنوان','text',true,20,'{}'::jsonb),
('45-quality-lifecycle','45-quality-lifecycle-field-3','امتیاز','text',true,30,'{}'::jsonb),
('45-quality-lifecycle','45-quality-lifecycle-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('46-risk-compliance','46-risk-compliance-field-1','شناسه ریسک','text',true,10,'{}'::jsonb),
('46-risk-compliance','46-risk-compliance-field-2','سطح ریسک','text',true,20,'{}'::jsonb),
('46-risk-compliance','46-risk-compliance-field-3','مسئول','text',true,30,'{}'::jsonb),
('46-risk-compliance','46-risk-compliance-field-4','تاریخ بازبینی','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('47-branch-network','47-branch-network-field-1','کد شعبه','text',true,10,'{}'::jsonb),
('47-branch-network','47-branch-network-field-2','نام شعبه','text',true,20,'{}'::jsonb),
('47-branch-network','47-branch-network-field-3','شهر','text',true,30,'{}'::jsonb),
('47-branch-network','47-branch-network-field-4','وضعیت','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('48-procurement-supply','48-procurement-supply-field-1','کد تأمین‌کننده','text',true,10,'{}'::jsonb),
('48-procurement-supply','48-procurement-supply-field-2','نام تأمین‌کننده','text',true,20,'{}'::jsonb),
('48-procurement-supply','48-procurement-supply-field-3','ارزش قرارداد','text',true,30,'{}'::jsonb),
('48-procurement-supply','48-procurement-supply-field-4','پایان قرارداد','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('49-customer-experience','49-customer-experience-field-1','گروه مشتری','text',true,10,'{}'::jsonb),
('49-customer-experience','49-customer-experience-field-2','کانال تجربه','text',true,20,'{}'::jsonb),
('49-customer-experience','49-customer-experience-field-3','امتیاز رضایت','text',true,30,'{}'::jsonb),
('49-customer-experience','49-customer-experience-field-4','سطح وفاداری','select',false,40,'{"options":["active","pending","closed"]}'::jsonb),
('50-service-lifecycle','50-service-lifecycle-field-1','شناسه انتشار','text',true,10,'{}'::jsonb),
('50-service-lifecycle','50-service-lifecycle-field-2','نسخه','text',true,20,'{}'::jsonb),
('50-service-lifecycle','50-service-lifecycle-field-3','محیط','text',true,30,'{}'::jsonb),
('50-service-lifecycle','50-service-lifecycle-field-4','وضعیت انتشار','select',false,40,'{"options":["active","pending","closed"]}'::jsonb)
) v(code,field_key,title,field_type,required,sort_order,options)
join platform_modules m on m.code=v.code
where not exists(select 1 from module_field_definitions f where f.module_id=m.id and f.field_key=v.field_key);

update platform_modules set is_active=true where id between 2 and 50;
