"use client";
import {useEffect,useState} from "react";import {api} from "../../../lib/api";import {FormBuilder,PageBuilder} from "../../../components/Builder";
export default function Editors(){const [tab,setTab]=useState("forms"),[forms,setForms]=useState<any[]>([]),[pages,setPages]=useState<any[]>([]),[menus,setMenus]=useState<any[]>([]),[name,setName]=useState("تعریف جدید"),[slug,setSlug]=useState("new"),[selected,setSelected]=useState<any>(),[moduleKey,setModuleKey]=useState("core"),[panel,setPanel]=useState("admin");
useEffect(()=>{Promise.all([api<any[]>("/api/content/forms"),api<any[]>("/api/content/pages"),api<any>("/api/dashboard/menu-tree?panel="+panel)]).then(([f,p,m])=>{setForms(f);setPages(p);setMenus(m.items||[])}).catch(()=>{location.href="/login"})},[panel]);
const fresh=()=>{setSelected(undefined);setName("تعریف جدید");setSlug(tab+"-"+Date.now());setModuleKey("core")};
async function saveForm(fields:any[]){const body={name,slug,moduleKey,schema:{fields}};if(selected)await api("/api/content/forms/"+selected.id,{method:"PUT",body:JSON.stringify(body)});else await api("/api/content/forms",{method:"POST",body:JSON.stringify(body)});setForms(await api<any[]>("/api/content/forms"))}
async function savePage(blocks:any[]){const body={name,slug,moduleKey,definition:{blocks}};if(selected)await api("/api/content/pages/"+selected.id,{method:"PUT",body:JSON.stringify(body)});else await api("/api/content/pages",{method:"POST",body:JSON.stringify(body)});setPages(await api<any[]>("/api/content/pages"))}
async function saveMenu(item:any){await api("/api/content/menus/"+item.id,{method:"PUT",body:JSON.stringify(item)});const m=await api<any>("/api/dashboard/menu-tree?panel="+panel);setMenus(m.items||[])}
async function moveMenu(item:any,delta:number){const current=menus.findIndex(x=>x.id===item.id);const next=Math.max(0,Math.min(menus.length-1,current+delta));if(current===next)return;await api("/api/dashboard/menu-items/"+item.id+"/move",{method:"PATCH",body:JSON.stringify({panel,sortOrder:(next+1)*10,shared:true,visible:true})});const m=await api<any>("/api/dashboard/menu-tree?panel="+panel);setMenus(m.items||[])}
async function shareAll(item:any){for(const p of ["admin","finance","seller","customer","credit","operations"])await api("/api/dashboard/menu-items/"+item.id+"/panels/"+p,{method:"PATCH",body:JSON.stringify({shared:true,visible:true,sortOrder:item.sort_order||0})});const m=await api<any>("/api/dashboard/menu-tree?panel="+panel);setMenus(m.items||[])}
return <section><div className="page-head"><div><span className="eyebrow">مدیریت قالب، منو و Frontend</span><h1>ویرایشگرهای سامانه</h1></div></div><div className="tabs"><button className={tab==="forms"?"primary":""} onClick={()=>setTab("forms")}>فرم‌ساز</button><button className={tab==="pages"?"primary":""} onClick={()=>setTab("pages")}>صفحه‌ساز</button><button className={tab==="menus"?"primary":""} onClick={()=>setTab("menus")}>ویرایش منو</button></div>{tab!=="menus"&&<div className="editor-grid"><aside className="list-panel"><button className="primary wide" onClick={fresh}>تعریف جدید</button>{(tab==="forms"?forms:pages).map(x=><button className="list-item" key={x.id} onClick={()=>{setSelected(x);setName(x.name);setSlug(x.slug);setModuleKey(x.module_key||"core")}}>{x.name}<small>{x.slug}</small></button>)}</aside><div className="editor-panel"><div className="field-pair"><label>نام<input value={name} onChange={e=>setName(e.target.value)}/></label><label>حوزه سامانه<select value={moduleKey} onChange={e=>setModuleKey(e.target.value)}><option value="core">مرکز مدیریت</option><option value="organization">سازمان و ساختار</option><option value="finance">مالی و حسابداری</option><option value="credit">اعتبار</option><option value="commerce">تجارت</option><option value="users">کاربران و دسترسی</option><option value="templates">مدیریت قالب</option><option value="menus">مدیریت منو</option><option value="frontend">مدیریت Frontend</option></select></label><label>شناسه<input value={slug} onChange={e=>setSlug(e.target.value)}/></label></div>{tab==="forms"?<FormBuilder initial={selected?.schema?.fields||[]} onSave={saveForm}/>:<PageBuilder initial={selected?.definition?.blocks||[]} onSave={savePage}/>}</div></div>}{tab==="menus"&&<div className="menu-editor"><div className="menu-row"><strong>پنل فعال</strong><select value={panel} onChange={e=>setPanel(e.target.value)}><option value="admin">مرکز مدیریت</option><option value="finance">حسابداری</option><option value="seller">فروشنده</option><option value="customer">مشتری</option><option value="credit">اعتبار</option><option value="operations">عملیات</option></select></div>{menus.map((x,i)=><div className="menu-row" key={x.id}><input value={x.title} onChange={e=>setMenus(v=>v.map(item=>item.id===x.id?{...item,title:e.target.value}:item))}/><input value={x.path} onChange={e=>setMenus(v=>v.map(item=>item.id===x.id?{...item,path:e.target.value}:item))}/><input value={x.permission||""} onChange={e=>setMenus(v=>v.map(item=>item.id===x.id?{...item,permission:e.target.value}:item))}/><button onClick={()=>moveMenu(x,-1)} disabled={i===0}>↑</button><button onClick={()=>moveMenu(x,1)} disabled={i===menus.length-1}>↓</button><button onClick={()=>saveMenu(x)}>ذخیره</button><button onClick={()=>shareAll(x)}>مشترک در همه پنل‌ها</button></div>)}</div>}</section>}