import {Router,type Request,type Response} from "express";
import {pool,query} from "./db.js";
import {requireAuth,requirePermission} from "./auth.js";
import {resolveTenant} from "./tenant-context.js";
const router=Router();
const tenantOf=async(req:Request)=>resolveTenant(req,(req as any).user);
const deny=(res:Response,s:number,e:string)=>res.status(s).json({error:e});
const n=(x:any)=>Number(x||0);
async function event(t:string,type:string,id:string,from:string|null,to:string,ev:string,user:string,reason:string|null=null){
 await query("insert into purchase_events(tenant_id,entity_type,entity_id,from_status,to_status,event_type,actor_user_id,reason) values($1,$2,$3,$4,$5,$6,$7,$8)",[t,type,id,from,to,ev,user,reason]);
}
const transitions:Record<string,string[]>={draft:["submitted","cancelled"],submitted:["approved","rejected","cancelled"],approved:["rfq","cancelled"],rfq:["ordered","closed"],ordered:["closed"],closed:[],cancelled:[],rejected:[]};
const orderTransitions:Record<string,string[]>={draft:["approved","cancelled"],approved:["sent","cancelled"],sent:["partially_received","received","cancelled"],partially_received:["received","cancelled"],received:["invoiced"],invoiced:["paid"],paid:[],cancelled:[]};
router.get("/api/purchasing/overview",requireAuth,async(req,res)=>{
 const t=await tenantOf(req);if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");
 const [suppliers,requests,rfqs,quotes,orders,receipts,invoices,payments,returns,evaluations,contracts,events]=await Promise.all([
  query("select * from purchase_suppliers where tenant_id=$1 order by created_at desc limit 500",[t.id]),
  query("select * from purchase_requests where tenant_id=$1 order by created_at desc limit 500",[t.id]),
  query("select r.*,s.request_no from purchase_rfqs r join purchase_requests s on s.id=r.request_id where r.tenant_id=$1 order by r.created_at desc limit 300",[t.id]),
  query("select q.*,s.name supplier_name,r.rfq_no from purchase_supplier_quotes q join purchase_suppliers s on s.id=q.supplier_id join purchase_rfqs r on r.id=q.rfq_id join purchase_requests pr on pr.id=r.request_id where pr.tenant_id=$1 order by q.created_at desc limit 500",[t.id]),
  query("select o.*,s.name supplier_name,coalesce((select json_agg(oi order by oi.id) from purchase_order_items oi where oi.order_id=o.id),'[]'::json) items from purchase_orders o join purchase_suppliers s on s.id=o.supplier_id where o.tenant_id=$1 order by o.created_at desc limit 500",[t.id]),
  query("select g.*,o.order_no from purchase_receipts g join purchase_orders o on o.id=g.order_id where g.tenant_id=$1 order by g.created_at desc limit 500",[t.id]),
  query("select i.*,s.name supplier_name from purchase_invoices i join purchase_suppliers s on s.id=i.supplier_id where i.tenant_id=$1 order by i.created_at desc limit 500",[t.id]),
  query("select * from purchase_payments where tenant_id=$1 order by paid_at desc limit 500",[t.id]),
  query("select r.*,o.order_no from purchase_returns r join purchase_orders o on o.id=r.order_id where r.tenant_id=$1 order by r.created_at desc limit 300",[t.id]),
  query("select e.*,s.name supplier_name from supplier_evaluations e join purchase_suppliers s on s.id=e.supplier_id where e.tenant_id=$1 order by e.created_at desc limit 300",[t.id]),
  query("select c.*,s.name supplier_name from supplier_contracts c join purchase_suppliers s on s.id=c.supplier_id where c.tenant_id=$1 order by c.created_at desc limit 300",[t.id]),
  query("select * from purchase_events where tenant_id=$1 order by created_at desc limit 500",[t.id])
 ]);
 res.json({suppliers:suppliers.rows,requests:requests.rows,rfqs:rfqs.rows,quotes:quotes.rows,orders:orders.rows,receipts:receipts.rows,invoices:invoices.rows,payments:payments.rows,returns:returns.rows,evaluations:evaluations.rows,contracts:contracts.rows,events:events.rows});
});
router.post("/api/purchasing/suppliers",requireAuth,requirePermission("modules:21-purchasing-supply:write"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{};if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");if(!b.code||!b.name)return deny(res,400,"کد و نام تأمین‌کننده الزامی است");
 const r=await query("insert into purchase_suppliers(tenant_id,code,name,national_id,phone,email,payment_terms_days) values($1,$2,$3,$4,$5,$6,$7) returning *",[t.id,b.code,b.name,b.nationalId||null,b.phone||null,b.email||null,n(b.paymentTermsDays)]);res.status(201).json(r.rows[0]);
});
router.post("/api/purchasing/requests",requireAuth,requirePermission("modules:21-purchasing-supply:write"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{},items=Array.isArray(b.items)?b.items:[];if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");if(!items.length)return deny(res,400,"حداقل یک قلم خرید الزامی است");
 const no=b.requestNo||"PR-"+Date.now(),c=await pool.connect();try{await c.query("begin");const r=await c.query("insert into purchase_requests(tenant_id,request_no,requester_user_id,required_date,department,notes) values($1,$2,$3,$4,$5,$6) returning *",[t.id,no,(req as any).user.id,b.requiredDate||null,b.department||null,b.notes||null]);for(const x of items)await c.query("insert into purchase_request_items(request_id,product_name,sku,quantity,unit,estimated_unit_price) values($1,$2,$3,$4,$5,$6)",[r.rows[0].id,x.productName,x.sku||null,n(x.quantity),x.unit||"عدد",n(x.estimatedUnitPrice)]);await c.query("commit");res.status(201).json(r.rows[0])}catch(e){await c.query("rollback");throw e}finally{c.release()}
});
router.patch("/api/purchasing/requests/:id/status",requireAuth,requirePermission("modules:21-purchasing-supply:approve"),async(req,res)=>{
 const t=await tenantOf(req);if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const r=await query("select * from purchase_requests where id=$1 and tenant_id=$2",[req.params.id,t.id]);if(!r.rowCount)return deny(res,404,"درخواست خرید پیدا نشد");const old=r.rows[0],to=String(req.body?.status||"");if(!transitions[old.status]?.includes(to))return deny(res,409,"تغییر وضعیت درخواست خرید مجاز نیست");await query("update purchase_requests set status=$1,updated_at=now() where id=$2",[to,old.id]);await event(t.id,"request",old.id,old.status,to,"status_change",(req as any).user.id,req.body?.reason||null);res.json({...old,status:to});
});
router.post("/api/purchasing/rfqs",requireAuth,requirePermission("modules:21-purchasing-supply:write"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{};if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const pr=await query("select * from purchase_requests where id=$1 and tenant_id=$2",[b.requestId,t.id]);if(!pr.rowCount||pr.rows[0].status!=="approved")return deny(res,409,"فقط درخواست تأییدشده قابل استعلام است");const suppliers=Array.isArray(b.supplierIds)?b.supplierIds:[];if(!suppliers.length)return deny(res,400,"حداقل یک تأمین‌کننده انتخاب کنید");const no=b.rfqNo||"RFQ-"+Date.now();const c=await pool.connect();try{await c.query("begin");const r=await c.query("insert into purchase_rfqs(tenant_id,rfq_no,request_id,deadline,notes,created_by,status) values($1,$2,$3,$4,$5,$6,'sent') returning *",[t.id,no,b.requestId,b.deadline||null,b.notes||null,(req as any).user.id]);for(const id of suppliers){const s=await c.query("select id from purchase_suppliers where id=$1 and tenant_id=$2 and status='active'",[id,t.id]);if(!s.rowCount)throw Error("تأمین‌کننده نامعتبر است");await c.query("insert into purchase_rfq_suppliers(rfq_id,supplier_id) values($1,$2)",[r.rows[0].id,id])}await c.query("update purchase_requests set status='rfq',updated_at=now() where id=$1",[b.requestId]);await c.query("commit");res.status(201).json(r.rows[0])}catch(e){await c.query("rollback");throw e}finally{c.release()}
});
router.post("/api/purchasing/quotes",requireAuth,requirePermission("modules:21-purchasing-supply:write"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{},items=Array.isArray(b.items)?b.items:[];if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");if(!b.rfqId||!b.supplierId||!items.length)return deny(res,400,"استعلام، تأمین‌کننده و اقلام الزامی است");const rf=await query("select * from purchase_rfqs where id=$1 and tenant_id=$2",[b.rfqId,t.id]);if(!rf.rowCount||!["sent","quoting"].includes(rf.rows[0].status))return deny(res,409,"استعلام قابل دریافت پیشنهاد نیست");const supplier=await query("select id from purchase_suppliers where id=$1 and tenant_id=$2 and status='active'",[b.supplierId,t.id]);if(!supplier.rowCount)return deny(res,400,"تأمین‌کننده فعال نیست");
 const sub=items.reduce((a:any,x:any)=>a+n(x.quantity)*n(x.unitPrice),0),tax=items.reduce((a:any,x:any)=>a+n(x.quantity)*n(x.unitPrice)*n(x.taxRate)/100,0),total=sub+tax+n(b.shippingTotal),c=await pool.connect();try{await c.query("begin");const q=await c.query("insert into purchase_supplier_quotes(rfq_id,supplier_id,quote_no,subtotal,tax_total,shipping_total,total,delivery_days,quality_score,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *",[b.rfqId,b.supplierId,b.quoteNo||null,sub,tax,n(b.shippingTotal),total,n(b.deliveryDays),n(b.qualityScore),b.notes||null]);for(const x of items)await c.query("insert into purchase_supplier_quote_items(quote_id,product_name,quantity,unit_price,tax_rate,line_total) values($1,$2,$3,$4,$5,$6)",[q.rows[0].id,x.productName,n(x.quantity),n(x.unitPrice),n(x.taxRate),n(x.quantity)*n(x.unitPrice)*(1+n(x.taxRate)/100)]);await c.query("update purchase_rfqs set status='quoting' where id=$1",[b.rfqId]);await c.query("update purchase_rfq_suppliers set status='responded' where rfq_id=$1 and supplier_id=$2",[b.rfqId,b.supplierId]);await c.query("commit");res.status(201).json(q.rows[0])}catch(e){await c.query("rollback");throw e}finally{c.release()}
});
router.patch("/api/purchasing/rfqs/:id/select",requireAuth,requirePermission("modules:21-purchasing-supply:approve"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{};if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const q=await query("select q.*,r.request_id from purchase_supplier_quotes q join purchase_rfqs r on r.id=q.rfq_id where q.id=$1 and r.tenant_id=$2",[req.params.id,t.id]);if(!q.rowCount)return deny(res,404,"پیشنهاد پیدا نشد");const x=q.rows[0];const c=await pool.connect();try{await c.query("begin");await c.query("update purchase_supplier_quotes set status='rejected' where rfq_id=$1",[x.rfq_id]);await c.query("update purchase_supplier_quotes set status='selected' where id=$1",[x.id]);await c.query("update purchase_rfqs set status='selected' where id=$1",[x.rfq_id]);await c.query("update purchase_requests set status='approved',updated_at=now() where id=$1",[x.request_id]);await c.query("commit");res.json({...x,status:"selected"})}catch(e){await c.query("rollback");throw e}finally{c.release()}
});
router.post("/api/purchasing/orders",requireAuth,requirePermission("modules:21-purchasing-supply:write"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{},items=Array.isArray(b.items)?b.items:[];if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");if(!b.supplierId||!items.length)return deny(res,400,"تأمین‌کننده و اقلام سفارش الزامی است");const s=await query("select id from purchase_suppliers where id=$1 and tenant_id=$2 and status='active'",[b.supplierId,t.id]);if(!s.rowCount)return deny(res,400,"تأمین‌کننده فعال نیست");const sub=items.reduce((a:any,x:any)=>a+n(x.quantity)*n(x.unitPrice),0),tax=items.reduce((a:any,x:any)=>a+n(x.quantity)*n(x.unitPrice)*n(x.taxRate)/100,0),total=sub+tax,c=await pool.connect();try{await c.query("begin");const o=await c.query("insert into purchase_orders(tenant_id,order_no,supplier_id,request_id,quote_id,expected_date,subtotal,tax_total,total,notes,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *",[t.id,b.orderNo||"PO-"+Date.now(),b.supplierId,b.requestId||null,b.quoteId||null,b.expectedDate||null,sub,tax,total,b.notes||null,(req as any).user.id]);for(const x of items)await c.query("insert into purchase_order_items(order_id,product_name,sku,quantity,unit,unit_price,tax_rate,line_total) values($1,$2,$3,$4,$5,$6,$7,$8)",[o.rows[0].id,x.productName,x.sku||null,n(x.quantity),x.unit||"عدد",n(x.unitPrice),n(x.taxRate),n(x.quantity)*n(x.unitPrice)*(1+n(x.taxRate)/100)]);await c.query("commit");res.status(201).json(o.rows[0])}catch(e){await c.query("rollback");throw e}finally{c.release()}
});
router.patch("/api/purchasing/orders/:id/status",requireAuth,requirePermission("modules:21-purchasing-supply:approve"),async(req,res)=>{
 const t=await tenantOf(req);if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const r=await query("select * from purchase_orders where id=$1 and tenant_id=$2",[req.params.id,t.id]);if(!r.rowCount)return deny(res,404,"سفارش خرید پیدا نشد");const old=r.rows[0],to=String(req.body?.status||"");if(!orderTransitions[old.status]?.includes(to))return deny(res,409,"تغییر وضعیت سفارش خرید مجاز نیست");await query("update purchase_orders set status=$1,updated_at=now() where id=$2",[to,old.id]);await event(t.id,"order",old.id,old.status,to,"status_change",(req as any).user.id);res.json({...old,status:to});
});
router.post("/api/purchasing/receipts",requireAuth,requirePermission("modules:21-purchasing-supply:receive"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{},items=Array.isArray(b.items)?b.items:[];if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");if(!b.orderId||!items.length)return deny(res,400,"سفارش و اقلام دریافت الزامی است");const c=await pool.connect();try{await c.query("begin");const o=await c.query("select * from purchase_orders where id=$1 and tenant_id=$2 for update",[b.orderId,t.id]);if(!o.rowCount||!["sent","partially_received"].includes(o.rows[0].status))return deny(res,409,"سفارش آماده دریافت نیست");for(const x of items){const it=await c.query("select * from purchase_order_items where id=$1 and order_id=$2 for update",[x.orderItemId,b.orderId]);if(!it.rowCount)return deny(res,400,"قلم سفارش نامعتبر است");const row=it.rows[0],qty=n(x.quantity),open=n(row.quantity)-n(row.received_qty);if(qty<=0||qty>open)return deny(res,409,"مقدار دریافت بیش از مانده سفارش است");await c.query("update purchase_order_items set received_qty=received_qty+$1 where id=$2",[qty,row.id]);}const no=b.receiptNo||"GRN-"+Date.now();const g=await c.query("insert into purchase_receipts(tenant_id,receipt_no,order_id,status,inspector_user_id,notes,created_by) values($1,$2,$3,'received',$4,$5,$4) returning *",[t.id,no,b.orderId,(req as any).user.id,b.notes||null]);for(const x of items)await c.query("insert into purchase_receipt_items(receipt_id,order_item_id,quantity,accepted_qty,rejected_qty) values($1,$2,$3,$4,$5)",[g.rows[0].id,x.orderItemId,n(x.quantity),n(x.acceptedQty||x.quantity),n(x.rejectedQty)]);const rem=await c.query("select count(*) filter(where received_qty<quantity) remaining from purchase_order_items where order_id=$1",[b.orderId]);await c.query("update purchase_orders set status=$1,updated_at=now() where id=$2",[(Number(rem.rows[0].remaining)>0)?"partially_received":"received",b.orderId]);await c.query("commit");res.status(201).json(g.rows[0])}catch(e){await c.query("rollback");throw e}finally{c.release()}
});
router.post("/api/purchasing/invoices",requireAuth,requirePermission("modules:21-purchasing-supply:invoice"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{};if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const o=await query("select * from purchase_orders where id=$1 and tenant_id=$2",[b.orderId,t.id]);if(!o.rowCount||!["received"].includes(o.rows[0].status))return deny(res,409,"فقط سفارش کاملاً دریافت‌شده قابل فاکتور است");const x=o.rows[0];const r=await query("insert into purchase_invoices(tenant_id,invoice_no,supplier_id,order_id,status,subtotal,tax_total,total,due_date,notes,created_by) values($1,$2,$3,$4,'issued',$5,$6,$7,$8,$9,$10) returning *",[t.id,b.invoiceNo||"PINV-"+Date.now(),x.supplier_id,x.id,x.subtotal,x.tax_total,x.total,b.dueDate||null,b.notes||null,(req as any).user.id]);await query("update purchase_orders set status='invoiced',updated_at=now() where id=$1",[x.id]);await query("insert into purchase_financial_events(tenant_id,source_type,source_id,event_type,amount,state,reference_no) values($1,'purchase_invoice',$2,'invoice_received',$3,'pending_accounting',$4)",[t.id,r.rows[0].id,x.total,r.rows[0].invoice_no]);res.status(201).json(r.rows[0]);
});
router.post("/api/purchasing/invoices/:id/payments",requireAuth,requirePermission("modules:21-purchasing-supply:payment"),async(req,res)=>{
 const t=await tenantOf(req),amount=n(req.body?.amount);if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const c=await pool.connect();try{await c.query("begin");const i=await c.query("select * from purchase_invoices where id=$1 and tenant_id=$2 for update",[req.params.id,t.id]);if(!i.rowCount)return deny(res,404,"فاکتور خرید پیدا نشد");const inv=i.rows[0];if(amount<=0||n(inv.paid_total)+amount>n(inv.total))return deny(res,400,"مبلغ پرداخت نامعتبر است");const p=await c.query("insert into purchase_payments(tenant_id,invoice_id,amount,method,reference_no,created_by) values($1,$2,$3,$4,$5,$6) returning *",[t.id,inv.id,amount,req.body?.method||"bank",req.body?.referenceNo||null,(req as any).user.id]);const paid=n(inv.paid_total)+amount;await c.query("update purchase_invoices set paid_total=$1,status=$2 where id=$3",[paid,paid>=n(inv.total)?"paid":"partially_paid",inv.id]);await c.query("update purchase_orders set status='paid',updated_at=now() where id=$1 and $2=true",[inv.order_id,paid>=n(inv.total)]);await c.query("insert into purchase_financial_events(tenant_id,source_type,source_id,event_type,amount,state,reference_no) values($1,'purchase_payment',$2,'supplier_payment',$3,'pending_accounting',$4)",[t.id,p.rows[0].id,amount,req.body?.referenceNo||null]);await c.query("commit");res.status(201).json(p.rows[0])}catch(e){await c.query("rollback");throw e}finally{c.release()}
});
router.post("/api/purchasing/returns",requireAuth,requirePermission("modules:21-purchasing-supply:return"),async(req,res)=>{
 const t=await tenantOf(req),b=req.body||{};if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");if(!b.orderId||n(b.amount)<=0)return deny(res,400,"سفارش و مبلغ برگشت الزامی است");const r=await query("insert into purchase_returns(tenant_id,return_no,order_id,amount,reason,created_by) values($1,$2,$3,$4,$5,$6) returning *",[t.id,b.returnNo||"PRET-"+Date.now(),b.orderId,n(b.amount),b.reason||null,(req as any).user.id]);res.status(201).json(r.rows[0]);
});
router.patch("/api/purchasing/returns/:id/status",requireAuth,requirePermission("modules:21-purchasing-supply:return"),async(req,res)=>{const t=await tenantOf(req);if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const r=await query("select * from purchase_returns where id=$1 and tenant_id=$2",[req.params.id,t.id]);if(!r.rowCount)return deny(res,404,"برگشت خرید پیدا نشد");const old=r.rows[0],to=String(req.body?.status||""),flow:Record<string,string[]>={requested:["approved","rejected","cancelled"],approved:["shipped","rejected"],shipped:["received"],received:["credited"],credited:[],rejected:[],cancelled:[]};if(!flow[old.status]?.includes(to))return deny(res,409,"تغییر وضعیت برگشت مجاز نیست");await query("update purchase_returns set status=$1 where id=$2",[to,old.id]);await event(t.id,"return",old.id,old.status,to,"status_change",(req as any).user.id,req.body?.reason||null);res.json({...old,status:to})});
router.post("/api/purchasing/evaluations",requireAuth,requirePermission("modules:21-purchasing-supply:write"),async(req,res)=>{const t=await tenantOf(req),b=req.body||{};if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const total=(n(b.qualityScore)+n(b.deliveryScore)+n(b.priceScore)+n(b.serviceScore))/4;const r=await query("insert into supplier_evaluations(tenant_id,supplier_id,period_start,period_end,quality_score,delivery_score,price_score,service_score,total_score,notes,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *",[t.id,b.supplierId,b.periodStart,b.periodEnd,n(b.qualityScore),n(b.deliveryScore),n(b.priceScore),n(b.serviceScore),total,b.notes||null,(req as any).user.id]);res.status(201).json(r.rows[0])});
router.post("/api/purchasing/contracts",requireAuth,requirePermission("modules:21-purchasing-supply:write"),async(req,res)=>{const t=await tenantOf(req),b=req.body||{};if(!t)return deny(res,403,"سازمان معتبر پیدا نشد");const r=await query("insert into supplier_contracts(tenant_id,contract_no,supplier_id,title,status,start_date,end_date,value,notes,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *",[t.id,b.contractNo||"SC-"+Date.now(),b.supplierId,b.title,b.status||"draft",b.startDate||null,b.endDate||null,n(b.value),b.notes||null,(req as any).user.id]);res.status(201).json(r.rows[0])});
export {router as purchasingSupplyRouter};