"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type Product={id:string;sku:string;title:string;description:string|null;category:string|null;price:string;currency:string;seller_name:string;store_id:string|null};
type Catalog={products:Product[]};
export default function StorePage(){
 const [data,setData]=useState<Catalog|null>(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/public/marketplace").then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error||"دریافت کاتالوگ ناموفق بود");return b}).then(setData).catch(e=>setError(e instanceof Error?e.message:"خطا")).catch(()=>{});},[]);
 const products=data?.products?.slice(0,8)??[];
 return <main className="sookar-store" dir="rtl">
  <header className="store-header"><Link href="/store" className="store-logo"><b>سوکار</b><span>فروشگاه هوشمند</span></Link><Link href="/store/shop" className="store-search">جستجو در محصولات، برندها و فروشندگان...</Link><nav><Link href="/store/shop">فروشگاه</Link><Link href="/marketplace">مارکت‌پلیس</Link><Link href="/pay">Sookar Pay</Link><Link href="/login">ورود</Link><Link href="/store/cart">سبد خرید</Link></nav></header>
  <div className="store-category-bar"><span>همه دسته‌ها</span><span>پرفروش‌ها</span><span>جدیدترین‌ها</span><span>خرید اعتباری</span><span>فروشندگان</span></div>
  <section className="store-hero"><div><span>خرید هوشمند، پرداخت هوشمند</span><h1>فروشگاه اینترنتی سوکار</h1><p>کالا، فروشنده، اعتبار و پرداخت در یک تجربه یکپارچه، متصل به کاتالوگ واقعی سامانه.</p><div className="store-actions"><Link href="/store/shop">مشاهده فروشگاه</Link><Link href="/pay" className="secondary">خرید با اعتبار</Link></div></div><div className="hero-card"><b>اعتبار خرید</b><strong>طرح‌های واقعی سوکار</strong><small>شرایط و ضوابط هر محصول مالی در صفحه همان طرح اعلام می‌شود.</small><Link href="/pay/plans">مشاهده طرح‌ها ←</Link></div></section>
  <section className="store-section"><header><div><span>کاتالوگ زنده</span><h2>محصولات موجود</h2></div><Link href="/store/shop">همه محصولات</Link></header>{error?<div className="product-card"><p>{error}</p></div>:!data?<div className="product-card"><p>در حال دریافت کاتالوگ واقعی...</p></div>:products.length?<div className="product-grid">{products.map(p=><article className="product-card" key={p.id}><div className="product-image"><span>{p.category||"محصول"}</span><b>سوکار</b></div><h3>{p.title}</h3><p>{p.description||"توضیحات محصول توسط فروشنده ثبت نشده است."}</p><strong>{Number(p.price).toLocaleString("fa-IR")} {p.currency}</strong><Link href={"/store/product/"+encodeURIComponent(p.id)}>مشاهده محصول</Link></article>)}</div>:<div className="product-card"><p>در حال حاضر محصول فعالی برای نمایش عمومی ثبت نشده است.</p><Link href="/marketplace">مشاهده بازارگاه ←</Link></div>}</section>
  <section className="store-section feature-row">{["فروشندگان تأییدشده","ارسال و پیگیری سفارش","خرید اعتباری","پشتیبانی و ارتباطات"].map(x=><article key={x}><b>{x}</b><span>سرویس یکپارچه سوکار</span></article>)}</section>
  <footer className="store-footer"><div><b>سوکار</b><p>فروشگاه، بازارگاه و خدمات مالی در یک اکوسیستم.</p></div><div><Link href="/store">فروشگاه</Link><Link href="/marketplace">بازارگاه</Link><Link href="/pay">Sookar Pay</Link><Link href="/pay/plans">طرح‌های اعتباری</Link></div><div><Link href="/store/orders">پیگیری سفارش</Link><Link href="/store/returns">مرجوعی</Link><Link href="/store/faq">پرسش‌های متداول</Link><Link href="/store/terms">قوانین</Link></div></footer>
 </main>;
}